### ISSUE TITLE
Snake III crashes

### ISSUE THREAD

**Issue by GreenMan2023** [nikita36078/J2ME-Loader#1002]
**Emulator version:**
1.7.8-open

**Game version:**
2.9.1

**Game resolution:**
Any device including 240x320 or 640x360

**Device:**
``Vivo Y02s"

**Android version:**
12
**Description of the issue:**
It crashes when I press adventure, classic and custom modes.

**Comment by nikita36078** [comment]
This game lacks a . jad file with `SNAKE_SPEED` property. As a temporary solution, you can open the .jar as archive, and add a line `SNAKE_SPEED: 65536` in the file META-INF/MANIFEST.MF. Or you can use another version which has the .jad file.
