### ISSUE TITLE
Custom Soundfont .sf2 for J2ME Loader

### ISSUE THREAD

**Issue by Lipomashi1510** [nikita36078/J2ME-Loader#1008]
### Quick summary

How to custom Soundfont .sf2 j2me loader without root working with kemulator pc YouTube link https://youtu.be/cGyK3ZAcshk
![Screenshot_20230727-122014_ZArchiver](https://github.com/nikita36078/J2ME-Loader/assets/138537047/099ce220-12b8-4356-9152-1e7a263a958d)
Not working add Soundfont this J2ME Loader
This Samsung Galaxy A21s Now Update Version 1.8.0

**Comment by lucmsilva651** [comment]
Duplicate of #569
