### ISSUE TITLE
Play J2ME Loader on .vxp games Files Nokia MRE?

### ISSUE THREAD

**Issue by Lipomashi1510** [nikita36078/J2ME-Loader#1009]
### Quick summary

Working J2ME Loader Play .vxp Games Nokia MRE Devices Support VXP (Support Nokia 216)
Android Devices Format .vxp Support J2ME Loader? How To Install Link: https://youtu.be/N_Wrkrc0PKM

**Comment by nikita36078** [comment]
Unfortunately, it's a completely different platforms, J2ME Loader emulates apps written in Java and VXP apps are written in C++. It would require creating another emulator.
