### ISSUE TITLE
Sony Ericsson Darts [BUG]

### ISSUE THREAD

**Issue by user0-tb** [nikita36078/J2ME-Loader#1035]
### Emulator version

1.7.9

### Game version

1.0.7

### Game resolution

240x320

### Device

Huawei Honor 9x

### Android version

Maybe Android 10🤔(Emui 12) They removed the Android Version from Settings

### Description of the issue

The dart is moving to fast.

https://github.com/nikita36078/J2ME-Loader/assets/104380885/141d9947-6205-4cab-bdd9-0c09e57bf7e1

Jar File from my Sony Ericsson K700i: 
[Darts_K700i_EU.jar.zip](https://github.com/nikita36078/J2ME-Loader/files/13623672/Darts_K700i_EU.jar.zip) (Unzip the zip file)

**Comment by woesss** [comment]
Set a comfortable FPS limit.

**Comment by user0-tb** [comment]
50 seems to be good
