### ISSUE TITLE
[Bug] Keylayout Edit Mode 

### ISSUE THREAD

**Issue by oatmeal01** [nikita36078/J2ME-Loader#104]
## **Issues:**
<p align="center">
<b>Game:</b> Ancient Empires II 240x320 <br>
<image height="400" width="240" src="https://user-images.githubusercontent.com/36059629/36217474-7f7842e2-11ec-11e8-866e-d33e68cda5da.jpg"></p>

1. Overlapped button when moving.
2. It lags when moving/resizing the buttons, when you move the button nothing happens because of lag the only solution is that you need to minimize the app and open it from recent apps to see the new position of the button (same with resizing issue).

**Comment by nikdiklic** [comment]
The problem is that the keylayout updates only when the game screen updates. The solution woul be to find a screen in game that has a constant animated sprite, and edit the layout there. Opening from recents is not the only way, you can also rotate the screen.
