### ISSUE TITLE
[Feature Request] Custom Orientation

### ISSUE THREAD

**Issue by oatmeal01** [nikita36078/J2ME-Loader#105]
# **SUGGESTION 1**
**This is good for all the games that needs auto-rotation to be able to play in landscape.** 

Portrait/Unspecified Orientation (Default Orientation)
<p align="center"><image height="400" width="240" src="https://user-images.githubusercontent.com/36059629/36219118-5afa03e2-11f1-11e8-9e88-7e12a9b90c7c.jpg"/></p>

This is a locked landscape orientation, it won't go to portrait even if you rotate your phone. Good for playing landscape games.
<p align="center"><image height="240" width="400" src="https://user-images.githubusercontent.com/36059629/36219146-69635d34-11f1-11e8-85b2-3b4b9e276ef8.jpg"/></p>

Try Implementing Sam Palmer's Floating Rotation
[Download](https://sfile.mobi/JT9NR98nmu7)
**Github:** [Floating Rotation](https://github.com/sampalmer/floating-rotation)
# **SUGGESTION 2**
- Like any other emulator(e.g.MyBoy! GBA Emulator) you can also add different orientation choices in **[Common Settings]**
<p align="center"><image height="400" width="240" src="https://user-images.githubusercontent.com/36059629/36243009-3716778a-125a-11e8-8406-0481cf468f3a.png"/></p>

**Related Discussion:** [#46](https://github.com/nikita36078/J2ME-Loader/issues/46)

**Comment by AdityaMH** [comment]
I think it will better if located to inside [COMMON SETTING] than floating screen. because can be disturbing while playing a touch screen games.

**Comment by leopard20** [comment]
I agree with AdityaMH

**Comment by nikita36078** [comment]
I think it will be better to add it in per-app settings, and we already discussed this issue - #46

**Comment by oatmeal01** [comment]
@nikita that's great btw, we are looking forward for it to be added soon. Thanks!

**Comment by AdityaMH** [comment]
And don't forget about (dual) virtual keyboard setting @nikita36078, because if orientation screen changed, keypad will change their position too.

**Comment by nikita36078** [comment]
I'm closing this issue since it's duplicate.
