### ISSUE TITLE
Touch screen flickers

### ISSUE THREAD

**Issue by skelletR** [nikita36078/J2ME-Loader#106]
Touch screen game without button flickers and stuck sometimes

**Comment by amarcioz** [comment]
What games?

**Comment by skelletR** [comment]
Crazy penguin 2,  Johnny bravo and how to train your Dragon.. Until now

**Comment by jasper1412** [comment]
press and hold any key before loading screen starts and it would be stuck even if you lift your finger on screen. It will be responsive again once the loading bar/screen reaches 100%

**Comment by skelletR** [comment]
Thanks I try

**Comment by nikita36078** [comment]
I think it is fixed now?

**Comment by oatmeal01** [comment]
tested all the games above and they work fine. using 1.2.8.1 jloader version, i think all the games mentioned above were fixed.

**Comment by amarcioz** [comment]
@nikita36078 N.O.V.A Lecacy  Issue https://github.com/nikita36078/J2ME-Loader/issues/206
