### ISSUE TITLE
List of Tested Java Games (Non-Touchscreen)

### ISSUE THREAD

**Issue by oatmeal01** [nikita36078/J2ME-Loader#108]
# **Non-Touchscreen Games**
>\- All the games that are listed here are tested to work with J2ME Loader. 

| Game Name | Size(s) | Orientation |
| :---         |     :---:      |     :---:      |
|   1000 Words   |   240x320   |  P    |
|   Air Strike 1944   |   240x320   |  P    |
|    Ancient Empires II  |   240x320   |  P    |
|   And 1  Street Basketball  |   240x320   |  P    |
|    Brothers & Arms Earned in Blood  | 240x320   |  P    |
|   Hamster Mansion   |   240x320   |  P    |
|   Heroes Lore Wind of Soltia   |   240x320   |  P    |
|    Icy Tower Me  |   240x320   |  P    |
|   Kasparov Chess   |   240x320   |  P    |
|   Madagascar Escape 2 Africa   |   240x320   |  P    |
|   MU Blood Empire   |   240x320   |  P    |
|    Prince Of Persia Warrior Within  |   352x416   |  P    |
|    Resident Evil - Degeneration  |   240x320   |  P    |
|    Splinter Cell: Rainbow 6 Vegas |   240x320   |  P    |
|    Splinter Cell: Rainbow Six 3 |   240x320   |  P    |
|   Shadowalker   |   240x320   |  P    |
|    Skate.  |   352x416 |  P    |
|    Special Crime Unit  |   240x320   |  P    |
|    Stranded  |   240x320   |  P    |
|    Stranded 2  |   240x320   |  P    |
|    The Dark Knight  |   240x320   |  P    |
|    The OC  |   240x320   |  P    |
|    Total War Mobile  |   240x320   |  P    |
|    Transformers  |   240x320   |  P    |
|  Transformers Revenge of the Fallen    |   240x320   |  P    |
|    Vans Skate & Slam  |   240x320   |  P    |
|      |      |      |

List of Tested Java Games (Touchscreen): #99
List of Java Games w/ Glitch: #94

## **Recommended Devices for Java Games Source:**
>**\- Nokia 5800 Xpress Music** - 360x640/640x360
**\- Samsung GT-5230** - 240x400
**\- Nokia 6300, N73, N95** - 240x320

**Comment by nikita36078** [comment]
What do you think about moving all these lists to the project wiki? It should be more convenient to place them there.

**Comment by nikita36078** [comment]
@oatmeal01

**Comment by oatmeal01** [comment]
@nikita i dont know the link

**Comment by nikita36078** [comment]
@oatmeal01 I mean there - https://github.com/nikita36078/J2ME-Loader/wiki

**Comment by oatmeal01** [comment]
@nikita i can't find the project wiki, im using mobile right now

**Comment by nikita36078** [comment]
I mean I can create project wiki and move these lists there.

**Comment by oatmeal01** [comment]
I switch desktop version i see wiki now, you mean  i create .md file

**Comment by nikita36078** [comment]
I can create wiki, if you don't mind.

**Comment by oatmeal01** [comment]
sure, how can i add updates btw

**Comment by nikita36078** [comment]
I will make it public, so everyone including you will be able to edit

**Comment by oatmeal01** [comment]
thanks, here is the list of touchscreen games too. #99

**Comment by nikita36078** [comment]
I moved all lists to the wiki.

**Comment by oatmeal01** [comment]
@nikita my device has 2GB ram and im running os 5.0
