### ISSUE TITLE
Dragon island audio bug

### ISSUE THREAD

**Issue by jasper1412** [nikita36078/J2ME-Loader#110]
![screenshot_2018-02-17-02-44-41](https://user-images.githubusercontent.com/22563129/36336423-a1bc2616-13c2-11e8-9f6f-4a23009a8587.png)
![screenshot_2018-02-17-02-41-35](https://user-images.githubusercontent.com/22563129/36336441-c636d8c4-13c2-11e8-827b-e2c45fddf2b6.png)
![screenshot_2018-02-17-02-34-29](https://user-images.githubusercontent.com/22563129/36336448-cd22a5d2-13c2-11e8-9542-874c0a6a9538.png)

**Dragon Island**, resolution is `240x320`
This is fully playable o

As you can see, top side of the screen is blanked. I've got a sample on internet and it should go like this:

> ![images1](https://user-images.githubusercontent.com/22563129/36336471-f9b8da1c-13c2-11e8-89e1-6e299aa5fd95.png)
Status screen should appear on top side.

**Also, give attention to this one:**
> ![screenshot_2018-02-17-02-41-35](https://user-images.githubusercontent.com/22563129/36336510-5b82c8ac-13c3-11e8-97c1-fe882ce4250c.png)
As the text displayed, this will appear if level was completed.

What should it do is to play fanfare music as `Level Cleared!` text appear. Yes, it plays the fanfare, but sometimes. If you continuously played until you completed second or third level, fanfare music is now broken, either it plays but it was the continuation part of what position is played last on previous level, or it doesn't play anymore.

> For example: level 1 completion plays fanfare at 0:00 to 0:04 , next level completion plays fanfare at 0:04 to 0:08, another level completion and the fanfare music wont play anymore.

**Comment by oatmeal01** [comment]
Tried it using (Android)PPSSPP Emulator, graphics is fine. ![Di](https://user-images.githubusercontent.com/36059629/36336750-94df62ca-13c5-11e8-9bd0-6b1573fb61ee.png). There's a lot of issues regarding graphical bug. Hope nikita will fix it soon.

**Comment by oatmeal01** [comment]
Try to minimize and open the app from recent apps, the status  above will appear

**Comment by nikita36078** [comment]
![screenshot_j2me loader_20180217-115020](https://user-images.githubusercontent.com/3035571/36339514-cec2d45a-13d8-11e8-96f8-7ad8f037ba6a.png)
It is fixed now.

**Comment by jasper1412** [comment]
@nikita36078 great! Does the audio also fixed?

**Comment by nikita36078** [comment]
I didn't check it, but I didn't edit anything audio related, so it should be still buggy.

**Comment by oatmeal01** [comment]
@nikita how about flip images graphical bug like the arrow bugs from the game miami nights, world at war and Mu  blood empire. I found new issue like that on this games: God of war and Holy wars 240x320

**Comment by jasper1412** [comment]
**Status screen bug was fixed on 1.2.7.4**

**Comment by jasper1412** [comment]
I'll close this one. Game tested on actual java device, also doing the same.
