### ISSUE TITLE
Screen gets hidden on Naruto (clone?) game

### ISSUE THREAD

**Issue by jasper1412** [nikita36078/J2ME-Loader#111]
![screenshot_2018-02-17-09-49-51](https://user-images.githubusercontent.com/22563129/36336950-3fd04a80-13c8-11e8-8bf9-d486bc3b0056.png)

This game is called **Naruto Blood Fighting 2010**, resolution is `360x640`. I don't know if this is an official game, text was written in Chinese.

Looking at the screenshot above, you will see those blue image goes through the bottom-right side, together with the main screen. I don't know what's causing this but the screen literally goes on bottom-right. This is not the first time it happen on emulator as I tested out some games on early version of J2ME Loader.

> I'm talking about this [other game](https://drive.google.com/file/d/19axmKoHd9JRrwu_GzMlfz4mLZ-8SI4vI/view?usp=drivesdk) that also occuring the same bug.

**Comment by nikita36078** [comment]
Fixed
![screenshot_1519836401](https://user-images.githubusercontent.com/3035571/36800255-2771e038-1cc0-11e8-8b6d-413a63967934.png)
