### ISSUE TITLE
Add option to disable touchscreen on keypad-supported touchscreen games

### ISSUE THREAD

**Issue by jasper1412** [nikita36078/J2ME-Loader#112]
I know it sounds like stupid but sometime it'll be useful on some games. For example, **How to train your dragon**, resolution is `360x640`, the touch feature here is not good, there aren't any directional pad, just hold upper screen to move up, same goes for other direction, and it sucks, on my own opinion. Keypad is the best option here but the input fails as I touch the keypad, it also triggers the touchscreen feature.

You may be asking:
> Why not use versions that would not require touchscreen support?

Because of quality so I prefer highest possible screen resolution available. 

Thanks for consideration :)

**Comment by oatmeal01** [comment]
Maybe an update to the `keyboard buttons` is needed cause when you use keyboard on touchscreen games and tap a button it also touch through the button key and triggers the touch feature of the game. `NBA Pro 2k10` also has a bad controls i prefer using directional button keys.

**Comment by jasper1412** [comment]
I think , just putting 'Disable Touchscreen' inside on '[Common Settings]' is enough to fix this issue.

**Comment by nikita36078** [comment]
This option is added in the new version.
