### ISSUE TITLE
Kamikaze 2: way of ninja lags and suddenly exits

### ISSUE THREAD

**Issue by jasper1412** [nikita36078/J2ME-Loader#113]
![screenshot_2018-02-17-17-32-26](https://user-images.githubusercontent.com/22563129/36339915-8f852e64-140a-11e8-8b4b-9fec42f9561d.png)

This is **Kamikaze 2: Way of Ninja**, screen resolution is `352x416`
The game sometimes lags, only on this screen resolution. I've tested lower resolution like 240x320 and it was okay.

The main reason here is that it suddenly exits after some time playing:

> This is what I've got always after 3-5 minutes of playing:
![screenshot_2018-02-17-17-35-05](https://user-images.githubusercontent.com/22563129/36339950-294bbcde-140b-11e8-9afd-505ad3fcfc89.png)
The screen goes to `Authors` (as it labeled on the Main Menu of the game) and then close/exits completely.

I tried another emulator to see how it behaves, and I found out that the game tries to go `Airtime`, or simply wants to connect through the internet. We can't see this prompting on J2ME Loader as it always allows any permissions the app requested. ( I mentioned this on #107 )

But even though it connects through the internet, it still closes.

Again, on another emulator, I tried installing it using its `.jad` method to see how it works. It was a success! Suddenly closes no more.

As of 1.2.7.3, J2ME Loader supports only the method `.jar` for installation. ( there is a request for it on #98 ).

**Comment by oatmeal01** [comment]
have you tried this in 1.2.7.8 version, it has jad support now

**Comment by oatmeal01** [comment]
have you tried this in 1.2.7.8 version

**Comment by jasper1412** [comment]
yes, the main problem here is the installation method so as jad installation is not yet implemented on J2ME-Loader, those demo thing still persist on this game.

**Comment by oatmeal01** [comment]
1.2.7.8 supports jad installation

**Comment by jasper1412** [comment]
oh my bad! I didnt look at the files. gonma check this now. thanks.

**Comment by jasper1412** [comment]
Fixed on 1.2.7.8
