### ISSUE TITLE
Silent Hill 1 and 2 constantly hangs

### ISSUE THREAD

**Issue by jasper1412** [nikita36078/J2ME-Loader#114]
**Silent Hill**, screen resolution is `320x240`
> ![screenshot_2018-02-17-20-57-15](https://user-images.githubusercontent.com/22563129/36341211-ebc8a5aa-1425-11e8-8a64-a5e1d8d80820.png)

**Silent Hill 2**, screen resolution is `240x400`
> ![screenshot_2018-02-17-20-51-21](https://user-images.githubusercontent.com/22563129/36341232-35df3532-1426-11e8-9717-e632018188d1.png)

Both have the same vendor, **Konami**. The third installment does not feature any problems, held by **Connect2Media**.

It constantly hangs at any time without any prompt. Like this one:
**Silent Hill**
> ![screenshot_2018-02-17-20-57-46](https://user-images.githubusercontent.com/22563129/36341281-c25ab5d6-1426-11e8-98b9-6252f48cad29.png)
Hangs before main menu appears.

> ![screenshot_2018-02-17-20-56-53](https://user-images.githubusercontent.com/22563129/36341295-0a891320-1427-11e8-82f6-dc27dafac348.png)
This one made it in-game, but then hangs right after I press some key.

**Silent Hill** was meant to be played at `320x240` (landscape).
**Silent Hill 2** was meant to be played at `240x400` (portrait).

**This is where the weird part comes in:** 

- On **Silent Hill** , those bugs only occur when the **phone orientation** is in landscape mode. Not to confuse with screen resolution, I ddn't swap the values, still in `320x240`, just my phone orientation is in landscape. When you put your **phone orientation** in portrait mode, the bug is not triggered.
- Same thing goes with **Silent Hill 2**. Do the vice versa of what I mentioned above.

To make myself clear, I provided some screenshots that would explain this:

> ![screenshot_2018-02-17-21-26-02](https://user-images.githubusercontent.com/22563129/36341479-e7cb3496-1429-11e8-8838-860129deba69.png)
**Silent Hill** playing it on portrait mode

> ![screenshot_2018-02-17-21-26-55](https://user-images.githubusercontent.com/22563129/36341497-117a0cb8-142a-11e8-8425-a9f262470aeb.png)
**Silent Hill 2** playing it on landscape mode

As you can see on the screenshots above, I can freely navigate inside the game, without any occuring problems, but it didn't follow the right screen orientation.

**Comment by jasper1412** [comment]
issue on this game got worse on `1.2.8.1` as the game sometimes hangs completely, making it unresponsive.

**Comment by nikita36078** [comment]
Yes, I noticed huge performance drop, will release new version soon.

**Comment by nikita36078** [comment]
Ok, I don't see this issue in the both games now.
