### ISSUE TITLE
Most games on Digital Chocolate had a blank screen

### ISSUE THREAD

**Issue by jasper1412** [nikita36078/J2ME-Loader#115]
**Pyramid Bloxx**, resolution is 240x320

This is how it behaves on the emulator:
> ![screenshot_2018-02-17-23-03-39](https://user-images.githubusercontent.com/22563129/36342268-d3754ff6-1436-11e8-8fa8-a0c9256f9c39.png)
Yes, this is the screenshot, only blank screen.

The audio is playing on background but the screen isn't showing. I tried `Immediate processing mode` and still nothing.

**Comment by amarcioz** [comment]
Same problem with other Digital Chocolate games. Can you test other Digital Chocolate games?

**Comment by jasper1412** [comment]
@amarcioz now that you mentioned it,I tried tested other games they release and found  that many of them would not boot properly on the emulator.

**Comment by oatmeal01** [comment]
same with EA, Glu, net lizard

**Comment by jasper1412** [comment]
@oatmeal01 I tried some of Glu releases, most of it was fine. For EA, there is only one bug that I found and it was their tetris revolution and was reported here.

**Comment by oatmeal01** [comment]
Try bundled games from ea, the screen is blank

**Comment by oatmeal01** [comment]
Try bundled games from ea, the screen is blank

**Comment by jasper1412** [comment]
Fixed
![screenshot_2018-02-22-21-23-37](https://user-images.githubusercontent.com/22563129/36540812-bdb86868-1816-11e8-91ad-dca1b9cdbb43.png)
