### ISSUE TITLE
Add a note to J2ME Loader's description on Google Play that "in-app purchases" are for donations

### ISSUE THREAD

**Issue by jan-kleks** [nikita36078/J2ME-Loader#116]
You can also write there something like: "If my app brought back the fond memories of your favorite dumbphone consider donating. I would really appreciate that, and it will help the J2ME Loader development." :)

**Comment by AdityaMH** [comment]
anything app with paid/money transaction (buy a item/donate) will showed "in-app purchase". But that was great idea. it will better if placed in Google description and "About" page (than showing in upper "Exit" without description donate mean).

Hmm... "your dumbphone favorite"?

**Comment by AdityaMH** [comment]
anything app with paid/money transaction (buy a item/donate) will showed "in-app purchase". But that was great idea. it will better if placed in Google description and "About" page (than showing in upper "Exit".

Hmm... "your favorite dumbphone"?

**Comment by nikita36078** [comment]
Yes, it is a good idea, in-app purchases can scare some people  :)

**Comment by jasper1412** [comment]
talking about IAP's, why don't use google play services for donation? I don't have Paypal so the only way I do transaction was mobile billing.

**Comment by nikita36078** [comment]
Version from Google play uses in-app purchases for donations, it is exactly what we are talking about here.

**Comment by jasper1412** [comment]
@nikita36078 sorry, i didn't follow 😅
