### ISSUE TITLE
Rally 3D graphical issues

### ISSUE THREAD

**Issue by jasper1412** [nikita36078/J2ME-Loader#117]
I don't know if 3D games was supposed to be reported as @nikita36078 clearly claims there is a limited support on 3D, this may be helpful for future references.

> ![screenshot_2018-02-18-08-16-35](https://user-images.githubusercontent.com/22563129/36346957-3b4a9070-1485-11e8-8f41-ae4cdbe7eade.png)
**Rally 3D**, screen resolution is `240x320`.

There is a graphical issue related to 3D models not appearing in game, same thing for road texture.

**Comment by nikita36078** [comment]
![screenshot_j2me loader_20180219-115845](https://user-images.githubusercontent.com/3035571/36369879-f9f1ba92-156d-11e8-88cb-4bc9a1c6c96e.png|width=500)
Well, I've got some progress...

**Comment by jasper1412** [comment]
wow! look at that progress!

**Comment by jasper1412** [comment]
this is what I've got on 1.2.7.4 update on this game
![screenshot_2018-02-21-19-08-36](https://user-images.githubusercontent.com/22563129/36478720-c82282f6-1740-11e8-9563-4846753b0777.png)
Enabling `Immediate processing mode` on the game would crash the app.

**Comment by nikita36078** [comment]
What phone do you use?

**Comment by jasper1412** [comment]
Jiayu S3 Plus
