### ISSUE TITLE
God of War Betrayal lags issues

### ISSUE THREAD

**Issue by kelve00** [nikita36078/J2ME-Loader#119]
The game works  

1 - Graphic errors
2 - Delays in the image and audio. 
3 - Slow FPS 

Thanks for this amazing emulator.

God of War: Betrayal  
Resolution: 240x320 Nokia S60  
Version: 1.4.62

**Comment by oatmeal01** [comment]
Graphical Bug Fixed. Download J2Me Loader 1.2.7.5 version

**Comment by kelve00** [comment]
graphic bugs have been fixed :)

- I still have delays in audio and slow FPS in version: 1.4.66

I uploaded version 1.4.66: https://mega.nz/#!UJNgga5B!xbIH2ImOzPh3AJ1P4Lonmoz5gWC5FeiCzWqOWyiFPKI


- with the new version 1.2.7.5 I have no delays in audio, fast FPS in God Of War Version 1.4.20

**Comment by msdos** [comment]
@kelve00 what size in bytes is the 1.4.20 version you're talking about?

**Comment by nikita36078** [comment]
Version 1.4.66 seems to be fixed now

**Comment by Lukeluke98** [comment]
The God of War series is really good. It's worth playing this game, especially since one of the parts was released on PC. If you haven't played yet, I recommend [this shop](https://royalcdkeys.com/products/god-of-war-steam-cd-key) with the God of War for pc offer.
