### ISSUE TITLE
Tower Bloxx 3D: texture houses doesn't show

### ISSUE THREAD

**Issue by zarkon0** [nikita36078/J2ME-Loader#120]
hi.

In Tower Bloxx 3D the textures of the falling houses aren't show.

**Comment by nikita36078** [comment]
Yes, I'm working on it.
![screenshot_j2me loader_20180219-121017](https://user-images.githubusercontent.com/3035571/36370088-c9499ba2-156e-11e8-87c2-3695eeaf69a7.png)

**Comment by amarcioz** [comment]
It is necessary to say what the resolution of the game is.

**Comment by zarkon0** [comment]
Great!

**Comment by hex007** [comment]
@nikita36078  Nice work. Hope to port it to FreeJ2ME later

**Comment by nikita36078** [comment]
@hex007 It should be pretty easy to port, licensing is the main problem (EPL code can't be used in GPL project).
