### ISSUE TITLE
Tower Bloxx Revolution graphical issues

### ISSUE THREAD

**Issue by jasper1412** [nikita36078/J2ME-Loader#123]
> ![screenshot_2018-02-21-20-12-19](https://user-images.githubusercontent.com/22563129/36479412-9cec36f6-1743-11e8-8a43-fca5c6f31938.png)
**Tower Bloxx Revolution**, screen resolution `360x640`

This captured on level select screen of the game:
> ![screenshot_2018-02-21-20-12-06](https://user-images.githubusercontent.com/22563129/36479477-d11ba5e2-1743-11e8-91b0-78a74cfdbf0c.png)
Background image seems do not match with their respective places

This captured before in-game starts:
> ![screenshot_2018-02-21-19-20-24](https://user-images.githubusercontent.com/22563129/36479540-01e0aaa6-1744-11e8-8f83-f1dc2bac5a90.png)
What's wrong with her eyes?
Also, try to look at the hint bar, those borders aren't aligned well

**Comment by nikita36078** [comment]
What is the game version? I don't have such problem at 1.0.0.

**Comment by jasper1412** [comment]
@nikita36078 [This one](https://drive.google.com/file/d/1K7C3iJFNFaedkHPk2JdK8hBF5LbGtwzd/view?usp=drivesdk), running on 360x640 v1.0.0 also

**Comment by nikita36078** [comment]
Fixed.

**Comment by jasper1412** [comment]
yes everythings fine now
