### ISSUE TITLE
Tomb Raider Legend Tokyo graphical issues

### ISSUE THREAD

**Issue by jasper1412** [nikita36078/J2ME-Loader#127]
**Tomb Raider Legend Tokyo**, screen resolution `240x320`
![screenshot_2018-02-22-22-20-33](https://user-images.githubusercontent.com/22563129/36545744-94d881e0-1824-11e8-8804-480be569b3c6.png)
![screenshot_2018-02-22-22-25-14](https://user-images.githubusercontent.com/22563129/36545752-9e25738e-1824-11e8-9efa-a0d770bb2e89.png)

This is a 3D game. Beside graphics issue, I'm not sure if there's also bug on controls on this game.

**Comment by UroshUchiha** [comment]
I can at least confirm that the game is fully playable. I finished it from start to end with the latest update. Those graphical bugs apparently appear only when a black background is present. Like stuff behind broken windows and between buildings. Something similar happens with Tomb Raider Underworld 3D in certain areas.

**Comment by nikita36078** [comment]
Fixed.
