### ISSUE TITLE
Heroes of War Sandstorm crashes before gameplay

### ISSUE THREAD

**Issue by jasper1412** [nikita36078/J2ME-Loader#128]
![screenshot_2018-02-22-23-11-06](https://user-images.githubusercontent.com/22563129/36546292-01c60498-1826-11e8-9453-86296aa2f0ed.png)
**Heroes of War Sandstorm**, screen resolution `any`

After choosing `Start Game`, the game loads and then crashes. This is a 3D-heavy game so I think it is what those limitations @nikita36078 are referring to.

**Comment by oatmeal01** [comment]
This game is also unplayable on (PC)KEmulator. It also hangs when moving the character.

**Comment by jasper1412** [comment]
meaning it will buy so much time for these to be resolved

**Comment by oatmeal01** [comment]
try it in 1.2.8.1 j2me loader version, with 1.1.0 game midlet

**Comment by jasper1412** [comment]
I think K800i version midlet causes the issue. i tried N95 midlet and works properly.
