### ISSUE TITLE
Bounce (By Nokia) - Visual glitches

### ISSUE THREAD

**Issue by UroshUchiha** [nikita36078/J2ME-Loader#129]
![screenshot_2018-02-23-09-46-08](https://user-images.githubusercontent.com/36758864/36585869-ddfa8ed0-187f-11e8-8fad-fc51f25e83e5.png)

Rings, the ball and certain powerups don't render correctly. 
Versions 1.9 and 1.24 tested, both 128x128
Android version: 4.2.1

The game can be completed from start to end without any gameplay issue though.

**Comment by nikita36078** [comment]
Fixed
![screenshot_1519414781](https://user-images.githubusercontent.com/3035571/36613494-b88d974e-18ea-11e8-8988-a19fdb1a523e.png)

**Comment by UroshUchiha** [comment]
Awesome! Thanks for being so quick! Even KEmulator has an issue with this
