### ISSUE TITLE
Crash Nitro Kart 1 - Error on startup

### ISSUE THREAD

**Issue by UroshUchiha** [nikita36078/J2ME-Loader#130]
![screenshot_2018-02-23-09-46-49](https://user-images.githubusercontent.com/36758864/36585967-2dfc4270-1880-11e8-8e7f-3c5d9660f217.png)

This popup appears when trying to run the game.
Versions 1.4.3 Nokia 6230 and 1.6.0 tested, both 128x128
Android version: 4.2.1

**Comment by UroshUchiha** [comment]
This error no longer appears. After the latest update you can get into the game main menu. But if you try to start a race the emulator hangs.

**Comment by UroshUchiha** [comment]
After the v1.3.8 uplade of J2ME Loader the version v1,4,3 of this game starts just fine, but the version 1.6.0 still hangs after the race starts.

**Comment by nikita36078** [comment]
Fixed, as well as #131.
