### ISSUE TITLE
Crash Twinsanity 2D - Error on startup

### ISSUE THREAD

**Issue by UroshUchiha** [nikita36078/J2ME-Loader#131]
![screenshot_2018-02-23-09-46-49](https://user-images.githubusercontent.com/36758864/36586013-5b5c5a7a-1880-11e8-8616-52bf0053706d.png)

Same error like the previous issue I reported with Crash Nitro Kart 1. This popup appears when trying to run the game.
Version 1.7.1 176x208 tested
Android version: 4.2.1

**Comment by UroshUchiha** [comment]
This error no longer appears. After the latest update you can get into the game. But if you press any keyboard button the emulator hangs.

**Comment by nikita36078** [comment]
Fixed.
