### ISSUE TITLE
Prince of Persia Warrior Within - Hangs/Crashes

### ISSUE THREAD

**Issue by UroshUchiha** [nikita36078/J2ME-Loader#134]
![screenshot_2018-02-23-09-50-10](https://user-images.githubusercontent.com/36758864/36586258-62392804-1881-11e8-9313-3d723f995e27.png)

Hangs/Crashes after the initial loading screen.
Version 1.0.5 352x416 N90 Hangs, version 1.0.2 240x320 crashes
Android version: 4.2.1

**Comment by oatmeal01** [comment]
1.0.5 352x416 works fine with my device.

**Comment by UroshUchiha** [comment]
I'll try with another device later today. Cause nothing I do with settings fixes the endless loading on my current device.

**Comment by oatmeal01** [comment]
maybe ram problem tho

**Comment by UroshUchiha** [comment]
It is an old model, Huawei G700. But it has 1.3GB free RAM before starting POPWW. Surely that has to be enough? Considering I can run POPTT, POP2008 and POP The Forgotten Sands on it. Currently playing Tomb Raider Underworld 3D as well without issues (not counting slight slowdowns here and there).

**Comment by amarcioz** [comment]
@UroshUchiha Tomb Raid 3D 240x320 does not work for me.
Samsung J1 2016

**Comment by UroshUchiha** [comment]
I'm playing 360x640 of Tomb Raider Underworld 3D version 1.8.8 with Filter disabled and Immediate processing mode enabled.  
Before the current J2ME Loader update it also worked fine but Lara's model didn't render, she was transparent. Not it works fine.

**Comment by UroshUchiha** [comment]
Version 1.0.2 is working now.
Version 1.0.5 still doesn't work on my device. But tested it in NoxPlayer Android Emulator and it works fine. So yeah, apparently this game is heavy. Even though my device can run more demanding games. Something is off with Warrior Within.

All in all, fixed.
