### ISSUE TITLE
Blades and Magic 3D does not work.

### ISSUE THREAD

**Issue by amarcioz** [nikita36078/J2ME-Loader#138]
Blades and Magic 3D 240x320 and 176x220 does not work. This message appears.
![180224_152706_rmscr](https://user-images.githubusercontent.com/35005836/36633789-118bb6ac-197a-11e8-943e-acd07ebce3db.jpg)

**Comment by nikita36078** [comment]
Emulator doesn't support games for MascotCapsule 3D (most 3d games for Sony Ericsson), so try version for Nokia, it should work correctly.
