### ISSUE TITLE
Template for issue submissions -- to facilitate valid bug reporting

### ISSUE THREAD

**Issue by jan-kleks** [nikita36078/J2ME-Loader#139]
Since your app is now on Google Play you should see even more people reporting bugs. To facilitate valid reports consider creating [an issue template for your repository](https://help.github.com/articles/creating-an-issue-template-for-your-repository/).

Ask people in that templete to provide all the things that would be useful for you when debugging (Android version, specific info about JAR files, etc.).

**Comment by nikita36078** [comment]
I added it, it definitely should be useful.
