### ISSUE TITLE
Gish hangs while progressing on another level

### ISSUE THREAD

**Issue by jasper1412** [nikita36078/J2ME-Loader#140]
![screenshot_2018-02-25-08-49-02](https://user-images.githubusercontent.com/22563129/36636833-0424421a-1a09-11e8-8d15-0eef2af32fcb.png)
**Gish**, screen resolution `any`

It has a bug that will occur after you finished any level on the game.

> ![screenshot_2018-02-25-08-53-35](https://user-images.githubusercontent.com/22563129/36636850-623a9552-1a09-11e8-9a1b-8afc03edd34f.png)
Hangs after beating the level.

To make progress again, you'll need to re-open the game and choose `Load Game` on game menu to continue through the next level.

**Comment by oatmeal01** [comment]
same issue with Metal Slug Mobile Impact

**Comment by jasper1412** [comment]
fixed in 1.2.7.8
![screenshot_2018-03-02-08-39-32](https://user-images.githubusercontent.com/22563129/36877464-4c690778-1df5-11e8-99ea-a970320b4949.png)
