### ISSUE TITLE
Multitouch bug

### ISSUE THREAD

**Issue by jack1432** [nikita36078/J2ME-Loader#141]
When I press two buttons on the keyboard at the same time for a while when I release the buttons one of them remains as if it were being tightened even after I have released them, this happens often when I am playing in the J2ME Loader
![screenshot_2018-02-25-00-10-45](https://user-images.githubusercontent.com/36806488/36638092-cdc30f4c-19e2-11e8-933c-8b2a33402f49.png)

In this image I am not touching the cell phone screen and still the button is still being pressed
Image Game: Gangstar - Crime City
Game resolution: 240: 320

**Comment by jack1432** [comment]
maybe it's a problem on the platform because the bug does not happen in version 6.0 and 7.0 of Android. I encountered the error only in version 5.1 and 4.1.

**Comment by AdityaMH** [comment]
For 1.3.1 d-pad layout always on upper left even edited/saved before (can't saving d-pad layout position).
And for some game can't moving keyboard (pro paint mobile for example).

**Comment by nikita36078** [comment]
Fixed.

**Comment by nikita36078** [comment]
I think it's finally fixed :)
