### ISSUE TITLE
[Request] Additional Screen Presets in Screen Options

### ISSUE THREAD

**Issue by oatmeal01** [nikita36078/J2ME-Loader#142]
Please add 176x208, 240x400 and 352x416 in Screen Presets. Thanks!

**Comment by AdityaMH** [comment]
And 132x176 (very rare but some old games have screen resolution like that), 208x208 too. But this request not too important than customize screen orientation ( #46 ) and "show "qwerty" keyboard" button ( #83 ).

**Comment by nikita36078** [comment]
In version 1.6.0 you can add your own screen presets
