### ISSUE TITLE
Doom 2 rpg - Weird graphical glitch

### ISSUE THREAD

**Issue by Maltbrew** [nikita36078/J2ME-Loader#145]
Hey there! 

I seem to be only one who can’t get Doom 2 rpg to run. It shows 90% of the game except for the actual gameworld. That means map, border, speech, picked up items info, pause screen. It’s reslly strange and I have no idea what’s wrong. 

![2018-02-26 04 10 25](https://user-images.githubusercontent.com/36845466/36667614-be7dab84-1aee-11e8-8467-38f02126d17c.jpg)

**Comment by nikita36078** [comment]
Finally fixed :)
![screenshot_1519846611](https://user-images.githubusercontent.com/3035571/36809123-14dab68a-1cd8-11e8-9b17-9359c9240e72.png)
![screenshot_1519846663](https://user-images.githubusercontent.com/3035571/36809124-14f61cae-1cd8-11e8-9a68-460240c91d4d.png)

**Comment by Maltbrew** [comment]
<3
