### ISSUE TITLE
Rayman 3 (132x176) Error

### ISSUE THREAD

**Issue by telanus** [nikita36078/J2ME-Loader#146]
The game runs like normal, but the game sprites doesn't get drawn at all, thus rendering the game unplayable.

MIDlet-Name: Rayman3
MIDlet-Description: Rayman3 for Nokia 7210
MIDlet-Version: 1.1.3

EDIT: does not happen in the 240x320 version

**Comment by nikita36078** [comment]
Does problem still exists? I can't find version for Nokia 7210, but siemens version works without any bugs.

**Comment by telanus** [comment]
Hi. Tested with 1.2.8.4 and it's still there

[Rayman3.jar.zip](https://github.com/nikita36078/J2ME-Loader/files/1847914/Rayman3.jar.zip)
note: just delete the zip part of the name

**Comment by nikita36078** [comment]
Fixed.
![rsz_1screenshot_j2me_loader_20180828-223934](https://user-images.githubusercontent.com/3035571/44746711-ce611f80-ab13-11e8-95f3-74d6eb21b9a2.png)
