### ISSUE TITLE
Colin Mcrae Rally 4 error

### ISSUE THREAD

**Issue by telanus** [nikita36078/J2ME-Loader#147]
I get the following error with the game:

> No Virtual method set Ticker(javax/microedition/lcdui/Ticker;)V in class Lb; or it's super classes (declaration of 'b' appears in /data/data.ru.playsoftware.j2meloader/tnp_dex/converted.dex)

MIDlet-Name: colin mcrae rally 4
MIDlet-Version: 1.0
MicroEdition-Profile: MIDP-2.0

**Comment by nikita36078** [comment]
I didn't find bug in the game, but I think I fixed this bug now :)
