### ISSUE TITLE
add the option to clear saved data from converted games

### ISSUE THREAD

**Issue by jack1432** [nikita36078/J2ME-Loader#148]
Hi, I think it would be nice if you had the option of clearing saved data from converted games in J2ME Loader because it is annoying to have to delete a game and convert again to start again, and also that not all games have the option to clear saved data , thank you.

**Comment by nikita36078** [comment]
Done.
![screenshot_1519675333](https://user-images.githubusercontent.com/3035571/36692468-2b631374-1b49-11e8-9222-c4d47d63b29f.png)

**Comment by jack1432** [comment]
thank you.😊

**Comment by AdityaMH** [comment]
Why just go folder /sdcard/J2ME-Loader/data/~game name~ via filebrowser and then deleted that folder?

**Comment by nikita36078** [comment]
Well, menu option is more easier, I think :)

**Comment by jack1432** [comment]
I also think it better to have this option in the menu because you do not have to leave the application to clear the data of the games.

**Comment by oatmeal01** [comment]
this is a useful feature cause some of games don't have reset data

**Comment by oatmeal01** [comment]
@nikita about the costumization of Background and Colors, the background, label, button, outline colors by the way. Can you make the settings global so that you will not set the colors in every game you installed. One Color Configuration for all of the games. Thanks!
