### ISSUE TITLE
[Request] Global Config for Color Customization

### ISSUE THREAD

**Issue by oatmeal01** [nikita36078/J2ME-Loader#152]
## Background, Button, Label, Outline Color
>\- Can you please separate color customization and make it as global config for all of the games installed. I think this is a good idea so that you can set the colors once instead of setting each colors everytime you install a game.

<p align="center"><img height="300" width="176" src="https://user-images.githubusercontent.com/36059629/36712086-f88a128a-1bc1-11e8-9d44-4274303028e4.png"/></p>

**Comment by AdityaMH** [comment]
And global keypad layout too, but the answer is on #90

**Comment by oatmeal01** [comment]
I think it's a better idea if the keypad/keyboard is not global . Why? So that you can costumize the keyboard layout of each game according to the game controls.

**Comment by AdityaMH** [comment]
Why not try add feature checked/unchecked "Using global setting" (if adding feature "Edit global keypad/color") if you scared about big thumb problem or want using different color instead global color?

**Comment by AdityaMH** [comment]
This feature now added. I think this issue need to be closed.
