### ISSUE TITLE
Can't access SD Card through sliding file browser

### ISSUE THREAD

**Issue by namandixit** [nikita36078/J2ME-Loader#153]
**Emulator version:** 1.2.7.7-play

**Description of the issue:** The sliding menu (that opens from left and allows to browse filesystem) opens up in default `/storage/emulated/0` directory. The SD card on my phone (Moto G4 with Android 7.0) is mounted on `/storage/0207-A4F2` (the last alphanumeric sequence is generated randomly). Since thw file browser does not allow to go up from initial directory, it's impossible to browse to SD card.

**Possible Fix:** Either give an option to browse up from any directory (`..`) or give an option to input the default directory (by manually typing it) in which the file browser should be located upon startup.

**Comment by namandixit** [comment]
Also, while the directory `/storage` is user-readable, `/storage/emulated` is not. Most file broswers deal with this issue by showing an error message upon browsing to `/storage/emulated` but still allowing to go up from there to ` /storage`.

**Comment by nikita36078** [comment]
I unlocked back button, now you can browse all available directories.
