### ISSUE TITLE
4x4 Extreme Rally: World Tour - graphics issue

### ISSUE THREAD

**Issue by nikita36078** [nikita36078/J2ME-Loader#154]
**Emulator version:**
1.2.7.7

**Game version:**
1.0.2

**Game resolution:**
240x320

**Description of the issue:**
An textures on the screen repeat without clearing, the game is absolutely unplayable.

![screenshot_j2me loader_20180227-100858](https://user-images.githubusercontent.com/3035571/36716280-c92b04f2-1baa-11e8-8579-c197b3996334.png)

**Comment by AdityaMH** [comment]
But for me, its works nicely even sound/MIDI still stopped if race restarted three times or above (ver: 1.0.2, 240×320 + BT)

**Comment by oatmeal01** [comment]
**v1.0.2**
>Nokia 6280 / 5300 (240x320)
378.7kB 
Issue: Messy graphics like the issue above

>Motorola E1000 (240x320)
366.4kB

>Nokia E50 / N95 / N82 / N86 (240x320)
377.0kB
Issue: No graphic issue but the gameplay is laggy.

>SonyEricsson K800i (240x320)
418.4kB
Issue: None (Recommended version)

**Comment by nikita36078** [comment]
Fixed.
