### ISSUE TITLE
4x4 Extreme Offroad graphics issue

### ISSUE THREAD

**Issue by jasper1412** [nikita36078/J2ME-Loader#155]
**Emulator version:**
1.2.7.7

**Game version:**
1.0.0

**Game resolution:**
``360x640``

**Description of the issue:**
![screenshot_2018-02-27-16-05-43](https://user-images.githubusercontent.com/22563129/36717361-c0590bfc-1bd8-11e8-896b-ac3c45df7716.png)
Road texture is missing here.

**Comment by nikita36078** [comment]
It isn't a bug, just wrong resolution, game works good with 240*320.
