### ISSUE TITLE
File Browser Touch Through Bug

### ISSUE THREAD

**Issue by oatmeal01** [nikita36078/J2ME-Loader#156]
**Emulator version:** 1.2.7.7 and later
>File browser seems to touch through the list of installed games(e.g. when accessing an empty folder in  file browser you can touch through it and can freely scroll and touch the list of the games. Please fix file browser bug. 

<p align="center"><img height="300" width="176" src="https://user-images.githubusercontent.com/36059629/36722301-20e5d856-1be8-11e8-8f29-73d6a4174110.png"/></p>

**Comment by nikita36078** [comment]
Fixed.

**Comment by oatmeal01** [comment]
much thanks!

**Comment by oatmeal01** [comment]
Is it also possible to apply this to `keyboard`cause it is also touch through. Some touchscreen games have a bad controls and i use `keyboard directional keys` but it also touch through the game and ruin the movement of the gameplay.

**Comment by nikita36078** [comment]
Fixed.
