### ISSUE TITLE
Simultaneous hardware and virtual keyboard support

### ISSUE THREAD

**Issue by aNNiMON** [nikita36078/J2ME-Loader#157]
I would like to use Xperia Pro hardware keyboard. However, after 9b28497697d42f52689f7ff1de8c3dd4237141b3 commit I need to disable on-screen keyboard so that the hardware keyboard can be processed. Xperia Pro doesn't support all bindings, e.g. numeric keys can be typed by pressing <kbd>Alt+Q</kbd>...<kbd>Alt+P</kbd>, there is no DPAD_CENTER etc.
Can you add simultaneous hardware and virtual keyboard support? I want to use hardware arrow keys and other on-screen keys.

**Comment by nikita36078** [comment]
Yes, I broke it by accident, will revert it now, thanks for the hint. By the way, I'm working on keybinding feature since current binding isn't really convenient.

**Comment by aNNiMON** [comment]
Resolved with 6b184abf5a3c45a8290964ee9de6f21f19e4c69c
