### ISSUE TITLE
The game Darkest Fear causes 2 strange bugs in the emulator

### ISSUE THREAD

**Issue by amarcioz** [nikita36078/J2ME-Loader#161]
Emulator version: 1.2.7.7

Game version: 1.55

Game resolution: 240x320 

The game causes 2 strange bugs in the emulator.

First bug:
![180227_234140_rmscr](https://user-images.githubusercontent.com/35005836/36767339-d23177e8-1c18-11e8-8d60-fe79f0b628bc.jpg)

Second bug: Even leaving the game and closing the emulator, the game's audio continues to play in the background.

**Comment by jasper1412** [comment]
This was from the midlet option itself I think. I also encounter this one on another game.

**Comment by AdityaMH** [comment]
it's not bug after all.. some games/apps who emulated in real j2me phone have this issue.

**Comment by nikita36078** [comment]
Options without text aren't a bug, it is how app adds them.
Second bug is already mentioned in #136.
