### ISSUE TITLE
Devil may cry 3D can't run

### ISSUE THREAD

**Issue by fireclouu** [nikita36078/J2ME-Loader#162]
**Emulator version:**
1.2.7.7

**Game version:**
1.0.1

**Game resolution:**
240x320

**Description of the issue:**
![screenshot_2018-02-28-20-33-37](https://user-images.githubusercontent.com/22563129/36790964-6e6f29bc-1cd1-11e8-8c2a-1355d122a3d3.png)
I dont really have an idea to explain this error.

**Comment by nikita36078** [comment]
The same problem as in #138 - emulator doesn't support MascotCapsule3D games.

**Comment by nikita36078** [comment]
Fixed
