### ISSUE TITLE
Real Football 2018 - Unable to Install

### ISSUE THREAD

**Issue by oatmeal01** [nikita36078/J2ME-Loader#163]
**Emulator version:**
1.2.7.7

**Game version:**
1.0.0 ( for Samsung GT-S5230)
1.0.1 (for Nokia 5800)

**Game resolution:**
``(240x400, 360x640)``

**Description of the issue:**
``(Unable to install. J2ME Loader will crash when installing)``

<img height="300" width="176" src="https://user-images.githubusercontent.com/36059629/36791143-ec901022-1cd1-11e8-8403-a0ea40b0af71.png"/>

**Comment by AdityaMH** [comment]
and 320×240, ver: 1.0.0 can't support input name because they using keyboard not keypad alphanumeric. but when normal playing still can using virtual keypad.

**Comment by nikita36078** [comment]
Fixed.
