### ISSUE TITLE
Hummer, Jump & Race 3D bug

### ISSUE THREAD

**Issue by jasper1412** [nikita36078/J2ME-Loader#164]
**Emulator version:**
1.2.7.7

**Game version:**
1.0.0

**Game resolution:**
320x240

**Description of the issue:**
![screenshot_2018-02-28-22-05-20](https://user-images.githubusercontent.com/22563129/36791816-be944eb6-1cd3-11e8-9efa-eb85a03b1e43.png)
- Texture of environment seems to be adapted by car texture
- Car shadow not showing
- Is it me or the controls on this game are messy? pressing right-arrow key turns the car to the right even though I tap it immediately

**Comment by jasper1412** [comment]
some texture seems to be fixed on 1.2.7.8
> ![screenshot_2018-03-02-08-29-48](https://user-images.githubusercontent.com/22563129/36877183-e2e69cd0-1df3-11e8-92a1-ba27635779f4.png)
take a look at the blue car here, its window panel seems to possess the same bug

**Comment by jasper1412** [comment]
Rally 3D also had these bug
> ![screenshot_2018-03-03-18-02-20](https://user-images.githubusercontent.com/22563129/36933084-57d27b2a-1f0e-11e8-8107-ec49833f54a9.png)
on the car windows

**Comment by jasper1412** [comment]
`1.2.8.1` fixes those green scanlines

**Comment by nikita36078** [comment]
Fixed.
