### ISSUE TITLE
Crash Mutant Island - Startup Error

### ISSUE THREAD

**Issue by oatmeal01** [nikita36078/J2ME-Loader#165]
**Emulator version:**
1.2.7.7

**Game version:**
1.0.0, 1.0.1 (Touchscreen Versions)

**Game resolution:**
``(240x400, 480x800)``

**Description of the issue:**
``(Error occurs when opening the game.) ``

<img height="300" width="176" src="https://user-images.githubusercontent.com/36059629/36792244-04849394-1cd5-11e8-9624-a17f9424988c.png"/>

**Comment by nikita36078** [comment]
It happens because the game wasn't installed with .jad file. Okay, I will add .jad support in the next version.

**Comment by oatmeal01** [comment]
Fixed in 1.2.7.8 without installing thru jad

**Comment by oatmeal01** [comment]
Fixed in 1.2.7.8 without installing thru jad

**Comment by oatmeal01** [comment]
Fixed in 1.2.7.8 without installing thru jad

**Comment by nikita36078** [comment]
The .jad file doesn't contain `Glu-Idle-Threshold: 0`, that's why the game crashes.
