### ISSUE TITLE
Blood+ just crashes after opening

### ISSUE THREAD

**Issue by jasper1412** [nikita36078/J2ME-Loader#166]
**Emulator version:**
1.2.7.7

**Game version:**
1.0.0

**Game resolution:**
480x800

**Description of the issue:**
Blood+ suddenly crashes on emulator.

**Comment by nikita36078** [comment]
It works now, the game should be installed through .jad.

**Comment by jasper1412** [comment]
@nikita36078 glad to hear that .jad is now supported :)
