### ISSUE TITLE
App tone composer working without sound

### ISSUE THREAD

**Issue by javi2man** [nikita36078/J2ME-Loader#167]
**Emulator version:**
1.2.7.7-open

**Game version:**
2.0

**Game resolution:**
``(For example, 240x320 or 640x360)``
Multi screen

**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)`
When using the app, no sound is played (with kEmulator sound is working ok)

**Comment by nikita36078** [comment]
Does this issue still exist in the last version? If yes, what is the exact app name?

**Comment by nikita36078** [comment]
Still no info, so I close the issue
