### ISSUE TITLE
KeyMapperActivity. Some buttons are not visible in landscape mode

### ISSUE THREAD

**Issue by aNNiMON** [nikita36078/J2ME-Loader#170]
![screenshot_2018-03-01-17-25-34](https://user-images.githubusercontent.com/1321838/36853450-3acdfdd0-1d77-11e8-8123-831587a7efeb.png)

**Comment by kelve00** [comment]
With this I can remap as xperia play keys?

**Comment by aNNiMON** [comment]
@kelve00 yes, you can. I've already tried it on Xperia Pro, works fine. Really useful feature. :+1:

**Comment by nikita36078** [comment]
Fixed in 8d08f541f39be5078ca15fa5603349074f7fbace.
