### ISSUE TITLE
app/game resets itself when putting J2me loader in background

### ISSUE THREAD

**Issue by javi2man** [nikita36078/J2ME-Loader#171]
**Emulator version:**

1.2.7.7-open
**Game version:**

**Game resolution:**
``(For example, 240x320 or 640x360)``

**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
When i use another app on  android device and leave J2me Loader in the background, then when i re open j2me loader the app/game converted previously that was running, automatically resets to the startup

**Comment by nikita36078** [comment]
What do you mean exactly? App/game restarts after j2me loader is reopened, right? Does it always happen?

**Comment by javi2man** [comment]
That java game restarts itself after i maximize j2me loader, it doesn't happen always but it happens to me very often

**Comment by nikita36078** [comment]
What is your device?

**Comment by javi2man** [comment]
Moto E1 with android 4.4.2

**Comment by oatmeal01** [comment]
i think i encountered this bug in some particular game.

**Comment by AdityaMH** [comment]
it. think, this issue happen when open via background* (*hold "home"/"menu" from home screen then click j2me loader image) if recent games installed before. to fix this, must clean/delete j2me loader background* /cache.

**Comment by javi2man** [comment]
AdityaMH when i click j2me loader image, sometimes appears this error: "width and height must be >0"

**Comment by SrCuchillo** [comment]
I need help, I try to emulate a game, the app starts to convert the game and then it leaves the app, and it does not convert.
My phone is a Alcatel One Touch Pixi 3 (3.5)

**Comment by SrCuchillo** [comment]
I need help, I try to emulate a game, the app starts to convert the game and then it leaves the app, and it does not convert.
My phone is a Alcatel One Touch Pixi 3 (3.5) android 4.4.2
