### ISSUE TITLE
Cannot load pico app/browser

### ISSUE THREAD

**Issue by javi2man** [nikita36078/J2ME-Loader#172]
**Emulator version:**
1.2.7.7-open

**Game version:**
3.5

**Game resolution:**
``(For example, 240x320 or 640x360)``
Multi screen

**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
The app pico and/or picoweb browser, by PicoWireless Inc can't be loaded after its conversion, appears this error con startup (i attach screenshot)

javax.microedition.lcdui.List.setFont

**Comment by nikita36078** [comment]
Fixed in the new version.

**Comment by javi2man** [comment]
Thanks!
