### ISSUE TITLE
5ud0ku: Duplicate and reverse menu items 

### ISSUE THREAD

**Issue by easyaspi314** [nikita36078/J2ME-Loader#179]
**Emulator version:**
1.2.7.8-play

**Game version:**
5ud0ku 1.8.9, source code dug up and reuploaded [here](https://github.com/easyaspi314/5ud0ku/tree/0fc4641ffb69a6cff7e0d8323cd4d0aa34f77b28) for everyone's convenience

**Game resolution:**
``(For example, 240x320 or 640x360)``
Doesn't matter. 
**Device:**
LG G3

**Android version:**
Android 7.1.2 (Resurrection Remix 5.8.5). I have Xposed, but literally nothing is installed to it, and I got this crash without it enabled.

**Description of issue:**

Menu items in the main game screen keep duplicating and appear to be added backwards.

The number of menu options accumulates the more times you go back to the game board, as it appears that items aren't being properly removed when new ones are added.

![screenshot_20180302-010323](https://user-images.githubusercontent.com/6258309/36885550-970182dc-1db5-11e8-8855-3e10d19ca901.png)

**Comment by aNNiMON** [comment]
Same issue with Gravity Defied
![gd](https://user-images.githubusercontent.com/1321838/36893606-5c689000-1e11-11e8-8977-36eca2833dea.png)

**Comment by nikita36078** [comment]
![screenshot_1520009957](https://user-images.githubusercontent.com/3035571/36911320-3f127b86-1e54-11e8-8eae-bbc606faef63.png)
Fixed
