### ISSUE TITLE
Medieval Combat: Age of Glory - Graphical Bug

### ISSUE THREAD

**Issue by oatmeal01** [nikita36078/J2ME-Loader#180]
**Emulator version:**
1.2.7.8 and later

**Game version:**
1.0.0

**Game resolution:**
``(240x320)``

**Device:**
``(Asus Z5)``

**Android version:**
5.0

**Description of the issue:**

>Battleground's background image was split in half and it seems the other background is different from the other one.
<image src="https://user-images.githubusercontent.com/36059629/36289702-6250494c-12fc-11e8-8f1b-09a45ed2c34a.jpg" width="176" height="300"/> <br>
The battleground's background was supposed to be like the image below.
 (Game via KEmulator)<br><image src="https://user-images.githubusercontent.com/36059629/36289782-e20f9372-12fc-11e8-9561-11f10bfe7ce2.png" width="176" height="240"/>

**Comment by nikita36078** [comment]
Fixed.
