### ISSUE TITLE
System properties

### ISSUE THREAD

**Issue by amarcioz** [nikita36078/J2ME-Loader#182]
What is the function of system properties?

**Comment by nikita36078** [comment]
It can be used to replace or add system properties, like "microedition.platform" or "microedition.encoding". 

> Some applications rely on system properties and perform some optimizations based on device manufacturer or model, e.g. reduce particles count for Nokia and Samsung devices or enable visual effects for Sony Ericsson.

**Comment by jasper1412** [comment]
@nikita36078 is it possible to create templates for it?

**Comment by nikita36078** [comment]
@jasper1412 There is a really lot of them, so I don't think the templates will be helpful.
