### ISSUE TITLE
Picoweb browser bug

### ISSUE THREAD

**Issue by javi2man** [nikita36078/J2ME-Loader#183]
**Emulator version:**
1.2.7.8

**Game version:**
3.5

**Game resolution:**
``(For example, 240x320 or 640x360)``
Multi screen
**Device:**
``(For example, Samsung Galaxy S7)``
Moto E1
**Android version:**
4.4.2
**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
The app is now working with the last update, but virtual keyboard is not shown after the initial splash screen (even enabled in options), and also page links are not clickable

**Comment by oatmeal01** [comment]
try to use opera or uc as an alternative browser

**Comment by jasper1412** [comment]
experience those similar bug also, starting the app is very slow, then the menu does not respond to any input.

**Comment by nikita36078** [comment]
I'm closing this issue because the browser's server is dead and I can't test it anymore.
