### ISSUE TITLE
Might and Magic: Switching to landscape mode screws up text

### ISSUE THREAD

**Issue by namandixit** [nikita36078/J2ME-Loader#184]
**Emulator version:** 1.2.7.8-play

**Game version:** 1.0.0

**Game resolution:** 240x320

**Device:** Moto G4

**Android version:** 7.0

**Description of the issue:** While the text renders correctly in portrait mode; as soon as devoce is rotated to switch to landscape mode, the text size increases by a large factor. If the device is rotated back to portrait mode, the increased text size persist.

Initial Portrait:

![Portrait](https://user-images.githubusercontent.com/8736472/36929410-1881f5d0-1e88-11e8-9560-a47522f40951.png)

After switching to Landscape:

![Landscape](https://user-images.githubusercontent.com/8736472/36929397-04e89ede-1e88-11e8-8df8-b5ae43489dcd.png)

After switching back to portrait:

![Portrait again](https://user-images.githubusercontent.com/8736472/36929447-a0597140-1e88-11e8-89e2-3b49874b0b89.png)

**Comment by namandixit** [comment]
Added: Simply starting the game in Landscape mode (as opposed to starting in potrait and then switching to landscape) has the same problem. Also, toggling `Immediate Mode` does **not** fix the problem.

**Comment by oatmeal01** [comment]
have you tried adjusting the font

**Comment by namandixit** [comment]
@oatmeal01 I tried all the all four options in `Presets` under `Font options`, none of them fixed the problem. Is that what you meant by "adjusting the font"?

**Comment by oatmeal01** [comment]
Here's the solution/fix: 
Font options: 128x128
[√] Values are in Scaled Pixels.

**Comment by oatmeal01** [comment]
just check the values are in scaled pixels,

**Comment by oatmeal01** [comment]
try preset 128x128

**Comment by namandixit** [comment]
@oatmeal01 That is what I did in above screenshot. To be sure, are you running 240x320 version of the game. (Maybe different versions do things differently)

**Comment by oatmeal01** [comment]
Game without tweaking font
<img height="176" width="300" src="https://user-images.githubusercontent.com/36059629/36932200-cd46ca36-1f00-11e8-8ce0-be6cbf7cebbe.png"/>
run the game in 128x128 font preset without checking scaled pixel.
<img height="176" width="300" src="https://user-images.githubusercontent.com/36059629/36932082-e1e629a2-1efe-11e8-9aa8-678b03b04d9a.png"/>

**Comment by namandixit** [comment]
@oatmeal01 In your _fixed_ screenshot, the line `© 2004 Gameloft` takes up more that half the width but in my original _unscrewed_ potrait screenshot, it only take only ⅓ of the screen width. I think that while it feels like it got fixed on your device because of it having a different resolution that mine, the problem is still there - it's only more easily detectable on my device.

**Comment by namandixit** [comment]
Wait, if I switch off the virtual keyboard in game settings, the problem fixes itself (of course, I can't play the game anymore without a keyboard). This is one weird bug.

**Comment by oatmeal01** [comment]
Font tweaking works fine. Sample image below.
**240x400 COC: Red Alert**
without tweaking font
<img height="300" width="176" src="https://user-images.githubusercontent.com/36059629/36932437-c63219f0-1f03-11e8-88a1-a4b08c78d328.png"/>

font preset 128x160
<img height="300" width="176" src="https://user-images.githubusercontent.com/36059629/36932443-ec397a9e-1f03-11e8-936b-2faf66f09767.png"/>

**Comment by namandixit** [comment]
@oatmeal01 It does not on my device (Moto G4 with Android 7.0). Also, check my last comment, it's most probably an emulator bug.

**Comment by nikita36078** [comment]
Yes, it is a virtual keyboard bug, I will fix it soon.

**Comment by nikita36078** [comment]
Fixed.
