### ISSUE TITLE
Dragon Island graphics bug

### ISSUE THREAD

**Issue by clouu27** [nikita36078/J2ME-Loader#186]
**Emulator version:**
1.2.7.8-open

**Game version:**
1.0.2

**Game resolution:**
240x320

**Device:**
Jiayu S3 Plus

**Android version:**
5.1.1

**Description of the issue:**
> ![screenshot_2018-03-03-17-11-40](https://user-images.githubusercontent.com/22563129/36932819-1cfb8cf2-1f0a-11e8-975b-9853d4f1d4b4.png)
on Misty Level 2

Those water sprites aren't rendered correctly. Despite on this bug, this only happen on this certain area called `Demon River` on the game. All water sprites on other area is fine. Here's the example:

> ![screenshot_2018-03-03-17-12-56](https://user-images.githubusercontent.com/22563129/36932854-a61334a4-1f0a-11e8-98c1-a333bbdaaf5f.png)
Also on Misty Level 2, but on other area.

**Comment by oatmeal01** [comment]
this issue is like #124

**Comment by nikita36078** [comment]
The game looks exactly the same on Nokia, so I close the issue.
