### ISSUE TITLE
Prompt warning to avoid overwrite

### ISSUE THREAD

**Issue by fireclouu** [nikita36078/J2ME-Loader#187]
The implementation of this request is to avoid overwriting installed applications on emulator, checking if the user would like to consider re-installing the app. It should be helpful for those who mistakenly re-installing the same version of the application to prompt them that it was already installed.

**Comment by AdityaMH** [comment]
More better if prompt warning added for pre-installed with information from manifest.mf (Name, Icon, Size, Vendor, Version, Description), (and button to cancel or install)(and add text "app_name was found, still keep to install?" If Jar was installed before/re-installing) and after-installed with text "Successfully Converted" same as like 1.4.2

**Comment by nikita36078** [comment]
Added in the latest version.
