### ISSUE TITLE
Treat .jad file extension as for this application

### ISSUE THREAD

**Issue by jasper1412** [nikita36078/J2ME-Loader#188]
Like what .jar file that can open by J2ME-Loader directly on a 3rd party application (Open as...), .jad file should be opened as default for this application.

**Comment by oatmeal01** [comment]
using xplore (3rd party filemanager) i tried to set  j2me loader as the default app to open jad files but the toast notification says can't convert. you can only install jad file through j2me loader's File browser. your suggestion is a good idea, hope nikita will add that feature soon.
