### ISSUE TITLE
J2ME Loader + BT Controller

### ISSUE THREAD

**Issue by oatmeal01** [nikita36078/J2ME-Loader#192]
## Use Your Android Device As A Bluetooth Gamepad For Another

<img height="240" width="400" src="https://user-images.githubusercontent.com/36059629/36943686-18718556-1fc8-11e8-87f4-19d6f8d915da.png"/>

**Requirements:**

```
- 2 Android Devices
- J2ME Loader (Java J2ME Emulator)
- Java Games [.jar/.jad] (Non-Touchscreen)
- Bt Controller 
- BT Controller Editor (For creating/editing keyboard controls. Supports Keymapping)
```

**Bt Controller Keyboard Controls for J2ME Loader:**
After downloading BT Controller and BT Controller Editor download your desired keyboard below. 
<details><summary><b>Keyboard</b></summary><p>

```(based on Heroes Lore Zero)```
<img height="300" width="176" src="https://user-images.githubusercontent.com/36059629/36944048-fc5d425e-1fce-11e8-84c5-c3072e6cf3dc.png">
</p></details>
- <a href="http://soft-igloo.com/btcontroller/viewController.php?ControllerName=j2me_full">Fullscreen</a> (Good for smallscreen devices such as Samsung Galaxy Y)
<img height="128" width="200" src="http://soft-igloo.com/btcontroller/viewImage.php?controllerid=1520171166&imagefilename=j2me_full.png"/>
- <a href="http://soft-igloo.com/btcontroller/viewController.php?ControllerName=j2me_medium">Medium</a> (For Widescreen)
<img height="128" width="200" src="http://soft-igloo.com/btcontroller/viewImage.php?controllerid=1520179672&imagefilename=j2me_medium.png"/>
- <a href="http://soft-igloo.com/btcontroller/viewController.php?ControllerName=j2me_small">Small</a> (For Widescreen)
<img height="128" width="200" src="http://soft-igloo.com/btcontroller/viewImage.php?controllerid=1520174292&imagefilename=j2me_small.png"/>

**Other Keyboards:**
\- [Keyboard 1](http://soft-igloo.com/btcontroller/viewController.php?ControllerName=J2ME_LOADER)
<img height="128" width="200" src="http://soft-igloo.com/btcontroller/viewImage.php?controllerid=1520026297&imagefilename=J2ME_LOADER.png"/>

\- [Keyboard 2](http://soft-igloo.com/btcontroller/viewController.php?ControllerName=J2ME_LOADER_2)
<img height="128" width="200" src="http://soft-igloo.com/btcontroller/viewImage.php?controllerid=1520155607&imagefilename=J2ME_LOADER_2.png"/>

**Note:** Bt Controller is user friendly and easy to use,  just download the  keyboard controls above and set as your default controls for j2me loader. Use small screen android devices for your controls (e.g. Samsung  Galaxy Y etc..)

**Comment by jasper1412** [comment]
@oatmeal01 I think it doesn't really necessary to plug this one here :) this was a direct promotion to 3rd party app. We should be a good example to future contributors :)

**Comment by oatmeal01** [comment]
@jasper this is just for reference, don't  have any bad intentions for posting this thread. Sorry if it offends you or the developer. I just want to share  an alternative controller for j2me loader. If this violates any rights/or is illegal then i should take down this thread asap.

**Comment by jasper1412** [comment]
@oatmeal01 no no it does not violate anything, just that inappropriate placement of the tip. It should be separated from Issues tab, else the meaning would be nullified :)

**Comment by oatmeal01** [comment]
thread was moved. thanks for reminding
