### ISSUE TITLE
Mission Impossible 3

### ISSUE THREAD

**Issue by oatmeal01** [nikita36078/J2ME-Loader#196]
**Emulator version:**
1.2.7.8

**Game version:**
All versions

**Game resolution:**
``(240x320 or 352x416)``

**Device:**
``(Asus Z5)``

**Android version:**
5.0

**Description of the issue:**
``(Blackscreen after Paramount logo.)``

**Comment by Manishbere** [comment]
Tankzors pro 2D  all versions Crashes

**Comment by Manish089** [comment]
It's impossible on your phone

**Comment by nikita36078** [comment]
Fixed.
