### ISSUE TITLE
PES 2014 stopped working after the new version

### ISSUE THREAD

**Issue by jack1432** [nikita36078/J2ME-Loader#202]
**Emulator version:**
1.2.7.9-play

**Game version:**
1.0.7

**Game resolution:**
(320x240)

**Device:**
Samsung Galaxy J1 Mini

**Android version:**
5.1.1

**Description of the issue:**

After the new version, the Konami (PES) football games stopped working, the game stops suddenly when starting a match. That happens with all the games (PES) I tested, in the version (1.2.7.8-play) worked perfectly. Why did this happen? Help me!
![screenshot_2018-03-05-23-34-21](https://user-images.githubusercontent.com/36806488/37013074-d767fb34-20ef-11e8-91ca-a317454ca6c4.png)
The game for when it arrives on this screen

**Comment by nikita36078** [comment]
I will release fixed version today.

**Comment by jack1432** [comment]
The same problem happens with: 
**Game:** Ben 10 The Power of Omnetrix

**Resolution:** 320x240

**Version:** 1.0.0

Being that it worked well in the previous version (1.2.7.8-play)

**Comment by nikita36078** [comment]
Fixed in 1.2.8.
