### ISSUE TITLE
Age of Empires II - Graphical Bug

### ISSUE THREAD

**Issue by oatmeal01** [nikita36078/J2ME-Loader#203]
**Emulator version:**
1.2.7.8

**Game version:**
1.1.1

**Game resolution:**
``(240x320)``

**Device:**
``(Asus Z5)``

**Android version:**
5.0

**Description of the issue:**
``(Issue 1: The status above will disappear if you minimize the game(go to homescreen))``
<img height="300" width="176" src="https://user-images.githubusercontent.com/36059629/37013176-8fe0edf4-2133-11e8-8924-e0fcaa48f7bf.png"/>

``(Issue 2: When you move the red square pointer to map, the characters will remain printed/drawn to the status bar)``
<img height="300" width="176" src="https://user-images.githubusercontent.com/36059629/37013084-fa27c0c6-2132-11e8-8761-e6e49b4383e8.jpg"/>

**Comment by nikita36078** [comment]
Fixed.

**Comment by nikita36078** [comment]
@oatmeal01 Now I can't find a version where this bug was fixed. You said `The bug came back`, so you have a stable version? Because it seems like I didn't fix it at all. Which is more more confusing, my Nokia has the Issue 2 too, so maybe it's a game problem.

**Comment by oatmeal01** [comment]
> @oatmeal01 Now I can't find a version where this bug was fixed. You said `The bug came back`, so you have a stable version? Because it seems like I didn't fix it at all. Which is more more confusing, my Nokia has the Issue 2 too, so maybe it's a game problem.

I installed the feb 14 version of j2me loader based on the time you posted the game was fixed but sadly the game still has a graphical issue. 
You fixed this issue before but i forgot what j2me version.

I'll try to find other game versions and check if the bug is still there.

**Comment by oatmeal01** [comment]
I think this is game bug. I found another version that works perfectly.

**Age of Empires II v01.02.15**
<img height="300" width="176" src="https://user-images.githubusercontent.com/36059629/69999957-d7516400-1594-11ea-9dd4-e5855dbf28fe.png"/>

There's another version of this game that is called deluxe and it has no graphical bugs at all.

**Age of Empires II Deluxe v02.00.35**
<img height="300" width="176" src="https://user-images.githubusercontent.com/36059629/70000118-4929ad80-1595-11ea-9a16-ea8ceec1a85f.png"/>

**Comment by oatmeal01** [comment]
Not an emulator bug.
