### ISSUE TITLE
Add multitouch support for touchscreen games

### ISSUE THREAD

**Issue by Instandhaltung** [nikita36078/J2ME-Loader#205]
Some games need multitouch (especially plattformers). I am unsure if it was supported back in the day, but I assume so since they are barely playable otherwise. Thanks !

![screenshot_20180306-155416](https://user-images.githubusercontent.com/20743229/37039196-253286b0-2157-11e8-936b-b68a8ac51d7e.jpg)

**Comment by jasper1412** [comment]
I dont think original java games designed to have multitouch. It was a limitation not on emulator but the j2me itself. Lets confirm this one to the owner if they can make workarounds for this.

**Comment by oatmeal01** [comment]
i hope this is possible tho, some games need button combination, just like the game above.

**Comment by nikita36078** [comment]
No, j2me doesn't support multitouch. Well, Nokia added multitouch handling to the Nokia API in 2012, but I never heard about any games which use it.

**Comment by oatmeal01** [comment]
multitouch only applied to symbian games (.sis)

**Comment by AdityaMH** [comment]
Total Conquest TS version for example, for build wall, they need drag screen for place wall correctly. or maybe simcity?

**Comment by nikita36078** [comment]
@AdityaMH Pointer dragging isn't related to multitouch.

**Comment by Instandhaltung** [comment]
I get that most games don't support multitouch, and that the plattform may have not supported it as well, but how are you supposed to play those games then, if you look at sonic above, it would mean that you can't dash or jump properly while running. Also, the game "LocoRocoHi" (touch version) clearly implies that you have to press the left and right touch fields together to jump, although you can also press between the two to do so.

**Comment by jasper1412** [comment]
The emulator isnt the concern here, it was API, adding those multitouch feature was way too late as devs on year 2012 migrated to another platform, leaving j2me platform behind. Also take note that if you got a game released between 2012 and below, multitouch wont work on it, so even though multitouch was implemented on the emulator, only few games would take benefit from it.

**Comment by AdityaMH** [comment]
@nikita36078 But I can not make a long wall (it may take two fingers to drag wall into long). I guess it's a bug. and in version 1.2.8 can not select buildings (Total Conquest).

**Comment by jasper1412** [comment]
@AdityaMH you may separately report this issue if thats the case.

**Comment by AdityaMH** [comment]
@jasper1412 and then, how build wall into long since drag only move wall position?

**Comment by jasper1412** [comment]
@AdityaMH continuous touch on "+" icon would do, tested on some original j2me supported devices. Multitouch really isnt implemented on on j2me version of Total Conquest.

**Comment by AdityaMH** [comment]
Ok, forget it about wall. one problem now for 480x800 ver: 1.0.0, building list now can't responded when clicked.
