### ISSUE TITLE
Gangstar 3: Miami Vindication & Gangstar Rio - Graphical Bug

### ISSUE THREAD

**Issue by oatmeal01** [nikita36078/J2ME-Loader#209]
**Emulator version:**
1.2.8 and later

**Game version:**
1.1.4 (Gangstar Rio), 1.0.3 (Gangstar 3)

**Game resolution:**
``(640x360)``

**Device:**
``(Asus z5)``

**Android version:**
5.0

**Description of the issue:**
``(Games are totally playable but the shadows are square instead of circle.)``
<img height="320" width="300" src="https://user-images.githubusercontent.com/36059629/36123035-661476de-1086-11e8-90fe-f0038ae51de9.jpg"/>

**Comment by Manishbere** [comment]
240x320 SE has better quality than 360p or 480p resolutions lol

**Comment by oatmeal01** [comment]
@Manishbere 240/480 still, the shadows are square instead of circle.

**Comment by Manishbere** [comment]
Shadows doesnt matter It's fine,It's great anyways

**Comment by Kouchi-kun** [comment]
Good

**Comment by nikita36078** [comment]
Fixed
