### ISSUE TITLE
Midnight Bowling 3 - Graphical Bug

### ISSUE THREAD

**Issue by oatmeal01** [nikita36078/J2ME-Loader#211]
**Emulator version:**
1.2.8 and later

**Game version:**
1.0.7

**Game resolution:**
``(360x640)``

**Device:**
``(Asus Z5)``

**Android version:**
5.0

**Description of the issue:**
``(This happens when you throw the bowling ball, when the rolling ball is near to the pins they become invisible. )``
<img height="300" width="176" src="https://user-images.githubusercontent.com/36059629/35844677-a1c5380e-0b49-11e8-9dec-9ff83e91afd9.png"/>
``(1.2.8 same issue above + additional graphical bug)``
<img height="300" width="176" src="https://user-images.githubusercontent.com/36059629/37156128-2d0757b0-2320-11e8-8877-63f8769137ce.png"/>

``(Game via (PC)KEmulator)``
<img height="300" width="176" src="https://user-images.githubusercontent.com/36059629/36083692-3a8a8206-0ff0-11e8-8bfa-c8ae57a26b81.png"/>

**Comment by jasper1412** [comment]
Tested on `1.2.8.1`, fixes bugs mentioned above
![screenshot_2018-03-15-19-25-18](https://user-images.githubusercontent.com/22563129/37460605-ae333fa0-2886-11e8-9bef-1f08d74e82e1.png)
![screenshot_2018-03-15-19-25-37](https://user-images.githubusercontent.com/22563129/37460657-d4db794c-2886-11e8-93ea-eff6ff87a02f.png)
