### ISSUE TITLE
Add gamepad support

### ISSUE THREAD

**Issue by herrdeschaos** [nikita36078/J2ME-Loader#213]
A lot of games should have a good playing experience

**Comment by oatmeal01** [comment]
u can try [this](https://github.com/nikita36078/J2ME-Loader/wiki/J2ME-Loader-(BT-Controller-as-Gamepad-Control))

**Comment by nikita36078** [comment]
Gamepads are already supported, you can set up your controller in the settings.

**Comment by herrdeschaos** [comment]
Oh, thank you very much, this app is one of the best
