### ISSUE TITLE
Duke Nukem Mobile 3D

### ISSUE THREAD

**Issue by telanus** [nikita36078/J2ME-Loader#214]
**Emulator version:**
1.2.8

**Game version:**
MIDlet-Version: 1.0.1
MicroEdition-Profile: MIDP-1.0
MIDlet-Description: Duke Nukem Mobile 3D

**Game resolution:**
``(240x320)``

**Device:**
``Proline Android 5.1 tablet``

**Android version:**
5.1

**Description of the issue:**
game loads fine, you get to the menu, then after you choose to start a game, and choose your difficulty lever, the game goes into the loading screen and stays there, you can hear the music in the background loop but it never finish loading

**Comment by telanus** [comment]
The latest 1.2.8.4-play now goes in-game but it don't work, you see hour hand & aim+ but nothing else:

![screenshot_0001](https://user-images.githubusercontent.com/19357986/37908351-4916b07c-3108-11e8-9246-44a988fecf8c.png)

**Comment by nikita36078** [comment]
I didn't notice it before - it's a Mascot Capsule game

**Comment by telanus** [comment]
totally forgot to close this a while back. it works currently

![Screenshot_20190415-110340](https://user-images.githubusercontent.com/19357986/56120902-6579cb00-5f6f-11e9-86c5-da732c90cb56.png)
