### ISSUE TITLE
I think the installation tips are needed

### ISSUE THREAD

**Issue by zf1234d** [nikita36078/J2ME-Loader#215]
I think it's good to pop up when installing. Don't exaggerate, play an icon and name, and ask if you install it. Otherwise, if the file doesn't change its name, it will only know what it has installed after installation. (Machine Translation may be a bit of a mess)

**Comment by nikita36078** [comment]
What do you mean, confirmation before install?

**Comment by AdityaMH** [comment]
@nikita36078 He mean, before converting, will show pop-up midlet information (name, vendor, version, description, etc. (can checked manually on manifest.mf in zip mode) and prompt to convert JAR.

**Comment by nikita36078** [comment]
Fixed
