### ISSUE TITLE
King of Fighter 2013

### ISSUE THREAD

**Issue by telanus** [nikita36078/J2ME-Loader#216]
**Emulator version:**
1.2.8

**Game version:**
MIDlet-Name: 拳皇2013-格斗之王
MIDlet-Version: 1.0
MicroEdition-Configuration: CLDC-1.0
MicroEdition-Profile: MIDP-1.0

**Game resolution:**
``(340x640)``

**Device:**
``Proline Android 5.1 tablet``

**Android version:**
5.1

**Description of the issue:**
when you start the game it comes up with this screen:

![screenshot_000006](https://user-images.githubusercontent.com/19357986/37301845-76f5dd96-2632-11e8-82a4-f2c00c57d040.png)

which states: "this game only supports portrait use". If you switch from 360x640 to 640x360 it still comes up with the same warning screen.  (I know there are other games that have the same problem, but I remember which ones). is there a way to get a toggle to switch on when games need portrait mode, to make games like this one to work?

**Comment by oatmeal01** [comment]
Same midlet version here, sometimes the game freezes so you need to restart j2me loadet.
<img height="300" width="176" src="https://user-images.githubusercontent.com/36059629/37319529-67319c10-26aa-11e8-9fd7-929afdf4e5c9.png"/>

**Comment by nikita36078** [comment]
Does the bug still exist? I can't find this game.
