### ISSUE TITLE
gedda headz willbe error,bluetooth disabled or busy

### ISSUE THREAD

**Issue by xuezhanpingrang** [nikita36078/J2ME-Loader#217]
**Emulator version:**

1.2.8
**Game version:**
2.1

**Game resolution:**
``(For example, 240x320 or 640x360)``

**Device:**
``(For example, Samsung Galaxy S7)``

**Android version:**
6.0
**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``

**Comment by amarcioz** [comment]
Where are the screenshots?

**Comment by nikita36078** [comment]
Yes, Bluetooth isn't supported yet, I created issue about it - #218
