### ISSUE TITLE
Bluetooth support

### ISSUE THREAD

**Issue by nikita36078** [nikita36078/J2ME-Loader#218]
Emulator doesn't support Bluetooth yet.

**Comment by Kriss7475** [comment]
I can provide a lot of games which use Bluetooth when you need those to test

**Comment by nikita36078** [comment]
No, thanks, I have enough Bluetooth games.

**Comment by AdityaMH** [comment]
Is possible using bluetooh for multiplayer and virtual hardware at same time (when they supported)?

**Comment by AdityaMH** [comment]
Maybe bluetooth connection can be implemented if replaced to Wifi Connection for bluetooth status instead.
Since bluetooth implemented for external gamepad.

**Comment by nikita36078** [comment]
The Bluetooth support is finally implemented

**Comment by AdityaMH** [comment]
Please, add turn off bluetooth prompt add it automatically, if want to close app/emulator? Sometime i forgetting to turn off bluetooth when closing app.
