### ISSUE TITLE
Add qwerty keyboard support

### ISSUE THREAD

**Issue by AdityaMH** [nikita36078/J2ME-Loader#220]
Some Nokia X2 games or another real 320×240 games using qwerty-pad when input letter/word. Since this emulator doesn't have own virtual qwerty keyboard or qwerty keymapping, any ideas to input letter/word when edit name (or create team on real football 2018 for example)?

**Comment by oatmeal01** [comment]
Try 240x320 portrait. You can type letters using the 0-9 keys.

**Comment by AdityaMH** [comment]
I very comfort playing on horizontal stadium (320×240, 640×360, etc.) but not diagonal stadium (portrait screen size).

**Comment by AdityaMH** [comment]
Can you add switching from virtual keypad to virtual qwerty keyboard feature (just like GameKeyboard+) with J2ME Loader own style. only different is qwerty cannot to be moved/resize because lack screen size.

All Nokia X2/320×240 games using qwerty keyboard.

**Comment by nikita36078** [comment]
Added
