### ISSUE TITLE
Clone 3D game crashes

### ISSUE THREAD

**Issue by ghost** [nikita36078/J2ME-Loader#222]
Emulator version: 1.2.8-open

Game version: 1.0

Game resolution: 240x320

Device: Gionee P5mini

Android version: 5.1

Game crashes while opening the first mission.

**Comment by Manishbere** [comment]
I played my first 2GB data game in my first phone Gionee p5mini  Lol.It works well and smooth no crashes..MODERN COMBACT 4.hehe

**Comment by oatmeal01** [comment]
have you tried installing through .jad? this game need to be installed though jad to remove the demo version. I think this issue is the same with #113 (the game also crashes)

**Comment by Aakash1217** [comment]
Could you please explain how to install a jad on j2me loader?

**Comment by Aakash1217** [comment]
Ok, I finally installed the the .jar by .jad file available on the same
webpage (http://dedomil.net/games/5786/download-jar/76674). But, the error
still persists.

**Comment by oatmeal01** [comment]
try the 900kb file

**Comment by Aakash1217** [comment]
I tried all of the files on that very website, but no luck. Did you test
any of them on your device, I mean, maybe theose files are corrupted
somehow.

**Comment by Aakash1217** [comment]
...or this app probably cannot run that java game on my device as it gets
'only' about 400MB RAM out of 1GB.

**Comment by oatmeal01** [comment]
try to free some ram before opening

**Comment by nikita36078** [comment]
Can't replicate the issue, closing it.
