### ISSUE TITLE
Midnight Bowling 3 - FPS Drop

### ISSUE THREAD

**Issue by oatmeal01** [nikita36078/J2ME-Loader#223]
**Emulator version:**
1.2.8.1

**Game version:**
1.0.7

**Game resolution:**
``(360x640)``

**Device:**
``(Asus z5)``

**Android version:**
5.0 

**Description of the issue:**
>\- Old Issue: #211 (Fixed)
\- New Issue: (FPS Drop(slow animation) when the ball hits the pins. only happens to 360x640 reso 240x400 and 480x800 seems fine.)

**Comment by Manishbere** [comment]
Boring game.let it be😬

**Comment by nikita36078** [comment]
@Manishbere Don't spam, please.

**Comment by Manishbere** [comment]
Sorry Mrs.Developer,I was a bit stupid to comment.I wont do it again😓

**Comment by nikita36078** [comment]
Fixed.
