### ISSUE TITLE
Extreme Air Snowboarding 3D - Graphical Bug

### ISSUE THREAD

**Issue by oatmeal01** [nikita36078/J2ME-Loader#224]
**Emulator version:**
1.2.8.1

**Game version:**
2.2.14

**Game resolution:**
``(240x320)``

**Device:**
``(Asus Z5)``

**Android version:**
5.0

**Description of the issue:**
``(snowflakes, sun rays graphical bug)``
<img height="300" width="176" src="https://user-images.githubusercontent.com/36059629/37517455-76344e48-294c-11e8-9cde-59e4320cf062.png"/>
<img height="300" width="176" src="https://user-images.githubusercontent.com/36059629/37517509-97fd309e-294c-11e8-8dc3-67cd3218f222.png"/>

**Comment by maestr0d** [comment]
I don't know if this will be helpful or relevant at all, but the same graphical bug appears when running the game on a Sony Ericsson k750i but not on a Nokia 6500 Classic.

**Comment by nikita36078** [comment]
Fixed.
