### ISSUE TITLE
Eon the Dragon 2 - Freezing Issue

### ISSUE THREAD

**Issue by oatmeal01** [nikita36078/J2ME-Loader#225]
**Emulator version:**
1.2.8.1 and later

**Game version:**
1.0.3

**Game resolution:**
``(240x320)``

**Device:**
``(Asus Z5)``

**Android version:**
5.0

**Description of the issue:**
``(Freezing Issue: can't play the game, the game freezes in menu.)``

**Comment by Manishbere** [comment]
It does freezes but I enabled IPmode and disabled Filter and it played a bit. I guess Android Nougat forces app more execution so Arm8-A cpu rolls. Anyways Nikita's sexy app really cool to able to run Fast and furious 3d-HD 240x320 (2.89mb).jar from I-play vendor. It's really great to play the game. But Fast and Furious Fugitive 2d or 3d freezes damn.

**Comment by nikita36078** [comment]
Fixed
