### ISSUE TITLE
Ice Age 2: Arctic Slide - Crashing Issue

### ISSUE THREAD

**Issue by oatmeal01** [nikita36078/J2ME-Loader#226]
**Emulator version:**
1.2.8.1 and later

**Game version:**
1.0.2

**Game resolution:**
``(240x320)``

**Device:**
``(Asus Z5)``

**Android version:**
5 0

**Description of the issue:**
``(The game will crash after the GLU logo.)``

**Comment by Manish089** [comment]
Shut up!

**Comment by nikita36078** [comment]
Fixed.
