### ISSUE TITLE
Micro Counter Strike - Graphical Bug

### ISSUE THREAD

**Issue by oatmeal01** [nikita36078/J2ME-Loader#227]
**Emulator version:**
1.2.8.1

**Game version:**
1.0.0

**Game resolution:**
``(240x320)``

**Device:**
``(Asus Z5)``

**Android version:**
5.0

**Description of the issue:**
>\- Old Issue: #103 (Fixed)
\- New issue: There's a graphical bug on the map when moving the character.)
<img height="300" width="176" src="https://user-images.githubusercontent.com/36059629/37523655-94808c5c-2962-11e8-9be0-7ee344baa4ea.png"/>

**Comment by Manishbere** [comment]
Use IP mode immediate processing

**Comment by Manish089** [comment]
Freak!

**Comment by jasper1412** [comment]
@Manish089 please don't spam.

**Comment by oatmeal01** [comment]
@jasper that kid has mental issues. it can't be fix :) just ignore.

**Comment by nikita36078** [comment]
Fixed.
