### ISSUE TITLE
3D Covert Ops 1943 freezes

### ISSUE THREAD

**Issue by ghost** [nikita36078/J2ME-Loader#228]
**Emulator version:**
1.2.8.1

**Game version:**
1.0.6

**Game resolution:**
240x320

**Device:**
Gionee P5mini

**Android version:**
5.1

**Description of the issue:**
The game freezes after the game dialogue of the first mission completes.

**Comment by Aakash1217** [comment]
![screenshot_2018-03-17-01-19-26](https://user-images.githubusercontent.com/37379322/37541592-28fdcfac-2981-11e8-85a7-622633a5cce2.png)

**Comment by nikita36078** [comment]
Fixed, second mission starts without any problems.
