### ISSUE TITLE
Converter crash log

### ISSUE THREAD

**Issue by GFOXSH** [nikita36078/J2ME-Loader#23]
Добрый день! Добавьте, пожалуйста, возможность просмотра и отправки логов после краша dx. Сейчас приложение просто закрывается, не выдавая даже сообщения об ошибке. Думаю, это было бы полезно, чтобы узнать причину невозможности конвертирования того или иного jar.

**Comment by nikita36078** [comment]
@GFOXSH Можно примеры игр, которые вызывают падение dx? По идее все ошибки должны обрабатываться, интересно, почему там этого не происходит.

**Comment by GFOXSH** [comment]
@nikita36078 Например: http://4pda.ru/forum/index.php?s=&showtopic=824201&view=findpost&p=63536665 J2ME Loader во время конвертирования просто вылетает, не предлагая отправить лог. Стоит отметить, что в /data/data/ при этом копируются все ресурсы и папка остается и после перезапуска.

**Comment by nikita36078** [comment]
@GFOXSH Я обновил dx, теперь конвертация проходит без ошибок. Чтобы добавить отслеживание ошибок в dx, придется лезть в его код, я пока не хочу этого делать. Если будут еще возникать ошибки, тогда добавлю туда логгирование.

**Comment by GFOXSH** [comment]
@nikita36078 В новой версии Gothic конвертировался, но при попытке запуска выдает сообщение об ошибке. Без информации о том, что пошло не так.

**Comment by metle44** [comment]
Back bug settings not tab s2

**Comment by nikita36078** [comment]
Думаю, тут не получится что-либо сделать - такая ошибка выводится, если андроид не может запустить сконвертированную игру из-за ошибок в коде. Можно выводить полный stacktrace на экран, но я не вижу в этом смысла.
