### ISSUE TITLE
Missing javax.microedition.lcdui.DateField

### ISSUE THREAD

**Issue by javi2man** [nikita36078/J2ME-Loader#231]
**Emulator version:**
1.2.8.1

**Game version:**
1.0.3

**Game resolution:**
``(For example, 240x320 or 640x360)``
Multi
**Device:**
``(For example, Samsung Galaxy S7)``
MotoE 1st gen.
**Android version:**
4.4.2
**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``

When trying to run dateCalc app (and many others related with dates and calendar), this error appears on startup: javax.microedition.lcdui.DateField

**Comment by jasper1412** [comment]
`DateField` added, does this mean it was fixed?

**Comment by nikita36078** [comment]
No, I just added a stub to fix crashes, DateField is still unimplemented.

**Comment by nikita36078** [comment]
Fixed now.
