### ISSUE TITLE
BallRush2 Xmas to after opening

### ISSUE THREAD

**Issue by jack1432** [nikita36078/J2ME-Loader#235]
**Emulator version:**
1.2.8.2-play

**Game version:**
1.0.0

**Game resolution:**
240x320

**Device:**
Samsung Galaxy J1 mini

**Android version:**
5.1.1
**Description of the issue:**
The game gets stuck in the loading screen.
![screenshot_2018-03-22-12-50-22](https://user-images.githubusercontent.com/36806488/37782448-c9e016ec-2dea-11e8-99f8-475c932db153.png)

**Comment by Manish089** [comment]
Where is the latest update liar?

**Comment by jack1432** [comment]
It's in the Google Play Store (beta version)
![screenshot_2018-03-22-16-23-49](https://user-images.githubusercontent.com/36806488/37793718-5c88bff0-2e07-11e8-9f6e-a782ccf2ec22.png)
![screenshot_2018-03-22-16-23-35](https://user-images.githubusercontent.com/36806488/37793765-7c8afae8-2e07-11e8-95cf-bbe6c4645c74.png)

**Comment by jack1432** [comment]
😅

**Comment by Manish089** [comment]
![screenshot_20180323-014508](https://user-images.githubusercontent.com/36963799/37796106-55f317f6-2e0e-11e8-848e-9e0433571962.png)
Damn! no shit till now

**Comment by Manish089** [comment]
Ohh beta less stable ha!

**Comment by Manish089** [comment]
Ssshhhh!! Beta version is too much slower loading.. Asphalt 6 lags  compared to 1.2.8 version

**Comment by jasper1412** [comment]
It was fixed on 1.2.8.3.
![screenshot_2018-03-24-06-45-14](https://user-images.githubusercontent.com/22563129/37856356-0fed9dcc-2f2f-11e8-9a86-7fb1436fb137.png)

**Comment by jack1432** [comment]
I've updated J2ME Loader to version 1.2.8.3 but still can not get past the load screen :(

**Comment by jack1432** [comment]
What version of the game did you use?

**Comment by jasper1412** [comment]
1.0.0 , also 240x320 with the same android version as yours, but I have -open version, yours are from -play , I didn't test -play version cause I think it is only the same as sideloaded release

**Comment by jack1432** [comment]
I found a version that works on the emulator: v1.0.0 Nokia E71
![screenshot_2018-04-13-09-50-06](https://user-images.githubusercontent.com/36806488/38736109-8a0d1088-3f1a-11e8-9f47-2843aa14ccd6.png)
