### ISSUE TITLE
Digital Chocolate games loads slower than usual

### ISSUE THREAD

**Issue by jasper1412** [nikita36078/J2ME-Loader#238]
**Emulator version:**
1.2.8.2-open

**Game version:**
doesn't matter

**Game resolution:**
doesn't matter

**Device:**
``Jiayu S3 Plus``

**Android version:**
5.1

**Description of the issue:**
Most of games from Digital Chocolate Inc. loading screen takes too much time to load.

**Comment by jasper1412** [comment]
nah, mostly all midlets installed on J2ME Loader having the same issue, especially 3D games

**Comment by nikita36078** [comment]
Yes, I'm working on it now.

**Comment by oatmeal01** [comment]
same issue with some gameloft games

**Comment by jasper1412** [comment]
fixed on 1.2.8.3, by the way those redesigned layout and file manager looks great!
