### ISSUE TITLE
Comcraft 3D Game Glitch

### ISSUE THREAD

**Issue by TRalperenTR** [nikita36078/J2ME-Loader#239]
**Emulator version:**
1.2.8-play

**Game version:**
1.0

**Game resolution:**
360x640

**Device:**
Samsung Galaxy J7 2016

**Android version:**
7.0

**Description of the issue:**
I opened this game, I choosed any world but it's glitching in-game.
![screenshot_20180323-210029](https://user-images.githubusercontent.com/37711793/37848810-82c573fe-2ee6-11e8-95e3-21d0faf30d55.png)

**Comment by nikita36078** [comment]
Fixed in the beta version (since 1.2.8.1)
