### ISSUE TITLE
Return back bug

### ISSUE THREAD

**Issue by metle44** [nikita36078/J2ME-Loader#24]
tab s2 fix bug back do not retry Settings view keystroke + 0-AZ

**Comment by metle44** [comment]
Version 1.2.3 error table returned?

**Comment by nikita36078** [comment]
@metle44  what do you mean? back button doesn't open settings menu on Tab S2, right?

**Comment by nikita36078** [comment]
I moved the emulator menu to the ActionBar, so bug is fixed now.
