### ISSUE TITLE
Metal Gear Acid 3D 240x320

### ISSUE THREAD

**Issue by amarcioz** [nikita36078/J2ME-Loader#241]
Emulator version: 1.2.8.3

Game version: 1.0.0

Game resolution 240x320

Device: Samsung Galaxy J1 2016

Android version: 5.1.1

Description of the issue:The game freezes on the loading screen.
![screenshot_2018-03-23-16-15-06](https://user-images.githubusercontent.com/35005836/37849679-618f6a02-2eb7-11e8-9065-5c01be016446.png)

**Comment by nikita36078** [comment]
J2ME Loader doesn't support Mascot Capsule 3D games.

**Comment by Indra2108** [comment]
@amarcioz This is the Alternative  MGA 3D Mobile. Works well on J2ME Loader.

Here it is:
[Metal_Gear_Acid_3D_Mobile_KU800.zip](https://github.com/nikita36078/J2ME-Loader/files/3907851/Metal_Gear_Acid_3D_Mobile_KU800.zip)


![Screenshot_2019-12-01-12-04-55](https://user-images.githubusercontent.com/47787767/69909929-5465c780-1435-11ea-9286-1a399d74793a.png)
![Screenshot_2019-12-01-12-04-11](https://user-images.githubusercontent.com/47787767/69909933-6182b680-1435-11ea-9d2e-b8cb87ef973a.png)
![Screenshot_2019-12-01-12-26-52](https://user-images.githubusercontent.com/47787767/69909969-0c937000-1436-11ea-93c8-4ac2f1df7a7d.png)
![Screenshot_2019-12-01-12-25-53](https://user-images.githubusercontent.com/47787767/69909984-45cbe000-1436-11ea-8275-c9a9a7e6a230.png)
