### ISSUE TITLE
E-5 underground 3D

### ISSUE THREAD

**Issue by RyukenT** [nikita36078/J2ME-Loader#242]
**Emulator version:**
1.2.8.3

**Game version:** All versions

**Game resolution:** 240x320,320x240 or 360x640
``(For example, 240x320 or 640x360)``

**Device:**Redmi note 4
``(For example, Samsung Galaxy S7)``

**Android version:**7.0

**Description of the issue:**Game freezes after 4-5 sec loading screen.
``(What's the problem? - Screenshots showing the issue if applicable)``

**Comment by nikita36078** [comment]
Fixed
