### ISSUE TITLE
Call of duty 2 2d

### ISSUE THREAD

**Issue by RyukenT** [nikita36078/J2ME-Loader#243]
**Emulator version:**1.2.8.3

**Game version:**All versions

**Game resolution:**All resolutions upto 240x320
``(For example, 240x320 or 640x360)``

**Device:**Redmi note 4
``(For example, Samsung Galaxy S7)``

**Android version:**7.1

**Description of the issue:**Cant open after it's installed. Surprising coz Call of duty 2 3d(stalingard) works wells but 2d doesnt well.ohh
``(What's the problem? - Screenshots showing the issue if applicable)``

**Comment by TRalperenTR** [comment]
My cod 2 3d game is opening well but it's stuck on loading screen always. Counter attack game is same too.
![screenshot_20180324-201704](https://user-images.githubusercontent.com/37711793/37866850-59f80e76-2fa1-11e8-9120-2c7e1ed187dc.png)
![screenshot_20180324-202204](https://user-images.githubusercontent.com/37711793/37866852-5f1c6e9c-2fa1-11e8-839b-c2d8c2e37ba4.png)

**Comment by TRalperenTR** [comment]
can it be solved?

**Comment by RyukenT** [comment]
![screenshot_20180325-061003](https://user-images.githubusercontent.com/37715742/37870428-48606a86-2fc5-11e8-9eb0-091b4aa07a9f.png)
![screenshot_20180325-061055](https://user-images.githubusercontent.com/37715742/37870427-4820e104-2fc5-11e8-8605-5cd848061d14.png)
Mine's v1.0.0 and it's working fine with no lag.Vendor Mob.ua

**Comment by nikita36078** [comment]
Fixed.
