### ISSUE TITLE
Prince of persia Zero(gameloft)

### ISSUE THREAD

**Issue by RyukenT** [nikita36078/J2ME-Loader#244]
**Emulator version:**1.2.8.3

**Game version:**1.0.3,1.0.5(600kb and 1mb version)

**Game resolution:**240x320
``(For example, 240x320 or 640x360)``

**Device:**redmi note 4
``(For example, Samsung Galaxy S7)``

**Android version:**7.1

**Description of the issue:**Game runs a bit slow,Click to continue screen glitch but overall gameplay runs somehow well.Nokia N73....to N95 doesnt run.it stuck in loading screen instead sony k800i opens
``(What's the problem? - Screenshots showing the issue if applicable)``

**Comment by RyukenT** [comment]
![screenshot_20180324-031106](https://user-images.githubusercontent.com/37715742/37855297-8fb8483e-2ee6-11e8-839b-9e3f5a5c2370.png)
![screenshot_20180324-032842](https://user-images.githubusercontent.com/37715742/37855298-90eab656-2ee6-11e8-9506-37f08eb3abe8.png)
comparision to Ppspp emulator

**Comment by oatmeal01** [comment]
1.2.8.3 (240x320 - 1.0.3 version seems fine)

**Comment by RyukenT** [comment]
Alas! It's still same on all versions less than 600kb and samsung series. Maybe There is something in my phone. And Sony K800i is 968kb and I see there is more graphic textures than nokia.So It would be fine instead.

**Comment by nikita36078** [comment]
Fixed
