### ISSUE TITLE
Comcraft 3D Game "Blocks don't appear" Bug

### ISSUE THREAD

**Issue by TRalperenTR** [nikita36078/J2ME-Loader#246]
**Emulator version:**
1.2.8.3-play

**Game & Version:**
Comcraft 1.0

**Game resolution:**
360x640

**Device:**
Samsung Galaxy J7 2016

**Android version:**
7.0 Nougat

**Description of the issue:**
I tested this game on my Galaxy Tab 4 (4.4.2 Kitkat),
Don't have problem on Android Kitkat.
But I tested again on my Galaxy J7 2016 (7.0 Nougat),
The Blocks don't appear.
Can u fix this?

Phone (Nougat):
![screenshot_20180324-220715](https://user-images.githubusercontent.com/37711793/37867996-34c6d3ca-2fb1-11e8-9c75-a7813c6d0a15.png)

Tablet (Kitkat):
![screenshot_2018-03-25-00-06-33](https://user-images.githubusercontent.com/37711793/37868010-5826fde0-2fb1-11e8-9220-a61bbc232139.png)

**Comment by TRalperenTR** [comment]
@nikita36078 I updated to 1.2.8.4-play but it can't solve this problem.

**Comment by TRalperenTR** [comment]
What I should do?

**Comment by nikita36078** [comment]
Fixed.
