### ISSUE TITLE
Still waiting 

### ISSUE THREAD

**Issue by skelletR** [nikita36078/J2ME-Loader#247]
Still waiting for that say the developer.. I know maybe is difficult to add that 

I'm planning to add an orientation lock setting in the app settings, so user will be able to select automatic, landscape or portrait orientation.

**Comment by nikita36078** [comment]
Duplicate issue (#46). And yes, it's done, will be available in the next version.

**Comment by skelletR** [comment]
Now i have the version 1.2.8.4-play
