### ISSUE TITLE
Blue FTP

### ISSUE THREAD

**Issue by ahmadprayoxxsy** [nikita36078/J2ME-Loader#248]
![screenshot_2018-03-26-14-20-51](https://user-images.githubusercontent.com/37769813/37892129-f1e9dd58-3100-11e8-9aa2-03fdbc9d680e.png)
**Emulator version:**1.2.8.4

**Game version:**blue Ftp v1.40

**Game resolution:**
``(For example, 240x320 or 640x360)``

**Device:**
``(samsung j1 120G)``

**Android version:*5.1.1*

**Description of the issue:**
``(can not run mp3 in blueFTp. when j2me loader works)``

**Comment by nikita36078** [comment]
Fixed.
