### ISSUE TITLE
HW acceleration ??

### ISSUE THREAD

**Issue by RyukenT** [nikita36078/J2ME-Loader#249]
**Emulator version:**
1.2.8.4

**Game version:**

**Game resolution:** 
``(For example, 240x320 or 640x360)``

**Device:**Redmi note 4
``(For example, Samsung Galaxy S7)``

**Android version:**7.0

**Description of the issue:**I dont see any change in gameplay.What does it do?
``(What's the problem? - Screenshots showing the issue if applicable)``

**Comment by nikita36078** [comment]
HW acceleration can improve perfomance in some games, but it also crashes sometimes.

**Comment by oatmeal01** [comment]
i can't seem to find HW acceleration on version 1.2.8.4.

**Comment by amarcioz** [comment]
Where is this option located?

**Comment by RyukenT** [comment]
![screenshot_20180326-094353](https://user-images.githubusercontent.com/37715742/37886691-62fcacfa-30ac-11e8-8ece-77099d6dd6ca.png)

**Comment by amarcioz** [comment]
There is not. I'm using version 1.2.8.4 installed through Google Play.
![screenshot_2018-03-26-01-31-49](https://user-images.githubusercontent.com/35005836/37887066-e9f2c5ee-3095-11e8-9e40-c1df53c59f4d.png)

**Comment by oatmeal01** [comment]
same here i downloaded version 1.2.8.4 and i can't find HW acceleration.

**Comment by AdityaMH** [comment]
Me too. But, in fact my all games and app emulated perfectly (without slowing frame).
Btw, HW acceleration not listed on crowdin.

**Comment by nikita36078** [comment]
HW acceleration is for 6.0+ only, I didn't update crowdin yet. Anyway, it's quite unstable, so I'm planning to try another optimization methods.

**Comment by RyukenT** [comment]
Only two Games from Gameloft, Asphalt 6 and fast and furious 6(240x320,higher than 1mb) do crash though GT racing 2(240x320,1.8mb) improved well using HW wow! no slow or laggy.awesome
