### ISSUE TITLE
freej2me collaboration

### ISSUE THREAD

**Issue by jan-kleks** [nikita36078/J2ME-Loader#25]
Hello!

Recently a new multi-platform open-source J2ME emulator called [freej2me (GitHub repo)](https://github.com/hex007/freej2me) has been released. [And the emulation scene seems to be quite happy about this news.](https://www.reddit.com/r/emulation/comments/722f8i/freej2me_emulator/) What's more, sooner or later it [should become a part of RetroArch](https://twitter.com/libretro/status/911725394641997824) what will allow for adding many awesome features that RetroArch is known for.

Would you be interested in working with them in some way, at least sharing the code, or maybe even consolidating the two projects at some point (RetroArch obviously supports Android)?

I will also leave this link here to the very important J2ME preservation discussion (to inspire you): [The state of j2me/midlet/jar emulation, and the in-danger software for the platform that needs to be preserved](https://www.reddit.com/r/emulation/comments/4o2er3/the_state_of_j2memidletjar_emulation_and_the/)

Regards and keep up good work!

**Comment by nikita36078** [comment]
Hello! 
This project seems to be really interesting, I'm happy to see that J2ME emulation remains actual. I will take a look to this project to see if I can help them somehow.

**Comment by hex007** [comment]
@nikita36078 I have been following this project since a long time. Can I ask why this project is not published on Play store?

**Comment by nikita36078** [comment]
@hex007 I really doubt that Google accept my app, because of Google Play rules:

"An app distributed via Google Play may not modify, replace, or update itself using any method other than Google Play’s update mechanism. Likewise, an app may not download executable code (e.g. dex, JAR, .so files) from a source other than Google Play. This restriction does not apply to code that runs in a virtual machine and has limited access to Android APIs (such as JavaScript in a webview or browser)."

**Comment by jan-kleks** [comment]
It's nice to see some interest on both sides (**Hex** is the maintainer of freej2me, of course), unfortunately, I find very sad that often there is very little collaboration even between similar open-source projects, and people try to reinvent the wheel...

This Google Play stuff can be figured out at a later date ([and RetroArch has quite a lot of "bad" experience with Google Play, so they can definitely help too](http://www.androidpolice.com/2014/01/06/retroarch-multi-platform-game-emulator-returns-to-the-play-store-get-it-while-you-can/)), but I guess you guys want to focus on game compatibility first.

**Comment by hex007** [comment]
@jan-kleks you are coming off as rude now. I know you are very much interested in the project.

 I am currently getting familiar with the code. Help me with finding and reporting bugs. Don't ask me to collaborate when I don't need it now. I can always ask Nikita for help when I need it. @recompileorg is currently helping me with the code.

Please check out the wiki on FreeJ2ME repository. You might like that

**Comment by recompileorg** [comment]
@hex007 I don't see anything particularly rude.  One of the best things about open source software is that similar projects can benefit from one another. 

I also find diversity very important.  As I've mentioned before, the big three j2me emulators all work with a different subset of games.  That is certainly a benefit to players, who, in a monoculture, would be stuck waiting for support to come to some of their favorite games.

I understand that you're still getting to know the code base, and the rapid-fire contributions yesterday must have been a bit stressful.  Still, that's part of what maintaining a project like this is all about.  It's also why I had so little interest in it myself.  :)

I know that you and I have very different visions for the project, just as you and @jan-kleks have different ideas about how best to move forward.  With any collaboration, it's important to set aside ego and work with others more diplomatically.  It was difficult for me to relinquish control of the large code base I put so much time and effort in to building, so I do understand that difficulty.

If @nikita36078 can help smooth out some of the rough edges or even take care of some of the larger issues, that would be fantastic.  I assume that that help comes with much more experience with Java and J2ME that either you or I have. TiledLayers might be working in a few hours, or a simple solution to the bug that keeps some games from showing anything on the display.  That's ultimately a good thing, isn't it?

**Comment by hex007** [comment]
Yes I am all about collaboration. @jan-kleks Its good that you are helping by spreading the word. Yesterday was a monday and with that you can understand the problems.

I first have to know how things work. Then I can start working on both projects.

**Comment by SciFi1818** [comment]
Hey you can publish this app in playstore..... thought it's rules are like this, there are many app which itself modify or execute external hard or Dex files....for example just think about parallel space app ....it work in the same way, and google has no problem of it...
