### ISSUE TITLE
Shader Implementation?

### ISSUE THREAD

**Issue by oatmeal01** [nikita36078/J2ME-Loader#251]
>Is it possible to add/implement shaders to j2me loader?

**Shaders**
<img height="400" width="240" src="https://user-images.githubusercontent.com/36059629/37890832-97eb0a76-3104-11e8-9dc2-6dcb51d6b2bf.png"/>

**Screenshot from MyBoy Emulator.**
<img height="400" width="240" src="https://user-images.githubusercontent.com/36059629/37890768-5c124564-3104-11e8-8e77-bdc09f5dfb14.png"/>

**Comment by nikita36078** [comment]
Emulator still isn't fast enough for shaders, so they maybe will be implemented, but not too soon.

**Comment by Manish089** [comment]
That's insane shading.Dont even think about any other junky implementation.It will just slow down or even crash

**Comment by oatmeal01** [comment]
@Manish089 it's just a suggestion kid. By the way stop trolling and posting stupid things. Are you like  a 4th grader? you seem like  hungry for attention. Youre being a retard. #227

**Comment by nikita36078** [comment]
Added in the latest releases, shaders in PPSSPP format are supported.
