### ISSUE TITLE
Accelerometer support

### ISSUE THREAD

**Issue by ahmadprayoxxsy** [nikita36078/J2ME-Loader#252]
**v.1.2.8.4**

**v.1.0.0**

**Game resolution:**
``(640x360)``

**Device:**
``(samsung)``

**5.1**

**Description of the issue:**
can you add "Accelerometer sensor"?
the game will not move if in touch and push.
![screenshot_2018-03-26-14-24-17](https://user-images.githubusercontent.com/37769813/37893084-290d0906-3104-11e8-80c6-58512a84a436.png)
![screenshot_2018-03-26-14-24-38](https://user-images.githubusercontent.com/37769813/37893101-30c3a308-3104-11e8-8588-02b831d0a8f5.png)

**Comment by oatmeal01** [comment]
The latest version of PC KEmulator supports Sensor, hope nikita will implement that feature to j2me loader.

**Comment by jack1432** [comment]
Same thing with TempleRun3D v1.1.0 (360x640)
![screenshot_2018-03-27-18-27-45](https://user-images.githubusercontent.com/36806488/37996157-40893ab6-3206-11e8-8225-0e3f333f2c8e.png)
![screenshot_2018-03-27-18-26-39](https://user-images.githubusercontent.com/36806488/37996194-5ea19638-3206-11e8-86f8-086769616b5d.png)

**Comment by oatmeal01** [comment]
Add also EDGE game

**Comment by andriwas** [comment]
+1
also, request ability to map key to accelerometer

**Comment by nikita36078** [comment]
Will be available in the next version.
