### ISSUE TITLE
Rayman Kart

### ISSUE THREAD

**Issue by telanus** [nikita36078/J2ME-Loader#253]
**Emulator version:**
1.2.8.4-play

**Game version:**
MicroEdition-Configuration: CLDC-1.0
MIDlet-Name: Rayman Kart
MIDlet-Version: 1.0.0

**Game resolution:**
240x320

**Device:**
``Proline Android 5.1 tablet``

**Android version:**
5.1

**Description of the issue:**
When you select to race it will load the loading screen and then freeze there

**Comment by nikita36078** [comment]
Fixed.
