### ISSUE TITLE
Sonic Runners Adventure

### ISSUE THREAD

**Issue by telanus** [nikita36078/J2ME-Loader#254]
**Emulator version:**
1.2.8.4-play

**Game version:**
MIDlet-Version: 1.1.4

**Game resolution:**
240x320

**Device:**
``Proline Android 5.1 tablet``

**Android version:**
5.1

**Description of the issue:**
It'll start then give you an option if you want sound or not, and after your choice it'll start to load get to approximately 93% and crash and drop you back to j2me loader

**Comment by nikita36078** [comment]
Game should be installed through .jad, it's why it crashes.
