### ISSUE TITLE
Ghost Recon: Future Soldier and Modern Combat 2 - sound bug

### ISSUE THREAD

**Issue by Gamerhenky** [nikita36078/J2ME-Loader#256]
**Emulator version:**
1.2.8.4-play

**Game version:**
1.3.1 (GRFS), 1.2.2 (MC2)

**Game resolution:**
240x320 (Sony Ericsson K800)

**Device:**
ASUS Zenfone Live

**Android version:**
6.0 Marshmallow

**Description of the issue:**
Ghost Recon: Future Soldier

SFX (Sound Effects) in K800 (240x320) version not playing together with Musics (specially during the menu) regardless when they still turned on unlike real (K800) phone did. Comparing with W810i (176x220) version, SFX working fine here and plays together with Musics. 

Modern Combat 2: Black Pegasus

SFX almost completely gone. Comparing with W810 version, SFX working fine and I don't believe plays with Musics like the other Gameloft games did. Didn't test them with real phone yet.

**Comment by Manish089** [comment]
The sound's pretty fucked up I hear it too.Shít Emulator's is trashed with 2D gameloft games.Still cannot handle sony K800i versions

**Comment by Gamerhenky** [comment]
Fixed in 1.5.9 version
