### ISSUE TITLE
Tankzors pro 2D

### ISSUE THREAD

**Issue by Manish089** [nikita36078/J2ME-Loader#257]
**Emulator version:**1.2.8.4 

**Game version:**6.2.04

**Game resolution:**240x320
``(For example, 240x320 or 640x360)``

**Device:**samsung galaxy S6active
``(For example, Samsung Galaxy S7)``

**Android version:**7.0

**Description of the issue:**Cant play the game.please make it supportive.only 523kb it is
``(What's the problem? - Screenshots showing the issue if applicable)``

**Comment by nikita36078** [comment]
Fixed
![screenshot_1522524090](https://user-images.githubusercontent.com/3035571/38166767-ef4cca26-3531-11e8-94f2-fa2a57f81d99.png)
