### ISSUE TITLE
Crazy Taxi

### ISSUE THREAD

**Issue by telanus** [nikita36078/J2ME-Loader#258]
**Emulator version:**
1.2.8.4-play

**Game version:**
MIDlet-Version: 1.4.2
MicroEdition-Profile: MIDP-2.0

**Game resolution:**
640x360

**Device:**
``Proline Android 5.1 tablet``

**Android version:**
5.1

**Description of the issue:**
Runs great but the shadow underneath the car isn't displayed correctly:

![screenshot_000002123123](https://user-images.githubusercontent.com/19357986/38021475-3d921a4a-327d-11e8-9e77-22abbb7cf4d4.png)

**Comment by Manish089** [comment]
I have been seen this issue before.I dont think it would be fixed

**Comment by nikita36078** [comment]
Fixed.
