### ISSUE TITLE
Some games and apps are out of error

### ISSUE THREAD

**Issue by tangcan1600** [nikita36078/J2ME-Loader#26]
such as  anyview,a book reader,outs of error when  browsing the storage card，the log points out  there is a
NullpointerExcepion at method ‘Void  java.util.Timer.cancel()’

**Comment by nikita36078** [comment]
@tangcan1600 I can't catch this error in Anyview, do you get this error anywhere else? I need to check more apps with this bug.

**Comment by tangcan1600** [comment]
I don’t know if anywhere  else has the same problem， Some midp1.0 games are stuck at startup interface,can improve  its compatibility ?
