### ISSUE TITLE
The emulator does not convert translated games

### ISSUE THREAD

**Issue by amarcioz** [nikita36078/J2ME-Loader#262]
Emulator version: 1.2.8.4

Game: Killing Machine Nazi Zombies 3D PT-BR

Game version: 1.0

Game resolution 240x320

Device: Samsung Galaxy J1 2016

Android version: 5.1.1

Description of the issue: The game was translated from Russian to Portuguese, but the emulator can not convert. The same goes for other games translated into any language.

**Comment by nikita36078** [comment]
Does it work on other emulators?

**Comment by AdityaMH** [comment]
have you tried to convert the original game before, @amarcioz ?

**Comment by amarcioz** [comment]
@nikita36078 Works on common phones but does not work on PPSSPP

**Comment by amarcioz** [comment]
@AdityaMH The original game works with a little delay.

**Comment by amarcioz** [comment]
[Download.zip](https://github.com/nikita36078/J2ME-Loader/files/1865856/Download.zip)

**Comment by amarcioz** [comment]
@nikita36078 The Nowhere game translated into Portuguese works well.

**Comment by nikita36078** [comment]
Ok, I see the problem now.

**Comment by nikita36078** [comment]
Fixed.
