### ISSUE TITLE
Crash Test Dummies 2 issues

### ISSUE THREAD

**Issue by fireclouu** [nikita36078/J2ME-Loader#264]
**Emulator version:**
1.2.8.4-open

**Game version:**
1.0.1

**Game resolution:**
``360x640 touchscreen``

**Device:**
``Jiayu S3 Plus``

**Android version:**
5.1

**Description of the issue:**
> `Level 14`
![screenshot_2018-03-30-10-36-03](https://user-images.githubusercontent.com/22563129/38128676-1ff4e1b8-342e-11e8-9701-31b8135b0fec.png)
![screenshot_2018-03-30-10-35-57](https://user-images.githubusercontent.com/22563129/38128678-20452c90-342e-11e8-8b22-978c48d3ec38.png)

> `Level 20`
[lvl20_demo.zip](https://github.com/nikita36078/J2ME-Loader/files/1862926/lvl20_demo.zip)

> `Level 22`
[lvl22_demo.zip](https://github.com/nikita36078/J2ME-Loader/files/1862933/lvl22_demo.zip)

> Also dialog screen sometimes pops up without any text written on it

**Comment by jasper1412** [comment]
1.4.9-play still had these bug. As I investigsted, when the game scrolls on the rightmost of map/area, graphics of character/sprite and its placement pushes to the leftmost area, putting it out of bounds.

**Comment by fireclouu** [comment]
fixed on 1.7.2-open
