### ISSUE TITLE
The Sims 3: World Adventures

### ISSUE THREAD

**Issue by Gamerhenky** [nikita36078/J2ME-Loader#265]
**Emulator version:**
1.2.8.4-play

**Game version:**
4.0.81 (Can be any)

**Game resolution:**
240x320

**Device:**
ASUS Zenfone Live

**Android version:**
6.0 Marshmallow
**Description of the issue:**
Game doesn't show anything afterwards but sound still fine. Screenshot below
![screenshot_20180330-162905](https://user-images.githubusercontent.com/37840226/38133364-0f1f913e-3439-11e8-9ba6-e3305e9249e7.png)
or this
![screenshot_20180330-163156](https://user-images.githubusercontent.com/37840226/38133373-1e11a768-3439-11e8-98a3-373a0b9c02f8.png)

**Comment by Manish089** [comment]
I played that game in v1.2.5.1 J2me loader but not in latest.haha

**Comment by BinariGuy** [comment]
You cannot Fix This?...
In the newer version (1.3.3 Open) no picture shows of the game

**Comment by nikita36078** [comment]
No, I didn't find a solution yet.

**Comment by nikita36078** [comment]
Fixed.
