### ISSUE TITLE
virtual buttons keeps getting stuck after menu screen

### ISSUE THREAD

**Issue by jasper1412** [nikita36078/J2ME-Loader#266]
**Emulator version:**
1.2.8.4-open

**Device:**
``Jiayu S3 Plus``

**Android version:**
5.1

**Description of the issue:**

> Last input before entering menu screen was `Up` and `Right`
![screenshot_2018-03-31-11-33-17](https://user-images.githubusercontent.com/22563129/38159287-d636bd44-34d7-11e8-94f6-c8921d7be962.png)

![screenshot_2018-03-31-11-33-58](https://user-images.githubusercontent.com/22563129/38159276-976bdf68-34d7-11e8-8547-995ddd8c11ad.png)

> buttons stuck at previous input
![screenshot_2018-03-31-11-34-34](https://user-images.githubusercontent.com/22563129/38159273-9357f722-34d7-11e8-8bea-052bf0a2a8a5.png)

**Comment by Manish089** [comment]
Because the emulator is not strong enough to handle multithreaded, It should have been bigger size of 5-10mb . 2mb fails so.

**Comment by nikita36078** [comment]
Fixed.
