### ISSUE TITLE
Bomberman 3D - Freezing/Crashing Issue

### ISSUE THREAD

**Issue by oatmeal01** [nikita36078/J2ME-Loader#267]
**Emulator version:**
1.2.8.4

**Game version:**
1.0.3

**Game resolution:**
``(240x320)``

**Device:**
``(Asus Z5)``

**Android version:** 
5.0

**Description of the issue:**
>**Issue 1:** The game freezes in menu (Can be fix by enabling immediate processing mode)
**Issue 2:** Enabled Immediate Processing Mode - The game crashes after finishing the first level.

**Comment by Manish089** [comment]
Dont use immediate processing mode. It crashes a lot

**Comment by nikita36078** [comment]
Fixed.
