### ISSUE TITLE
Ragnarok Mage - Movement Issue

### ISSUE THREAD

**Issue by oatmeal01** [nikita36078/J2ME-Loader#268]
**Emulator version:**
1.2.8.4

**Game version:**
1.2.1

**Game resolution:**
``(128x128)``

**Device:**
``(Asus Z5)``

**Android version:**
5.0

**Description of the issue:**
>\- Bug when moving the character: When tapping a directional  key e.g.(Down/8 button), it won't stop moving unless you double tap. 
\- Same issue with Ragnarok Archer (128x128).

**Comment by Manish089** [comment]
No maybe phone's too buggy I think.

**Comment by nikita36078** [comment]
Oh, that's actually a game feature, I didn't notice it before.
