### ISSUE TITLE
Hulk - Startup Issue

### ISSUE THREAD

**Issue by oatmeal01** [nikita36078/J2ME-Loader#269]
**Emulator version:**
1.2.8.4

**Game version:**
<img height="38" width="240" src="https://user-images.githubusercontent.com/36059629/38160579-e3a853f0-34f2-11e8-8881-7dc83242be7d.jpg"/>

**Game resolution:**
``(240x320)``

**Device:**
``(Asus Z5)``

**Android version:**
5.0

**Description of the issue:**
``(White screen only when launching the game.)``

**Comment by Manish089** [comment]
This is madness.unpredictable

**Comment by nikita36078** [comment]
@Manish089 Please stop spamming

**Comment by nikita36078** [comment]
Fixed.
