### ISSUE TITLE
j2me loader can run myboy-F emulator

### ISSUE THREAD

**Issue by ahmadprayoxxsy** [nikita36078/J2ME-Loader#271]
**Emulator version:**v.1.2.8.4

**Game version:**2.2.1

**Game resolution:**
``(For example, 240x320 or 640x360)``

**Device:**
``(For example, Samsung j120G)``

**Android version:**5.1.1

**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
the java meboy-f v.2.2.1 emulator can be run through the j2me loader application. very great
test game harvest moon.gbc
![screenshot_2018-03-31-17-33-13](https://user-images.githubusercontent.com/37769813/38162404-b48fde04-350a-11e8-839b-d2a1e75fea51.png)
![screenshot_2018-03-31-17-33-13](https://user-images.githubusercontent.com/37769813/38162405-b9a01bac-350a-11e8-89cb-a3ec7751b5a2.png)

**Comment by ahmadprayoxxsy** [comment]
![screenshot_2018-03-31-17-33-43](https://user-images.githubusercontent.com/37769813/38162412-fb754250-350a-11e8-8f44-0fcbe64acd67.png)
test game harvest moon.gbc

**Comment by ahmadprayoxxsy** [comment]
![screenshot_2018-03-31-17-44-01](https://user-images.githubusercontent.com/37769813/38162421-2585a576-350b-11e8-8748-c02d00e9a0f9.png)
all advanced gameboy games successfully played in the j2me loader emulator

**Comment by oatmeal01** [comment]
#93

**Comment by nikita36078** [comment]
I don't see any problems in the issue, so I close it.
