### ISSUE TITLE
Edge Extended Message to activate and buy the game

### ISSUE THREAD

**Issue by amarcioz** [nikita36078/J2ME-Loader#274]
Emulator version: 1.2.8.4

Game: Edge Extended touchscreen.

Game version: any. 

Game resolution: any

Device: Samsung Galaxy J1 2016

Android version: 5.1.1

Description of the issue: After a few minutes, a message appears to activate and buy the game via SMS. Of course this activation does not work
![180401_152639_rmscr](https://user-images.githubusercontent.com/35005836/38176392-175723b2-35c4-11e8-8c47-fe21d4eb3e7a.jpg)

**Comment by ahmadprayoxxsy** [comment]
download game Edge EX v.1.0.2 in "dedomil"
![screenshot_2018-04-02-05-03-24](https://user-images.githubusercontent.com/37769813/38178007-95bc501e-3633-11e8-87eb-d49e638ea459.png)

**Comment by amarcioz** [comment]
@ahmadprayoxxsy I did not find this version and the others are not touchscreen

**Comment by ahmadprayoxxsy** [comment]
try this version, no more error messages
![screenshot_2018-04-02-07-36-01](https://user-images.githubusercontent.com/37769813/38179057-b87f9ab0-3648-11e8-9f87-522116c57b1a.png)

**Comment by amarcioz** [comment]
@ahmadprayoxxsy Thank you.

**Comment by oatmeal01** [comment]
have you tried midlet version 1.0.3 (360x640)?

**Comment by nikita36078** [comment]
Emulator doesn't support sms sending because of security issues - there is a lot of sms viruses on j2me.

**Comment by nikita36078** [comment]
It's not a emulator problem then :) It shouldn't crack games, it would be copyright violation.
