### ISSUE TITLE
Devil may cry bug.

### ISSUE THREAD

**Issue by JunioJsv** [nikita36078/J2ME-Loader#275]
Emulator version: 1.2.8.4-play
Game: Devil may cry
Game version: any
Game resolution: 240x320
Device: Lg K10 2017
Android version: 7.0

O menu funciona ok, más quando eu dou new game a tela fica branca.

![](https://i.imgur.com/BTKZpZ9.png) 
![](https://i.imgur.com/IaPuwDa.png)

**Comment by amarcioz** [comment]
Você deve escrever em inglês.

**Comment by oatmeal01** [comment]
O emulador ainda não suporta o mascot casule 3D.

**Comment by nikita36078** [comment]
Issue #162.
