### ISSUE TITLE
UniFM

### ISSUE THREAD

**Issue by RenanSD007** [nikita36078/J2ME-Loader#276]
Name: UniFM
Emu-Version: v1.2.8.4
App-Version: v1.4
Device: LG E445
Problem: In Return the app close.

**Comment by nikita36078** [comment]
What do you mean? App closes when you return back in the file manager?

**Comment by RenanSD007** [comment]
When you are installing the J2ME Loader closes.

**Comment by RenanSD007** [comment]
I created "converted.dex" and moved all files to the "res" folder the app starts with the following message:
"STOP java.lang.NullPointerException" press to return and the app closes .

**Comment by oatmeal01** [comment]
same issue with Real Football 2018 (360x640) touchscreen version. J2ME loader crashes when installing/converting the game.

**Comment by AdityaMH** [comment]
But for me, Real Football 2018 (360×640) work nice without any bug, @oatmeal01 .

**Comment by oatmeal01** [comment]
@AdityaMH i can't convert RF2018  (360x640) for Nokia 5800. Installation takes too long to process then afterwards the emulator freezes(v1.2.8.4). The later version of the emulator crashes tho.

**Comment by RenanSD007** [comment]
@oatmeal01 Your smartphone convert the "UC Browser v9.5.449" in my smartphone when installing the emulator closes.

**Comment by RenanSD007** [comment]
@nikita36078 You can add "Mobile Media API (JSR 135)" support in the next update for apps like "Nescube" and "Meboy-F".

**Comment by oatmeal01** [comment]
@RenanSD007 I can install "UC Browser v9.5.0.449 java pf69 (build 14061718)" with no problem, both .jad and .jar.

**Comment by AdityaMH** [comment]
@oatmeal converting JAR is completed?

**Comment by oatmeal01** [comment]
@AdityaMH no, the emulator freezes(the later version crashes) while converting Real Football 2018 (360x640). The only compatible resolution is 240x320/320x240. Maybe there's a problem with the android version(Same issue like installing diamond rush. The game is only playable/compatible for os 4.4, os 7.1 but not playable on android os 5.0, 5.1 and 6.0.1)

**Comment by AdityaMH** [comment]
@oatmeal01 crashes occurred when converting JAR or while starting game (clicked a game), or sayin' "can't convert"? Because almost all Android phone when converting real football 2018, always take a time (little longer). But for me, game working like a charm. without any crash/freeze.

**Comment by oatmeal01** [comment]
@AdityaMH crashes occured when converting jar(this happens to the later version of emulator but for the latest update 1.2.8.4 the installation process freezes.).

**Comment by javi2man** [comment]
Some apps can't be converted. On screen appears can't convert", but they work on real java devices, please fix it

**Comment by nikita36078** [comment]
J2ME Loader needs at least 1.5 GB of RAM to convert java applications, low memory amount usually causes this problem.
