### ISSUE TITLE
Add Theme file & Global Keypad/keyboard color setting

### ISSUE THREAD

**Issue by AdityaMH** [nikita36078/J2ME-Loader#278]
this is really troublesome if they want set another keypad color to all games but must set keypad colors one by one.
I think add global keypad color setting will be better.

And I found interesting project for this emulator.
https://github.com/KNOLSKAPE/chameleon
I think about adding theme and theme selected from a listed folder/file.
And this who successfully implemented css as main theme: http://github.com/droidmjt/Droidsound

**Comment by nikita36078** [comment]
I've added the "Default settings" feature in the last version, now you can change settings for all games.

**Comment by nikita36078** [comment]
I don't plan to implement the theme engine, so I close this issue.

**Comment by AdityaMH** [comment]
That's what i needed now. Thanks.
