### ISSUE TITLE
SimCity: Societies

### ISSUE THREAD

**Issue by Gamerhenky** [nikita36078/J2ME-Loader#279]
**Emulator version:**
1.2.8.4-play

**Game version:**
1.12.56

**Game resolution:**
240x320

**Device:**
ASUS Zenfone Live

**Android version:**
6.0 Marshmallow

**Description of the issue:**
None of them are working, either both Nokia and Sony Ericsson version
![screenshot_20180408-155741](https://user-images.githubusercontent.com/37840226/38465476-551bde9a-3b46-11e8-810c-d4c70a200fe7.png)

**Comment by TRalperenTR** [comment]
Look this error.
![screenshot_20180408-204303](https://user-images.githubusercontent.com/37711793/38470572-8c39e53a-3b6d-11e8-8608-ad454f4b6dde.png)

**Comment by nikita36078** [comment]
Duplicate #194
