### ISSUE TITLE
N. O. V. A. 3 game graphics rendering problem

### ISSUE THREAD

**Issue by ghost** [nikita36078/J2ME-Loader#286]
**Emulator version:**
1.2.8.4-open

**Game version:**
1.2.0

**Game resolution:**
240x320

**Device:**
Gionee P5mini

**Android version:**
5.1

**Description of the issue:**
There is graphics rendering issue. The items/characters retain multiple images when there is movement and the game visuals get messed up.

**Screenshots:**
![screenshot_2018-04-09-11-31-05](https://user-images.githubusercontent.com/37379322/38482196-eb867692-3beb-11e8-89df-fc275a7291f5.png)
![screenshot_2018-04-09-11-31-16](https://user-images.githubusercontent.com/37379322/38482205-f169b592-3beb-11e8-986f-a3e2a60c4295.png)
![screenshot_2018-04-09-11-31-46](https://user-images.githubusercontent.com/37379322/38482217-fee64f1e-3beb-11e8-8b62-990851232912.png)
![screenshot_2018-04-09-11-32-03](https://user-images.githubusercontent.com/37379322/38482224-03c1c964-3bec-11e8-9c17-16e09dacf7c7.png)
![screenshot_2018-04-09-11-32-11](https://user-images.githubusercontent.com/37379322/38482229-080e3192-3bec-11e8-9dd0-3f39e3ac06a5.png)

**Comment by ahmadprayoxxsy** [comment]
Nova 3 toucheren 
![screenshot_2018-04-09-13-31-17](https://user-images.githubusercontent.com/37769813/38482712-9dce763e-3bfa-11e8-98a5-0d54b7a6fb6b.png)
480x800 no problem

**Comment by ahmadprayoxxsy** [comment]
240x320 no problem
![screenshot_2018-04-09-13-39-04](https://user-images.githubusercontent.com/37769813/38482983-86abe26a-3bfb-11e8-8392-6ec1d8acaaf3.png)

**Comment by ahmadprayoxxsy** [comment]
Game version V1.1.9

**Comment by nikita36078** [comment]
Fixed.
