### ISSUE TITLE
Dragon EYES episode 1-3

### ISSUE THREAD

**Issue by ahmadprayoxxsy** [nikita36078/J2ME-Loader#289]
**Emulator version:**
1.2.8.5.1

**Game version:**
1.0

**Game resolution:**
``(For example, 240x320 or 640x360)``
240x320
**Device:**
``(For example, Samsung j1)``

**Android version:**
5.1
**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
Dragon eyes episode 1-3 the screen blinks And in (j2me loader v1.2.8.5.1) new version, Games like: 360x640 Attack Tank, Galaxy on fire 2 full, the game feels heavy. Previously not in (j2me loader v1.2.7.9) game went very well.

**Comment by ahmadprayoxxsy** [comment]
In emulator (PhoneME) Asphalt 6 (480x800) and Dragon Eyes no problem

**Comment by Lanz89** [comment]
This bug is solved in a new update of emulator...
