### ISSUE TITLE
Add a option for selecting the way it should show the  menu.

### ISSUE THREAD

**Issue by SciFi1818** [nikita36078/J2ME-Loader#29]
Please add a option for selecting the way it should show the  menu...
That is current version of loader shows the menu in the action bar , it can be used full in many apps, but it is a kind of disturbing in a game etc...so please add a option to show the menu option in action bar or the normal back button way...

**Comment by SciFi1818** [comment]
Though current version  (1.2.4-test2) has a option to disable action bar, it can't bring back old feature..(back button show menu)

**Comment by nikita36078** [comment]
Back button doesn't work correctly on some devices, so I decided to remove this option.

**Comment by AdityaMH** [comment]
^ I have better solution as mentioned on #391
