### ISSUE TITLE
Rainbow Six Lockdown

### ISSUE THREAD

**Issue by Gamerhenky** [nikita36078/J2ME-Loader#291]
**Emulator version:**
1.2.8.5.1-play

**Game version:**
1.0.0

**Game resolution:**
240x320

**Device:**
ASUS Zenfone Live

**Android version:**
6.0 Marshmallow

**Description of the issue:**
This 1.2.8.5.1-play version of J2ME Loader when playing Rainbow Six Lockdown (240x320) sometimes gives you total black screen or not, the game may rarely work after quitting Rainbow Six Vegas then running this one. Previous version (1.2.8.4-play) is just fine
![screenshot_20180411-004309](https://user-images.githubusercontent.com/37840226/38574071-11672302-3d22-11e8-9a15-d7a7bd101818.png)

**Comment by nikita36078** [comment]
Fixed.
