### ISSUE TITLE
Sims 3 

### ISSUE THREAD

**Issue by RyukenT** [nikita36078/J2ME-Loader#292]
**Emulator version:**1.2.8.5.1

**Game version:**Maybe all

**Game resolution:**Maybe all
``(For example, 240x320 or 640x360)``

**Device:**Redmi note 4
``(For example, Samsung Galaxy S7)``

**Android version:**7.0

**Description of the issue:**Game stucks at loading screen. Crashes after few seconds by black screen
``(What's the problem? - Screenshots showing the issue if applicable)``

**Comment by telanus** [comment]
I'm using 
**Game version:**
MIDlet-Name: The Sims 3
MIDlet-Version: 7.8.68
MIDlet-Vendor: Electronic Arts

And it works as intended, been playing it on and off for a while now

**Comment by nikita36078** [comment]
Fixed.
