### ISSUE TITLE
Midnight Bowling 3 - Graphical Bug

### ISSUE THREAD

**Issue by oatmeal01** [nikita36078/J2ME-Loader#295]
**Emulator version:**
1.2.8.5.1

**Game version:**
1.0.7

**Game resolution:**
``(360x640)``

**Device:**
``(Asus z5)``

**Android version:**
5.0

**Description of the issue:**
``(Vertical lines appeared in Gameloft logo. Works fine in j2me 1.2.8.4)``
<img height="400" width="240" src="https://user-images.githubusercontent.com/36059629/38616949-47a1635a-3dc8-11e8-83b5-b72e008575cf.png"/>

**Comment by nikita36078** [comment]
Fixed.
