### ISSUE TITLE
Heroes Lore: Wind of Soltia crash in the main menu.

### ISSUE THREAD

**Issue by nikita36078** [nikita36078/J2ME-Loader#298]
**Emulator version:**
1.2.8.6

**Game version:**

**Game resolution:**
``(For example, 240x320 or 640x360)``

**Device:**
``(For example, Samsung Galaxy S7)``

**Android version:**

**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
Game crashed while going to main menu.

**Comment by oatmeal01** [comment]
Heroes Lore Wind of Soltia (240x320) v0.0.2 seems fine

**Comment by nikita36078** [comment]
@AdityaMH Do you still have any crashes? I don't see them too.

**Comment by AdityaMH** [comment]
your right, HL:WoS work great after disable "Immediate processing mode".
Sorry about that.

And another bug for Total Conquest (480×800, 1.0.0) market menu can't clickable. so i can't build building or spend resources. and for 360×640, 1.0.2 work great but sfx/sound unplayable.

**Comment by oatmeal01** [comment]
@Aditya do you experience slow loading screen in 480x800  games. All 480x games i installed is slow, comparing to 360x games loading screen is much smoother/faster.

**Comment by AdityaMH** [comment]
@oatmeal01 me too, All 480× not only slow in loading screen (like real j2me phone loading) and very little slow but still work and playable.

But from my testing, more smaller screen resolution, more smoother/faster.
