### ISSUE TITLE
Lag in game tank battle 3D

### ISSUE THREAD

**Issue by ahmadprayoxxsy** [nikita36078/J2ME-Loader#300]
**Emulator veesion**
1.2.8.7

**Game version:**
1.5.1

**Game resolution:**
``(For example, 240x320 or 640x360)``
630x360 Toucheren
**Device:**
``(For example, Samsung Galaxy S7)``
J120G
**Android version:**
5.1
**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
@nikita36078, Try playing the game (Tank battle). 
the game is very slow.

**Comment by nikita36078** [comment]
Fixed
