### ISSUE TITLE
You Made My Dream Come True ! Thanks... Great Emulator! 

### ISSUE THREAD

**Issue by T4P4N** [nikita36078/J2ME-Loader#301]
Thank You Very Much! I fall in love with this App!!!!!! Great Work! :+1:

**Comment by amarcioz** [comment]
The emulator needs to improve more. There are still many games that do not work correctly.

**Comment by AdityaMH** [comment]
this page only for reporting issue, glitch, bug, crashed game or wanting enhancement. If you like this app, you can rate on Play Store/Google Play and read full description.

**Comment by nikita36078** [comment]
I created a discussion thread on XDA - https://forum.xda-developers.com/android/apps-games/app-j2me-loader-t3777889
