### ISSUE TITLE
Sound issues with Sonic Unleashed

### ISSUE THREAD

**Issue by FateForWindows** [nikita36078/J2ME-Loader#304]
**Emulator version:**
~~1.2.8.7-play~~ Currently 1.3.8-play

**Game version:**
1.2.1

**Game resolution:**
``(For example, 240x320 or 640x360)``
240x320
**Device:**
``(For example, Samsung Galaxy S7)``
Amazon Fire (5th Gen)
**Android version:**
Fire OS 5.6.1.0
**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
There are numerous sound-related issues.
- ~~Sound effects don't play at all, even though this version has them.~~ Fixed.
- Music stops playing after a few loops or if the player dies.

These symptoms are not shown in two PC-based emulators I've tried, KEmulator and FreeJ2ME.
Besides these two issues, the game runs great. There are lots of different versions and it's hard to find the best ones due to the differences between them. For example, instead of the continue option some versions have quick play which is identical but not all versions allow progression in the story, instead forcing the player to start a new game. Other versions are also missing background details and on some there's no background at all. Some versions don't include sounds, while others have sound effects and others have music, whether it's a really short version of the tune or it's a slightly longer loop. A few versions use 3D models in a few short areas, like in Dragon Road acts 2 and 3, while others use basic 2D platforms or grind rails. This one contained all of those, the only issue being that the 240x320 resolution caused a bit of screen crunch. And this emulator is able to nail everything with almost no issues whatsoever. This emulator is fantastic. More people need to know about it and I'm glad this exists.

**Comment by FateForWindows** [comment]
Alright, I'm updating this really late but a version from late last year fixed the sound effects. Music looping is still partially broken.

**Comment by nikita36078** [comment]
No problems with the music looping in 1.5.3
