### ISSUE TITLE
L/R softkey can't function and load saves from another chapter game for series games.

### ISSUE THREAD

**Issue by lavius** [nikita36078/J2ME-Loader#306]
**Emulator version:**
1.2.8.8-play

**Game version:**

**Game resolution:**
240x320 

**Device:**
Sony XZ1

**Android version:**
8.0

**Description of the issue:**
I am so happy I can play old games on Android. Thank you!
I have some beautiful Chinese RPGs which made by Taiwanese team.
One is it called LOA_T(Legend of Ancient). LOA_T is this team's earlist game, the emulator L/R softkey can't function for this game. But the team's newer games, LOA_NT and LOAII, are normal.
And it is separate chapter game (11 chapters), the game will load save from last chapter, but can't load the save in emulator. I make a story flow for LOA_T1-1 because the language is Traditional Chinese, the story will run automatically when enter the maps. It will save after story end, and LOA_T1-2 will load save from LOA_T1-1.
I appreciate that you make the J2ME Loader. :)
[LOA_T.zip](https://github.com/nikita36078/J2ME-Loader/files/1921158/LOA_T.zip)

**Comment by nikita36078** [comment]
This game uses 7 and 9 instead of soft keys. About saves - just move old saves to the next game folder. Saves are located in J2ME-Loader/data.
