### ISSUE TITLE
Doom RPG language 

### ISSUE THREAD

**Issue by nakanaki** [nikita36078/J2ME-Loader#307]
**Emulator version:**
1.2.8.8-play

**Game version:**
1.0.92

**Game resolution:**
240x320

**Device:**
Motorola Moto E (2nd gen)

**Android version:**
6.0
**Description of the issue:**
game language is russian by default, can't change it. tried differents jar files and its the same.
![doom](https://user-images.githubusercontent.com/26018170/38915569-9690e5b6-42ba-11e8-94f0-9a8cfc96b482.png)

**Comment by AdityaMH** [comment]
It's not emulator bug, but game only have Russian language. Please convert jar with english language or languages your understanding.

**Comment by oatmeal01** [comment]
find another j2me game source, e.g. dedomil, sefan

**Comment by nikita36078** [comment]
Yes, it isn't an emulator issue.
