### ISSUE TITLE
The `microedition.locale` property isn't set correctly

### ISSUE THREAD

**Issue by vilugao** [nikita36078/J2ME-Loader#308]
**Emulator version:**
J2ME Loader 1.2.8.8-play

**Game version:**
Climate Mission v1.0.6, Memorize v1.0.13, by Nokia;
and others apps with localization support.

**Game resolution:**
240x320

**Device:**
Blackberry Priv

**Android version:**
6.0.1 (Marshmallow)

**Description of the issue:**
I can see that localized texts in Java ME game aren't getting right if the Android already have configured to Brazilian Portuguese. I suspect the `microedition.locale` is set to the country code and not to the language code.

With the default J2ME Loader `microedition.locale`:
![screenshot_20180418-230555_ok](https://user-images.githubusercontent.com/5456204/38967697-ab6837b0-435e-11e8-8cb7-4a70acd672a3.png)

With the `microedition.locale` manually set to `pt-BR`:
![screenshot_20180418-230502_ok](https://user-images.githubusercontent.com/5456204/38967730-c4d0be34-435e-11e8-9843-b8ee7fa544e4.png)

**Comment by nikita36078** [comment]
Pull request merged, thanks.
