### ISSUE TITLE
I hope to add Chinese resources and virtual keys to support hiding

### ISSUE THREAD

**Issue by xiexin52k** [nikita36078/J2ME-Loader#31]
Hello, I'm from China. Thank you very much for providing such a simulator for us. Can you add Chinese resources? If you don't have the time, I'd be happy to provide Chinese resources for your project, and can you provide hidden functionality for the virtual keys?

**Comment by mini536** [comment]
你好，我也来自中国

**Comment by nikita36078** [comment]
You can hide virtual keys, just uncheck the Show keyboard option.

**Comment by nikita36078** [comment]
I guess I can close this issue now :-)
