### ISSUE TITLE
Total Conquest (TS) bug on lollipop

### ISSUE THREAD

**Issue by AdityaMH** [nikita36078/J2ME-Loader#312]
When i tried all version, each resolution and version have different bug.
480×800, 240×400 for Samsung: Building/Unit on list can't selected normally.
360×640: Music can't playing normally, sometime crashed when battle mode.
240×400 for Nokia: All both bug included.
All non-TS: work great, but finger cursor is missing when installing TS version before (and without delete data game).

TS = Touch Screen

**Comment by nikita36078** [comment]
Fixed
