### ISSUE TITLE
how to use on android tv?

### ISSUE THREAD

**Issue by manyhelp** [nikita36078/J2ME-Loader#314]
use this project on android tv ?

How to set the resolution 640x530 or 1280x720 or 1920*1080 ?

How do you use it in the Android project?

 I'm developing is 640x530  or 1280x720  J2ME game ，I want to play on the Android set-top box。

**Comment by nikita36078** [comment]
You can set the app resolution with the "screen presets" button, but emulator isn't optimized for Android TV yet, so I'm not sure if it will work properly.

**Comment by manyhelp** [comment]
because the android tv install app very  trouble. so i hope this project  appled android tv with j2me project.
use  android launcher  + web  + j2me.
