### ISSUE TITLE
Night at the museum 2 touch screen failed

### ISSUE THREAD

**Issue by skelletR** [nikita36078/J2ME-Loader#315]
**Emulator version:**1.2.8.8

**Game version:**Night at the museum 2

**Game resolution:**
``(480x800 or 640x360)``

**Device:**
``(Sony Xperia Z5 )``

**Android version:**7.1.1

**Description of the issue:**
``Say this....  when the game in touch screen mode only 
Didn't find class "G" on path: DexPathList[[dex file "/data/user/0/ru.playsoftware.j2meloader/tmp_dex/converted.dex"],nativeLibraryDirectories=[/system/lib, /vendor/lib]]  ``

**Comment by skelletR** [comment]
My device Xperia z5.. But only some touch screen version of the game.. Now the game work with touch screen 640x360

**Comment by AdityaMH** [comment]
This issue for some Gameloft touchscreen games.
My life in New York (640x360, at beginning)
Dragon Mania (640x360, when choosing Dragon for Battle).
Total Conquest ( #312 ).
That's all i know.
Maybe another Gameloft game (touchscreen) have same issue too.

All problem is same, normal to touching but hardly to response.

**Comment by skelletR** [comment]
Understand.. Thanks for answer
