### ISSUE TITLE
Galaxy on Fire - Stucked Ship

### ISSUE THREAD

**Issue by TheVance** [nikita36078/J2ME-Loader#318]
**Emulator version:**
1.2.8.8-play

**Game version:**
1.2.9
**Game resolution:**
240x320

**Device:**
LG G3 D855
**Android version:**
6.0 Stock

**Description of the issue:**
After playing 12 missions ingame, on mission 13 the ship stuck "inside" other ship causing friction and in conclusion game ends.
Below I'm repeating bug presentation (video on YouTube):
[https://youtu.be/H7aVti8B8w8](https://youtu.be/H7aVti8B8w8)

**Comment by AdityaMH** [comment]
why not trying "Galaxy on Fire 2"? they have better feature game.

**Comment by nikita36078** [comment]
@AdityaMH I don't think it really matters in this issue.
@TheVance Can you provide game saves? You can find them in J2ME-Loader/data folder.

**Comment by AdityaMH** [comment]
I don't know why, but too many converting JAR to same game making game save error and affected to gameplay/graphic too.

**Comment by TheVance** [comment]
@nikita36078 Unfortunately, I had lost my data, because of overheating, but I can confirm that this bug repeats also on KEmulator ver. 0.9.8 on PC (both 240x320/176x220 resolutions, same game version).

**Comment by AutoVeron** [comment]
@TheVance  it's an in-game problem.... Some later version has the ship spawned outside the cruiser.... So it is an in-game bug... In my phone the ship spawned correctly, but in my brother's phone it stuck... But he did some turning and finally get free from that cruiser (albeit with low HP). He completed the mission though.

**Comment by SerhiyZSP** [comment]
Hello. I had same problem in Galaxy on Fire in version 1.2.9. So I installed version 1.1.2 and copy my save files - mission 13 started without problem. So it is definitely game problem.
