### ISSUE TITLE
I'm having trouble hiding buttons in landscape mode

### ISSUE THREAD

**Issue by jack1432** [nikita36078/J2ME-Loader#322]
**Emulator version:**
1.2.9
**Device:**
Samsung Galaxy J1 mini
**Android version:**
5.1.1
**Description of the issue:**
On my device, the option to hide buttons is almost hidden when playing in landscape mode.
![screenshot_2018-05-04-10-44-22](https://user-images.githubusercontent.com/36806488/39657860-b95fc8c0-4ffb-11e8-98df-e2240a5f579d.png)

**Comment by nikita36078** [comment]
No, he can't scroll because of statusbar, it seems to be Android bug.

**Comment by jack1432** [comment]
@nikita36078 so you have no solution for that?

**Comment by nikita36078** [comment]
@jack1432 I'm working on it.

**Comment by jack1432** [comment]
😊

**Comment by AdityaMH** [comment]
That not Android bug.
This issue only affected when disable ActionBar or immersive mode.

**Comment by 1234Sameer** [comment]
Previously it was working fine. Tested on 1.2.8

**Comment by nikita36078** [comment]
Fixed
