### ISSUE TITLE
Potrait mode gameplay

### ISSUE THREAD

**Issue by RyukenT** [nikita36078/J2ME-Loader#323]
**Emulator version:**
1.2.9

**Game version:**

**Game resolution:**240x320
``(For example, 240x320 or 640x360)``

**Device:**redmi note 4 pro
``(For example, Samsung Galaxy S7)``

**Android version:**7.1.2

**Description of the issue:*Slow game speed and drops frame rate in potrait mode compared to landscape mode in 240x320 screen games.Mostly gameloft games
``(What's the problem? - Screenshots showing the issue if applicable)``

**Comment by nikita36078** [comment]
It's an optimization issue, so it's the same as #310
