### ISSUE TITLE
Java app becomes unable to run after few days

### ISSUE THREAD

**Issue by sami-ur** [nikita36078/J2ME-Loader#324]
Emulator version: 1.2.9

Device : Samsung galaxy j7 nxt

Os: android 7.0

Games name: Ra one, bounc tale, k.g.b swat etc

Description: some java games become unable to run after somtime of installing and one more is that facebook jar is not running too.

**Comment by nikita36078** [comment]
What do you mean by "unable to run"? Do these games show any errors?

**Comment by sami-ur** [comment]
After intalling these i can open them for few hours or day then i cant open

**Comment by sami-ur** [comment]
Yea it keep stopping with error

**Comment by nikita36078** [comment]
Did the latest version fix this problem?
