### ISSUE TITLE
Some game stuck 

### ISSUE THREAD

**Issue by skelletR** [nikita36078/J2ME-Loader#325]
Emulator version:1.2.9-play

Game version:

Game resolution:All screen 

Device:Sony Xperia Z5 

Android version:7.1.1

Description of the issue:
some game like mtv star factory.. play it for little but after stuck the game and must close and after open again work for little but again the same stuck

**Comment by nikita36078** [comment]
Use Immediate proccesing mode.

**Comment by skelletR** [comment]
Thanks.. I think work for this game not stuck for lot minutes.. What can do the Immediate proccesing mode?

**Comment by nikita36078** [comment]
It disables limit for frames in the rendering queue, can be very useful sometimes.
