### ISSUE TITLE
Bugs On Some Games

### ISSUE THREAD

**Issue by abjnwb007** [nikita36078/J2ME-Loader#326]
**Emulator Version:**
1.2.9-open

**Game Resolution:**
240x320

**Device:**

Lenovo A1000

**Android version:**
5.0

**Description of the issue:**
especially Deep 3d, those blue lines is really annoying

**Micro Counter Strike**
![screenshot_2018-05-06-03-32-46](https://user-images.githubusercontent.com/39013876/39667469-a4f8aea0-50a6-11e8-92f8-072a976defa5.png)

**BattleBoats 3D**
![screenshot_2018-05-06-03-30-09](https://user-images.githubusercontent.com/39013876/39667474-b3410444-50a6-11e8-8097-7087a7d1c3fe.png)

**Playman Xtreme Running - Stuck In Select Screen**
![screenshot_2018-05-06-04-16-45](https://user-images.githubusercontent.com/39013876/39667624-0b6d6d94-50aa-11e8-9885-1a0e4b255c36.png)

**Deep 3D - The Annoying Bugs**
![screenshot_2018-05-06-03-28-45](https://user-images.githubusercontent.com/39013876/39667476-bfbf7eda-50a6-11e8-9812-281fae9068df.png)

**Comment by nikita36078** [comment]
Micro Counter Strike - #227 
Playman - just use Immediate proccessing mode

I will create separate issues for Deep and Battleboats, one issue for multiple games isn't really convenient.
