### ISSUE TITLE
WWE Legends of Wrestlemania graphical issue

### ISSUE THREAD

**Issue by leopard20** [nikita36078/J2ME-Loader#330]
**Emulator version:**
1.2.9

**Game version:**
0.9.88

**Game resolution:**
240x320

**Device:**
Mi 5s Plus

**Android version:**
7.0
**Description of the issue:**
The background where the crowd is standing is white:
![screenshot_2018-05-11-15-03-37-951_ru playsoftware j2meloader](https://user-images.githubusercontent.com/16115820/39920616-f0d98e2c-552c-11e8-851d-58ea4ddb0bed.png)

**Comment by nikita36078** [comment]
Fixed.
