### ISSUE TITLE
Shinobi 2 shows error on open

### ISSUE THREAD

**Issue by sakamoto-neko** [nikita36078/J2ME-Loader#331]
**Emulator version:**
1.2.9-play

**Game version:**
1.0.0

**Game resolution:**
240x320

**Device:**
Sony Xperia XZ1

**Android version:**
8.0.0

**Description of the issue:**
Game errors on open. Proper resolution was set before opening. Tried both English and Chinese versions.

![screenshot_20180516-094924](https://user-images.githubusercontent.com/17673235/40092296-14a052d2-58ac-11e8-9afe-4e55143322fb.png)

**Comment by sakamoto-neko** [comment]
Yes. Not sure why mine does not work. Is there any particular settings that you used for this game?

**Comment by amarcioz** [comment]
I have not used any settings. I downloaded it from the Phoneky site.
Version 1.0.0

**Comment by amarcioz** [comment]
I have not used any settings. I downloaded it from the Phoneky site.
Version 1.0.0.
Samsung Gslaxy J1 2016 
Android 5.1

**Comment by sakamoto-neko** [comment]
Okay I got one to work from that site. Thanks.
