### ISSUE TITLE
game wont load

### ISSUE THREAD

**Issue by monkeybee11** [nikita36078/J2ME-Loader#332]
**Emulator version:**
1.2.9-play

**Game version:**
2.2.5

**Game resolution:**
``(For example, 240x320 or 640x360)``
not sure
**Device:**
``(For example, Samsung Galaxy S7)``
samsung galaxy tab10?
**Android version:**
5.1.1
**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
try to load up salem the crafting mmo
and it just gives me a broken menifest message
mate of mine said the menifest look allright to him
game can be found here : http://www.salemthegame.com (u get it as a jnlp here)
the games jar file can be found here : http://game.salemthegame.com/java/salem.jar

**Comment by nikita36078** [comment]
It's not a J2ME game, this emulator supports only J2ME games.

**Comment by AdityaMH** [comment]
If you don't know what j2me is, try searching game such like "My life in New York".

Btw, Java and J2ME is different/not same.

**Comment by nikita36078** [comment]
@monkeybee11 Your game is made for Java Standard Edition (targeting workstation environments), this emulator supports Java Micro Edition (targeting environments with limited resources).
