### ISSUE TITLE
Save scroll position after midlet destroy

### ISSUE THREAD

**Issue by jack1432** [nikita36078/J2ME-Loader#333]
**Description of the issue:**
@nikita36078 could you put an option to choose whether the emulator will restart or not after quitting a game? I liked it better when I did not have this reboot in the emulator, I know this was added to fix the problem with the sound running in the background after exiting some games (#136), but I never had this problem with the sound. For me, which has many games installed, it's annoying to always scroll down every time I quit a game, and also explains this in `` Help``, so users understand why the emulator restarts after quitting a game.

**Comment by hex007** [comment]
@nikita36078  It would be worth it to save scroll state so when the activity comes back in focus the list is scrolled to the game already. Possibly move to RecyclerView for its various advantages.

**Comment by nikita36078** [comment]
The emulator restarts not only because of the sound issues, there are  also another problems which can be fixed by this way. And I guess the scroll position saving would be really good feature, I will consider it.

**Comment by jack1432** [comment]
Well, I think this has been solved, so I close this question.
