### ISSUE TITLE
Civilization V Bug

### ISSUE THREAD

**Issue by TragicLifeHu** [nikita36078/J2ME-Loader#335]
Emulator version:1.7.9 Open
Game version:1.2.3
Game resolution:800x480
Device:Samsung Galaxy S3,S5;Xiaomi Redmi 1SC
Android version:4.3;7.1.2
Description of the issue:Normally Playing,and after a shout time it suddenly became lag,then it back to the main menu and my saves lost

**Comment by AdityaMH** [comment]
Try install 640×360 version, they run like a charm. But not for another gameloft games.

**Comment by TragicLifeHu** [comment]
Ok,just the poor device.
