### ISSUE TITLE
your emulator's keyboard doesn't well

### ISSUE THREAD

**Issue by mini536** [nikita36078/J2ME-Loader#342]
**Emulator version:**
1.2.9

**Game version:**
1.0（only have that version）

**Game resolution:**
``240×320``

**Device:**
``Xiaomi One``

**Android version:**
4.1
**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
when I use it to play APRG game ,It seems that the key which I usually press often not recover until I press another key

**Comment by nikita36078** [comment]
I know about this issue, it was already mentioned in #141
