### ISSUE TITLE
App shortcuts are not working anymore

### ISSUE THREAD

**Issue by Instandhaltung** [nikita36078/J2ME-Loader#345]
**Emulator version:**
1.30

**Device:**
OnePlus 5T

**Android version:**
8.1

**Description of the issue:**
After updating to 1.30, the shortcuts to the games are not working anymore. Even after deleting them and shortcutting the game again, Android says the App is not installed. :-(

![screenshot_20180621-212643](https://user-images.githubusercontent.com/20743229/41741460-72039e50-759b-11e8-97b6-7e48dcd74d3b.jpg)

**Comment by nikita36078** [comment]
Fixed in 1.3.1. But unfortunately you need to add all shortcuts again.

**Comment by Instandhaltung** [comment]
All right. Thanks man, I'm glad you're back! :-*
