### ISSUE TITLE
Diamond Island 1 and 2 (touch/HD edition) stuttering

### ISSUE THREAD

**Issue by Instandhaltung** [nikita36078/J2ME-Loader#346]
**Emulator version:**
1.30

**Game version:**
Diamond Island - 1.0.47
Diamond Island 2 - 1.0.48

**Game resolution:**
360x640 (DI1) and 640x360 (DI2)

**Device:**
OnePlus 5T

**Android version:**
8.1

**Description of the issue:**
These games stutter a lot while playing. These are the versions where 4 people are moving the block you have to move to a goal. There are simpler versions of the game where you can only see the block (and that are for smaller resolution phones), these work without stuttering.

![screenshot_20180621-212936](https://user-images.githubusercontent.com/20743229/41741738-3bcc9e6c-759c-11e8-9ddd-eff95fef083f.jpg)
![screenshot_20180621-213035](https://user-images.githubusercontent.com/20743229/41741751-3f2def16-759c-11e8-9d47-21f6b771690a.jpg)

**Comment by nikita36078** [comment]
Don't see any lags on 1.5.3.
