### ISSUE TITLE
Treasure Towers

### ISSUE THREAD

**Issue by z3ntu** [nikita36078/J2ME-Loader#349]
**Emulator version:**
1.3.1

**Game version:**
1.4.4

**Game resolution:**
240*320?

**Device:**
Fairphone 2

**Android version:**
7.1.2

**Description of the issue:**
When I start the game I get "Error" "divide by zero"

**Comment by nikita36078** [comment]
J2ME Loader doesn't support Mascot Capsule 3D games.

**Comment by aliza-ada** [comment]
Hi 
i runed Treasure Towers v1.4.4 and 1.3 and more version.
Game is runed but not played

**Comment by nikita36078** [comment]
Fixed

**Comment by z3ntu** [comment]
That's amazing, thank you so much!

![Screenshot_20230710-143200](https://github.com/nikita36078/J2ME-Loader/assets/3768500/56f9f6ba-c5f6-4809-b017-c794d67503d2)
