### ISSUE TITLE
'Mute' text shows background of a screen that's not yet supposed to show

### ISSUE THREAD

**Issue by faissaloo** [nikita36078/J2ME-Loader#350]
**Emulator version:**  
1.3.1  

**Game version:**  
Sonic The Hedgehog Part 2  

**Game resolution:**  
240x320  

**Device:**  
Moto G4  

**Android version:**  
Android 7.1.2 / Lineage 14.1  

**Description of the issue:**  
As you can see here 'mute' shows part of the main menu background ![](https://i.imgur.com/elHdDE4.png)

**Comment by nikita36078** [comment]
Fixed
