### ISSUE TITLE
Sonic The Hedgehog Part 2

### ISSUE THREAD

**Issue by faissaloo** [nikita36078/J2ME-Loader#351]
**Emulator version:**  
1.3.1  

**Game version:**  
Sonic The Hedgehog Part 2

**Game resolution:**  
240x320  

**Device:**  
Moto G4  

**Android version:**  
Android 7.1.2 / Lineage 14.1  

**Description of the issue:**  
As you  can see from this image the arrows aren't aligned with the text, this present wherever these arrows are used in the game ![](https://i.imgur.com/hYuCCXJ.png)

**Comment by oatmeal01** [comment]
did you declare the right game resolution and orientation?

**Comment by nikita36078** [comment]
Fixed
