### ISSUE TITLE
Soft button labels not displayed

### ISSUE THREAD

**Issue by schierlm** [nikita36078/J2ME-Loader#352]
**Emulator version:**
1.3.1

**Game version:**
e.g. http://midp-calc.sourceforge.net/ (not a game though)

**Game resolution:**
For example 320x240

**Device:**
Nokia 3

**Android version:**
8.0

**Description of the issue:**
Several phones (e.g. old Symbian Nokia phones or Sony Ericsson phones) when having a screen not running in fullscreen and the J2ME menu contains exactly 2 items, show the labels of these menu items above the soft buttons. Some apps (not so much games, but for example the calculator app I linked above) heavily depend on this way to quickly tell the user what button to press.

When running these apps in this emulator, it is possible to use them, by opening the menu every time and clicking the commands there, but since the apps are optimized to have the most important actions on soft buttons, it is a lot slower than on a real device.

**Comment by AdityaMH** [comment]
so..., what the main problem of that?

**Comment by DrBomb** [comment]
Ran into the same issue. I think those soft button labels should be added to the keymaps, would be great.

**Comment by nikita36078** [comment]
Fixed

**Comment by schierlm** [comment]
Thank you, works great!
