### ISSUE TITLE
will ios version possible？

### ISSUE THREAD

**Issue by mini536** [nikita36078/J2ME-Loader#353]
I hope iphone can have an better emulator like this

**Comment by hex007** [comment]
J2ME loader uses the same Java VM, Dalvik or Art, as Android and thus leverage it to gain significant performance boosts. I dont know if that would be possible on iOS.

**Comment by nikita36078** [comment]
This emulator is written and optimized specifically for Android, so it can't be ported on iOS.

**Comment by alysdexia** [comment]
http://google.com/search?q=J2ME+OR+"Java+ME"+"iPhone OS"+OR+iOS+Oracle
