### ISSUE TITLE
Bug Devil May Cry 3D

### ISSUE THREAD

**Issue by DiegoSousa123** [nikita36078/J2ME-Loader#357]
**Emulator version:**
 V 1.3.1-play

**Game version:**
V 1.0.1

**Game resolution:**
   240x320

**Device:**
Samsung Galaxy J7 Neo

**Android version:**
  Android 7.0 Nougat

**Description of the issue:**
    
The game has a white bug on the screen, neither one of the improvement options worked

**Comment by jack1432** [comment]
This game needs Mascot Capsule 3D support to work and the emulator still does not have support for this, which is why the game does not open.

**Comment by DiegoSousa123** [comment]
Does not he use the same Resident Evil Degeneration engine? Re: Degeneration works normally

**Comment by nikita36078** [comment]
It was already mentioned in #162
