### ISSUE TITLE
Prince of india error

### ISSUE THREAD

**Issue by ashutoshmaurya1122** [nikita36078/J2ME-Loader#362]
**Emulator version:**
1.3.1

**Game version:**
1.0

**Game resolution:**
240×320

**Device** tested on panasonic eluga i3 and redmi note 5

**Android version:**5.1 and 7.1

**Description of the issue:**
![screenshot_2018-07-31-15-46-20-762_ru playsoftware j2meloader](https://user-images.githubusercontent.com/41411168/43454302-2d0234a2-94da-11e8-8887-a79242125f10.png)

**Comment by woesss** [comment]
@nikita36078  For fix this issue need add `toLowerCase()` for `type` in method [Manager.createPlayer(InputStream stream, String type)](https://github.com/nikita36078/J2ME-Loader/blob/2fcff548e307ed23d7cdbbfa698e6110f0409013/app/src/main/java/javax/microedition/media/Manager.java#L44)  
Mime types is case-insensitive ([RFC 2045]((https://tools.ietf.org/html/rfc2045#page-12)).

**Comment by nikita36078** [comment]
@woesss Thanks, fixed!

**Comment by ashutoshmaurya1122** [comment]
When this fixed update will arrive?

**Comment by nikita36078** [comment]
Definitely this month :)
