### ISSUE TITLE
Chrome's ARC Welder hardware acceleration

### ISSUE THREAD

**Issue by stranno** [nikita36078/J2ME-Loader#363]
J2ME-Loader works fine with ARC Welder Chrome APP, but there's no hardware acceleration.

Can this be added? As far as i tried games run smooth but it could be a neat feature.

**Comment by nikita36078** [comment]
Currently, the emulator requires at least Android 6.0 for hardware acceleration (ARC Welder is based on 5.0), maybe I will add support for an older OS versions in the future, but I don't have such plans right now.

**Comment by chiddekel** [comment]
The source code of Android 5 compare to Android 6 of the emulator 4 hardware acceleration? 
Better option replaces the code of Android 5 emulator to Android 6 emulator of ARC Welder ?

**Comment by chiddekel** [comment]
https://github.com/vladikoff/chromeos-apk/blob/master/archon.md
Try this it is HW accelerated.

**Comment by nikita36078** [comment]
The hardware acceleration support is available now for Android 4.0-5.0.
