### ISSUE TITLE
[Improvement] Layout simulation

### ISSUE THREAD

**Issue by JunioJsv** [nikita36078/J2ME-Loader#364]
- Remake the interface to try to simulate the appearance of old cell phones, like the Retro2me fork, but to be cool it has to be something well done to really look like you're running an old j2me system
![Screenshot](https://i.imgur.com/CnTPQKN.png)
![](https://i.imgur.com/AeUlg34.png)

**Comment by amarcioz** [comment]
This emulator is a copy of j2ME Loader with few settings. You can only play vertical.

**Comment by oatmeal01** [comment]
j2me loader is far way more better, but if you want theme like old java phones ask the dev to add that feature to the next update

**Comment by AdityaMH** [comment]
It will be more nostalgia when (game/app) list very like full-screen old nokia or walkman/se..
And playing emulation still like original (for j2me loader identity)..

PS: More greater if add .nth or .thm as file theme (only for game/app list).

**Comment by 1234Sameer** [comment]
Guys, don't you think this feature is a bit fancy and unnecessary. I mean look at other emulators, they don't try to mimic the look their respective systems instead they are more focused on functionality to provide similar experience.

**Comment by AdityaMH** [comment]
Appearance just for nostalgia purpose. But functional and game/app compability most important than that.

**Comment by ahmadprayoxxsy** [comment]
AdityaMH kamu orang indonesia?

**Comment by AdityaMH** [comment]
It's much better if improved theme color, just like this:


![1538651272039](https://user-images.githubusercontent.com/33791472/46470864-a1b1bf00-c7c7-11e8-84b4-e6ecaea88bd1.png)
That really weird when icon color, default keypad color are blue but actionbar is black.

![1538651271347](https://user-images.githubusercontent.com/33791472/46471048-39171200-c7c8-11e8-9497-941273760561.png)
With little transparent in menu, make J2ME Loader look modern.

Only one thing, can you add setting to showing actionbar only, navbar only or both, @nikita36078 ?

**Comment by 1234Sameer** [comment]
@AdityaMH 
How did you do these things?
You did this by programming or these are just simple edited images?

**Comment by oatmeal01** [comment]
@Sameer i guess he modified the app

**Comment by jack1432** [comment]
I liked that, it would be cool if it had a theme like this in the app or an option to change colors to our liking, just like on the keyboard. I would very much like that to be added.

**Comment by AdityaMH** [comment]
of course not, @oatmeal01 . i only edited screenshot to making example.

**Comment by sameer** [comment]
You got the wrong sameer @oatmeal01 
(mentioning @1234Sameer )

**Comment by nikita36078** [comment]
The phone-like keyboard has been added, I'm not planning to add themes to it.
