### ISSUE TITLE
Asphalt 3 3D and NitroStreet Racing 3D close

### ISSUE THREAD

**Issue by Edher-Ivan** [nikita36078/J2ME-Loader#365]
**All versions**

**A3: 1.1.5
NSR: 1.1.2 **

**Game resolution: 240x320 and 320x240 both**

**Device: Moto G1**

**Android version: 5.1**

**Description of the issue: **
A3: http://tinypic.com/r/2rr4aaa/9 
NSR: http://tinypic.com/r/1z23780/9

**Comment by nikita36078** [comment]
Can't be fixed, this issue exists only on Android 5.0-6.0.
