### ISSUE TITLE
Someone stole your beautiful work !!

### ISSUE THREAD

**Issue by Edher-Ivan** [nikita36078/J2ME-Loader#366]
https://mobile.twitter.com/retro2me

**Comment by amarcioz** [comment]
This emulator is a copy of j2ME Loader with few settings. You can only play vertical.

**Comment by nikita36078** [comment]
J2ME Loader is an open source project, so there is nothing wrong with this app, until it doesn't violate the Apache License.

**Comment by AdityaMH** [comment]
This issue same like pcsx2 vs damonps2.
Even this emulator have better UI, I'm still love J2ME Loader because flexibility setting.
![screenshot_2018-08-05-21-38-58-926_net ovaplay retro2me](https://user-images.githubusercontent.com/33791472/43687026-46fb26d8-98be-11e8-9217-2901c47edef6.png)

**Comment by nikita36078** [comment]
Not the same issue, the developer of retro2me mentioned all used projects in his app, so actually he didn't steal anything.
