### ISSUE TITLE
Racing fever GT 3d shadow bug.

### ISSUE THREAD

**Issue by 1234Sameer** [nikita36078/J2ME-Loader#367]
**Emulator version:**
1.3.1-play

**Game resolution:**
240x320

**Android version:**
5.0

**Description of the issue:**
![screenshot_2018-08-09-10-51-59](https://user-images.githubusercontent.com/39208952/43880245-36a1f7da-9bc5-11e8-8bc3-acb9896d9dba.png)
![screenshot_2018-08-09-10-51-06](https://user-images.githubusercontent.com/39208952/43880261-44b384f6-9bc5-11e8-8d66-adb058bce3a3.png)
Color of the shadow is not black.

**Comment by nikita36078** [comment]
Fixed.
