### ISSUE TITLE
Uno and Friends no sound

### ISSUE THREAD

**Issue by 0xh3LL0** [nikita36078/J2ME-Loader#368]
**Emulator version:**
1.3.1 open

**Game version:**
Uno and Friends v1.0.7

**Game resolution:**
640x360

**Device:**
Oppo F1F Snapdragon 616

**Android version:**
5.1.1

**Description of the issue:**
Game run just fine, i'm able to finish it, 
but there is no sound even if i activate music and sfx

**Comment by nikita36078** [comment]
Fixed
