### ISSUE TITLE
[BUG] Splinter Cell - Extended Ops (v1.3.9) (176x208) 

### ISSUE THREAD

**Issue by BeF1990** [nikita36078/J2ME-Loader#369]
**Emulator version:**
1.3.1

**Game version:**
1.3.9

**Game resolution:**
176x208

**Device:**
Samsung Galaxy S TAB 2

**Android version:**
7.0

**Description of the issue:**
The game has graphic issue and crash - it's impossible to continue game.
You can see what happens in this video what I made:
https://youtu.be/Njr7i3cjLKE

**Comment by nikita36078** [comment]
Fixed
![screenshot_1535460991](https://user-images.githubusercontent.com/3035571/44724315-00a25b00-aadb-11e8-8098-bb4637b15206.png)

**Comment by BeF1990** [comment]
Good job! Thanks.
When can we expect new emulator version?

And I made mistake - it wasn't Galaxy S7. I play on Galaxy S TAB 2.

**Comment by nikita36078** [comment]
New version will be released in few days.
