### ISSUE TITLE
Turbo jet ski 3d bug.

### ISSUE THREAD

**Issue by 1234Sameer** [nikita36078/J2ME-Loader#370]
**Emulator version:**
1.3.1-play

**Game resolution:**
240x320 s40v3.

**Android version:**
5.0

**Description of the issue:**
![screenshot_2018-08-29-10-23-53](https://user-images.githubusercontent.com/39208952/44768456-ff2a6e80-ab7e-11e8-80f3-67378ecca667.png)

The water is black.

**Comment by nikita36078** [comment]
Fixed.
