### ISSUE TITLE
UC Browser graphic bug

### ISSUE THREAD

**Issue by AdityaMH** [nikita36078/J2ME-Loader#373]
![screenshot_2018-09-01-17-10-25-010_ru playsoftware j2meloader](https://user-images.githubusercontent.com/33791472/44945023-84589200-add0-11e8-8144-5f3f2925079c.png)
since using version 1.3.1 - 1.3.3, Browsing (YouTube for example) with UC Browser 9.5, graphic become glitched when scrolling down.
![Uploading Screenshot_2018-09-01-17-10-25-010_ru.playsoftware.j2meloader.png…]()

**Comment by nikita36078** [comment]
Will be fixed in the next version.

**Comment by AdityaMH** [comment]
Thanks, that's great..
