### ISSUE TITLE
Need for speed most wanted 3d 

### ISSUE THREAD

**Issue by RyukenT** [nikita36078/J2ME-Loader#374]
**Emulator version:**

1.3.3
**Game version:**1.0

**Game resolution:**240x320
``(For example, 240x320 or 640x360)``

**Device:**samsung galaxy S6 active
``(For example, Samsung Galaxy S7)``

**Android version:**6.0.1

**Description of the issue:** Cant open the game.
``(What's the problem? - Screenshots showing the issue if applicable)``

**Comment by RyukenT** [comment]
![screenshot_20180901-010100](https://user-images.githubusercontent.com/37715742/44932333-867d0b00-ad54-11e8-8b18-a500c8dc72b3.png)

**Comment by nikita36078** [comment]
Fixed.
