### ISSUE TITLE
Need for speed carbon

### ISSUE THREAD

**Issue by RyukenT** [nikita36078/J2ME-Loader#375]
**Emulator version:**

1.3.3
**Game version:**1.1.98

**Game resolution:**240x320
``(For example, 240x320 or 640x360)``
samsung Galaxy  S6 active
**Device:**
``(For example, Samsung Galaxy S7)``

**Android version:**6.0.1

**Description of the issue:**Terrible graphics textures drawn.broken
``(What's the problem? - Screenshots showing the issue if applicable)``

**Comment by RyukenT** [comment]
![screenshot_20180901-010913](https://user-images.githubusercontent.com/37715742/44932749-2b4c1800-ad56-11e8-80dd-83eb3fe2acd0.png)
![screenshot_20180901-010906](https://user-images.githubusercontent.com/37715742/44932769-43239c00-ad56-11e8-8896-245e9e927467.png)

**Comment by RyukenT** [comment]
Even by using those options
![screenshot_20180901-011508](https://user-images.githubusercontent.com/37715742/44932832-6fd7b380-ad56-11e8-82ca-50958e2a5ef4.png)

**Comment by 1234Sameer** [comment]
@amarcioz 
You are plating the 2d version.

**Comment by nikita36078** [comment]
Fixed.
