### ISSUE TITLE
[Feature request] Motorola phone keypad support.

### ISSUE THREAD

**Issue by 1234Sameer** [nikita36078/J2ME-Loader#376]
Motorola phone games are not playable due to keypad limitation.

**Comment by oatmeal01** [comment]
Selection options of keypad mode (nokia/motorolla) would be a good idea to add in game config.

**Comment by AdityaMH** [comment]
And add virtual qwerty keypad (nokia 320×240) too..
Much better if they set as main template and add switch keypad layout (per template) option [in general menu].

**Comment by 1234Sameer** [comment]
@AdityaMH @oatmeal01
I guess it would be easy to implement the keypads but the difficult part would be the design. By design I mean how things will work. I think adding these features like this would make things messy for editing and saving templates. So it is better to design a flexible layout editor first.

**Comment by AdityaMH** [comment]
flexible layout editor was added from beginning.. maybe add fully managing template editor (edit keypad layout, hidden key and configuration)(or maybe add selected template (keypad layout) for swap keypad layout option in [general menu]).

**Comment by 1234Sameer** [comment]
@nikita36078 
Please consider this now.

**Comment by nikita36078** [comment]
Motorola and Siemens layouts have been added

**Comment by Lanz89** [comment]
> Motorola and Siemens layouts have been added

How to add Motorola layouts? Any guide?

**Comment by woesss** [comment]
In game settings:
![Image](https://user-images.githubusercontent.com/36137354/75704128-d3cf9500-5cc9-11ea-915f-cf38f3212660.png)
