### ISSUE TITLE
R.U.S.H street war

### ISSUE THREAD

**Issue by RyukenT** [nikita36078/J2ME-Loader#377]
**Emulator version:**1.3.3

**Game version:**1.0

**Game resolution:**240x320
``(For example, 240x320 or 640x360)``

**Device:**Samsung galaxy S6
``(For example, Samsung Galaxy S7)``

**Android version:**6.0.1

**Description of the issue:**Game freezed and force stop emulator after opening the game
![screenshot_20180905-160947](https://user-images.githubusercontent.com/37715742/45088417-6eacda80-b0f8-11e8-9cf0-313651cb6960.png)

``(What's the problem? - Screenshots showing the issue if applicable)``

**Comment by nikita36078** [comment]
Fixed.
