### ISSUE TITLE
Feature request: emulation speed

### ISSUE THREAD

**Issue by 0xh3LL0** [nikita36078/J2ME-Loader#378]
is it possible to add ability to set emulation speed? some games like diamond twister run so fast and somewhat not playable...

**Comment by AdityaMH** [comment]
Maybe because you ticked/enabled  HW acceleration?

**Comment by 0xh3LL0** [comment]
i didnt see any HW acceleration anywhere?

**Comment by 0xh3LL0** [comment]
![screenshot_2018-09-07-11-37-19-91](https://user-images.githubusercontent.com/23132217/45198818-0bd25500-b258-11e8-8b9e-883aa1ecc778.png)
![screenshot_2018-09-07-11-37-32-52](https://user-images.githubusercontent.com/23132217/45198832-1856ad80-b258-11e8-8c34-5dde41f80d02.png)

**Comment by 1234Sameer** [comment]
@0xh3LL0 
HW acceleration is available on android 6.0+ devices only.

**Comment by 0xh3LL0** [comment]
i see, so there is a way to make it slower? according to the readme, applying filter will slow it down, but it wont, game still run so fast...

**Comment by 1234Sameer** [comment]
@0xh3LL0 
Well, actually applying filter can cause performance loss in some games. But It is not here to slowdown games. It is here improve picture quality. The emulator doesn't have a speed control setting yet. But I would recommend you to try a different version of the game with different screen size for now.

**Comment by 0xh3LL0** [comment]
guess there is no choices then...

**Comment by oatmeal01** [comment]
Try another game versions. some version are fast some are normal. Just like god of war game and And 1 Street Basketball other versions are laggy/slow but if you find suitable version of the game the gameplay is smooth and fast.

**Comment by nikita36078** [comment]
Frame limiter is added in the previous version.

**Comment by amarcioz** [comment]
Frame limiter solved the problem of the super speed of some games.
