### ISSUE TITLE
Weird mapping behaviour in XIII and maybe other games

### ISSUE THREAD

**Issue by stranno** [nikita36078/J2ME-Loader#379]
I have tried to play XIII with gamepad but once i remap the layout, the game's controls using the virtual keyboard are screwed, while they work fine without gamepad remapping. The gamepad works fine with all buttons except 5/F, both dont seem to work at all.

I havent noticed this behaviour in any other game but i havent tried many.

OS: Nougat 7.1. Device: Shield Tablet K1.

Here's a video showing the problem.

https://streamable.com/l4mwg

**Comment by nikita36078** [comment]
Fixed!

**Comment by stranno** [comment]
Thank you nikita, i have tried 1.3.5 and it works properly in XIII now.

Donation sent 👌
