### ISSUE TITLE
About virtual-keyboard layout

### ISSUE THREAD

**Issue by glKarin** [nikita36078/J2ME-Loader#38]
Sry for my bad English.
Could you exchange number pad(left) and arrow pad(right) position, I mean, arrow pad is on the left-hand side of the layout and number pad is on other side.
Thx for your development, a great work.

**Comment by glKarin** [comment]
Or can it support global setting of on-screen keyboard layout, as initial default layout.

**Comment by nikita36078** [comment]
I will add a key hiding feature in the next versions, it looks like a best solution :-)

**Comment by AdityaMH** [comment]
and how to show a gone keypad instead reset keylayout? (alfanumeric are gone after click ""double" switch keylayout" in common setting.)

**Comment by nikita36078** [comment]
It is a bug, will be fixed in the next version.

**Comment by nikita36078** [comment]
Keyboard bug was fixed in the last version.

**Comment by AdityaMH** [comment]
but keypad still going to upper left if moved separately.

(test: moved right button (d-pad, f, l, r) to any postion then save, exit and start again. )

**Comment by nikita36078** [comment]
Ok, I will check it.

**Comment by nikita36078** [comment]
I think I can close this issue now.
