### ISSUE TITLE
Mr and Mrs Tarzan

### ISSUE THREAD

**Issue by jnlawler** [nikita36078/J2ME-Loader#380]
Game freezes sometimes at the beginning of a level & sometimes freezes right at the ending of a level Ive almost completed. I love this game and want to play it so bad without having to.exit and start over repeatedly. I love J2ME loader . Is there anything I can do to prevent game to freeze? 
Plz advise...thank you.

**Comment by 1234Sameer** [comment]
@jnlawler
Try to enable immediate processing mode.

**Comment by RyukenT** [comment]
Dont use immediate process mode it crashes and bleeds graphics

**Comment by nikita36078** [comment]
@RyukenT Sometimes it can cause crashes, but this option fixes a lot of games and it is worth trying if game freezes or just runs slowly.

@jnlawler Did the immediate processing mode help?
