### ISSUE TITLE
The buttons still can get stuck.

### ISSUE THREAD

**Issue by enomat** [nikita36078/J2ME-Loader#381]
**Emulator version:**
1.3.3

**Device:**
Samsung Galaxy S2

**Android version:**
4.1.2

**Description of the issue:**

The latest update fixed the most common keyboard stuck bug and improved the controls, but the keyboard stuck bug is still not completely fixed.

Here I don't press any button, but the character is still running right.

<img src="https://user-images.githubusercontent.com/12612250/45266071-9f24a980-b455-11e8-97cd-dee9e41b3042.png" height="500px">
<img src="https://user-images.githubusercontent.com/12612250/45266072-9f24a980-b455-11e8-9fe4-64ad51adc613.png" width="500px">

It happens when I quickly press and release multiple buttons.

This is how to reproduce the bug:
Swipe your fingers on the keyboard and some keys will get stuck. It's easier to reproduce the bug if you swipe with two fingers at the same time and in portrait mode. The red arrows illustrate where I was swiping the screen. If you can't reproduce, swipe slower or faster, try other directions and buttons.

Maybe this bug does not happen in 6.0 or higher version of Android, like the original report.
https://github.com/nikita36078/J2ME-Loader/issues/141#issuecomment-380637017

**Comment by RyukenT** [comment]
It's funny, the app couldnt run 'the sims 3 world adventures(500-800kb) whereas it runs The sims 3 supernatural 993kb & aslo the game is higher in details than that of adventure.

**Comment by jack1432** [comment]
Enomat now that you mentioned, I realized that this error actually happens when you slide your finger on the keyboard, but it may not be a bug of the emulator, but of the game itself. I tested this in other games and the error did not happen, I also tested in other versions of this game and found no errors.

**Comment by RyukenT** [comment]
Haha

**Comment by jack1432** [comment]
but I'm not sure about that.

**Comment by 1234Sameer** [comment]
This happens in other games too. I have experienced this problem in clone 3d, army rangers, ops sniper 3d and in The Bourne conspiracy all while playing (not by the above method). Also if I rotate my device while holding down a button, It will get stuck (although not same as this bug). Emulation lag might be the problem.

**Comment by nikita36078** [comment]
Ok, I'll reopen #141 although I'm not sure if it's the same bug.

**Comment by enomat** [comment]
@nikita36078 
It's hard to reproduce the bug. But I could reproduce this bug in other games, for example Contr Terrorism Episode 2, American Gangster, Rainbow Six Vegas, Smersh 3d ( Смерш 3D ).

The method to reproduce the bug that I wrote in the first post is just a raw example. I have experienced this bug in normal gameplay. For example in FPS games the player needs to press multiple buttons (run, sidestep, turn, shoot), therefore the player will slide his finger on the keyboard to quickly press the other buttons.

The reason why you can't reproduce it in certain games is maybe that certain games require the player to release the button and press it again to perform an action. Or the game does not allow multiple inputs at all (for example you can't turn and run at the same time in Alien Shooter 3D).

I used Gangstar Crime City to interpret this bug, because 8 keys control the movement, and more keys mean higher probability to reproduce/visualize the bug. Also, you can see when a key is stuck even when the character hit a wall or obstacle, because the running animation won't stop.
