### ISSUE TITLE
It is no longer possible to play FMX Rage in the emulator

### ISSUE THREAD

**Issue by jack1432** [nikita36078/J2ME-Loader#382]
**Emulator version:**
1.3.3-play

**Game version:**
1.0.0

**Game resolution:**
``(176x220)``

**Device:**
``(Samsung Galaxy J1 mini)``

**Android version:**
5.1.1
**Description of the issue:**
The FMX Rage game can not be played on newer versions of the J2ME Loader

![screenshot_2018-09-12-16-02-06](https://user-images.githubusercontent.com/36806488/45450755-adc6c700-b6c8-11e8-93c9-f629febc7aa8.png)
This is an image of the game being played in version 1.2.8.7-play, which presents no errors and is perfectly playable.

![screenshot_2018-09-12-16-07-45](https://user-images.githubusercontent.com/36806488/45450810-d353d080-b6c8-11e8-9047-a599407ec272.png)
Already in this second image the game is being played in the latest version of the 1.3.3-play emulator and you can not see game menu options.

![screenshot_2018-09-12-16-10-15](https://user-images.githubusercontent.com/36806488/45451372-68a39480-b6ca-11e8-8632-afe423b2725f.png)
And a few seconds after starting to play the game closes and this appears.

**Comment by nikita36078** [comment]
Will be fixed in the next version.
