### ISSUE TITLE
Minigolf castles doesn't show 3D

### ISSUE THREAD

**Issue by Catfriend1** [nikita36078/J2ME-Loader#383]
**Emulator version:**
1.3.3 fdroid

**Game version:**
1.3.1 
http://www.mobiles24.co/downloads/s/59957-m601-mini_golf_castles_3d

**Game resolution:**
240x320

**Device:**
Lg-h815 (g4)

**Android version:**
7.1.2 lineageos

**Description of the issue:**
Game starts, works and plays music well but 3d parts (golf trails and characters) are not shown.
![screenshot_20180915-080756](https://user-images.githubusercontent.com/16361913/45583347-80446e00-b8c0-11e8-8fdc-d0c6702817a7.png)

**Comment by woesss** [comment]
In this game, Mascot Capsule 3D API is used. But J2ME Loader does not support it.   
[Mascot Capsule 3D support (issue#240)](https://github.com/nikita36078/J2ME-Loader/issues/240)

**Comment by Catfriend1** [comment]
Closed as duplicate, thanks for your quick answer.
