### ISSUE TITLE
Playman extreme running

### ISSUE THREAD

**Issue by matt29silva** [nikita36078/J2ME-Loader#384]
**Emulator version:**
1.3.3-play

**Game version:**

1.1.2
**Game resolution:**

240x320
**Device:**
Moto g4 play

**Android version:**
7.1
**Description of the issue:**
In the most times the game freezers in select phase menu and sometimes crashes in certains phases

**Comment by 1234Sameer** [comment]
Try to enable immediate processing mode.

**Comment by nikita36078** [comment]
How does it work with the immediate processing mode?

**Comment by matt29silva** [comment]
worked well for me, thanks. Now only rest the lag on the start of the phases

**Comment by T4P4N** [comment]
Working smooth on my device after updating the emulator to latest version from Google playstore
