### ISSUE TITLE
Steering buttons are delayed in V-Rally 3D

### ISSUE THREAD

**Issue by enomat** [nikita36078/J2ME-Loader#385]
**Emulator version:**
 1.3.3

**Game version:**
Any (ignore the Sony Ericsson (Mascot Capsule 3D) versions)

**Device:**
 Samsung Galaxy S2 I9100

**Android version:**
 4.1.2

**Description of the issue:**

When I press and hold the left or right turn buttons, the car will start turning about 1 second later.

**Comment by 1234Sameer** [comment]
Maybe same thing for high speed 3d 240x320 versions. 320x240 works fine.

**Comment by AdityaMH** [comment]
If that game need keypad, I think maybe that from game itself..
But some game with touchscreen support (My Life in New York, and Total Conquest for example) not fast enough to touching respond.

**Comment by woesss** [comment]
@nikita36078, случайно обнаружил. что этой проблемы нет при уменьшенном интервале в [`KeyRepeater`](https://github.com/nikita36078/J2ME-Loader/blob/bdde75948466d2f12fed3959268908fd457150a8/app/src/main/java/javax/microedition/lcdui/pointer/KeyRepeater.java#L24). Пол секунды для повтора реально много - на мой взгляд более-менее привычно выглядит `150ms`. И ещё: вызов [`waiter.wait()`](https://github.com/nikita36078/J2ME-Loader/blob/bdde75948466d2f12fed3959268908fd457150a8/app/src/main/java/javax/microedition/lcdui/pointer/KeyRepeater.java#L80) нужно обернуть в условие (думаю по `enabled`) - сейчас репеатер посылает одно событие сколько кнопку не держи. Ну и принцип его работы не ахти: только одна кнопка одновременно, нажатие и удержание другой игнорируется, но отпускание любой кнопки сбрасывает повтор.

**Comment by nikita36078** [comment]
@woesss Спасибо за подсказку, я посмотрю, что можно с ним сделать. И тут есть проблема - события ввода и отрисовки складываются в одну очередь, поэтому слишком большое количество событий ввода может замедлить отрисовку (по крайней мере, в теории).

**Comment by woesss** [comment]
@nikita36078, логика очереди выбрасывает евенты повторов, если их накапливается больше двух - так что на прозводительность отрисовки не должно особо повлиять.

**Comment by nikita36078** [comment]
Fixed
