### ISSUE TITLE
alchemy os bugs

### ISSUE THREAD

**Issue by mini536** [nikita36078/J2ME-Loader#387]
**Emulator version:**
1.3.4

**Game version:**
2.1.8

**Game resolution:**
``(For example, 240x320 or 640x360)``
240×320
**Device:**
``(For example, Samsung Galaxy S7)``
xiaomi redmi note4
**Android version:**
8.1
**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
I have run it with the following steps:
1.install and open it
2.choose installer
3.choose install
4.choose Native (JSR 75)
5.It crash
6.open j2me loader and alchemy os again
7.choose alchemy os
8.choose next
9.choose no
10.Try step 6-7 again
11.You will see a terminal ,but no matter what command you enter, it doesn't respond, but it have respond on the Java phone.
Oh ,I hava download alchemy OS from this link:https://sourceforge.net/projects/alchemy-os/files/2.1.8/alchemy-os-2.1.8.jar/download 

1.In version 1.3.7 it add icon support,but sometimes it will use an incorrect icon
incorrect https://wx4.sinaimg.cn/large/007bFx8Mly1fxat2mmpewj30u01qg421.jpg
correct https://wx2.sinaimg.cn/large/007bFx8Mly1fxat2i3k0hj30u01qgtc7.jpg
2.Sometimes "Browse files" can't read local files, or it will crash
such as open this folder:cfg,bin

**Comment by T4P4N** [comment]
Working in my device:
![screenshot_2019-01-19-12-15-19-217_ru playsoftware j2meloader](https://user-images.githubusercontent.com/32695903/51423300-0d3b6300-1be4-11e9-8215-70fee434ea79.png)

**Comment by T4P4N** [comment]
I have to press three dots, and then tap on input , to emulate ok button of j2me devices

**Comment by T4P4N** [comment]
but i forgot to choose jsr native!  I forgot , which option i choosed, maybe 1st one?
