### ISSUE TITLE
please improve the m3g 3d compatibility of the  j2meloader

### ISSUE THREAD

**Issue by doge1234567890** [nikita36078/J2ME-Loader#39]
some of the apps that uses m3g api to render 3d scenes would not work which included:
stranded2 -mystries of the time(3d version)
jbenchmark 3d 
jbenchmark hd
3d rollcoaster rush 
it s exciting to see that finally a j2me emulator supports m3g api
but some of my favourite games are still inplayable
hope this will be fix soon

**Comment by glKarin** [comment]
I played a racing game named "3D Racing Evolution" by NETLizard, using M3G, the screen flashes all the time. Fortunately, other 3D games of NETLizard are not, because they have their own 3D engine without M3G.

**Comment by doge1234567890** [comment]
@glkarin screen flashing may stop after you enable drawbuffer cleaning function

**Comment by nikita36078** [comment]
A new m3g engine is in the development now.
