### ISSUE TITLE
Wechat

### ISSUE THREAD

**Issue by mini536** [nikita36078/J2ME-Loader#392]
**Emulator version:**
1.3.6

**Game version:**

2.0.2
**Game resolution:**
``(For example, 240x320 or 640x360)``
240×320
**Device:**
``(For example, Samsung Galaxy S7)``
Xiaomi 1
**Android version:**
4.1.2
**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``

Can't open wechat，When I open it it crash

**Comment by nikita36078** [comment]
#214 Emulator currently doesn't support the newest Nokia J2ME API

**Comment by AdityaMH** [comment]
Maybe almost all social media app has same bug..
Facebook for example

**Comment by nikita36078** [comment]
Forgot to close, it's actually a duplicate #219
