### ISSUE TITLE
Your emulator can't use music playeer

### ISSUE THREAD

**Issue by mini536** [nikita36078/J2ME-Loader#393]
**Emulator version:**

1.3.6
**Game version:**
3.6.0

**Game resolution:**
``(For example, 240x320 or 640x360)``
240×320
**Device:**
``(For example, Samsung Galaxy S7)``
xiaomi 1
**Android version:**
4.1.2
**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
I can't use any music player for java play any songs

**Comment by nikita36078** [comment]
Any examples of such players?

**Comment by mini536** [comment]
such as thishttps://wpd.shouji.com.cn/cdn/attach/soft/jar/20120202/5918993212.jar

> Any examples of such players?

**Comment by AdityaMH** [comment]
I heard mp3 tag editor have same problem, too.

**Comment by nikita36078** [comment]
Fixed.
