### ISSUE TITLE
Super Pocket Football 2017 not opening

### ISSUE THREAD

**Issue by j2meplay** [nikita36078/J2ME-Loader#398]
name: Super Pocket Football 2017
source: java.mob.org
issue: not opening. but Retro2ME opens it succesfully. so problem is in J2ME-Loader.

![screenshot_20181028-192631](https://user-images.githubusercontent.com/44535291/47618783-29999900-dae8-11e8-96c1-a834f6e45300.png)
![screenshot_20181028-192803](https://user-images.githubusercontent.com/44535291/47618782-29010280-dae8-11e8-911b-0d342521b2d7.png)

**Comment by nikita36078** [comment]
Which Android version do you use?

**Comment by j2meplay** [comment]
Android: 6.0.1
J2ME-Loader: 1.3.6-play

**Comment by woesss** [comment]
@nikita36078, здесь конфликт имён обфусцированных классов - вместо класса мидлета загружается класс какой-то библиотеки и в нём, соответственно, нет подходящего по сигнатуре метода. Можно отключить обфускацию строкой `-dontobfuscate` в прогуард-файле - на сегодня это решит проблему. Но не даёт стопроцентной гарантии, потому что какая-нибудь зависимость, в теории, может притащить с собой уже обфусцированные классы. Поэтому в перспективе стоит подумать о модификации логики класс-лодыря, загружающего мидлет.

**Comment by nikita36078** [comment]
@woesss Думаю, что такой ClassLoader будет достаточно надежен - [MyCoreClassLoader](https://github.com/nikita36078/J2ME-Loader/blob/master/app/src/main/java/javax/microedition/shell/MyCoreClassLoader.java).

@j2meplay Fixed.
