### ISSUE TITLE
Caching audio files into memory instead of caching it into Android/data

### ISSUE THREAD

**Issue by doge1234567890** [nikita36078/J2ME-Loader#40]
writing into phone memory frequently can damage the memory chip of the phone as amounts of write-erase cycle a memory chip can stand is limited, which is ranging from 1000 times to 10000 times

**Comment by nikita36078** [comment]
A number of cache files isn't critical for the memory. Anyway, I can't change caching method, it is impossible to implement for now.

**Comment by AdityaMH** [comment]
maybe another way is cache files moved to individual folder such "/J2ME-Loader/cache/~MIDlet Name~/" permanently until confirm delete cache or cleared for some time period.

And this way only for who have a plenty space memory and afraid about memory chip damage.
