### ISSUE TITLE
Nature park 

### ISSUE THREAD

**Issue by Rosabis** [nikita36078/J2ME-Loader#401]
**Emulator version:**
1.3.6

**Game version:**
0.2

**Game resolution:**
``(For example, 240x320 or 640x360)``
128×128
**Device:**
``(For example, Samsung Galaxy S7)``
xiaomi 1
**Android version:**
4.1.2
**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``

It is always crash when I choose new game and play it for a little while

**Comment by AdityaMH** [comment]
And emulation for this game bit too fast..

**Comment by nikita36078** [comment]
@woesss Спасибо за наводку! Об этом трюке в Kemulator я знал, но не мог понять, зачем он нужен, теперь-то понятно)

**Comment by nikita36078** [comment]
Fixed
