### ISSUE TITLE
Artefact of Glory

### ISSUE THREAD

**Issue by uforgivent** [nikita36078/J2ME-Loader#402]
**Emulator version: 1.3.6**

**Game version: Artefact of Glory 1.2.0**

**Game resolution: 240x320**

**Device: LG Optimus L70 (D320)**

**Android version: Android  Kit Kat 4.4.2**

**Description of the issue:**

Delay when starting the game, sometimes the application is closed.
The on-screen keyboard does not react when the game starts, sometimes it reacts again and proceeds with the game normally.
The application closes at certain levels when starting a game.
Some texture errors (from level 2)

![Uploading Screenshot_2018-10-31-11-28-56[1].png…]()

![screenshot_2018-10-31-11-29-30](https://user-images.githubusercontent.com/5973208/47795205-e403e880-dd00-11e8-9928-e9a51ffc4f27.png)

![screenshot_2018-10-31-11-31-00](https://user-images.githubusercontent.com/5973208/47795243-f716b880-dd00-11e8-9134-eea4c980056f.png)
![screenshot_2018-10-31-11-30-13](https://user-images.githubusercontent.com/5973208/47795247-faaa3f80-dd00-11e8-8cb4-94c32921b7fd.png)

**Comment by nikita36078** [comment]
The game looks pretty stable now.
