### ISSUE TITLE
Treasure Towers (Bug)

### ISSUE THREAD

**Issue by uforgivent** [nikita36078/J2ME-Loader#403]
Emulator version: 1.3.6

Game version: Treasure Towers 1.3

Game resolution: 128x160

Device: LG Optimus L70 (D320)

Android version: Android Kit Kat 4.4.2

Description of the issue:

When starting the game does not load the corresponding textures to play.

![screenshot_2018-10-31-11-49-49](https://user-images.githubusercontent.com/5973208/47796976-31ce2000-dd04-11e8-8c8a-fb444e47fdb2.png)
![screenshot_2018-10-31-11-50-08](https://user-images.githubusercontent.com/5973208/47796989-3bf01e80-dd04-11e8-971d-7a70fda6af7a.png)
![screenshot_2018-10-31-11-50-15](https://user-images.githubusercontent.com/5973208/47797001-41e5ff80-dd04-11e8-873f-39c7ed25f527.png)
![screenshot_2018-10-31-11-49-22](https://user-images.githubusercontent.com/5973208/47797010-45798680-dd04-11e8-8020-57198b01e803.png)

**Comment by nikita36078** [comment]
Duplicate #349
