### ISSUE TITLE
Fantasy Warrior 2 - Evil

### ISSUE THREAD

**Issue by uforgivent** [nikita36078/J2ME-Loader#405]
Emulator version: 1.3.6

Game version: Fantasy Warrior 2 - Evil 1.1.84

Game resolution: 240x320

Device: LG Optimus L70 (D320)

Android version: Android Kit Kat 4.4.2

Description of the issue:

Everything works well until you have to face the first monster in the game, and when you face it, the emulator does not load the textures to battle.
PS: the game continues to emulate the sounds of battle and running without crashing.

![screenshot_2018-10-31-11-53-12](https://user-images.githubusercontent.com/5973208/47797708-99389f80-dd05-11e8-8fa4-261c5915bf6d.png)
![screenshot_2018-10-31-11-53-53](https://user-images.githubusercontent.com/5973208/47797722-9d64bd00-dd05-11e8-8667-723ca8fbec05.png)
![screenshot_2018-10-31-11-53-22](https://user-images.githubusercontent.com/5973208/47797735-a190da80-dd05-11e8-992e-57cae448bb10.png)

**Comment by nikita36078** [comment]
#404 is the same issue

**Comment by stevenfelix505** [comment]
I have the same issue on Nokia 6300

**Comment by IgrikXD** [comment]
> I have the same issue on Nokia 6300

I've patched both **Fantasy Warrior 2 - Good & Evil** with GPT-6 Astra to fix an issue where the battle screen gets stuck at 240×320 while the battle sounds continue playing.

The original renderer can access tiles outside the map bounds when a battle arena is smaller than the screen. The patch corrects the camera positioning and safely renders smaller maps while preserving the original arena layouts and gameplay.

**Tested on a real Nokia 6300:** battles now load correctly and display properly in full screen at 240×320.

<img width="240" height="320" alt="Image" src="https://github.com/user-attachments/assets/21ced9c2-dea2-4971-81f5-c1aa0af0a5b8" /><img width="240" height="320" alt="Image" src="https://github.com/user-attachments/assets/983f81b3-fb26-4625-b2e7-5070a8adb92b" />

The [patched JARs can be downloaded from my Google Drive](https://drive.google.com/drive/folders/1AUVuxatqntOThp4ESRHGzrcJ32ZZ2xbl). Hope this helps others experiencing the same issue!
