### ISSUE TITLE
Land of the Dead (LOTD) game freezes

### ISSUE THREAD

**Issue by peta9** [nikita36078/J2ME-Loader#409]
**Emulator version:**
1.3.7-open

**Game version:**
1.1.14

**Game resolution:**
240x320

**Device:**
Lenovo Tab 2 X30F (1GB RAM, ARMv7a)

**Android version:**
6.0.1
**Description of the issue:**
Game freezes just before loading the in-game menu with sound playing in the background. But if I go to my android home screen without closing the game and then come back to the frozen part, it runs normally. This glitch can be seen every now and then while playing the game.
![screenshot_20181112-022140](https://user-images.githubusercontent.com/44788763/48318139-f136a680-e621-11e8-8ffc-4f3c5d6b443e.png)
The moment it freezes–>
![screenshot_20181112-022148](https://user-images.githubusercontent.com/44788763/48318153-204d1800-e622-11e8-8698-ceef30243ad6.png)

**Comment by nikita36078** [comment]
Fixed

**Comment by peta9** [comment]
Just finished the game \(^o^)/ ...went buttery smooth ...thank you for addressing the issue :`)
