### ISSUE TITLE
New alchemy os bugs

### ISSUE THREAD

**Issue by mini536** [nikita36078/J2ME-Loader#410]
**Emulator version:**

1.3.7
**Game version:**

2.1.8
**Game resolution:**
``(For example, 240x320 or 640x360)``
240×320
**Device:**
``(For example, Samsung Galaxy S7)``
xiaomi 1
**Android version:**
4.1.2
**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if  @ap
1.From this version it add icon support,but sometimes it will use an incorrect icon
incorrect https://wx4.sinaimg.cn/large/007bFx8Mly1fxat2mmpewj30u01qg421.jpg
correct https://wx2.sinaimg.cn/large/007bFx8Mly1fxat2i3k0hj30u01qgtc7.jpg
2.Sometimes "Browse files" can't read local files, or it will crash
such as open this folder:cfg,bin

**Comment by nikita36078** [comment]
I will update the previous issue
