### ISSUE TITLE
Opera Mini doesn't show any images

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [nikita36078/J2ME-Loader#411]
**Emulator version:**
1.3.7

**Game version:**
[Opera Mini](http://m.opera.com/cn/en/mini.jad) 8.0

**Game resolution:**
540x960 (only this resolution reproducible)

**Device:**
Oppo N1

**Android version:**
5.1.1
**Description of the issue:**
While I installed Opera Mini, I can't see any images of the webpage, while I switch to other resolution, they works as expected.

**Comment by nikita36078** [comment]
It seems fine for me, maybe you accidentally disabled images loading in the settings?￼

**Comment by KrasnayaPloshchad** [comment]
OK in my settings Load images was enabled, and I tested all three image qualities, but the sroblem is still there. When I switched to smaller resolution the problem is disappeared.

**Comment by oatmeal01** [comment]
Same issue here, downloaded the app link above. Tried to resize, 720x1280 image becomes invisible.

**Comment by woesss** [comment]
On high resolutions not enough Heap-memory for images.

**Comment by AdityaMH** [comment]
Change your resolution 720x1280 to 480x854.
might it helps.

**Comment by nikita36078** [comment]
Closed, not an emulator issue.
