### ISSUE TITLE
Nova Luncher not creating shortcuts

### ISSUE THREAD

**Issue by telanus** [nikita36078/J2ME-Loader#412]
**Emulator version:**
1.3.7-play

**Device:**
Mobicel X4

**Android version:**
Android Go (8.1.0)

**Description of the issue:**
I'm Running [Nova Launcher](https://play.google.com/store/apps/details?id=com.teslacoilsw.launcher&hl=en) (5.5.4). And trying to create a shortcut for a game doesn't work. J2ME Launcher claims to create a shortcut but nothing is created.

**Comment by nikita36078** [comment]
Are you sure that shortcut isn't added? I tested it right now and I didn't see any problems.

**Comment by telanus** [comment]
Not sure why I couldn't create shortcuts over he weekend, but this morning at work it suddenly worked
