### ISSUE TITLE
God wars 1

### ISSUE THREAD

**Issue by mini536** [nikita36078/J2ME-Loader#413]
**Emulator version:**
1.3.7

**Game version:**
1.0

**Game resolution:**
``(For example, 240x320 or 640x360)``
240×320
**Device:**
``(For example, Samsung Galaxy S7)``
xiaomi1
**Android version:**
4.1.2
**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
your emulator can not install this game,but it can be installed in my nokia
you can download it from
http://appdown.7723.cn/wuza/sofaa/2010928O3965054.jar
by the ways another version your emulator can not save data ,but it can save data in my nokia
http://appdown.7723.cn/wuza/softx/2010911O6409032.jar
screenshot 
 http://wx3.sinaimg.cn/large/007bFx8Mly1fxj2s70xurj30u01nh0wc.jpg

**Comment by nikita36078** [comment]
Fixed
