### ISSUE TITLE
J2ME Loader does not recognize Blackberry keyboard

### ISSUE THREAD

**Issue by nfnguyenz95** [nikita36078/J2ME-Loader#414]
**Emulator version: 1.3.7

**Game version: 1.0.0

**Game resolution: 240x320

**Device: Blackberry Classic Q20

**Android version: 4.3 (Blackberry 10 OS)

**Description of the issue:
Only two Left Shift and Right Shift keys can be set

https://youtu.be/nfr53hlORmw

**Comment by nikita36078** [comment]
I think it's a device problem. Do another Android apps support these keys?
