### ISSUE TITLE
da hua xi you wu kong zhuan(大话西游-悟空传)

### ISSUE THREAD

**Issue by mini536** [nikita36078/J2ME-Loader#415]
**Emulator version:**
1.3.7

**Game version:**
1.0

**Game resolution:**
``(For example, 240x320 or 640x360)``
240×320
**Device:**
``(For example, Samsung Galaxy S7)``
xiaomi 1
**Android version:**
4.1.2
**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
can not open it
screenshot
https://wx2.sinaimg.cn/large/007bFx8Mly1fxj1m3t1p4j30u01qgaaq.jpg
download link
http://www.51sjyx.com/download/game/rpg/dhxywkz.jar

**Comment by 70852** [comment]
谢谢让我知道了51sjyx这个网站(●'◡'●)

**Comment by nikita36078** [comment]
Fixed.
