### ISSUE TITLE
Gujian Qitan(古剑奇谭)

### ISSUE THREAD

**Issue by mini536** [nikita36078/J2ME-Loader#416]
**Emulator version:**

1.3.7
**Game version:**
1.0.0

**Game resolution:**
``(For example, 240x320 or 640x360)``
240×320
**Device:**
``(For example, Samsung Galaxy S7)``
xiaomi 1
**Android version:**
4.1.2
**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
it can  be installed ,but your emulator can not open it
screenshot：http://wx3.sinaimg.cn/large/007bFx8Mly1fxlaxc0rrrj30u01qgmy6.jpg
download link:http://down.52emu.cn/jargame/2/%E5%8F%A4%E5%89%91%E5%A5%87%E8%B0%AD.jar

**Comment by nikita36078** [comment]
Fixed
