### ISSUE TITLE
Locale overriding fails

### ISSUE THREAD

**Issue by jack980517** [nikita36078/J2ME-Loader#418]
This is not a game-specific problem. It occurs on two Nokia games I've tested. (Bounce and Space Mahjong)

These two games (and some other Nokia games) offer multilanguage by having "lang.{language}-{country}" files inside the jar file, with English having the special language code "xx" for fallback. When the system language of Android is en-US or zh-CN (I haven't tested other languages), the language of the game would be English and Chinese (China), accordingly. But when I try to override the locale value by writing "microedition.locale: zh-CN", the game's language becomes English even when the system language of Android is Chinese (China).

**Comment by woesss** [comment]
In current implementation "System properties" must be writed as "key:value" per line without unnecessary spaces, tabs and other symbols. Try replace property as "microedition.locale:zh-CN".

**Comment by nikita36078** [comment]
Yes, the hint is really confusing, I'll edit it. About the separator symbol - some users already use custom properties and I don't want to break their settings.

**Comment by woesss** [comment]
@nikita36078, можно задействовать оба варианта - строка ведь разбивается регуляркой:  
 [`String[] prop = line.split("[:=]", 2);`](https://github.com/nikita36078/J2ME-Loader/blob/ddf7e33438ae3218c0c586f91cb91060c48cc2d1/app/src/main/java/ru/playsoftware/j2meloader/config/ConfigActivity.java#L447)   
Можно даже универсализировать пробелы вокруг `" ?[:=] ?"` - один/два/ни одного.  
Вопрос только в том - не будет ли конфликта с содержимым ключей/значений.  
Хотя я таких вроде не встречал.  
П.С. Лично мне не нравится ограничение в две строки для поля ввода (неудобно), и захардкоденные дефолтные проперти - хотелось бы их видеть, редактировать и, главное, иметь возможность удалять, потому что переопределить ключ можно любым значением, кроме `null`, а это иногда нужно. Ну и  существующие значения были бы примером правильного синтаксиса.

**Comment by nikita36078** [comment]
@woesss Думаю, удобнее всего будет редактирование в отдельный фрагмент перенести, и там уже на весь экран поле ввода сделать.

**Comment by woesss** [comment]
@nikita36078, можно конечно и фрагмент, но я б не заморачивался - просто убрал `lines=2` и подвинул в конец макета, чтоб не мешалось.

**Comment by 1234Sameer** [comment]
Why don't you use English. It may help somebody out.

**Comment by nikita36078** [comment]
@1234Sameer We're discussing the source code, nothing really helpful there.
