### ISSUE TITLE
Changing the virtual keypad theme to save power during emulation (?)

### ISSUE THREAD

**Issue by peta9** [nikita36078/J2ME-Loader#421]
It would be great if there was a global option (preferably, as a subcategory under the main option of 'enabling dark theme') to set the theme of the virtual keypad as dark/black, including the background, only keeping the labels white (which may finally show these colour values– Background: 0, Labels: FFFFFF,  Buttons: 0, Outlines: 0 ; **although it a matter of one's personal taste**, but is perhaps more visually appealing for dark mode). In this case, the option for changing keypad theme in individual app settings may be kept unaltered.

A game in default settings (**landscape mode**):
![screenshot_20181223-045623](https://user-images.githubusercontent.com/44788763/50379407-2dbcdf80-066f-11e9-852a-598a2ebb54e5.png)

and after applying the changes:
![screenshot_20181223-044019](https://user-images.githubusercontent.com/44788763/50379327-6065d880-066d-11e9-983c-ebd4a9ddd95a.png)
...here the keys maybe also **look more polished, discrete and modern**.

**Comment by T4P4N** [comment]
@peta9 it's your personal preference, app already has customization options,
It will not gonna make much difference in battery life
