### ISSUE TITLE
SIlent hill 1 crash issue is back in the new version of j2me loader

### ISSUE THREAD

**Issue by peta9** [nikita36078/J2ME-Loader#422]
**Emulator version:**
1.3.7-open

**Game version:**
0.1.0

**Game resolution:**
240x320

**Device:**
Lenovo tab 2 X30F

**Android version:**
6.0.1
**Description of the issue:**
Silent Hill 1 game crashes just after the in-game 'play' button is pressed. In the earlier versions (last tried it in the version: 1.3.4-open) of j2me loader, this game could be played, with minor glitches occasionally.
Even tried it by unchecking both the 'filter' and 'HW acceleration' option, still no luck.

**Comment by nikita36078** [comment]
Did you try "Immediate processing mode" option?

**Comment by peta9** [comment]
Sorry for the late response, and yes that method that you had mentioned worked very good.
