### ISSUE TITLE
Clitter Crunch

### ISSUE THREAD

**Issue by amarcioz** [nikita36078/J2ME-Loader#423]
Emulator version: 1.3.7

Game version: Any

Game resolution:
128x128, 176x208, 208x208, 240x320

Device:
Samsung Galaxy J1 2016

Android version:
5.1

Description of the issue: The game works well until some time, but it freezes and only the audio continues. Video: [https://youtu.be/EUi_9bx4Zi4](https://youtu.be/EUi_9bx4Zi4)

![screenshot_2018-12-26-00-30-20](https://user-images.githubusercontent.com/35005836/50447437-40027c00-0902-11e9-9338-934f7e671be6.png)

**Comment by nikita36078** [comment]
Try to use Immediate processing mode
