### ISSUE TITLE
Fps location

### ISSUE THREAD

**Issue by ahmadprayoxxsy** [nikita36078/J2ME-Loader#426]
**Emulator version:**
V1.3.8 play

**Game version:**
Gameloft 480x800 portait mode

**Game resolution:**
``(480x800 portait mode)``

**Device:**
``(j510fn)``

**Android version:**
6.0.1
**Description of the issue:**
``(Reverse FPS when playing the gameloft 480x800 portait mode game
![tmp-cam--1600353847](https://user-images.githubusercontent.com/37769813/51005019-1158e800-1535-11e9-90f6-eaf336fae44b.jpg)
![tmp-cam-1935563041](https://user-images.githubusercontent.com/37769813/51005030-1b7ae680-1535-11e9-877c-a5ce391515f9.jpg)
![screenshot_20190111-065521](https://user-images.githubusercontent.com/37769813/51005041-2897d580-1535-11e9-8749-6c028cfe195e.png)

)``

**Comment by ahmadprayoxxsy** [comment]
![tmp-cam--1303865497](https://user-images.githubusercontent.com/37769813/51005090-5a10a100-1535-11e9-934b-33fe5f2b5c6f.jpg)

**Comment by amarcioz** [comment]
And no version of Tetris Revolution works.

**Comment by nikita36078** [comment]
480*800 is a portrait orientation and that's why the fps counter isn't rotated. It's not a bug.
