### ISSUE TITLE
Need for speed underground 2 

### ISSUE THREAD

**Issue by RyukenT** [nikita36078/J2ME-Loader#427]
**Emulator version:**1.3.8

**Game version:**2.5.0

**Game resolution:**240x320
``(For example, 240x320 or 640x360)``

**Device:**Lenevo k8 plus
``(For example, Samsung Galaxy S7)``

**Android version:**7.1.1

**Description of the issue:**Game opens but freezes at main menu
``(What's the problem? - Screenshots showing the issue if applicable)``

**Comment by nikita36078** [comment]
Fixed
