### ISSUE TITLE
Need for speed underground 3

### ISSUE THREAD

**Issue by RyukenT** [nikita36078/J2ME-Loader#428]
**Emulator version:**1.3.8

**Game version:**any versions.even 1.0

**Game resolution:**240x320
``(For example, 240x320 or 640x360)``

**Device:**lenevo Z5s
``(For example, Samsung Galaxy S7)``

**Android version:**8.1

**Description of the issue:**Game opens only at start menu and crashes..
``(What's the problem? - Screenshots showing the issue if applicable)``

**Comment by nikita36078** [comment]
Fixed
