### ISSUE TITLE
Guitar Hero 5 can't multitouch

### ISSUE THREAD

**Issue by shenbolado** [nikita36078/J2ME-Loader#430]
**Emulator version:**
1.3.8-play
**Game version:**
2.0.0

**Game resolution:**
360x640

**Device:**
Samsung Galaxy J3 Emerge

**Android version:**
8.1.0

**Description of the issue:**
Can't press two buttons at same time ingame, activates one fret only.
![index](https://user-images.githubusercontent.com/46650212/51086730-58133180-1731-11e9-8d32-8206a069c8ad.jpg)

**Comment by nikita36078** [comment]
J2ME games don't support multitouch, so I don't think it's an emualtor bug. What song is it? I didn't find such combo in the game.

**Comment by shenbolado** [comment]
> J2ME games don't support multitouch, so I don't think it's an emualtor bug. What song is it? I didn't find such combo in the game.
Didn't know it. Tried with songs in expert, "Only Happy When It Rains" is one of them. I'll try to edit MANIFEST.MF to disable double notes.

**Comment by nikita36078** [comment]
Yes, Glu-Disable-Multi-Key should be true, I guess.
