### ISSUE TITLE
Need for speed hot pursuit bonus edition

### ISSUE THREAD

**Issue by dhanial** [nikita36078/J2ME-Loader#434]
**Emulator version:**
1.3.9

**Game version:**

**Game resolution:**
240x320
**Device:**
Xiaomi Redmi Note 4x

**Android version:**
7.1.2
**Description of the issue:**
I have black screen issue when i playing need for speed hot pursuit 3D bonus edition

**Comment by Yautja-Wolf** [comment]
Cuz emulator doesnt give what our gpu is really made of gaming..this emulator doesnt let us run on full potential gaming experience

**Comment by Bakugan77** [comment]
Sorry It's sony version satio..it works even 320x240..supports landscapre only.
![screenshot_20190203-125919](https://user-images.githubusercontent.com/47291055/52173994-fc7a1800-27b3-11e9-9a24-eed7d6b799ee.png)

**Comment by Bakugan77** [comment]
but the graphics sucks heehee😆

**Comment by nikita36078** [comment]
Fixed
