### ISSUE TITLE
Come on,Dear developer..please implement some better performance for high end phones.Give more settings for opengl 3.2 & vulkan supported phones.Dont  worry about low end phones..

### ISSUE THREAD

**Issue by Yautja-Wolf** [nikita36078/J2ME-Loader#435]
**Emulator version:**

**Game version:**

**Game resolution:**
``(For example, 240x320 or 640x360)``

**Device:**
``(For example, Samsung Galaxy S7)``

**Android version:**

**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``

**Comment by T4P4N** [comment]
j2me loader is about running java games not ps or pc games -____-,
Can you kindly close these #436 & #435.

**Comment by Yautja-Wolf** [comment]
Shut up fool!

**Comment by Yautja-Wolf** [comment]
You have weak phone..dont gaggle

**Comment by T4P4N** [comment]
:-1:

**Comment by Yautja-Wolf** [comment]
Funk! Faggot

**Comment by nikita36078** [comment]
@Yautja-Wolf Such behavior is prohibited here, I've blocked and reported you.
