### ISSUE TITLE
Emulator runs too weak being seen with the fps only 30.. My poco F1 can hit 60fps 4k easily

### ISSUE THREAD

**Issue by Yautja-Wolf** [nikita36078/J2ME-Loader#436]
**Emulator version:**

**Game version:**

**Game resolution:**
``(For example, 240x320 or 640x360)``

**Device:**
``(For example, Samsung Galaxy S7)``

**Android version:**

**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``

**Comment by T4P4N** [comment]
First, Java games are designed within a resolution of (720x1280) maximum and minimum 128x128. Can you explain what error you are suffering
Specifically in which game? -___-

**Comment by T4P4N** [comment]
Most java game runs on 30 fps, not 60

**Comment by Yautja-Wolf** [comment]
I need performance,quality and fps for gameloft games especially which is for sony k800i.And aslo the emulator is like optimized and made for low end phones only lol
