### ISSUE TITLE
Fishing Hook is having some problems

### ISSUE THREAD

**Issue by jack1432** [nikita36078/J2ME-Loader#441]
**Emulator version:**
``1.3.9 and 1.4.0``

**Game version:**
``1.0.16``

**Game resolution:**
``240x320``

**Device:**
``Samsung Galaxy J5 Pro``

**Android version:**
``8.1.0``
**Description of the issue:**

The game Fishing Hook does not respond to the command to pull the fish in versions (1.3.9 and 1.4.0) of the emulator. After catching the first fish I can not pull it to the boat, in the previous versions this did not happen.

And this is not the only problem, after returning to the main menu the game closes and this appears.
![screenshot_20190121-132029_j2me loader](https://user-images.githubusercontent.com/36806488/51488664-e9635300-1d84-11e9-833a-5dc5789dddf2.jpg)

**Comment by nikita36078** [comment]
I've added the accelerometer support in 1.3.9 and it causes errors in this game. As temporary solution, you can disable motion controls in the game settings.

**Comment by jack1432** [comment]
Thank you, so that's what caused the problems. After turning off the motion controls all the problems are gone, I can play without any problem now.

**Comment by Bakugan77** [comment]
That's cool😀

**Comment by nikita36078** [comment]
Fixed.
