### ISSUE TITLE
I hope your emulator can support sd card emulate

### ISSUE THREAD

**Issue by mini536** [nikita36078/J2ME-Loader#443]
**Emulator version:**

1.4.0
**Game version:**

0.7
**Game resolution:**
``(For example, 240x320 or 640x360)``
240×320
**Device:**
``(For example, Samsung Galaxy S7)``
xiaomi 1
**Android version:**
4.1.2
**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
when i run it,it says:
Загрузка...
Вставьте карту памяти!

**Comment by woesss** [comment]
Duplicate of #321

**Comment by AdityaMH** [comment]
Not sd card but external memory card.
