### ISSUE TITLE
Why Sims 3 all versions cant be played?? Except only Sims winter edition&Supernatural works!!

### ISSUE THREAD

**Issue by Bakugan77** [nikita36078/J2ME-Loader#447]
**Emulator version:**1.4.0

**Game version:**sims 3 all versions and sims World adventure

**Game resolution:**
``(For example, 240x320 or 640x360)``

**Device:**
``(For example, Samsung Galaxy S7)``

**Android version:**

**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``

**Comment by nikita36078** [comment]
duplicate #292
