### ISSUE TITLE
Sims 2 all versions can be played but sims 3 world adventure,Ambitions cant be played,why!!!? It's only 2d game EA.so good

### ISSUE THREAD

**Issue by Bakugan77** [nikita36078/J2ME-Loader#448]
**Emulator version:**

**Game version:**

**Game resolution:**
``(For example, 240x320 or 640x360)``

**Device:**
``(For example, Samsung Galaxy S7)``

**Android version:**

**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``

**Comment by nikita36078** [comment]
duplicate #292
