### ISSUE TITLE
[Feature Request] Floating Button For Accessing Menu

### ISSUE THREAD

**Issue by oatmeal01** [nikita36078/J2ME-Loader#451]
Please update menu access. Add floating(movable button) that can access the menu. 

Worried about conflicting with touchscreen games? Make the button movable to any position, adjustable opacity, color and size.

Theres a bug when clicking back button when accessing menu, sometimes status bar stays. Hope this floating button will solve this issue.

**Comment by nikita36078** [comment]
duplicate #232. Unfortunately, floating button won't help with it, since the menu would be called in the same way. But I think I found solution, I'm testing it right now.
