### ISSUE TITLE
App without drawing image (Dictionary or text-based app) problem

### ISSUE THREAD

**Issue by AdityaMH** [nikita36078/J2ME-Loader#452]
I found dictionary app where they not drawing/buffering image needed,
But this app not effected any setting such like ActionBar, virtual keypad, and screen size.

I disabled ActionBar, enabled virtual keypad, and resizing screen,
but they keep same result as on image..
![Main Menu](https://user-images.githubusercontent.com/33791472/52403891-594e3900-2afa-11e9-8199-caa3f56cbd56.png)

In version 1.2.3 and lower, i can back to main menu by pressing "back" in navigation button (act as RightSoftKey) but since "back" button now become menu.. i must open menu twice to back main menu or force to exit *and that's annoying*..
![Dictionary result](https://user-images.githubusercontent.com/33791472/52405254-75070e80-2afd-11e9-9cc2-f56622ba90b7.png)

And only solution is fixing virtual keypad for this app or #391

**Comment by nikita36078** [comment]
So it's the same issue as #391, it's a duplicate then

**Comment by AdityaMH** [comment]
The problem is this app can't using virtual keypad.. (something blocked by game screen)
