### ISSUE TITLE
Midi sounds stop playing after first play

### ISSUE THREAD

**Issue by enomat** [nikita36078/J2ME-Loader#454]
**Emulator version:**
Any

**Device:**
Samsung Galaxy S2, Samsung Galaxy S3 Neo`

**Android version:**
Any (tested on 4.1.2, 4.4.2)

**Description of the issue:**
The sounds play only once. This bug happens with games that have midi sound. Usually with old Nokia S40 128x128 java games. For example:

3D Adventure 2
http://dedomil.net/games/5472/screen/2

Bounce
http://www.mobiles24.co/downloads/s/569041-m958-bounce_128x128

**Comment by nikita36078** [comment]
Fixed
