### ISSUE TITLE
Menu Bug When Pressing Back Key

### ISSUE THREAD

**Issue by oatmeal01** [nikita36078/J2ME-Loader#455]
**Emulator version:** 1.4.1

**Game version:**

**Game resolution:**
``(For example, 240x320 or 640x360)``

**Device:**
``(For example, Samsung Galaxy S7)``

**Android version:**

**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``

Here is a screenshot when pressing back key to access menu
![screenshot_2019-02-12-21-15-22](https://user-images.githubusercontent.com/36059629/52637913-a754a980-2f0b-11e9-9c35-b9c135855344.png)

Pressing Recent/ Menu key button
![screenshot_2019-02-12-21-15-37](https://user-images.githubusercontent.com/36059629/52637829-6066b400-2f0b-11e9-8855-1c94557f21cf.png)

**Comment by nikita36078** [comment]
It's not a bug, this is fix to prevent the menu overlapping bug, which you mentioned in your previous issue. But it seems to work incorrectly with menu button.

**Comment by nikita36078** [comment]
Ok, now the menu should look the same in both cases.

**Comment by AdityaMH** [comment]
That's way, adding feature #391 may better solution.
