### ISSUE TITLE
Freezing App Issue: v1.4.1-1.4.2

### ISSUE THREAD

**Issue by oatmeal01** [nikita36078/J2ME-Loader#457]
**Emulator version:**
v1.4.1, v1.4.2

**Game version:**

**Game resolution:**
``(For example, 240x320 or 640x360)``

**Device:**
``(For example, Samsung Galaxy S7)``
Asus Zenfone 5

**Android version:** 
5.0

**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
After installing a java game(jar file) and configuring the game's configuration the app suddenly freezes when tapping START.   
You can't even minimize and close the app that it forces you to restart your phone. Sometimes when you leave the game idle it freezes too and you also need to restart your phone. It only occur to the latest versions 1.4.1, 1.4.2, the past versions seems to work fine.

**Comment by nikita36078** [comment]
Do you have this issue with all games?

**Comment by oatmeal01** [comment]
Yes, all games. Everytime i go to the games configuration and tapping Start the app freezes.

**Comment by amarcioz** [comment]
is a Samsung J1 2016 and the emulator is working perfectly.

**Comment by oatmeal01** [comment]
This happens 3 times in a row right now. I don't know what triggers the freezing issue. Sometimes its fine, sometimes it freezes.

**Comment by oatmeal01** [comment]
tried installing different games and for the 6th times my phone freezes when tapping start after configuring the settings after installation.

**Comment by amarcioz** [comment]
Try use other celular.

**Comment by nikita36078** [comment]
@oatmeal1 Are you sure you didn't have this problem in 1.3.9?

**Comment by oatmeal01** [comment]
i didn't notice in 1.3.9 cause everytime i see update i download and install. I just notice this issue after updating to 1.4.0 to the latest. everytime i install java games it freezes when opening after configuring

**Comment by oatmeal01** [comment]
ill try to reinstall 139 and check it if it also freezes

**Comment by oatmeal01** [comment]
i dont know if the template is the reason why the app freezes cause i load template from the old versions.

**Comment by nikita36078** [comment]
No, templates can't cause it.

**Comment by oatmeal01** [comment]
Tried 1.3.9 and it works fine. Even when fast tapping START after configuring intalled java.

**Comment by oatmeal01** [comment]
Installed 1.4.2 again and still, freezing occur after configuring, phone also freezes when exiting a game. I think im going to stick with the old version of J2me.

**Comment by nikita36078** [comment]
Thank you for the info, I will try to reproduce this bug. I have some ideas about it.

**Comment by oatmeal01** [comment]
I installed 1.4.1 version and it seems working fine now. smooth exit and Start.

**Comment by oatmeal01** [comment]
Sorry my mistake, this only occur to 1.4.2 version, i installed 1.4.1 and it works fine now.

**Comment by nikita36078** [comment]
Hmm, it's a bit confusing. What about 1.4.0?

**Comment by nikita36078** [comment]
I guess 1.4.0 should work fine then.

**Comment by oatmeal01** [comment]
Darn, still my phone hangs after minimizing and going back to the app. 1.4.1 still freezes though.

**Comment by oatmeal01** [comment]
ill try and observe 1.4.0 ill feedback if freezing still occur.

**Comment by oatmeal01** [comment]
Got it, 1.4.0 is stable to my device.

**Comment by Bakugan77** [comment]
Oatmeal,stop blamming for freezing.it's ur dumb phone which cant even run a game properly..U suck!!

**Comment by Bakugan77** [comment]
Change ur old cow device and stop confusing the developer,dummy boy😬

**Comment by woesss** [comment]
@oatmeal01, do you have this problem when the “Parallel screen drawing” option is enabled?

**Comment by oatmeal01** [comment]
@woesss nope it seems like the latest version has a bug that causes freezing. Im using 1.4.0 right now and it is stable.

@Bakugan Stop cussing, nothing is wrong reporting issue. Im not even blaming the dev. Are you stupid?

**Comment by woesss** [comment]
I understand very little English. I have an idea how to fix it. I need a clear answer - does "Parallel screen drawing" fix this problem or not (in the latest version)?

**Comment by oatmeal01** [comment]
@woess nope parallel is not enabled, im loading Templates with no active parallel screen drawing.

**Comment by woesss** [comment]
Try enable and test

**Comment by oatmeal01** [comment]
Tested, and the result is still the same phone freezes. Enabled or not. Im okay using v1.4.0 for now.

**Comment by woesss** [comment]
OK. Then the problem lies elsewhere.

**Comment by Bakugan77** [comment]
His dumb phone is too old already & freezing cuz emulator api is too strong for it haha.

**Comment by Lufog-git** [comment]
@Bakugan77 You act like a seven year old child. This is not the right place for this behavior.

**Comment by oatmeal01** [comment]
Just ignore that kid, she lacks of attention. Probably a retard.

**Comment by Bakugan77** [comment]
U r some tough java gamer then.Can u fix the Fast&furious Fugitive 3d&2d version of 240x320?😆

**Comment by AdityaMH** [comment]
And the problem is, what real "parallel screen redrawing" using for?

**Comment by hex007** [comment]
Hey it is hard to take you seriously after this.


![](https://i.imgur.com/vSbLQjY.png)

**Comment by Bakugan77** [comment]
whatever😞.If u know what java games are,u shouldnt have any problem with me.smhh!

**Comment by nikita36078** [comment]
Please, stop spamming! It's not a chat.

**Comment by nikita36078** [comment]
@oatmeal01 Can you take a log? It would be useful since I can't reproduce this bug, it seems to be really specific.

**Comment by oatmeal01** [comment]
how to take logs if phone freezes and need to force restart? i think the hardware acceleration for 4.0-5.0 was the cause of phone freezing. Btw 1.4.0 version of J2me is stable to my device

**Comment by Bakugan77** [comment]
on Gionee P5 mini and Samsung Galaxy grand prime 4G,the 1.4.2 version works well with improved performance in fps.I am surprised myself..It's 5.0 & 5.1.1 Android stock version

**Comment by Bakugan77** [comment]
My friend has Mircomax unite 2 4.4 kitkat..It works well with no lag issues but bit slow down sometimes or after 10mins of gameplay cuz of old cpu&gpu.Need atleast snapdragon 625,the most capable chipset of mid range to handle tasks.heehee😆

**Comment by nikita36078** [comment]
@oatmeal01 You can do it from your PC, with adb she'll. Maybe phone will be able to send the log.

**Comment by nikita36078** [comment]
Still have this issue in the latest version?
