### ISSUE TITLE
Water Rapids crashes on launch

### ISSUE THREAD

**Issue by m93a** [nikita36078/J2ME-Loader#458]
**Emulator version:** 1.4.0-play

**Game version:** Water Rapids 1.9

**Game resolution:** 128x128

**Device:** Xiaomi Redmi 6

**Android version:** 8.1.0

**Description of the issue:** It is possible to get through the splash screen to the menu. Options "High scores" and "Instructions" work too, but when I select "New game", the emulator crashes immediately.

**Comment by nikita36078** [comment]
Fixed
