### ISSUE TITLE
Customize Screen Rotate

### ISSUE THREAD

**Issue by AdityaMH** [nikita36078/J2ME-Loader#46]
Please add screen rotation setting in setting menu or individual like DraStic.
Some game like Civilization V need landscape to full screen or Real Footbal Manger 2009 need to portait to full screen.

**Comment by nikita36078** [comment]
You can change resolution to launch games which needs the landscape (320*240 instead 240*320, 640*360 instead 640*360) and rotate your device to get the fullscreen. I'm not sure if it will be comfortable to play the landscape games in the portrait mode and vice versa.

**Comment by oatmeal01** [comment]
please add a feature that locks or launch (640x360, HxW) games in Landscape/Reverse-Landscape and (360x640,WxH) in portrait. for better solution just add rotation lock control in configuring each game. this helps so that when you activate auto-rotation it won't affect games in portrait mode or vice versa.

**Comment by skelletR** [comment]
Yes.. Oatmeal01.. I agree with that you write that needed in next update

**Comment by AdityaMH** [comment]
it will better if add option screen orientation (automatic, portait, landscape, and reversed-landscape) than auto-lock orientation by game screen (WxH). because, i still want play 320x240 games in portait screen.

**Comment by skelletR** [comment]
Yes understand all that must read the dev of the j2me and if can add this feature

**Comment by nikita36078** [comment]
I'm planning to add an orientation lock setting in the app settings, so user will be able to select automatic, landscape or portrait orientation.

**Comment by AdityaMH** [comment]
That will be great hope for 360x640 games, @nikita36078.

**Comment by nikita36078** [comment]
@AdityaMH, yes, I remember about it :)

**Comment by AdityaMH** [comment]
Can you solve this issue, @aNNiMON ?

**Comment by nikita36078** [comment]
Done￼

**Comment by skelletR** [comment]
Now i have Version 1.2.8.4-play not have screen orientation.. I updated the app before 6 hours.. This with screen orientation when can update to this version?

**Comment by oatmeal01** [comment]
@skellet lets just wait for the next release, 

btw HW Acceleration options is not showing, maybe os5.0 is not also supported.

**Comment by skelletR** [comment]
Yes just waiting.. My phone Xperia z5 nougat 7.1.1..  I have the option..  HW Acceleration (unstable)

**Comment by AdityaMH** [comment]
Thanks for adding that feature. That very useful.
Btw, that text not listed on crowdin.

**Comment by skelletR** [comment]
Now just waiting for the next release update with screen orientation..  I have HW Acceleration(unstable)
