### ISSUE TITLE
Boxes are invisible in Gish

### ISSUE THREAD

**Issue by m93a** [nikita36078/J2ME-Loader#460]
**Emulator version:** 1.4.0-play

**Game version:** Gish 0.9.4

**Game resolution:** 240x320

**Device:** Xiaomi Redmi 6

**Android version:** 8.1.0

**Description of the issue:** The wooden boxes are invisible, or disappear when moved. I was able to replicate it both on high and low details.

![52071439_2086120158100434_2082561523649085440_n](https://user-images.githubusercontent.com/1671665/52828641-ddd82300-30c9-11e9-80de-28c44fd55016.png) 
![52129985_297843370928893_2099020001536114688_n](https://user-images.githubusercontent.com/1671665/52828645-e4ff3100-30c9-11e9-9b0c-75e5e8620315.png)

In Gish Reloaded 1.0.0 the boxes are visible only as a placeholder texture.

![52327053_2258197461115094_6542967738665533440_n](https://user-images.githubusercontent.com/1671665/52828709-21329180-30ca-11e9-85d6-fee8230d2b01.png)

**Comment by nikita36078** [comment]
Fixed

**Comment by m93a** [comment]
Awesome! Can't wait to play Gish again <3
