### ISSUE TITLE
what's new in this 1.4.2 version?? I dont see any changes

### ISSUE THREAD

**Issue by Bakugan77** [nikita36078/J2ME-Loader#461]
**Emulator version:**

**Game version:**

**Game resolution:**
``(For example, 240x320 or 640x360)``

**Device:**
``(For example, Samsung Galaxy S7)``

**Android version:**

**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``

**Comment by nikita36078** [comment]
Version 1.4.2:
- Minor bugfixes

Version 1.4.1:
- Bugfixes
- Added hardware acceleration support for Android 4.0-5.0
- Improved perfomance

**Comment by Bakugan77** [comment]
yeahh I see it's cool fps .great performance 😃
