### ISSUE TITLE
Perfomance drops in 1.4.2

### ISSUE THREAD

**Issue by Bakugan77** [nikita36078/J2ME-Loader#462]
**Emulator version:**1.4.2

**Game version:**Most gameloft games of 1mb file or higher (mostly sony k800i)

**Game resolution:**
``(For example, 240x320 or 640x360)``

**Device:**
``(For example, Samsung Galaxy S7)``

**Android version:**

**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``

**Comment by Bakugan77** [comment]
I enabled or disabled the new option drawing....It doesnt make any changes in games though. 1.4.1 version works fine and stable

**Comment by nikita36078** [comment]
So, has something changed in recent versions?
