### ISSUE TITLE
American Gangster(Gameloft)

### ISSUE THREAD

**Issue by Bakugan77** [nikita36078/J2ME-Loader#464]
**Emulator version:**1
4.2

**Game version:**1.0.1,1.0.9 ...

**Game resolution:**240x320
``(For example, 240x320 or 640x360)``

**Device:*Realme U1
``(For example, Samsung Galaxy S7)``

**Android version:**8.1

**Description of the issue:**Still this game lags badly,dunno why..It's 500-550kb in N73,Sony K800i...Is the graphics that much strong?

``(What's the problem? - Screenshots showing the issue if applicable)``

**Comment by oatmeal01** [comment]
Your phone is not capable of playing low end games, just bin it retard. :)

**Comment by nikita36078** [comment]
This game's framerate is locked to 14fps, so it's not a bug.
