### ISSUE TITLE
 add features for jar file recovery

### ISSUE THREAD

**Issue by ahmadprayoxxsy** [nikita36078/J2ME-Loader#465]
**Emulator version:**
1.4.2

**Game version:**
All

**Game resolution:**
``(all)``

**Device:**
``(all)``

**Android version:**
All
**Description of the issue:**
in the emulated folder / 0 / j2me loader / converted / game / Res and converted.dex can it be changed to the jar file

**Comment by ahmadprayoxxsy** [comment]
![screenshot_20190217-100507-picsay](https://user-images.githubusercontent.com/37769813/52907915-30007c00-3263-11e9-8a01-3db797ecdd7d.jpg)
For example, in the mt maneger application there is (dex2jar)

**Comment by nikita36078** [comment]
What's the point of it? Jar won't work on other emulators anyway, because J2ME Loader modifies application code.

**Comment by ahmadprayoxxsy** [comment]
because file.dex is easier to edit than the .class file
it will be easier if we modify / edit the game, but it will be difficult if we return it to file.jar
jadi kami tidak dapat mengirim hasil modifikasi ke telepon java

**Comment by jasper1412** [comment]
i think they're talking about dexing on android framework, theres no point with reverse engineering it to jar cause first of all, you hold the jar file downloaded compatible to convert it to the app. if they want, they may reverse class-to-java inside j2me applications with .jar file. This does not give a clear argument why it needs those implementations.

**Comment by jasper1412** [comment]
to put it simple, they are talking about having a backup on jar files being converted to the app

**Comment by nikita36078** [comment]
Now the emulator stores original .jar file in J2ME-Loader/converted/game_name/res.jar.
