### ISSUE TITLE
Street fighter alpha- multitouch support

### ISSUE THREAD

**Issue by matt29silva** [nikita36078/J2ME-Loader#467]
**Emulator version:**
1.4.2-play

**Game version:**
1.0.3

**Game resolution:**
``(800x400)``

**Device:**
``(Moto G4 Play)``

**Android version:**
6.0
**Description of the issue:**
``(is there a possibility of add multitouch support? this game only works with two fingers sadly)``

**Comment by nikita36078** [comment]
No, j2me games don't support multitouch.
