### ISSUE TITLE
480x800 screen orientation bug

### ISSUE THREAD

**Issue by BeF1990** [nikita36078/J2ME-Loader#468]
**Emulator version:**
1.4.2

**Game version:**
Most of Gameloft's games in 480x800 resolution
(Samsung S8000 or Sony Ericsson Xperia X1i)

**Game resolution:**
480x800

**Device:**
I think all, but tested on:
- Samsung Galaxy Tab S4
- Samsung Galaxy J5 (2017)

**Android version:**
8.1

**Description of the issue:**
Screen orientation bug - screen is rotated 90°.
![screenshot_20190220-140603_j2me loader](https://user-images.githubusercontent.com/42754764/53093863-e2149e00-3518-11e9-9636-1718ccfec8a4.jpg)
![screenshot_20190220-141016_j2me loader](https://user-images.githubusercontent.com/42754764/53094045-5b13f580-3519-11e9-9a53-d45d5c35ea4d.jpg)
![screenshot_20190220-141428_j2me loader](https://user-images.githubusercontent.com/42754764/53094242-e3929600-3519-11e9-9045-b0093d358d51.jpg)

**Comment by woesss** [comment]
This is not a bug. The game uses pseudo-landscape mode. The emulator has no way to know about it.  
You need to make the screen settings as for portrait mode, and lock the auto-rotate.

**Comment by woesss** [comment]
@nikita36078, надо бы для подобных игрушек сделать отдельную настройку для принудительного поворота клавиатуры.

**Comment by BeF1990** [comment]
Ok, understand. So the best solution is to stay with 360x640 games.

**Comment by nikita36078** [comment]
Yes, or you can lock the orientation, as @woesss said.

@woesss Я не видел еще не одной кнопочной игры с такой проблемой, видимо, это только для тачфонов такой хак придумали (не пойму, зачем).

**Comment by woesss** [comment]
@nikita36078, так далеко не каждый аппарат мог похвастаться функцией авто- и вообще поворота экрана, а в ландшафте играться как-то покомфортнее, особенно на широкоформатном экране.

**Comment by woesss** [comment]
@BeF1990, Have you tried to set the landscape resolution (800x480)? 

![screenshot_2019-02-20-23-54-28](https://user-images.githubusercontent.com/36137354/53124027-74459200-356b-11e9-893f-3cc5c99f5706.png)

![screenshot_2019-02-20-23-49-01](https://user-images.githubusercontent.com/36137354/53124028-74de2880-356b-11e9-9a26-dee8150b859b.png)
   
@nikita36078, а тут "сюрприз" - вообще управление под qwerty-клаву, поиграть не выйдет. А если ещё вспомнить про Сименсы, Моторолы и другие "особенности", то напрашивается настройка кей-кодов на кнопки.

**Comment by nikita36078** [comment]
И то, и другое давно лежит в issues, просто руки ещё не дошли.

**Comment by BeF1990** [comment]
I'm stupid. Everything works fine. Sorry for problem.
