### ISSUE TITLE
Bad Manga Girls 3

### ISSUE THREAD

**Issue by amarcioz** [nikita36078/J2ME-Loader#469]
Emulator version:
1.4.2

Game version:
1.0

Game resolution:
All

Device:
Samsung Galaxy j1 2016

Android version:
5.1

Description of the issue:
The game does not open.

**Comment by Bakugan77** [comment]
cuz u r below 18.Adult only Hahaha😂

**Comment by amarcioz** [comment]
> cuz u r below 18.Adult only Hahaha

If you have nothing useful to say, do not say nonsense.

**Comment by woesss** [comment]
In other emulators (on PC) also does not work. Most likely the problem is in the game itself.

**Comment by nikita36078** [comment]
It doesn't work on Nokia 3710 too, so it's definitely game problem.
