### ISSUE TITLE
3D Black Shark

### ISSUE THREAD

**Issue by uforgivent** [nikita36078/J2ME-Loader#479]
**Emulator version:** 1.4.2

**Game version:** 1.3.0

**Game resolution:** 240x320

**Device:** Samsung Galaxy J6

**Android version:** 8.0

**Description of the issue:** Some textures in the game aren't loaded...
![Screenshot_20190320-111348_J2ME Loader](https://user-images.githubusercontent.com/5973208/54691040-5f740400-4b01-11e9-8c19-61da9bf1995b.jpg)

**Comment by nikita36078** [comment]
Mascot Capsule games aren't supported, use version for Nokia.

**Comment by amarcioz** [comment]
Nokia version of the site dedomil.

![Screenshot_2019-03-21-13-21-03](https://user-images.githubusercontent.com/35005836/54768352-c0710a00-4bdd-11e9-8497-322808eb8800.png)

**Comment by nikita36078** [comment]
Fixed

**Comment by TruongTanLuc201270** [comment]
Repoen issue: Jumping to credits bug
App version 1.8.2-play, game version  1.1.0, 240x320
https://photos.app.goo.gl/4iUBn5AZphUzzia68
[log.txt](https://github.com/user-attachments/files/19925630/log.txt)
http://dedomil.net/games/2788/screen/8
