### ISSUE TITLE
Add softkey actions to the app menu

### ISSUE THREAD

**Issue by BoysCode** [nikita36078/J2ME-Loader#48]
文本输入框太窄小,不可换行,编辑文本时长文本显示不正常.

**Comment by nikita36078** [comment]
English please. And send me screenshot, I don't understand what do you mean by "text input box is too narrow".

**Comment by BoysCode** [comment]
It is suggested that the exhaled keyboard option is added to the shortcut settings. Some of the contents need to be confirmed by the keyboard, but the menu is not displayed.
long text the screen line feed . Paragraph line feed. type Enter to line feed. The input box adapts to the screen .  Thank.--------I'm sorry this is Machine Translation. I'm not good at English. @nikita36078

**Comment by nikita36078** [comment]
So you need to confirm some action, but keyboard isn't displayed, right?
