### ISSUE TITLE
ANNO - The creation of a new world

### ISSUE THREAD

**Issue by uforgivent** [nikita36078/J2ME-Loader#480]
**Emulator version:** 1.4.2

**Game version:** 1.0.0

**Game resolution:** 240x320

**Device:** Samsung Galaxy J6

**Android version:** 8.0

**Description of the issue:** The game Run slowly...
Only runs to - 30 FPS
![Screenshot_20190320-112857_J2ME Loader](https://user-images.githubusercontent.com/5973208/54692838-66e8dc80-4b04-11e9-97bb-36b5391dcaef.jpg)

**Comment by amarcioz** [comment]
I tested it and the game is very playable.

**Comment by nikita36078** [comment]
Yes, it seems like 25-30 fps is native framerate for this game, I'm getting the same perfomance on Nokia 3710.
