### ISSUE TITLE
Feature request: Center applet screen in portrait mode

### ISSUE THREAD

**Issue by AnIcePerson** [nikita36078/J2ME-Loader#481]
**Emulator version:**
1.4.3-play

**Game version:**
Any game not in native ratio

**Game resolution:**
Any non native resolution

**Device:**
Samsung Galaxy S9

**Android version:**
9.0
**Description of the issue:**
In portrait mode, all applications align with the top of the screen, instead of the center like in landscape. This is an issue for games which have a portrait mode resolution but play in landscape (many 240x400 touchscreen games, such as Plants vs. Zombies), or for devices with curved/rounded display corners, causing elements/text from the top corners to be cut off. A solution would be the option to select a centered option for the screen in portrait mode.

**Comment by nikita36078** [comment]
Added
