### ISSUE TITLE
Deep 3D Submarine Oddysey glitch

### ISSUE THREAD

**Issue by Indra2108** [nikita36078/J2ME-Loader#483]
**Emulator version:**
1.4.3

**Game version:**
1.0.8

**Game resolution:**
320x240

**Device:**
Smartfren Andromax G

**Android version:**
4.1.2

**Description of the issue:**
A Glitch Occured on the left side of the screen

Screenshot :
https://ibb.co/9GkKCLm
https://ibb.co/KmrV9Qs
https://ibb.co/0fVrs79
https://ibb.co/bmK2MZW

The link i am downloaded
http://phoneky.com/games/?s=download&id=j4j12743

**Comment by nikita36078** [comment]
It looks like graphics driver problem, I can't reproduce this bug.

**Comment by amarcioz** [comment]
Download this game from Java.mob site. I downloaded the game from this site and it works fine.

**Comment by nikita36078** [comment]
Does this bug still exist?

**Comment by Indra2108** [comment]
@nikita36078 No, Thank you. I tried it on another cellphone and it worked well
