### ISSUE TITLE
Performance dropped badly while using the latest version  of this emulatoe while playing asphalt 6 

### ISSUE THREAD

**Issue by RyukenT** [nikita36078/J2ME-Loader#484]
**Emulator version:**1.4.3

**Game version:**1.0.0

**Game resolution:**240x320
``(For example, 240x320 or 640x360)``

**Device:**Poco F1,Sam GS7
``(For example, Samsung Galaxy S7)``

**Android version:**7.1.2 ; 9.0

**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``

**Comment by RyukenT** [comment]
1.4.2 version dropped 2-8 fps but this 1.4.3 versions starts to lag from beginning. 5-10 fps

**Comment by RyukenT** [comment]
The emulator sucks and too buggy..please fix it instead

**Comment by nikita36078** [comment]
Device? Game version? Game resolution?

**Comment by RyukenT** [comment]
Asphalt 6 1.0.0 1.5mb sony version. My phone Samsung GS 7 and tried on poco F1 too

**Comment by RyukenT** [comment]
it's just too bad I never got this issue before.performace was never backward on previous versions of this emulator..1.4.1version works very fine

**Comment by nikita36078** [comment]
I will close this issue since it's the same problem as in #462
