### ISSUE TITLE
Can't Open Blood +

### ISSUE THREAD

**Issue by Indra2108** [nikita36078/J2ME-Loader#485]
**Emulator version:**
1.4.3

**Game version:**
1.0.0

**Game resolution:**
352x146 and 480x800

**Device:**
Smartfren Andromax G

**Android version:**
4.1.2

**Description of the issue:**
I can't open the game, error if I open the game

Screenshot :
https://ibb.co/mRQT0rX
https://ibb.co/1TRxryW

Link Games :
352x416 : http://dedomil.net/games/1579/screen/14
480x800 : http://dedomil.net/games/1579/screen/17

**Comment by nikita36078** [comment]
Install game using .jad, not .jar.

**Comment by Indra2108** [comment]
Ohhh thank you, Is the method exactly the same as using phoneME?

**Comment by nikita36078** [comment]
I don't remember how phoneME works, but you just need to download jad file and select it.

**Comment by Indra2108** [comment]
I tried to select the jad file only, but the results "can't download .jar" and I have tried editing the jad file in the MIDlet.url section so that it can be downloaded, but after I try again, it turns out the results are still the same.

But after I tried it in the exact same way as PhoneME. It Works!

Screenshoot https://ibb.co/s136GF0

**Comment by amarcioz** [comment]
Always open .jad files by the J2ME Loader emulator.

**Comment by nikita36078** [comment]
Some .jad files doesn't have a direct download link, the emulator can't open them.
