### ISSUE TITLE
Config MIDlet load with background service

### ISSUE THREAD

**Issue by kekhong95** [nikita36078/J2ME-Loader#486]
I want to play a lot of games in the background, but there is one problem: I have to run too many activities, so I want to turn it into a service.
 So is there a way to configure the game to be a service form and how to rebind it from that service to draw back on the screen when I reopen the activity.
Thanks

**Comment by AdityaMH** [comment]
In other ways, you want playing multiple midlet games?

**Comment by kekhong95** [comment]
> In other ways, you want playing multiple midlet games in same time?

Yes and i want playing same service ...

**Comment by nikita36078** [comment]
No, I can't add the multitasking feature because it would require rewriting the emulator from scratch. It just isn't possible in the current implementation.
