### ISSUE TITLE
Not quite stable for low end 32bit cpu phones. Better to stick to v1.4.0 of this emu

### ISSUE THREAD

**Issue by RyukenT** [nikita36078/J2ME-Loader#489]
**Emulator version:**1.4.1 to 1.4.3

**Game version:** gameloft games like Thor 2,asphalt 6,fast&furious 6 and many more...but most sony k800i version..note..they dont need mascot capsule API. 

**Game resolution:**240x320
``(For example, 240x320 or 640x360)``

**Device:*samsung J2 2016, and most quad core 32bit cpu 
``(For example, Samsung Galaxy S7)``

**Android version:** 5.0,6.0.1 and 7.1.2(lineage os)

**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``

**Comment by RyukenT** [comment]
Issues like sound or audio missing in action games.braking or drifting tire burnout sound missing in racing games.The game sound syncs less or other misses when restart the game..It just aint proper in audio

**Comment by nikita36078** [comment]
I will close this issue since it's the same problem as in #462
