### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by minhducsun2002** [nikita36078/J2ME-Loader#49]
Trying to run Facebook for Every Phone, which has the package name <com.moblica.client.ClientMain>, and J2ME Loader shows a dialog titled "Error" and a letter below it. Sometimes it's 'c', another times it's 'd'.
Anyway, tweaking the options doesn't make the application work. 

Here I'm including the jar file of the application (which I has modified the extension to zip to be able to upload to GitHub).

Hope you can fix this. Anyway, thanks for such a great program.
[facebook-3.4.3-moblica.zip](https://github.com/nikita36078/J2ME-Loader/files/1521728/facebook-3.4.3-moblica.zip)

**Comment by nikita36078** [comment]
I checked this jar and it looks like a problem in the app code, so I can't fix it.
