### ISSUE TITLE
Guitar Hero World Tour - "Failed to start music" message

### ISSUE THREAD

**Issue by mbc07** [nikita36078/J2ME-Loader#492]
**Emulator version:**
1.4.3-play

**Game version:**
1.0.7

**Game resolution:**
240x320

**Device:**
Sony Xperia X Dual (F5122)

**Android version:**
8.0.0

**Description of the issue:**
To be honest, I don't know if this version of the game was officially released or if it's just a mod done by someone. What I know is the file name only mention it's for K800 (Guitar_Hero_World_Tour_K800.jar) and the JAR seems abnormally huge for a J2ME game (7.27 MB, more specifically). The only real difference I could notice between this and the other 240x320 versions of the game (that sits around 900 KB in size) is that this one has MP3 songs instead of MIDI songs. Despite the huge size, it installs and plays normally on my SE W705 phone, but on J2ME-Loader, the game itself show a "FAILED TO START MUSIC" message and then return to the song selection list whenever you try to play any song:

![Screenshot_20190405-214551](https://user-images.githubusercontent.com/8005966/55665106-7efc7380-5807-11e9-8622-a081f5720059.png)

**Comment by nikita36078** [comment]
Can you send me this game at j2me.loader@mail.ru (or just here)? I can't find it at all.

**Comment by mbc07** [comment]
Here is it
[Guitar_Hero_World_Tour_K800.zip](https://github.com/nikita36078/J2ME-Loader/files/3128904/Guitar_Hero_World_Tour_K800.zip)

**Comment by Indra2108** [comment]
I Try it from the Nokia version, it can start music, but the Avatar Character not appear.
![Screenshot_20190507-073958](https://user-images.githubusercontent.com/47787767/57264785-1f131a00-709e-11e9-9631-010dbd407524.png)

Here the games : http://dedomil.net/games/3449/screen/14

**Comment by Indra2108** [comment]
I Use J2ME Loader Version 1.4.6-play

**Comment by nikita36078** [comment]
Fixed
