### ISSUE TITLE
Jingling Zhaohuan-Mengyou Xianjing 

### ISSUE THREAD

**Issue by mini536** [nikita36078/J2ME-Loader#496]
**Emulator version:**
1.4.4

**Game version:**

1.0
**Game resolution:**
``(For example, 240x320 or 640x360)``
240×320
**Device:**
``(For example, Samsung Galaxy S7)``
Xiaomi 2
**Android version:**
5.0
**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
Can not open it
Download url http://appdown.7723.cn/wuza/softh/201082O460271.jar

**Comment by nikita36078** [comment]
This app checks time after the start, and if it's more than 19.01.2014 - the app closes. So it's not a bug, just some kind of license check.

**Comment by amarcioz** [comment]
Have you tried the jad file for this game?
