### ISSUE TITLE
make a direct installation

### ISSUE THREAD

**Issue by ahmadprayoxxsy** [nikita36078/J2ME-Loader#500]
**Emulator version:**
All

**Game version:**
All

**Game resolution:**
``(For example, 240x320 or 640x360)``

**Device:**
``(For example, Samsung Galaxy S7)``
All
**Android version:**
2-9
**Description of the issue:**
make 2 different installations.
For example, in the j2me loader the application .jar is extracted into a dex file.
And in the phoneME and ppskvm applications. Aplikasi.jar is played directly.

**Comment by ahmadprayoxxsy** [comment]
For example in ppskvm
![Screenshot_20190421-140528](https://user-images.githubusercontent.com/37769813/56808706-a00e1e00-6821-11e9-87c0-23a5942f534d.png)

**Comment by nikita36078** [comment]
It's impossible, since J2ME Loader doesn't have a VM and it uses Android Dalvik/ART (which doesn't support .class files) to run applications. PSPKVM is a VM, so it can run .jar files without any additional actions.
