### ISSUE TITLE
[Bug]Phantom spider 2D

### ISSUE THREAD

**Issue by kyaros** [nikita36078/J2ME-Loader#502]
**Emulator version:1.4.5**

**Game version:0.3**

**Game resolution:**
``128x128``

**Device:**
``LG Leon LTE``

**Android version:6.0**

**Description of the issue:**
the game stays on that screen
![Screenshot_2019-05-01-23-41-52](https://user-images.githubusercontent.com/50189701/57054614-0ead0a80-6c6c-11e9-8632-88682ce15ab7.png)
 and no option responds sometimes by touching the 3-point menu and select load the game a second and return to the menu

PD:translated by Google, yep my english is bad

**Comment by nikita36078** [comment]
Fixed.
