### ISSUE TITLE
Nature park still always crash

### ISSUE THREAD

**Issue by mini536** [nikita36078/J2ME-Loader#503]
**Emulator version:**
1.4.5

**Game version:**
1.0

**Game resolution:**
``(For example, 240x320 or 640x360)``
128×128
**Device:**
``(For example, Samsung Galaxy S7)``
redmi note 3
**Android version:**
8.1
**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
      It seems that this problem have existed for a long time,I hope you can solve it,thanks

**Comment by nikita36078** [comment]
Please don't create duplicate issues, #401 is still opened, I remember it.
