### ISSUE TITLE
Sim City Societies

### ISSUE THREAD

**Issue by GoldenX29** [nikita36078/J2ME-Loader#504]
Emulator version: 1.4.5-play

Game: Sim City Societies, version: 1.11.81

Game resolution: 240x320

Device: Samsung Galaxy J7 Nxt

Android version: 8.1.0

Description of the issue: Game crashes at start. Some description comes up:
Verifier rejected class a: boolean failed to verify.......

Unable to upload screenshots due to some error.

**Comment by nikita36078** [comment]
Duplicate #194
