### ISSUE TITLE
Race Driver Grid

### ISSUE THREAD

**Issue by GoldenX29** [nikita36078/J2ME-Loader#505]
Emulator version: 1.4.5-play

Game: Race Driver Grid, version: all high graphics versions (900 kb+ size ones)

Game device: Samsung Galaxy J7 Nxt

Android version: 8.1.0

Description of the issue: Graphics glitch during race, can't play races. Menus run fine.

**Comment by nikita36078** [comment]
J2ME Loader doesn't support Mascot Capsule games, but you can find the version of this game for Nokia, it works fine.

**Comment by GoldenX29** [comment]
Thanks for the info. Can you please add an option to change midi soundfonts in the app so that the music instruments would the same as those java phones?

Another request: Can you please develop a Symbian and NGage emulator?

**Comment by nikita36078** [comment]
Developing a Symbian emulator isn't that easy, it can take years :)
Anyway, it's already in development, check out https://github.com/EKA2L1/EKA2L1.
Maybe I will add the sound fonts support in the future, but right now I'm more focused on fixing bugs.

**Comment by AdityaMH** [comment]
> Maybe I will add the sound fonts support in the future, but right now I'm more focused on fixing bugs.

Yeah, i really like that feature, but you need plugin (like bassmidi)..

**Comment by nikita36078** [comment]
Fixed
