### ISSUE TITLE
A problem

### ISSUE THREAD

**Issue by mini536** [nikita36078/J2ME-Loader#508]
**Emulator version:**
1.4.6-1.4.7

**Game version:**

0.2
**Game resolution:**
``(For example, 240x320 or 640x360)``
128×128
**Device:**
``(For example, Samsung Galaxy S7)``
redmi note3
**Android version:**
8.1
**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
Some jar emulator can't install it but j2me phone can,such as this jar ,http://downloadwap.com/java-games/thegames/down/0/Classic/naturepark.jar
How to solve it?
By the way,do you have j2me loader 1.4.7 for android 2.3?

**Comment by Indra2108** [comment]
Hi @mini536 , I've found a solution! , I tried the method from the J2ME Loader Thread on the 4PDA Forum, it work!
![Screenshot_20190508-104131-1](https://user-images.githubusercontent.com/47787767/57348146-442b8980-717f-11e9-9d1a-0ea1f2362a12.png)

**Comment by nikita36078** [comment]
I know about this problem, I will fix it in the next release.
No, I don't have a newer version for Android 2.3.

**Comment by nikita36078** [comment]
Fixed.
