### ISSUE TITLE
Age Of Empires III Not Working

### ISSUE THREAD

**Issue by Emulatorer** [nikita36078/J2ME-Loader#510]
**Emulator version:**
J2ME Loader v1.4.7-play

**Game version:**
Age Of Empires III v1.0.3
AOE III Asian Dynasties v1.0.0

**Game resolution:**
``(For example, 240x320 or 640x360)``
240x320
**Device:**
``(For example, Samsung Galaxy S7)``
Cloudfone Excite Prime
*Android 5.1 Lollipop
*Mali-450 GPU
*2gb RAM
**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
Can't play any one of them :(
### Screenshots
![Screenshot_2019-05-09-11-45-41](https://user-images.githubusercontent.com/37603562/57429432-a9a27780-725e-11e9-86bc-5bcfdf99ca04.png)
![Screenshot_2019-05-09-11-45-48](https://user-images.githubusercontent.com/37603562/57429442-b1621c00-725e-11e9-8038-135c87e444c2.png)

**Comment by Indra2108** [comment]
Works Well on my Device, Samsung SM-G313HZ Android 4.4.2 KitKat

try to download on other sites

Download From Here : http://dedomil.net/games/search/Age%20Of%20Empires%20III/page/1 

![Screenshot_2019-05-09-13-44-41](https://user-images.githubusercontent.com/47787767/57432961-685f9700-7261-11e9-8af2-23b14cf03cda.png)
![Screenshot_2019-05-09-13-46-56](https://user-images.githubusercontent.com/47787767/57432992-7e6d5780-7261-11e9-8aea-59af17431f94.png)

**Comment by Emulatorer** [comment]
@Indra2108 still the same
![Screenshot_2019-05-09-17-18-18](https://user-images.githubusercontent.com/37603562/57442431-8f789180-727e-11e9-98b0-17c859a9a222.png)
What the resolution did you download and did you change some of the settings?

**Comment by nikita36078** [comment]
@Emulatorer Select Menu->Save log, and send a log file from J2ME-Loader/log.txt

**Comment by Emulatorer** [comment]
@nikita36078 ok
[log.txt](https://github.com/nikita36078/J2ME-Loader/files/3161342/log.txt)

**Comment by nikita36078** [comment]
Thanks, now I see the error

**Comment by nikita36078** [comment]
Please try this [fixed version](https://mega.nz/#!ZIl10K6b!cKQW1g2ZCQVSS1rr_iOYTbLd7qyNI-OvXVK8FrqmvY0). I think you need to uninstall the google play version first.
I can't reproduce this error, so I need to test my fixes.

**Comment by Emulatorer** [comment]
@nikita36078 THANK YOU it's working now :)
![Screenshot_2019-05-09-18-12-12](https://user-images.githubusercontent.com/37603562/57446020-43c9e600-7286-11e9-8da1-291ccaf19f28.png)
