### ISSUE TITLE
Desktop app?

### ISSUE THREAD

**Issue by vadosnaprimer** [nikita36078/J2ME-Loader#511]
Is is possible to build this for Windows or Linux?

**Comment by nikita36078** [comment]
No, this app has always targeted Android, it contains a lot of Android-specific hacks and optimizations, so it's almost impossible to port it to the desktop platforms.

**Comment by vadosnaprimer** [comment]
For the sake of potential future reference, can you elaborate on that? Maybe some part could be extracted or reused in some other project. A few notes just on how this tool works would also be very nice.

**Comment by nikita36078** [comment]
First of all, this app converts the JVM bytecode to the Dalvik bytecode, Android can't just run J2ME apps. The emulator stores all converted apps in one folder. Desktop emulators don't need all that stuff, they usually only apply a few patches to the bytecode and launch the j2me apps from any location. Also, high-level user interface and media playback emulation are strongly tied with Android APIs. I think the low-level UI (like Canvas, Graphics etc) can be ported relatively easy.

**Comment by vadosnaprimer** [comment]
Thanks!
