### ISSUE TITLE
Facebook erorr

### ISSUE THREAD

**Issue by ahmadprayoxxsy** [nikita36078/J2ME-Loader#513]
**Emulator version:**
New

**Game version:**
V.2.3.0

**Game resolution:**
``(All)``

**Device:**
``(All)``

**Android version:**
All
**Description of the issue:**
``in the emulator = phoneME, Jbend, j2me runer. everyone can run facebook.jar
is there no improvement for the facebook.jar application on the j2me loader``

**Comment by nikita36078** [comment]
Duplicate #245. It works on phoneME and JBed because they have their own java virtual machine implementation, while J2ME-Loader use Dalvik VM. That's why it can't load a game, if its code has any verification issues.
