### ISSUE TITLE
Splinter Cell: Pandora Tomorrow 176x220 W810i/K600i

### ISSUE THREAD

**Issue by pantomm** [nikita36078/J2ME-Loader#518]
**Emulator version:**
1.4.9-play

**Game version:**
1.0.5

**Game resolution:**
``176x220
**Device:**
``(For example, Samsung Galaxy S7)``
Samsung galaxy j5 2016
**Android version:**
6.0.1
**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
The game loads fine but when starting the mission it goes to blank screen.
Can't do anything except exit the game

**Comment by Sahkulu** [comment]
Hello you should try Splinter Cell Pandorra Tomorrow 176x208 s60v1/N3230 version (which is the best). Other versions suck in my opinion. Give it a try.

**Comment by pantomm** [comment]
@sahkulu
That version size is only 179.5kB, while this version has 272.1kB, the difference almost 100kb. Surely this version is the best

**Comment by nikita36078** [comment]
The SE version of this game is based on Mascot Capsule engine, which isn't supported.

**Comment by pantomm** [comment]
Why isn't supported?

**Comment by nikita36078** [comment]
I need to rewrite Mascot Capsule from scratch and it's almost impossible because I don't have enough information about it (unlike M3G,  it's a proprietary software). Maybe the support will be added in the future, but it definitely won't happen soon.

**Comment by nikita36078** [comment]
Fixed
