### ISSUE TITLE
希望加入即时存档

### ISSUE THREAD

**Issue by 2929490899** [nikita36078/J2ME-Loader#519]
*仿真器版本：1.4.9
*游戏解析：*
`(例如，240x320或640x360)`
*设备 meizu note 9
*Android版本：Android 9
*问题的描述：希望模拟器能加入即时存档功能，这样就可以不用担心要重新玩了。

**Comment by amarcioz** [comment]
English, please.

**Comment by stevenfelix505** [comment]
Translated: Add Quick-Save Function
