### ISSUE TITLE
Parallel screen redrawing

### ISSUE THREAD

**Issue by Indra2108** [nikita36078/J2ME-Loader#520]
Excuse me, can you explain the features of the Parallel screen redrawing?
what is the Function of this feature?
![Screenshot_2019-05-25-12-48-31](https://user-images.githubusercontent.com/47787767/58368822-76c5d800-7f1c-11e9-87de-532a85bc3259.png)

Thank you

**Comment by nikita36078** [comment]
This option can improve perfomance sometimes.

**Comment by Indra2108** [comment]
@nikita36078 In your opinion, which is better, HW Acceleration or Parallel screen redrawing?

**Comment by woesss** [comment]
@Indra2108 It depends on the device. And on Android 5.0 and above, both options can be enabled.
