### ISSUE TITLE
Hope to be able to add instant archiving function

### ISSUE THREAD

**Issue by 2929490899** [nikita36078/J2ME-Loader#522]
English, please.

_Originally posted by @amarcioz in https://github.com/nikita36078/J2ME-Loader/issues/519#issuecomment-495902243_

**Comment by nikita36078** [comment]
Do you mean a save state feature? It's isn't possible to implement in this emulator.

**Comment by 2929490899** [comment]
> 你是说保存状态功能吗？在这个模拟器中不可能实现。

May I ask why?

**Comment by 2929490899** [comment]
> 你是说保存状态功能吗？在这个模拟器中不可能实现。

Can I ask why

**Comment by 2929490899** [comment]
> 你是说保存状态功能吗？在这个模拟器中不可能实现。

may i know the reason.please

**Comment by 2929490899** [comment]
> Do you mean a save state feature? It's isn't possible to implement in this emulator.

may i know the reason.please

**Comment by 2929490899** [comment]
> Do you mean a save state feature? It's isn't possible to implement in this emulator.

can you tell me why

**Comment by 2929490899** [comment]
> Do you mean a save state feature? It's isn't possible to implement in this emulator.

can you tell me why？

**Comment by nikita36078** [comment]
J2ME Loader doesn't emulate hardware, so it can't save the CPU/RAM state.

**Comment by 2929490899** [comment]
> J2ME Loader doesn't emulate hardware, so it can't save the CPU/RAM state.

ok
