### ISSUE TITLE
The Burnout game closes when you press Back

### ISSUE THREAD

**Issue by jack1432** [nikita36078/J2ME-Loader#527]
**Emulator version:**
1.4.9-play

**Game version:**
4.3.1

**Game resolution:**
240x320

**Device:**
Samsung Galaxy J5 Pro

**Android version:**
8.1.0
**Description of the issue:**
!When you try to access the common settings in the game main menu by pressing the back button, the game closes and the emulator returns to the initial screen with the following message.
![Screenshot_20190527-113501_J2ME Loader](https://user-images.githubusercontent.com/36806488/58426900-4db85b00-8074-11e9-9240-bc760b36f80a.jpg)

**Comment by nikita36078** [comment]
Select Menu->Save log, and send a log file from J2ME-Loader/log.txt

**Comment by jack1432** [comment]
[log.txt](https://github.com/nikita36078/J2ME-Loader/files/3224498/log.txt)

**Comment by jack1432** [comment]
Done

**Comment by nikita36078** [comment]
Have you enabled hardware acceleration?

**Comment by amarcioz** [comment]
No meu celular funciona sem problemas. Versão 4.3.21 que baixei do site dedomil.

**Comment by jack1432** [comment]
> Você ativou a aceleração de hardware?

Not

**Comment by jack1432** [comment]
> No meu celular funciona sem problemas. Versão 4.3.21 que baixei do site dedomil.

@amarcioz I tested the version (4.3.21) you mentioned and for some reason the error did not happen the first time I pressed Back, but by repeating this several times the same error ended up happening.

**Comment by nikita36078** [comment]
Does it happen only in Burnout? I have seen this error before, and it usually doesn't appear in some specific places. Seems like it's an Android internal error, so I can't fix it.

**Comment by AdityaMH** [comment]
Only happen when press "back" button right?
What happen if you pressed "recent" button?

**Comment by Indra2108** [comment]
Works fine on my Device, Samsung SM-G313HZ (Android 4.4.2 KitKat)
![cmmnstting1](https://user-images.githubusercontent.com/47787767/58525418-df9ba180-81f5-11e9-8ba1-41445145159d.png)
![cmmnstting2](https://user-images.githubusercontent.com/47787767/58525433-e7f3dc80-81f5-11e9-8e2b-e4b512cc2299.png)

Looks like you must Enable HW Acceleration
![setting0](https://user-images.githubusercontent.com/47787767/58525485-1a9dd500-81f6-11e9-8e14-bbe7f8f49c76.png)

**Comment by jack1432** [comment]
> Does it happen only in Burnout? I have seen this error before, and it usually doesn't appear in some specific games. Seems like it's an Android internal error, so I can't fix it.

I understand
