### ISSUE TITLE
Can you join the installation function of selecting multiple jar applications?

### ISSUE THREAD

**Issue by 2929490899** [nikita36078/J2ME-Loader#528]
**Emulator version:**

**Game version:**

**Game resolution:**
``(For example, 240x320 or 640x360)``

**Device:**
``(For example, Samsung Galaxy S7)``

**Android version:**

**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``

**Comment by Indra2108** [comment]
Looks like Duplicate of #482

**Comment by 2929490899** [comment]
> 看起来像重复的#482

yes

**Comment by 2929490899** [comment]
> Looks like Duplicate of #482

Yes

**Comment by nikita36078** [comment]
I'm planning to add it in the one of the next releases.
