### ISSUE TITLE
RISK Error d

### ISSUE THREAD

**Issue by Indra2108** [nikita36078/J2ME-Loader#529]
**Emulator version:**
1.4.9

**Game version:**
1.12.86

**Game resolution:**
320x240

**Device:**
Samsung G313HZ

**Android version:**
4.4.2 KitKat

**Description of the issue:**
When I Press "START" After finishing setting the game, suddenly an error message appears, "error d"
![Screenshot_2019-05-30-08-14-56](https://user-images.githubusercontent.com/47787767/58602000-52b81d00-82b5-11e9-8db9-57ddff834b52.png)

File Game : 
[RISK_NokiaE71_320x240.zip](https://github.com/nikita36078/J2ME-Loader/files/3235092/RISK_NokiaE71_320x240.zip)

The Log
[log.txt](https://github.com/nikita36078/J2ME-Loader/files/3235094/log.txt)

**Comment by AdityaMH** [comment]
Try another version, 240×320 for example. For me, working fine.

**Comment by Indra2108** [comment]
Thank you, 
![Screenshot_2019-05-30-14-32-10](https://user-images.githubusercontent.com/47787767/58617354-19e66b00-82ea-11e9-9735-5103a04c2224.png)
