### ISSUE TITLE
Gameloft's NOVA3 second level graphical corruption

### ISSUE THREAD

**Issue by stranno** [nikita36078/J2ME-Loader#530]
Latest J2ME-Loader build.
NOVA3 1.1.9
Sony Ericsson K800i version
Nvidia Tablet K1 device
Android 7.1

Game gets totally messed up after the first level.

https://gfycat.com/welllitweightyindigowingedparrot

**Comment by amarcioz** [comment]
Working right here. Try to play another version. Games for Sony Ericsson give problems.

**Comment by stranno** [comment]
> Working right here. Try to play another version. Games for Sony Ericsson give problems.

Yes, i guess. But it is the best version of the game, and it works, not a Mascot Cap game and it can be fixed. So its definitely an issue.

**Comment by nikita36078** [comment]
Hmm, after I pressed 5 in the final dialog, the first level was finished, no glitches at all. I guess you have seen it multiple times?

**Comment by stranno** [comment]
Just happened me once, i thought it was a J2ME bug. I will try it again. Coul be a game bug, there are newer versions i think.

**Comment by nikita36078** [comment]
Looks like a random game bug, so I close the issue.
