### ISSUE TITLE
[Bug] Monopoly World

### ISSUE THREAD

**Issue by kyaros** [nikita36078/J2ME-Loader#531]
**Emulator version:1.5.0**

**Game version:4.17.3**

**Game resolution: 240x320**

**Device: LG Leon**

**Android version:6.0**

**Description of the issue: The game freezes in this part when touching the properties
![Screenshot_2019-06-02-11-47-02](https://user-images.githubusercontent.com/50189701/58769193-f0903e00-857a-11e9-9aba-9b6ad67b7332.png)
But if I touch decline and then no the game does not get stuck**

**Comment by amarcioz** [comment]
Is it touchscreen? I did not find this version to download. The non-touchscreen version I tried, worked well.

**Comment by kyaros** [comment]
yes it's touch
if there is no problem I can pass that version

**Comment by nikita36078** [comment]
Any updates? I haven't found the bugged version back then, so I'd like to know if the issue is still relevant.
