### ISSUE TITLE
Rollercoaster Revolution 99 Tracks bug

### ISSUE THREAD

**Issue by AdityaMH** [nikita36078/J2ME-Loader#534]
Emulator version: 1.5.0
Game version: 1.0.9
Game resolution: 240×320

1. When cart crashed and show prompt to restart, music won't stop playing.
In original phone and previous version, music stopped when prompt restart level showed and music play again when choose them.

2. When playing at third times or restarting level twice. Game become mute completely until exit the game.

**Comment by nikita36078** [comment]
Fixed
