### ISSUE TITLE
Zombie Infection crashes on start

### ISSUE THREAD

**Issue by peta9** [nikita36078/J2ME-Loader#535]
**Emulator version:**
1.5.0

**Game version:**
Any version higher than 1.0.1 (yes, all tested)

**Game resolution:**
240x320

**Device:**
Lenovo Tab 2 X30F

**Android version:**
6.0.1

**Description of the issue:**
The game shows a blank screen and does not start at all.

**Screenshot:**
![Screenshot_20190612-195915](https://user-images.githubusercontent.com/44788763/59360009-0b1da080-8d4d-11e9-9628-523a8e06d98b.png)

**Comment by amarcioz** [comment]
Normal here. version 1.0.2
Samsung gran prime Android 4
![Screenshot_2019-06-12-11-50-52](https://user-images.githubusercontent.com/35005836/59362168-60d05980-8d09-11e9-9af5-36f0866862a5.png)
![Screenshot_2019-06-12-11-51-25](https://user-images.githubusercontent.com/35005836/59362194-69c12b00-8d09-11e9-9aa1-4b169f6a15df.png)

**Comment by Indra2108** [comment]
Try to download on other site

**Comment by nikita36078** [comment]
I know about this bug, but it seems to be impossible to fix. This game works only on Android 4.0-4.4, 7.0+.
