### ISSUE TITLE
Samurai Jack Samurai Showdown unplayable

### ISSUE THREAD

**Issue by jasper1412** [nikita36078/J2ME-Loader#542]
**Emulator version:**
1.5.0-open

**Game version:**
1.0.2

**Game resolution:**
``176x220``

**Device:**
``Redmi 5A``

**Android version:**
7.1.2

**Description of the issue:**
Just unplayable, killing the activity instantly. Midlet tested on java phone and plays fine, tried it also on another emulator, still fine.

[log.txt](https://pastebin.com/2wkZvXsK)

**Comment by amarcioz** [comment]
This game works well for me.

Samsung Gran Prime Duos Android 4.4.4

![Screenshot_2019-07-01-16-41-27](https://user-images.githubusercontent.com/35005836/60462573-0e0b0300-9c20-11e9-8f78-957f07fc7c93.png)

**Comment by amarcioz** [comment]
What is this other emulator?

**Comment by jasper1412** [comment]
its kemulator on pc, yeah i remember this game works on my old lollipop device, but now crashing in nougat.

**Comment by jasper1412** [comment]
now works on 1.5.1-open
