### ISSUE TITLE
Soul of darkness graphics bug

### ISSUE THREAD

**Issue by fireclouu** [nikita36078/J2ME-Loader#543]
**Emulator version:**
1.5.0-open

**Game version:**
1.3.2

**Game resolution:**
``240x320``

**Device:**
``Redmi 5A``

**Android version:**
7.1.2

**Description of the issue:**
![Screenshot_2019-07-04-00-59-41-374_ru playsoftware j2meloader](https://user-images.githubusercontent.com/22563129/60755905-0a64eb00-a029-11e9-958a-459217544e58.png)

As you can see here, there is a missing chandelier sprite should be constantly or in fixed position aligned on the white metal bar image swinging where user cannot be modified whatsoever, it acts as a platform to transport character onto a high ledge. With this bug, you simply cannot make progress with it (unless relaunching the game and executing your way perfectly without any restarts).

To reproduce this one is not quite clear to me but based on what I've observed is that you need to turn on the sound, make new game and after falling on first chandelier, enter the room on the left to retrieve pink crystal then make your way to get the treasure on right, go straight to the eye and let your character die then restart (in this part youll be respawned at checkpoint right below on the same room). Then patiently wait on the room below with swinging chandelier, let the music loop I think 15-20 times (or more) and let these fog or smoke effect pass 7-10 times. Roam back and forth on that same spot and continuosly swing the sword on ground and midair.

[log.txt](https://pastebin.com/a4Fe2jDe)

**Comment by oatmeal01** [comment]
try v1.3.1 N95 
<img height="300" width="176" src="https://user-images.githubusercontent.com/36059629/69965332-fc22e880-154e-11ea-927f-047b31d49463.png"/>

**Comment by clouu27** [comment]
@oatmeal01 hi! my version 1.3.2 also works fine :) , but when you perform what I've described above, maybe youll get the same error. Its just a strange/rare bug that needs many conditions to trigger, whether introduced on the game itself or in emulator,  and well, needs to be fixed since some programs may (or may not) benefit if this resolved.
