### ISSUE TITLE
Audio bug in some games

### ISSUE THREAD

**Issue by th0rig** [nikita36078/J2ME-Loader#545]
**Emulator version:**
J2me loader v1.5.0 open

**Game version:**
angry bird v.1.2.4 and other games

**Game resolution:**
``(For example, 240x320 or 640x360)``
240x320 touch screen version

**Device:**
``(For example, Samsung Galaxy S7)``
Smartfren andromax Es

**Android version:**
custom rom based android 6.0.1

**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
There are sfx bug in various games almost all my games suffer this issue the bug is there is sound crackling acompined with messed sound when sfx occur the bug happen in game that use wav format for sfx audio file midi file run just fine when i play wav file generated by the emulator the sound playback same as in the game is this audio decoder `problem?`

what should happen?
the sfx should play normal rather than crackling noise.
And here the log file

https://drive.google.com/file/d/1kCM8cVJ8nlvfFgPwVN_dTmi3suxyTakb/view?usp=drivesdk
After further investigation the problem not only sfx but in bgm as well as long as the audio file in wav format but this problem exist on some version and on other hand some other version run just fine despite using wav file for audio format for some strange reason and the log file say qc mediaplayer not present what is that? Is that normal?
I deeply apologize for terrible gramar english isn't my native language
I realy need help here i dont know exactly the problem here.
Is this runtime issue?(unlikely because i changed that and no avail) is this audio av offload issue? Is this audio decoder issue? Or is this audio latency issue? Oh man my brain is freezing right now dont know what to do i am not an deveploper so i can only guessing.
Please i need help this is the reason create github account.

**Comment by th0rig** [comment]
Edit:
My bad sound glitch only happen for game that use wav format(both sfx  and bgm sound) after i did more testing the other version of game that work fine that i think use wav format actualy use amr for sfx and bgm beside audio file in midi format i think so the main problem is game that use wav format  i've tried different version of the emu but the result is the same because the problem is not the emu but Os/device i use,,,i wish the problem fixable sorry for terrible gramar and make you confused.

**Comment by th0rig** [comment]
Well i will close this since i have no answer i dont know if the developer realy busy or my problem hard or impossible to fix well device specifict problem way harder to fix than the other... i wish the problem go  away by itself after several update or waiting new j2me emulator that made from scratch

**Comment by nikita36078** [comment]
I haven't worked on the project last month, I'll check this issue soon.

**Comment by th0rig** [comment]
Tanks for your hardwork but the problem not solved in newer version btw tanks for responding to my issue despite i using custom on my phone, according to rom cooker it based original AOSP
Here the gameplay footage of angry bird in new version
https://youtu.be/9VYgQvEWOzw
I should do that earlier, well never
Again thanks for your hardwork and take your time to improve the emulator no need to hurry.
Cheers :-D

**Comment by th0rig** [comment]
Sadly this issue not fixed on latest version i'm using v1.5.3 btw maybe the problem caused by audio file that compressed i think beside built in media codec/player problem what do you think? i want to avoid to flash new Rom if that possible i dont want to lost important data because this issue to make my game play normaly,,,my mother's phone doesn't have this issue even without QC media player. i'm wondering what the cause,,,, of course not because of custom they are created using android source code anyway. my old phone that run custom rom based kitkat  can run any java games without problem it's support QC Mediaplayer btw,, so missing QC media player the cause of this bug,, hmm not likely my mother's phone missing QC Mediaplayer support but still able to play java games in j2me loader without problem,, i guess the problem still mystery then,, well i'll wait patienly.
