### ISSUE TITLE
Shadow Of Egypt 3D

### ISSUE THREAD

**Issue by amarcioz** [nikita36078/J2ME-Loader#546]
Emulator version: 1.5.0

Game version: 1.0

Game resolution: 240x320

Device: Samsung Galaxy J5 

Android version: 6

Description of the issue:Impossible to play. The game screen keeps spinning. Vídeo:
https://youtu.be/g1iHW6rrA9k

But in this video the game works well on J2ME Loader v1.2.8.7:
https://youtu.be/6NteKo5AJlM

Game: 
[SofE3D](https://www.mediafire.com/download/kqfom93hur8dqhk)

Text Log: 
[log.txt](https://github.com/nikita36078/J2ME-Loader/files/3439337/log.txt)

**Comment by amarcioz** [comment]
Continue with screen spinning in version 1.5.1

**Comment by oatmeal01** [comment]
Turn of the sensor. Mine keeps spinning too until i turned off the sensor from the game settings.

![Screenshot_2019-12-03-11-18-26](https://user-images.githubusercontent.com/36059629/70017721-c87fa700-15be-11ea-9601-06fb4a50d7b4.png)

**Comment by amarcioz** [comment]
> > Continue with screen spinning in version 1.5.1
> 
> Turn off the sensor. Mine keeps spinning too until i turned off the sensor from the game settings. Im using J2Me Loader v1.5.5.
> 
> ![Screenshot_2019-12-03-11-18-26](https://user-images.githubusercontent.com/36059629/70017721-c87fa700-15be-11ea-9601-06fb4a50d7b4.png)

Thank you.
