### ISSUE TITLE
Ancient Empires II bug

### ISSUE THREAD

**Issue by Diegoddk** [nikita36078/J2ME-Loader#547]
**Emulator version:**
1.5.0-play

**Game version:**
1.0.2

**Game resolution:**
240x320

**Device:**
``(For example, Samsung Galaxy S7)``
Huawei P smart
**Android version:**
8.0
**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
Slow rendering of the intro glu logo.

**Comment by nikita36078** [comment]
Does it render slower than [that](https://dump.video/i/PDzszT.mp4)?

**Comment by Diegoddk** [comment]
sorry for the late response, yes it is:
[https://vimeo.com/351740697](url)

**Comment by nikita36078** [comment]
Try this version - maybe it will work faster
https://mega.nz/#!gctxmKYR!pSHN5UU5YU8478uHCPMF0lhBUxFWXpZk1Os6xgbCV6w

**Comment by Diegoddk** [comment]
still the same,  here's a full load to the main menu, everything else looks normal:
[https://vimeo.com/352766964](https://vimeo.com/352766964)

pd:
emulator version 1.4.0 with android 4.4.2 phone, the game runs normal.

**Comment by nikita36078** [comment]
Try these two versions
https://mega.nz/#F!IEtFGa5I!I5kwSZGIgiz2CUWh2doyrw

**Comment by Diegoddk** [comment]
Nothing changes in both. Also, tried the 1.4.0 version in my 8.0 phone and the same happened, I think this is a specific device/android version issue

**Comment by oatmeal01** [comment]
**Game Version:** 1.0.2
**Device:** OS 5.0 PowerVR
**Video:** <a href="https://drive.google.com/uc?authuser=0&id=12XNQK3YkchPgK7faV8YvM_iZRFDylTwa&export=download"/>Download</a>

Try the ff. config. If still slow, try to uncheck filter and check the Hardware Acceleration.
![Screenshot_20191203_110249](https://user-images.githubusercontent.com/36059629/70017209-80ac5000-15bd-11ea-8188-3e2da5fadcf5.png)

**Comment by nikita36078** [comment]
Should work fine now, it was an Android 8.0 bug
