### ISSUE TITLE
Opera Mini 4 not launching on Android 4.4 devices. Works on 5.0 ones though.

### ISSUE THREAD

**Issue by Near1980** [nikita36078/J2ME-Loader#549]
**Emulator version:**
1.5.0-open
**Game version:**
https://github.com/sergiolopes/operamini-offline/blob/master/opera-mini-4.4.28684-advanced-en-us.jar
**Game resolution:**
Fails with any.
**Device:**
Fails on Samsung phones with Android 4.4.2 and Android 4.4.4
Works on BQ Edison 3 Tablet with Android 5.0
**Android version:**
Tested on Android 4.4.4 and 4.4.2
**Description of the issue:**
Midlet fails to start on Android 4.x devices, while working on Android 5.0
Attached log, also: https://openload.cc/d8r59c1dn5/log_txt

**Comment by nikita36078** [comment]
duplicate #334
It seems to be connected with the convertation, but I still don't know how to fix it. By the way, it works fine on Android 7.0 and higher.
