### ISSUE TITLE
Rotation bug

### ISSUE THREAD

**Issue by skelletR** [nikita36078/J2ME-Loader#55]
I have Xperia z5 nougat 7.1.1..  When I go and open one game and set resolution when rotation my phone in landscape mode the only I see is black screen and after all games inside the emulator don't work and must delete the emulator

**Comment by nikita36078** [comment]
There are some issues with rotation/minimizing, I will try to fix them in the next version.

**Comment by skelletR** [comment]
Thanks for answer

**Comment by AdityaMH** [comment]
I test using lollipop its work correctly. but if i play landscape games, i must turn on auto-rotate and turn off again when i stopping a game.

**Comment by skelletR** [comment]
And one another inside in game when is touch screen and when not show the button.. When put in the settings of the game not show the button not working.. Always show it

**Comment by AdityaMH** [comment]
you need clear cache data to work a changing "show keypad".

**Comment by skelletR** [comment]
Thanks

**Comment by skelletR** [comment]
![_20171215_145626](https://user-images.githubusercontent.com/25982450/34043098-36236668-e1a8-11e7-83e9-1cbb89b3359a.JPG)
![_20171215_145535](https://user-images.githubusercontent.com/25982450/34043103-3cfa9a88-e1a8-11e7-9d9f-e68fa370d280.JPG)
How can fill this white frame?  Or a black background?

**Comment by nikita36078** [comment]
Check the "background" button in emulated app settings.
P.S. I know about keyboard bug, I will try to fix it in next release.

**Comment by skelletR** [comment]
I try thanks for the answer

**Comment by AdityaMH** [comment]
game/app can't flip screen (240x320 to 320x240) except they support full screen. i still using that method before update "screen rotate button".

**Comment by nikita36078** [comment]
I fixed rotation bug in the last test version.
