### ISSUE TITLE
Could you please add the rocker to play the RPG game more convenient.

### ISSUE THREAD

**Issue by xusonfan** [nikita36078/J2ME-Loader#550]
**Emulator version:**

**Game version:**

**Game resolution:**240*320
``(For example, 240x320 or 640x360)``

**Device:**vivo z5x
``(For example, Samsung Galaxy S7)``

**Android version:**9.0

**Description of the issue:**I am playing the game with landscape mode and it is more convenient to have a rocker to move the character.So could you please add a rocker??Thank you very much!!!

![360截图20190802220012335](https://user-images.githubusercontent.com/20855706/62375464-f1405300-b570-11e9-93da-506b3864652d.jpg)

``(What's the problem? - Screenshots showing the issue if applicable)``

**Comment by Indra2108** [comment]
Do you mean Analog Controller?

**Comment by xusonfan** [comment]
> Do you mean Analog Controller?

yes,just like the picture. I do not know how to discribe it but just like the moba games in android。we could move the character without move the finger out the screen.

https://github.com/yhl714387953/KingOfGlory

**Comment by amarcioz** [comment]
In PPSSPP it is possible to play like this.
![Screenshot_20190803-175858](https://user-images.githubusercontent.com/35005836/62417029-36c65400-b635-11e9-8d78-73ba6efc0c24.png)

**Comment by nikita36078** [comment]
That's already in the issues list, #329, so I'm closing this one as duplicate.
