### ISSUE TITLE
Outland 3d 

### ISSUE THREAD

**Issue by amarcioz** [nikita36078/J2ME-Loader#552]
**Emulator version:**
1.5.0

**Game version:**
1.00.42

**Game resolution:**
240x320

**Device:**
Samsung Galaxy J5

**Android version:**
6

**Description of the issue:**
When this part arrives the game freezes.

![Screenshot_20190806-085716](https://user-images.githubusercontent.com/35005836/62538300-fb4ca500-b841-11e9-8c04-5fec8e8c3514.png)

**Comment by nikita36078** [comment]
Could you share your .jar? I tried a few versions and all of them work fine.

**Comment by amarcioz** [comment]
> Could you share your .jar? I tried a few versions and all of them work fine.

I downloaded the game from this site and none work.
[http://dedomil.net/games/2750/screens](http://dedomil.net/games/2750/screens)

Vídeo [https://youtu.be/8X8ecv4jFf8](https://youtu.be/8X8ecv4jFf8)

**Comment by amarcioz** [comment]
Now works on version 1.5.1

**Comment by 1234Sameer** [comment]
It still does not work on my phone. Android 5.0

**Comment by 1234Sameer** [comment]
It looks like if I turn sound on, this happens. With sound turned off, the game works fine.
@amarcioz can you test on your phone?

**Comment by amarcioz** [comment]
@1234Sameer Only works with audio off.

**Comment by nikita36078** [comment]
Yes, it was the sound issue, fixed now.
