### ISSUE TITLE
Honey cave 3d

### ISSUE THREAD

**Issue by carlusanbar1993** [nikita36078/J2ME-Loader#555]
**Emulator version:**
1.5.1

**Game version:**
1.3

**Game resolution:**
240x320

**Device:**
``Samsung Galaxy Xcover 2``

**Android version:**
4.1.2
**Description of the issue:**

The game starts, but does not show the stage.
![Screenshot_2019-08-19-16-17-30](https://user-images.githubusercontent.com/45405269/63292813-ec7fdc80-c29c-11e9-8011-1cbe28ffec07.png)

**Comment by Indra2108** [comment]
Sony 3D games generally use Mascot Capsule 3D which J2ME Loader does not support it.

**Comment by nikita36078** [comment]
Fixed
