### ISSUE TITLE
Option to enlarge game screen in landscape mode

### ISSUE THREAD

**Issue by Deivmsr** [nikita36078/J2ME-Loader#559]
Nikita, Gameloft k800i model 240x320 games have the best graphics, but when the phone is landscape, the screen is small on devices with large screens, as in my Note 8, for example. Could there not be an option to increase the screen size in landscape mode without causing distortion in the game? I already tried to do this using the game dimension tool, but it causes distortion in the games.
This is just a suggestion. If you think it is not possible you can close this issue.

**Comment by nikita36078** [comment]
The emulator can't provide multiscreen support, but you can experiment with the screen width (for example, set 480*320 instead of 240*320). If game supports multiscreen, it will scale correctly.

**Comment by Deivmsr** [comment]
Ok I understand. I will close this question.
