### ISSUE TITLE
Add into f-droid

### ISSUE THREAD

**Issue by KOLANICH** [nikita36078/J2ME-Loader#56]

**Comment by nikita36078** [comment]
This project isn't stable enough to release it at any markets now, I will think about it later.

**Comment by KOLANICH** [comment]
It is possible to mark it as unstable in f-droid.

**Comment by jan-kleks** [comment]
Maybe you could find some nice testers there?

**Comment by nikita36078** [comment]
Now I have enough testers :-)

**Comment by hotlittlewhitedog** [comment]
Please don't provide illegal roms with your emulator.

**Comment by jasper1412** [comment]
java midlets, not rom.

**Comment by nikita36078** [comment]
@hotlittlewhitedog, so warez links in the issues should be deleted, right? Or it is only about the app itself?

**Comment by jasper1412** [comment]
I'll take it down on #96 :)

**Comment by JuniorJPDJ** [comment]
And now can it be added to F-Droid? :D

**Comment by nikita36078** [comment]
An inclusion request stucked there, so I'm just waiting now :)

**Comment by KOLANICH** [comment]
Here is the link to the thread: https://gitlab.com/fdroid/fdroiddata/merge_requests/2934

**Comment by nikita36078** [comment]
Done! 
https://f-droid.org/app/ru.playsoftware.j2meloader
