### ISSUE TITLE
NullPointerException javax.microedition.media.Player.deallocate (Orcs and Elves)

### ISSUE THREAD

**Issue by retrobits** [nikita36078/J2ME-Loader#560]
**Emulator version:**
1.5.3

**Game version:**
Orcs and Elves, 1.3.38

**Game resolution:**
240x320

**Device:**
Samsung Galaxy Note 3

**Android version:**
9

**Description of the issue:**
![Screenshot_20190905-090716_J2ME_Loader](https://user-images.githubusercontent.com/2013534/64378205-07628880-cfe1-11e9-99f7-04b8417e2921.png)

[data.zip](https://github.com/nikita36078/J2ME-Loader/files/3581088/data.zip)

http://retrobits.net/jar/OrcsAndElves_v1_3_38.jar

to repro this issue, use the attached data folder, start the game with sound.  Open the green door ("To Throne Room") by tapping "F" then tap DPAD-UP then "F"

**Comment by retrobits** [comment]
to repro this issue, use the attached data folder, start the game with sound.  Open the green door ("To Throne Room") by tapping "F" then tap DPAD-UP then "F"

**Comment by MCPE-Beta1177** [comment]
Me Too, i got several gliches and issues in this emulator

**Comment by nikita36078** [comment]
Fixed
