### ISSUE TITLE
Compiling classes with J2ME SDK Mobile

### ISSUE THREAD

**Issue by Kouzeru** [nikita36078/J2ME-Loader#561]
**Emulator version:**
Current

**Game version:**
1.0

**Game resolution:**
Any

**Device:**
Samsung Galaxy J7

**Android version:**
9.0.0
**Description of the issue:**
I'm trying to compile Meboy-F, but it fails due to:
![Screenshot_20190909-233737_Trebuchet](https://user-images.githubusercontent.com/46141631/64545904-37e95000-d35c-11e9-8405-f9daf7947ff8.png)

Required files: [sdcard.zip](https://mega.nz/#!N6BkAAxK!P_EeTgAlJpQtwufZd-UUqZuIVyg7s5vG8SYKLE2nBKw) 

Place /other in /sdcard, required JAR also included in sdcard.zip with their data. In order to reproduce, in J2ME SDK Mobile, Open Project "Meboy", go to Menu, Build the Project, restart to continue compiling process.

**Comment by nikita36078** [comment]
Fixed. However you still can't compile it because J2ME SDK Mobile doesn't have a Bluetooth API support.
![Screenshot_1569151629](https://user-images.githubusercontent.com/3035571/65386493-18332e00-dd45-11e9-8aad-fbc3ea13fa79.png)

**Comment by Kouzeru** [comment]
Thank you for the fix anyway.
I aware that there are pro version of J2ME SDK Mobile which supports more API (including bluetooth). Meboy itself has one single issue of MediaPlayerAPI in J2ME loader. I'll post about it later.
