### ISSUE TITLE
The Lord Of The Rings - Legends (S40v2-N6230) - Bug

### ISSUE THREAD

**Issue by Lanz89** [nikita36078/J2ME-Loader#563]
Emulator version: 1.5.3
Game version: 1.7.9
Game resolution: 128x128
Device: Realme Pro 2
Android version: 9
-------------

Link: http://dedomil.net/games/5599/screen/2

Issue: Characters sprite freeze at chapter 2 (like in the picture below). Can't move, only can jump.

https://imgs.info/i/c8a3v

**Comment by nikita36078** [comment]
Seems like device-specific issue, can't reproduce it. I finished stage 2 without any visible problems.

**Comment by Lanz89** [comment]
I found the cause of this problem. It because the screen resolution. This game only can be played with its original resolution (128x128)...
