### ISSUE TITLE
Lord Of The Rings Trilogy 

### ISSUE THREAD

**Issue by Lanz89** [nikita36078/J2ME-Loader#566]
**Emulator version: 1.5.3
Game version: 1.0.2
Game resolution: 128x128
Device: Realme Pro 2
Android version: 9**

......................................
Link: http://phoneky.com/games/?id=j4j5278

Issue: LEFT and RIGHT SOFT KEYS are not working. So, can't return or proceed to the next levels...

![Screenshot_20190921-033929](https://user-images.githubusercontent.com/46138298/65354681-b4184900-dc22-11e9-98e9-b53aae3ff12b.png)
![Screenshot_20190921-034126](https://user-images.githubusercontent.com/46138298/65354683-b4b0df80-dc22-11e9-9612-efffea6f6b76.png)

**Comment by woesss** [comment]
This version of the game is for Motorola phones and therefore uses non-standard key-codes. But the emulator has not yet implemented the setting of key-codes (already requested #376). Try searching other version of the game (if possible).

**Comment by Lanz89** [comment]
Oh, thanks for the answer...

But, only this version of the game is available. So just can wait for the implementation of Motorola phone keypad support.

**Comment by nikita36078** [comment]
Closed as duplicate
