### ISSUE TITLE
Ridge Racer crashes

### ISSUE THREAD

**Issue by Panderner** [nikita36078/J2ME-Loader#568]
**Emulator version:**
1.5.3

**Game version:**
1.0.7 

**Game resolution:**
(any resolution)

**Device:**
(Realme C2)

**Android version:**
Android 9 Pie

**Description of the issue:**
When I trying to launch Ridge Racer the emulator crashes

**Comment by nikita36078** [comment]
I found only one version 1.0.7 of this game and it doesn't crash at all. However, this version uses Mascot Capsule API, so maybe this can be a reason.

**Comment by Panderner** [comment]
No. I'm using Nokia version

**Comment by nikita36078** [comment]
Could you share it?

**Comment by Panderner** [comment]
Also happens on non sony phone versions

**Comment by Panderner** [comment]
http://dedomil.net/games/3258/screen/8
Here

**Comment by nikita36078** [comment]
Install the game from jad file, it should work fine.

**Comment by Panderner** [comment]
It's works! Thank you
