### ISSUE TITLE
Ir_DAroo 2 - Can't patch

### ISSUE THREAD

**Issue by 3j9fkyahunqoxwqu** [nikita36078/J2ME-Loader#570]
**Emulator version:**
1.5.3

**Game version:**
2.0

**Game resolution:**
``(For example, 240x320 or 640x360)``

The jar app doesn't even open, the j2me loader says can't patch.

**Device:**
``(For example, Samsung Galaxy S7)``
Honor 10 lite

**Android version:**
9

**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``

The jar app doesn't even open, the j2me loader says can't patch.

This is the jar file:
https://upload.disroot.org/r/BpLneD7f#yB/jd6znGf0/yKVSYmuRnGkzmGt/S2hh707UlfSEq3o=

**Comment by MCPE-Beta1177** [comment]
it's nikita's fault

**Comment by MCPE-Beta1177** [comment]
Nikita, why you have so many issues to this emulator

**Comment by woesss** [comment]
@MCPE-Beta1177, Seriously? Then help - this is an open source project, anyone can make improvements and suggest applying them. And this is a freeware application - the developer spends on him as much time as he considers possible.

**Comment by woesss** [comment]
@3j9fkyahunqoxwqu, You can repack this jar using the zip archiver - this will solve the installation problem.

**Comment by 3j9fkyahunqoxwqu** [comment]
@woesss
Thank you very mush 
It worked. :)

**Comment by MCPE-Beta1177** [comment]
@woesss, where is the new version of 1.5.4! If you know where is the new version, i'll support you if you know where is the new version

**Comment by MCPE-Beta1177** [comment]
@woesss, i want this emulator to be fixed because people are having issues with this emulator! I know the developer was too lazy to fix all of these issues, but how do i change the system properties on j2me loader

**Comment by nikita36078** [comment]
Fixed
