### ISSUE TITLE
Missing sounds

### ISSUE THREAD

**Issue by AndyKrozz** [nikita36078/J2ME-Loader#571]
**Emulator version:**
All

**Game version:**
All

**Game resolution:**
All

**Device:**
Samsung Gt-S7275R

**Android version:**
4.2.2

**Description of the issue:**
Hi Nikita, you could solve the problem of midi effects among others, for example, in gangstar 2 the sound of explosions does not sound like in the other games, if you solve this problem I will give you 5 stars in the google games store.

**Comment by amarcioz** [comment]
But sound effects vary from game to game and from version to version.

**Comment by MCPE-Beta1177** [comment]
Yeah, i tried to High Up The Volume using Speaker Boost, but it doesn't allow me to play Bounce Tales at The same boost, which is 27%!
nikita, if you solve this problem, i will give you 5 stars in google play store

**Comment by AndyKrozz** [comment]
yes, but you don't hear the midi effects at all

**Comment by MCPE-Beta1177** [comment]
@AndyKrozz i don't hear the midi effects that Bounce Tales Has it while i'm playing it! If nikita add Speaker Boost Support, i will give this app 5 stars if he add Speaker Boost Support

**Comment by oatmeal01** [comment]
Audio/Sound Effects may vary from different versions of the game/device model.

**Here's an example:**

**Ghost Recon Future Soldier (240x320)**
1. <a href="http://dedomil.net/games/559/download-jar/6748">Nokia 6280</a>
2. <a href="http://dedomil.net/games/559/download/44036">N95</a>

Check the two games above, the first one has sound effects while the second one has none. Both games are also tested using (PC) Kemulator v1.0.3 - Same Results.

Just a tip downloading 240x320 games, choose Nokia 6300, 6280 models. Most games from N73, N95 devices has audio bug. If you are downloading other resolutions try to download 2 different versions and compare audio or graphics.

**Comment by nikita36078** [comment]
After the latest update music should play fine in most games. Gangstar 2 has all sounds now.

**Comment by nikita36078** [comment]
Ghost Recon Future Soldier is fixed too
