### ISSUE TITLE
Speaker Boost Support For J2ME Loader

### ISSUE THREAD

**Issue by MCPE-Beta1177** [nikita36078/J2ME-Loader#574]
Hi nikita, if you reading this title, please Add Speaker Boost Support for J2ME Loader! I tried to increase my multimedia volume using Speaker Boost, but it does not Support Speaker Boost On Samsung, Including Hawaii smartphones!
For Example, i'm using Samsung Galaxy J4+, J2ME Loader, And Speaker Boost that it does not support volume booster because of the update

**Comment by nikita36078** [comment]
Duplicate

**Comment by MCPE-Beta1177** [comment]
@nikita36078 it's not a duplicate, it just an issue that j2me loader could not support speaker boost! Open it up pls

**Comment by MCPE-Beta1177** [comment]
@nikita36078 i have created this issue so hard, and then you close it for no reason! I'm just gonna create an issue and close it so you can't reopen it

**Comment by MCPE-Beta1177** [comment]
@nikita36078 i know it's duplicate, but we need speaker boost support!
if you never heard of this app, it boosts your phone volume, but don't go further above 30 or 40, just go to 27%
