### ISSUE TITLE
Add Game Store Server 

### ISSUE THREAD

**Issue by ahmadprayoxxsy** [nikita36078/J2ME-Loader#575]
**Emulator version:**
New

**Game version:**

All
**Game resolution:**
``(All)``

**Device:**
``(For example, Samsung Galaxy j7 2016)``

**Android version:**
8.1
**Description of the issue:**
``(Add server store games such as "wapshop.gameloft.com" and "ply.mob.org". So that people know where to Donload Java Games.)``

**Comment by nikita36078** [comment]
It's impossible to add `mob.org` since it's a piracy and I would be banned for that. I've checked out `wapshop.gameloft.com` and haven't found any java games there. Opera Mobile store has very few games and often redirects to the gameloft shop. I don't think there is any legit and good java store.

**Comment by MCPE-Beta1177** [comment]
@nikita36078 why java option was removed from mob.org

**Comment by MCPE-Beta1177** [comment]
@nikita36078 Why Java Games are removed from mob.org! I've checked out from mob.org, and then they removed it for no reasons

**Comment by ahmadprayoxxsy** [comment]
@nikita36078 
 Official website of Devloper Teamobi. And the game is also free. "http://world.teamobi.com/home-page.html"

**Comment by woesss** [comment]
@ahmadprayoxxsy, you propose adding a long list of sites by 5 games to the emulator and monitoring their relevance? I think it’s easier to add the item “Search games”, by clicking on which to open a browser with a search query, for example: ["j2me games download"](https://www.google.com/search?ei=BgO0XZnQHLD3qwH_vqGoBQ&q=j2me+games+download&oq=j2me+games+download&gs_l=psy-ab.3..0j0i22i30l3j0i22i10i30j0i22i30l5.7905.13027..14234...0.2..1.2344.8289.2-1j5-1j1j2j1j1......0....1..gws-wiz.......0i71.6Btw812FAfU&ved=0ahUKEwiZ66WZwLnlAhWw-yoKHX9fCFUQ4dUDCAs&uact=5)

**Comment by MCPE-Beta1177** [comment]
@nikita36078 dedomil.net is to be exact

**Comment by amarcioz** [comment]
The emulator cannot have links to download games as this would be piracy.  Anyone can search Google for "Download Java Games".

**Comment by MCPE-Beta1177** [comment]
@amarcioz go to the different website called dedomil.net to Download Java Games using J2ME Loader

**Comment by MCPE-Beta1177** [comment]
sorry, but they removed this option on mob.org!
you can't download symbian and java games, they removed it for no reason!
also wayback machine could not Exclude java.mob.org, dedomil.net has java games and other different catagories

**Comment by MCPE-Beta1177** [comment]
link: https://www.dedomil.net
