### ISSUE TITLE
Add N-Gage

### ISSUE THREAD

**Issue by MCPE-Beta1177** [nikita36078/J2ME-Loader#576]
Hey, if you reading this description, i would like you to Add NGage Support For J2ME Loader! So if you don't mind, Nokia N95 has NGage In The Menu so You Can Play Other Games! And i know it's a duplicate, so please don't say it otherwise! If you add NGage Support For J2ME Loader, i will give you 5 stars in the google play store

**Comment by AdityaMH** [comment]
Why you don't send this request to developer who working at N-GAGE project?

**Comment by MCPE-Beta1177** [comment]
@AdityaMH just because N95 Has NGage Store in the menu screen,  but what if he adds sis or sisx files to J2ME Loader

**Comment by nikita36078** [comment]
Adding support of the Symbian apps isn't that easy, it can take years, and actually there's already one Symbian emulator in the development - EKA2L1.

**Comment by MCPE-Beta1177** [comment]
@nikita36078 thank you for letting me know, but sis or sisx files does not work properly, But Jad or jar files is actually working for me, so that's why i created this issue, and then you closed it! So i must confess that sis or sisx files is not that easy to get
