### ISSUE TITLE
[bug] snowball fight

### ISSUE THREAD

**Issue by kyaros** [nikita36078/J2ME-Loader#578]
**Emulator version: 1.5.4**

**Game version: 1.0**

**Game resolution:**
``128x160``

**Device:**
``lg leon``

**Android version: 6.0**

**Description of the issue:**

![Screenshot_2019-11-01-23-21-56](https://user-images.githubusercontent.com/50189701/68064800-073fea00-fcff-11e9-918c-bf2142be7e5d.png)
after updating the last pixels below are missing as seen in the screenshot

sorry if i been`t update the monopoly bug, i've formatted the phone and i lost it

**Comment by nikita36078** [comment]
Fixed, I've added the forced fullscreen mode in the last update.
