### ISSUE TITLE
Is J2ME-Loader more stable on Android 9 than 7?

### ISSUE THREAD

**Issue by stranno** [nikita36078/J2ME-Loader#582]
I've been using J2ME-Loader in LineageOS 14 (Nougat) for Tablet K1 (former Shield Tablet) and, in some titles, the game freezes or the sound stops, skips and many other problems.

While the same games work perfectly fine in LineageOS 16 (Pie) for Xiaomi Redmi Note 7. Perfectly stable gameplay, proper sound, etc.

K1 has some roms in LineageOS 15, unfortunately drivers are not nearly as good as 14 and there's no hardware acceleration at all.

**Comment by ahmadprayoxxsy** [comment]
Probably because the Tegra GPU is incompatible.
The J2ME loader Emulator runs smoothly on Adreno and Mali GPUS

**Comment by nikita36078** [comment]
J2ME-Loader needs Android 7.0+ for stable work, so it's most likely the rom issue

**Comment by stranno** [comment]
I have tried other roms, including the stock one, and it doesnt seem to be a rom problem.

I guess it would be a GPU thing, it runs fine on Adreno, yes, on Note 7 and OPO 7T it works flawlessly.
