### ISSUE TITLE
1 Million Downloads For J2ME Loader

### ISSUE THREAD

**Issue by MCPE-Beta1177** [nikita36078/J2ME-Loader#584]
i have an announcement to make!
your app has reached to 1 Million Downloads

**Comment by AndyKrozz** [comment]
> ¡Tengo un anuncio que hacer! 
> su aplicación ha alcanzado 1 millón de descargas

Wow

**Comment by AndyKrozz** [comment]
> ¡Tengo un anuncio que hacer! 
> su aplicación ha alcanzado 1 millón de descargas

just wait to release version 1.5.5

**Comment by nikita36078** [comment]
Yeah, I'm glad that J2ME-Loader became so popular :)
