### ISSUE TITLE
About the install jars...

### ISSUE THREAD

**Issue by 1130381752** [nikita36078/J2ME-Loader#588]
**Emulator version:**1.5.5

**Description of the issue:**  --> we need "auto install" function <--
``Can you consider developing the function"auto install all the jars in the selected file dir", I find it's too slow to install them one by one``

**Comment by MCPE-Beta1177** [comment]
Add Auto install please

**Comment by AndyKrozz** [comment]
Yes very good

**Comment by nikita36078** [comment]
I'm planning to add the batch install feature in the future releases. Installing all files in the directory would be too slow and confusing for users.

**Comment by oatmeal01** [comment]
@nikita36078 installing jar file while minimizing can cause interruption to the installation, can you add a feature of installation to work in background.  thanks!
