### ISSUE TITLE
3D Formula Racing Error

### ISSUE THREAD

**Issue by RobertoR0** [nikita36078/J2ME-Loader#589]
**Emulator version:**
1.5.5-play

**Game version:**
1.0

**Game resolution:**
``240x320``

**Device:**
``Samsung Galaxy J5 Pro``

**Android version:**
8.1.0
**Description of the issue:**
3D Formula Racing closes when trying to start match.
![Screenshot_20191129-124221_J2ME Loader](https://user-images.githubusercontent.com/36806488/69880538-ec827600-12a8-11ea-9262-a0103c4f8704.jpg)

This appears after the game closes.

**Comment by MCPE-Beta1177** [comment]
This issue is wontfix or enhancement

**Comment by oatmeal01** [comment]
Same issue with Galaxy on fire, the game totally works. The only problem is when closing/exiting the game. Error detected will appear everytime i close the game.

**Comment by nikita36078** [comment]
Fixed
