### ISSUE TITLE
Missing project description, the list of not working games, and changelogs

### ISSUE THREAD

**Issue by jan-kleks** [nikita36078/J2ME-Loader#59]
Could you add the more detailed project description in English here, as well as the list of not working games, and changelogs that are present on the Russian forum, please?

**Comment by nikita36078** [comment]
Yes, I will add it later.

**Comment by WanderMax** [comment]
can you please take the .md file in GitHub into consideration?
it will better to check the unsupported game list update.

**Comment by nikita36078** [comment]
I use GDocs to allow users to add games to the list, so it can be updated faster than .md file on Github.

**Comment by AdityaMH** [comment]
But not all user can access GDocs. "UC Mini" user for example.
