### ISSUE TITLE
Volume Bug

### ISSUE THREAD

**Issue by oatmeal01** [nikita36078/J2ME-Loader#590]
**Emulator version:**
1.5.5

**Game version:**
Any Games

**Game resolution:**
``(For example, 240x320 or 640x360)``

**Device:**
``(For example, Samsung Galaxy S7)``

**Android version:**

**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
Bug when pressing volume, main volume won't appear unless you minimize the game and press the volume again.

When pressing volume, main volume won't appear.
![Screenshot_20191201_072446](https://user-images.githubusercontent.com/36059629/69907231-26b85880-140c-11ea-8ec7-5c97b4ac95df.png)

After minimizing, main volume will appear but only once. You will need to minimize the game again to access main volume.
![Screenshot_20191201_072523](https://user-images.githubusercontent.com/36059629/69907254-7139d500-140c-11ea-99b3-f77273b091cc.png)

**Comment by jack1432** [comment]
I also think there is something that needs to be changed in volume, because when you press the volume button while in a game, if there is no audio playing in the game at the time you pressed it, the volume that will change will be the "Ringtone" and not the volume from the "Media".

**Comment by nikita36078** [comment]
Fixed, now the media volume channel is always active.
