### ISSUE TITLE
Anito Call of the Land Graphical Bug

### ISSUE THREAD

**Issue by oatmeal01** [nikita36078/J2ME-Loader#591]
**Emulator version: 1.5.5**

**Game version: 1.0**

**Game resolution: **
``240x320``

**Device:**
``Asus Zenfone 5``

**Android version: 5.0**

**Description of the issue:**
``Just like #203 Issue no. 2(the bug came back with version 1.5.5)``

<img height="300" width="176" src="https://user-images.githubusercontent.com/36059629/69932933-edfda980-1507-11ea-9b1f-bf76b77409f4.png"/>

Related Issue #203 (Issue no. 2) 
The bug came back with ver 1.5.5.
<img height="300" width="176" src="https://user-images.githubusercontent.com/36059629/69933347-5b5e0a00-1509-11ea-8333-51cc3ed608f2.png"/>

**Comment by nikita36078** [comment]
1. It's a game bug, it looks the same on Nokia 5320 and KEmulator
2. This one is strange, I wonder how I've managed to break it again.

**Comment by nikita36078** [comment]
I've reopened old issue and closing this one.

**Comment by nikita36078** [comment]
UPD: Call of the Land's native resolution is 176*220, that's why it looks so weird.
