### ISSUE TITLE
Color of Menu When Using Dark Theme

### ISSUE THREAD

**Issue by oatmeal01** [nikita36078/J2ME-Loader#593]
**Emulator version:** 1.5.5
**Game version:** All
**Game resolution:** All
**Device:** All
**Android version:** All
**Description of the issue:** Please also include Dark theme to menu, the background color is white even if i use dark theme. thanks!

<img height="200" width="130" src="https://user-images.githubusercontent.com/36059629/69938013-25278700-1517-11ea-840b-b815457bee6a.png"/> <img height="200" width="130" src="https://user-images.githubusercontent.com/36059629/69938055-3f616500-1517-11ea-92a7-37d041820b3a.png"/>

**Comment by nikita36078** [comment]
Fixed
<img src="https://user-images.githubusercontent.com/3035571/72205893-1e3a4f80-3499-11ea-859a-1e9db2553928.png" width="360">

**Comment by MCPE-Beta1177** [comment]
i like that enhancement., so keep working on for the next version
