### ISSUE TITLE
Tetris Revolution - Graphical Bug

### ISSUE THREAD

**Issue by oatmeal01** [nikita36078/J2ME-Loader#601]
**Emulator version:** 1.5.5
**Game version:** 1.16.55, 1.11.71(N95)
**Game resolution:** 360x640, 240x320
**Device:** Asus Zenfone 5
**Android version:** 5.0

**Description of the issue:** Graphical bug when accessing Pause Menu. 
<table><tr><td align="center">
<b>J2ME Loader:</b> (<a href="https://drive.google.com/uc?authuser=0&id=130vd3j0RIPY0hkmIj1U4PvM3DdYX-9qR&export=download">Video</a>)</td>
<td align="center"><b>[PC] Kemulator:</b> (<a href="https://drive.google.com/uc?authuser=0&id=132mWtKmk6uvy5zc8LgD3gAE-khzc2zhv&export=download">Video</a>)</td></tr>
<tr><td align="center">
<img height="200" width="139" src="https://user-images.githubusercontent.com/36059629/70116714-757d2100-169e-11ea-923d-5179720267a0.png"/>

</td><td align="center">
<img height="200" width="130" src="https://user-images.githubusercontent.com/36059629/70116804-bb39e980-169e-11ea-89ad-cef59b889d7e.png"/>
</td></tr></table>

**Comment by nikita36078** [comment]
Fixed
