### ISSUE TITLE
Lock App/Protection Feature

### ISSUE THREAD

**Issue by oatmeal01** [nikita36078/J2ME-Loader#603]
**[Feature Request]** To avoid accidentaly deletion of app and games can you please add an app lock/protection to it. This will prevent the app to access the option menu until you unlock the app. Thanks!

This feature is from Samsung Corby II (Java Phone).

![3](https://user-images.githubusercontent.com/36059629/70369557-82944d00-18f6-11ea-9396-b34ec92fcf29.JPG)

**Comment by nikita36078** [comment]
You can't accidentally delete an app because there's a confirmation. I don't see the need in any additional protection features.
