### ISSUE TITLE
Unable to Install Offline JAD from 3rd Party File Managers.

### ISSUE THREAD

**Issue by oatmeal01** [nikita36078/J2ME-Loader#604]
### Installing Offline JAD file through 3rd Party File Manager

\- Failed to install. [(Watch Video)](https://drive.google.com/uc?authuser=0&id=14jEHbXsX7Rd-pabn743WeKUVmFY2n3Ea&export=download)

**Error Log:**
>D/ru.playsoftware.j2meloader.d.e( 3706): doInBackground$ pathToJar=/data/data/ru.playsoftware.j2meloader/tmp_uri/tmp.jad
>I/OpenGLRenderer( 3706): Initialized EGL, version 1.4
>W/System.err( 3706): ru.playsoftware.j2meloader.d.b: Can't download jar
[(Download logs.txt)](https://github.com/nikita36078/J2ME-Loader/files/3935763/log.txt)

The jar and jad are in the same folder with the same file name. 
I also edited the midlet jar url from jad. 
<img width="176" height="300" src="https://user-images.githubusercontent.com/36059629/70383307-a1eab300-19a6-11ea-989c-d2b9ab9a0e15.png"/>

<img widtth="800" heitght="176" src="https://user-images.githubusercontent.com/36059629/70382786-6ba83600-199c-11ea-9884-a86bfde497a4.png"/>

***Offline JAD Installer:*** [Download](https://drive.google.com/uc?authuser=0&id=146DyGwYshptkzUPEYnHxAdlYY_KZ1yY6&export=download)
\- Can only be installed via J2ME Loader Built-In Filepicker.

***Online JAD Installer:*** [Download](https://drive.google.com/uc?authuser=0&id=14oueMlfHQz51tsMm9kNDjrfrCDZwd9t9&export=download)
\- Can be installed via J2ME Loader Filepicker/any third party file manager. [(Download logs.txt)](https://github.com/nikita36078/J2ME-Loader/files/3935788/log.txt)

...

### Installing Offline JAD file through J2ME Loader file manager
\- Successfully installed. [(Watch Video)](https://drive.google.com/uc?authuser=0&id=14esecqkRH2yaVlOMgYkLuATPhoN7x4OT&export=download)

***Success Log:***
>D/ru.playsoftware.j2meloader.d.e(29452): doInBackground$ pathToJar=/storage/MicroSD/J2ME Archive/Apps/Opera Mini [4.5] Multi.jad
>D/OpenGLRenderer(29452): endAllStagingAnimators on 0xb8d82730 (RippleDrawable) with handle 0xb8db7ab0
>D/ru.playsoftware.j2meloader.d.e(29452): appConverted=/storage/emulated/0/J2ME-Loader/converted/Opera Mini 4
[(Download logs.txt)](https://github.com/nikita36078/J2ME-Loader/files/3935772/log.txt)

<img widhth="800" heigfht="176" src="https://user-images.githubusercontent.com/36059629/70382808-af02a480-199c-11ea-8c5c-c3cf19362a7b.png"/>

**Comment by ahmadprayoxxsy** [comment]
This is not a "j2me loader" app error.
maybe you haven't (storage permission) in the xploler app.

**Comment by oatmeal01** [comment]
> This is not a "j2me loader" app error.
> maybe you haven't (storage permission) in the xploler app.
I got also this error using built-in file manager. I can only install JAD via third party file manager by using Online Jad installer. Offline installaion via 3rd party is not working on my device. Ill check other device if the result is the same.

**Comment by ahmadprayoxxsy** [comment]
"J2me loader" takes a sample file from "zarchiver".
So in the "zarchiver" file (jad) app you can also install it.

**Comment by oatmeal01** [comment]
> "J2me loader" takes a sample file from "zarchiver".
> So in the "zarchiver" file (jad) app you can also install it.

same issue can't install offline jad from zarchiver. but when installing online jad it works fine.

**Comment by ahmadprayoxxsy** [comment]
![Screenshot_20191208-112628_MT Manager](https://user-images.githubusercontent.com/37769813/70384216-0eb57b80-19ae-11ea-9937-e3a7e0e55854.jpg)
Add it:MIDlet-Jar-URL: file:///sdcard/file.jar

**Comment by oatmeal01** [comment]
Try to test this two files:
``MIDlet-Jar-URL: Opera Mini 4 [4.5] Multi.jar``
[Offline JAD](https://drive.google.com/uc?authuser=0&id=14684aadjs3eyXJky9oN8GtrNuXl670Kh&export=download) - consist of both jad and the jar 

``MIDlet-Jar-URL: https://drive.google.com/uc?authuser=0&id=14-KNB7XwyjPEMdWOFkfISAN1J8QbAZ-8&export=download``
[Online Installer](https://drive.google.com/uc?authuser=0&id=14684aadjs3eyXJky9oN8GtrNuXl670Kh&export=download) - install online

**Comment by oatmeal01** [comment]
> ![Screenshot_20191208-112628_MT Manager](https://user-images.githubusercontent.com/37769813/70384216-0eb57b80-19ae-11ea-9937-e3a7e0e55854.jpg)
> Add it:MIDlet-Jar-URL: file:///sdcard/file.jar

ill try this one, thanks

**Comment by ahmadprayoxxsy** [comment]
Add it:MIDlet-Jar-URL: file:///sdcard/file.jar

**Comment by ahmadprayoxxsy** [comment]
![20191208_120637](https://user-images.githubusercontent.com/37769813/70384591-61456680-19b3-11ea-83e3-d03dab68de2a.jpg)
![Screenshot_20191208-120604_J2ME Loader](https://user-images.githubusercontent.com/37769813/70384592-64405700-19b3-11ea-8f3f-12f643c30f30.jpg)

**Comment by ahmadprayoxxsy** [comment]
Let me see your "jad" text file

**Comment by woesss** [comment]
If you have a local JAR, you can install it. Otherwise, the JAD MUST have an absolute (full) address in the MIDlet-Jar-URL. When the JAD and JAR are in the same folder and the MIDlet-Jar-URL is specified as the name of the JAR file, installation from the JAD is not possible, because the file manager does not transmit file location information to the emulator. For this, we must say thanks to Google - they believe that direct access to files in Android is not needed at all.

**Comment by oatmeal01** [comment]
> If you have a local JAR, you can install it. Otherwise, the JAD MUST have an absolute (full) address in the MIDlet-Jar-URL. When the JAD and JAR are in the same folder and the MIDlet-Jar-URL is specified as the name of the JAR file, installation from the JAD is not possible, because the file manager does not transmit file location information to the emulator. For this, we must say thanks to Google - they believe that direct access to files in Android is not needed at all.

Offline Jad installation only works with J2ME File Browser. (both jar and jad inside folder and midlet url specified as the name of the jar file.)
<img src="https://user-images.githubusercontent.com/36059629/70382808-af02a480-199c-11ea-8c5c-c3cf19362a7b.png"/>

The only problem is i can't make it work outside the app.

**Comment by ahmadprayoxxsy** [comment]
No Spaces in jar / jar file.
Incorrect: a b c d.jad / a b c d.jar
Correct: abcd.jad / abcd.jar

**Comment by oatmeal01** [comment]
> No Spaces in jar / jar file.
> Incorrect: a b c d.jad / a b c d.jar
> Correct: abcd.jad / abcd.jar

Still no luck, doesn't seems to fix the problem. I can install it through j2me loader file manager but not from other 3rd party filemanager.

**Comment by oatmeal01** [comment]
**Video**
\- [Offline Jad Installation through 3rd Party File Manager ](https://drive.google.com/uc?authuser=0&id=14VQkm1i06P1wEXkg_QKhje2OQ1BN1CtJ&export=download)
\- [Offline Jad Installation through J2ME Filemanager](https://drive.google.com/uc?authuser=0&id=14esecqkRH2yaVlOMgYkLuATPhoN7x4OT&export=download)

**Comment by ahmadprayoxxsy** [comment]
> **Video**
> - [Offline Jad Installation through 3rd Party File Manager ](https://drive.google.com/uc?authuser=0&id=14VQkm1i06P1wEXkg_QKhje2OQ1BN1CtJ&export=download)
> - [Offline Jad Installation through J2ME Filemanager](https://drive.google.com/uc?authuser=0&id=14esecqkRH2yaVlOMgYkLuATPhoN7x4OT&export=download)

There are no spaces in the file name.

**Comment by woesss** [comment]
Why do you need a JAD when you have a JAR? The emulator does not need it.  And only in rare cases, installation via JAD is required by the java application itself, if it uses some parameters that are specified only in this JAD and are absent in the jar's manifest.

**Comment by oatmeal01** [comment]
> Why do you need a JAD when you have a JAR? The emulator does not need it. And only in rare cases, installation via JAD is required by the java application itself, if it uses some parameters that are specified only in this JAD and are absent in the jar's manifest.
> If the application works fine after installing from the JAR, then the JAD is not needed at all.

To install the signed version of Opera you need Jad. 

Some games won't also work without installing through Jad, yes you can install the local Jar file but the game won't open (example: [Blood+.zip](https://drive.google.com/uc?authuser=0&id=14ko4rsZczBUEHCNxvcp1NdS9EYjJYeAb&export=download).

To also make some demo games totally full, you need the Jad file.

**Comment by ahmadprayoxxsy** [comment]
``

**Comment by ahmadprayoxxsy** [comment]
Take a look at this video.
https://drive.google.com/file/d/1CneY3-o355dc8LRDu-HGCxoGDePhZone/view?usp=drivesdk

**Comment by oatmeal01** [comment]
> Take a look at this video.
> https://drive.google.com/file/d/1CneY3-o355dc8LRDu-HGCxoGDePhZone/view?usp=drivesdk

This is the result.
<img src="https://user-images.githubusercontent.com/36059629/70384465-cf8d2780-19b9-11ea-8b7b-5d87adf7d8be.png"/>

 i even rename it to test.jar and test.jad and midlet url to test.jar just to make sure no spaces.

we have different path i use file:///sdcard/test.jar for midlet url first but error occur as you can see from the screenshot.

tried also file:///storage/emulated/0/test.jar as midlet url but still the same error.

**Comment by ahmadprayoxxsy** [comment]
Try not to put it in a folder.
Donload operamini:https://drive.google.com/file/d/1Xxzf9yURX7mOnHZPSUCjDbTq5XmSdKru/view?usp=drivesdk

Put in internal memory

**Comment by woesss** [comment]
> To install the signed version of Opera you need Jad.
> 
> Some games won't also work without installing through Jad, yes you can install the local Jar file but the game won't open (example: Blood+.zip.
> 
> To also make some demo games totally full, you need the Jad file.

 But, in such exceptional cases, you can install through the built-in file piсker. Another thing is if such an opportunity did not exist at all... In order to do the way you want, the emulator will have to scan the entire file system each time to find the JAR - this is a long time and there may be errors if there are several JARs with the same name.

**Comment by oatmeal01** [comment]
> > To install the signed version of Opera you need Jad.
> > Some games won't also work without installing through Jad, yes you can install the local Jar file but the game won't open (example: Blood+.zip.
> > To also make some demo games totally full, you need the Jad file.
> 
> But, in such exceptional cases, you can install through the built-in file piсker. Another thing is if such an opportunity did not exist at all... In order to do the way you want, the emulator will have to scan the entire file system each time to find the JAR - this is a long time and there may be errors if there are several JARs with the same name.

I'll just install offline Jad through J2ME Loader's built-in file picker. I agree on what you said earlier, jad are just used in rare cases. Btw im collecting Java App & Games for J2ME Loader and most of it are in Jar format.

**Comment by oatmeal01** [comment]
**Solution:** Just install Offline JAD through J2ME loader's Built-in filepicker.

**Comment by nikita36078** [comment]
There's no reliable way to get the .jad path, so the emulator simply can't find the corresponding .jar file.
