### ISSUE TITLE
Add clearer system properties

### ISSUE THREAD

**Issue by ahmadprayoxxsy** [nikita36078/J2ME-Loader#605]
**Emulator version:**
All

**Game version:**
All

**Game resolution:**
``(All)``

**Device:**
``(All)``
![20191208_120125](https://user-images.githubusercontent.com/37769813/70384625-20018680-19b4-11ea-8093-3ce27e617e48.jpg)

**Android version:**
All
**Description of the issue:**
Add clearer system properties

**Comment by nikita36078** [comment]
I don't quite understand what do you mean.

**Comment by ahmadprayoxxsy** [comment]
![20191208_215213](https://user-images.githubusercontent.com/37769813/70391213-31bf4a00-1a05-11ea-98c3-f7bd441517bd.jpg)
One will not know the function of this setting.

**Comment by oatmeal01** [comment]
I only use system properties for Java Browsers like Opera and UCWeb. 
**Check system info:** [SystemInfo.jar](https://drive.google.com/uc?authuser=0&id=15sktehCPLIepnOKZzdc3gRqBG3J8wKV0&export=download)

**Sample:**
>microedition.platform: Nokia6300/04.71
microedition.profiles: MIDP-2.0

<img width="176" height="300" src="https://user-images.githubusercontent.com/36059629/70415422-8ca18180-1a97-11ea-8c66-add5006ff253.png"/>
<img width="176" height="300" src="https://user-images.githubusercontent.com/36059629/70415458-9d51f780-1a97-11ea-83fb-e0f13a1c7ed8.png"/>

**Effect on Browser:**
<img width="176" height="300" src="https://user-images.githubusercontent.com/36059629/70415720-426cd000-1a98-11ea-8abc-c43067591def.png"/>


I just don't know what the effect if you applied this to java games.

**Comment by nikita36078** [comment]
In 99,99% games this setting does nothing. Sometimes some values can affect a game but you need to reverse-engineer the game to find it out.
