### ISSUE TITLE
Keyboard Customization Bug

### ISSUE THREAD

**Issue by oatmeal01** [nikita36078/J2ME-Loader#606]
**Emulator version:** 1.5.5
**Game version:**
**Game resolution:** 240x320
**Device:** Asus Zenfone 5
**Android version:** 5.0
**Description of the issue:** Customized keyboard bug. This game needs both arrow and number keys to play.

**Saved Layout After Editing:**
![Screenshot_2019-12-13-17-37-42](https://user-images.githubusercontent.com/36059629/70790523-33f02280-1dd0-11ea-83e4-7ad614a094a6.png)

**Reopening the Game with the Customized Layout:**
![Screenshot_2019-12-13-17-38-03](https://user-images.githubusercontent.com/36059629/70790570-52eeb480-1dd0-11ea-9f33-9c4a8b662aa7.png)

**Comment by nikita36078** [comment]
Duplicate - #498. By the way, I still can't replicate it. Could you send me your layout just after editing? It's located in J2ME-Loader/configs/game_name/VirtualKeyboardLayout

**Comment by woesss** [comment]
@nikita36078, 
[VirtualKeyboardLayout.zip](https://github.com/nikita36078/J2ME-Loader/files/3961203/VirtualKeyboardLayout.zip)
у меня легко воспроизводится - просто меняем местами блоки, перетаскивая их за угловые кнопки. Потом завершаем редактирование и выходим из игры. Запускаем снова - картина маслом.

**Comment by oatmeal01** [comment]
[TibiaME.zip](https://github.com/nikita36078/J2ME-Loader/files/3961722/TibiaME.zip)

**Comment by oatmeal01** [comment]
**Video:**
<a href="https://drive.google.com/uc?authuser=0&id=18GEkgySFiFEr6vr2K4edBKPWKQFsXFqZ&export=download"><img src="https://user-images.githubusercontent.com/36059629/70844292-ecbe6c00-1e79-11ea-86f4-d888b95af41f.png"/></a>

**Comment by nikita36078** [comment]
Thanks, now I've got this error. I close this issue as duplicate, hopefully I will find a solution soon.
