### ISSUE TITLE
Block Breaker 3 Java error

### ISSUE THREAD

**Issue by Tetriser** [nikita36078/J2ME-Loader#607]
**Emulator version:**
1.5.5-play

**Game version:**
1.2.7

**Game resolution:**
``360x640``

**Device:**
``Redmi 5A``

**Android version:**
8.1.0 (MIUI 11)

**Description of the issue:**
``Block Breaker 3 Unlimited, version 1.2.7 throws a null object reference error``
![Screenshot_2019-12-15-11-11-21-053_ru playsoftware j2meloader](https://user-images.githubusercontent.com/5746458/70857660-c22deb00-1f2d-11ea-887e-c43fa1dfcd9b.jpg)

**Comment by nikita36078** [comment]
Install the game using a jad file, it will fix the problem.

**Comment by Tetriser** [comment]
> Install the game using a jad file, it will fix the problem.

Oh, it works! Thanks!
(though I'm now playing the non-touchscreen version of the game now.)
