### ISSUE TITLE
Chuzzle

### ISSUE THREAD

**Issue by Tetriser** [nikita36078/J2ME-Loader#609]
**Emulator version:**
1.5.5-play

**Game version:**
4.4.32

**Game resolution:**
``360x640(?)``

**Device:**
``Redmi 5A``

**Android version:**
8.1.0
**Description of the issue:**
``Blank screen with only the soft key buttons were visible``
![Screenshot_20191217-213442](https://user-images.githubusercontent.com/5746458/71000003-7e95d580-2115-11ea-959a-acb6f7b052d6.png)

**Comment by oatmeal01** [comment]
try to swap reso (640x360) then set orientation to landscape.

**Comment by Tetriser** [comment]
> try to swap reso (640x360) then set orientation to landscape.

Just did, it shows a fully blank screen instead.

But from what I tried (or accidentally tried), the game is actually playable if the screen's width is set to 240.

Not sure what the height is though.

**Comment by nikita36078** [comment]
I've checked app manifest, its native resolution is 240*432.
