### ISSUE TITLE
Some (all?) original (96x64 B&W) Gameloft games has graphical glitches

### ISSUE THREAD

**Issue by stranno** [nikita36078/J2ME-Loader#611]
It seems all Gameloft games from their first years (black & white and 96x64) have graphical glitches with scrolling, lines, corrupted sprites, etc. I havent seen these issues in color games from the same time (in 96x64 too). Here are a few examples:

Prince of Persia corrupted platform.

![Screenshot_20191222-034933](https://user-images.githubusercontent.com/6293197/71316401-70c2b600-246f-11ea-95ca-8927394484d8.png)

It gets fixed once you reach there.

![Screenshot_20191222-034937](https://user-images.githubusercontent.com/6293197/71316402-70c2b600-246f-11ea-85c0-41e7cb3c7bac.png)

Same glitch in other platform.

![Screenshot_20191222-035016](https://user-images.githubusercontent.com/6293197/71316403-715b4c80-246f-11ea-8946-fff7569874e3.png)

![Screenshot_20191222-035021](https://user-images.githubusercontent.com/6293197/71316404-715b4c80-246f-11ea-9dca-896f2f7eb328.png)

Splinter Cell has issues with the scroll. Some elements of the level (darkness dithering, lines, etc) move with the screen scroll.

![Screenshot_20191222-035157](https://user-images.githubusercontent.com/6293197/71316405-715b4c80-246f-11ea-9dce-e38db85da6d1.png)

Rainbow Six (the first one) has corrupted text graphics (pic 1) and corrupted sprites (pic 2), the dots mess in the left side of the screen is a corrupted enemy. It gets fixed once the enemy stop moving.

![Screenshot_20191222-035331](https://user-images.githubusercontent.com/6293197/71316406-715b4c80-246f-11ea-8e25-8f256ecf7812.png)

![Screenshot_20191222-035411](https://user-images.githubusercontent.com/6293197/71316400-70c2b600-246f-11ea-8ff8-9a62fecf0c41.png)

I could send more examples but it seems its a common thing in B&W Gameloft games. It could be related to the small resolution, maybe it is not correctly handled by J2ME-Loader, but, as i said, color games work fine and they have the same resolution.

I'm using the latest build and it happens with all options disabled (except screen scaling and aspect ratio lock, otherwise screen would be almos invisible in a modern phone, lol).

**Comment by oatmeal01** [comment]
s30 series games? where to download?

**Comment by MCPE-Beta1177** [comment]
@oatmeal01 you need a specific Jar Or Jad Games using X-Plore file manager app

**Comment by MCPE-Beta1177** [comment]
Yeah, i tried to add jar or jad files, but nothing seem to happen!
So i'm using X-plore file manager!
It's available on google play store!
If anyone tries to add jad or jar games, this might work for you

**Comment by stranno** [comment]
Sorry, i forgot this thread. Here's a Nokia 3410 pack with all B&W games with that resolution.
[Full Games.zip](https://github.com/nikita36078/J2ME-Loader/files/4174093/Full.Games.zip)

**Comment by nikita36078** [comment]
Fixed. Nokia used really weird formats for B&W graphics, but I think all of them are handled properly now.

**Comment by stranno** [comment]
> Fixed. Nokia used really weird formats for B&W graphics, but I think all of them are handled properly now.

I will check and report tomorrow, thanks Nikita.

**Comment by nikita36078** [comment]
It's only in the automated builds, not in the release yet

**Comment by stranno** [comment]
Yes, i tested the automated build and the resolution problems has been fixed.

Unfortunately the Rainbow Six corrupted sprites/text problem is still there. So it probably doesnt have anything to do with the resolution. It could be a corrupted dump but i havent found any other. Is there any other way to make sure if it is an emulation problem?

Here's a gif.

![file](https://user-images.githubusercontent.com/6293197/74946000-ec51cc80-53f8-11ea-9204-78e8e057834b.gif)

The sprite is only corrupted while it is moving and it only happens with enemies that appear from that area of the screen.

**Comment by nikita36078** [comment]
Fixed, it was a bit more complicated than I thought

<img src="https://user-images.githubusercontent.com/3035571/75459797-ae711d00-5991-11ea-8ddf-c45fd1d68285.png" width="360" height="640">

**Comment by stranno** [comment]
Thank you Nikita! As you said, now it works properly. I havent tested every B&W game from the pack but both problems have been fixed. I will close the issue.
