### ISSUE TITLE
Something tells me that midi files from bounce tales should sound exactly like nokia x2-00

### ISSUE THREAD

**Issue by MCPE-Beta1177** [nikita36078/J2ME-Loader#612]
You read the title right!
I'm thinking that the midi files from bounce tales should sound exactly like nokia x2-00, but I don't know how to change the system properties in j2me loader

**Comment by nikita36078** [comment]
There's already issue for that - #569.

**Comment by MCPE-Beta1177** [comment]
@nikita36078 yeah, every midi files from bounce tales should not sound exactly like nokia x2-00!
hopefully in the next update (1.5.6), this should change the phone system properties to see how it sounds like nokia x2-00

**Comment by MCPE-Beta1177** [comment]
@nikita36078 but seriously, how can i play java games!
i tried to add java games, but this weird bug needs to be fixed like, right now!
Sorry, i got mad because of this bug in your app when adding java games
