### ISSUE TITLE
Nhan

### ISSUE THREAD

**Issue by NightmasterT** [nikita36078/J2ME-Loader#613]
**Emulator version:**

**Game version:**

**Game resolution:**
``(For example, 240x320 or 640x360)``

**Device:**
``(For example, Samsung Galaxy S7)``

**Android version:**

**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``

**Comment by MCPE-Beta1177** [comment]
this issue is ridiculous and I think nitkita should close it

**Comment by nikita36078** [comment]
Empty issue

**Comment by MCPE-Beta1177** [comment]
@nikita36078 thanks for closing his issue, but there is a bug where you add java games and it won't let you to convert java games!
I know someone who's laughing at me, but i changed the title that you see!
Title: Fix Adding Java Games Bugs
