### ISSUE TITLE
Fix Java Game Adding Bugs in the next update for j2me loader

### ISSUE THREAD

**Issue by MCPE-Beta1177** [nikita36078/J2ME-Loader#614]
hi nikita, this is just a request for Java Game Adding Bugs, so can you fix it in the next update

**Comment by lufog** [comment]
Really? You think your issue is not ridiculous?

**Comment by MCPE-Beta1177** [comment]
Yes it is, it's a bug of attempting to add java games and it got me mad😠
If you see a bug of attempting to add java games, let nikita know if you see a bug

**Comment by MCPE-Beta1177** [comment]
@lufog Yes it is, it's a bug of attempting to add java games and it got me mad😠!
If you see a bug of attempting to add java games, let nikita know if you see a bug in the next update for J2ME Loader!
Also, sorry for closing my issue, it was just a glitch, so that's why i reopened this issue because of this glitch

**Comment by lufog** [comment]
![изображение](https://user-images.githubusercontent.com/10379487/71819333-a9cc6e80-309c-11ea-843a-8720d1418766.png)
Are you serious?

**Comment by MCPE-Beta1177** [comment]
@lufog yes, i'm serious, but Adding Java Games had bug reports that should be fixed in the next update for j2me loader🙂

**Comment by nikita36078** [comment]
@MCPE-Beta1177 Could you explain clearly, what exactly issue you are experiencing? You get some error when adding a game or what?

**Comment by MCPE-Beta1177** [comment]
also, sorry for closing my issue!
just wanted to tell you that version 1.5.6 will be released when there is a lot of changes and fixes that people is complaining about converting Java Games to the folder of j2me loader

**Comment by MCPE-Beta1177** [comment]
@nikita36078 yes, I get the same error when adding Jad files in j2me loader!
and it says: Can't Download jar

**Comment by nikita36078** [comment]
@MCPE-Beta1177 As I've already said before, this is an Android problem, I can't fix it. Use built-in file manager to install .jad files.

**Comment by MCPE-Beta1177** [comment]
@nikita36078 you mean: X-plore file manager!
Yes, that's what i'm installing jad files using x-plore file manager
