### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by jack1432** [nikita36078/J2ME-Loader#617]
Why do diagonal keyboard arrows have a different shape on some devices?

**Comment by MCPE-Beta1177** [comment]
maybe because j2me loader is in the development

**Comment by MCPE-Beta1177** [comment]
and it's work in progress

**Comment by MCPE-Beta1177** [comment]
I do have the same problem with Jad files!
if you make Jad files to work in j2me loader, all you need to do is download a specific Jar files and then use X-Plore to rename jar to jad files to make it work on j2me loader!
if anyone has the problem with the jad files, X-Plore file manager should work with the jad files

**Comment by nikita36078** [comment]
@MCPE-Beta1177 Please stop spamming!
@jack1432 It depends on the font, different devices use different font.

**Comment by jack1432** [comment]
@nikita36078 Thanks. I just asked this because, on my device, the diagonal arrows are different from the others and I don't like it very much, I wish they were all in the same format, but thanks anyway.

**Comment by nikita36078** [comment]
I think I'll add a separate font for the virtual keyboard, to unify its appearance.

**Comment by jack1432** [comment]
> Acho que vou adicionar uma fonte separada para o teclado virtual, para unificar sua aparência.

So do it when you have some time, please :)

**Comment by MCPE-Beta1177** [comment]
@nikita36078 ok, i will stop spamming if you need a jad files to work using Xplore

**Comment by MCPE-Beta1177** [comment]
@nikita36078 you told me to not spamming you after you have some time for not releasing 1.5.6 on j2me loader

**Comment by MCPE-Beta1177** [comment]
@nikita36078 Really! you told me to stop spamming you after you have some time for not releasing the next version for j2me loader, so what is the problem

**Comment by MCPE-Beta1177** [comment]
@nikita36078 OK, but please add a specific feature request that people wanted an update

**Comment by lamdemon** [comment]
@MCPE-Beta1177 what a moron!

**Comment by MCPE-Beta1177** [comment]
@lamdemon rude

**Comment by MCPE-Beta1177** [comment]
@lamdemon stop using your language

**Comment by MCPE-Beta1177** [comment]
@nikita36078 landemon is swearing at me for no reason

**Comment by MCPE-Beta1177** [comment]
@lamdemon you deserved a dislike for swearing at me

**Comment by lamdemon** [comment]
@MCPE-Beta1177 the way you spammed make me sick, and you don't even apologize

**Comment by MCPE-Beta1177** [comment]
@lamdemon I blocked you because you weren't being nice enough

**Comment by nikita36078** [comment]
@lamdemon Please, don't spam or insult people. There's already enough of that stuff in that repo.

**Comment by lamdemon** [comment]
@nikita36078 i really sorry, i just felt annoyed by his comment

**Comment by MCPE-Beta1177** [comment]
@lamdemon you're just jealous when you swear it, so i'm apologizing to you, then Me, And Nikita36078 will unblock you after muliple violations

**Comment by MCPE-Beta1177** [comment]
@lamdemon oh, that's true, but why you keep insulting people like that! That's very cruel

**Comment by MCPE-Beta1177** [comment]
@lamdemon i'm still disappointed:pensive:

**Comment by MCPE-Beta1177** [comment]
@lamdemon you're just a jealous person when you said the f word that i hate!

**Comment by MCPE-Beta1177** [comment]
@lamdemon I blocked you when you spam the f word that I consider it as swearing

**Comment by MCPE-Beta1177** [comment]
@lamdemon I blocked when you spam the f word that I consider it as swearing or insulting! 
if you would think that I'm gonna go away, then i accept your apology

**Comment by MCPE-Beta1177** [comment]
@lamdemon it's okay, I unblocked you and accept your apology

**Comment by MCPE-Beta1177** [comment]
@nikita36078 I unblocked him, and accept his apology

**Comment by lamdemon** [comment]
@MCPE-Beta1177 Are you kidding me, kid??? I apologized to @nikita36078, NOT you

**Comment by woesss** [comment]
@MCPE-Beta1177, @lamdemon - find out the relationship in a different location, please - this is not a social network or a forum.

**Comment by MCPE-Beta1177** [comment]
@lamdemon hey, I apologized to you

**Comment by MCPE-Beta1177** [comment]
@lamdemon then you should apologize to me

**Comment by MCPE-Beta1177** [comment]
@lamdemon i apologized to @nikita36078

**Comment by MCPE-Beta1177** [comment]
@lamdemon seriously, he blocked you after multiple violations

**Comment by MCPE-Beta1177** [comment]
@woesss but he swearing at me for no reason

**Comment by MCPE-Beta1177** [comment]
@lamdemon just leave me alone!
I don't have time for you swearing at me

**Comment by MCPE-Beta1177** [comment]
@lamdemon you're pure evil

**Comment by MCPE-Beta1177** [comment]
@lamdemon then you deserved it as a dislike

**Comment by MCPE-Beta1177** [comment]
@woesss i'm sorry, but i blocked when he insults people that i consider as swearing

**Comment by MCPE-Beta1177** [comment]
🤦‍♂️@lamdemon

**Comment by lamdemon** [comment]
MCPE-Beta1177 do you even understand what I said, moron? And do you even understand English???? Why should I have to apologize to you??? I have already apologized @nikita36078 in the above message

**Comment by lamdemon** [comment]
@woesss there is no "relationship" in here, and I don't want to turn this into a forum or social network, his comment and his attitude annoyed me, so I told him to leave, after that he started crying lol😂😂😂

**Comment by MCPE-Beta1177** [comment]
@woesss

**Comment by MCPE-Beta1177** [comment]
@lamdemon you're a cyberbully

**Comment by lamdemon** [comment]
MCPE-Beta1177 how old are you?

**Comment by MCPE-Beta1177** [comment]
@lamdemon 16

**Comment by lamdemon** [comment]
MCPE-Beta1177 really??? You behaved like a child lol

**Comment by lamdemon** [comment]
So anyway, I will stop now because i don't want to continue this pointless conversation and bothering you guys anymore,

**Comment by MCPE-Beta1177** [comment]
@lamdemon Do you understand what i've said! Stop insulting me or you'll get a dislike

**Comment by MCPE-Beta1177** [comment]
@lamdemon i'm serious!
I don't want to bother anyone, so please, let's just stop arguing, okay
