### ISSUE TITLE
How to hack cheat game offline?

### ISSUE THREAD

**Issue by hoichemgio9x** [nikita36078/J2ME-Loader#619]
**Emulator version:** 1.5.5

**Game version:** 1.0

**Game resolution:**
``(For example, 240x320 or 640x360)``
240x320
**Device:**
``(For example, Samsung Galaxy S7)``
Zte Nubia Red Magic 3
**Android version:**
9.0
**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
- I want hack or cheat a game offline. Example: level, atk (not coin)

**Comment by nikita36078** [comment]
Either you can analyze game code, figure out how it stores save data and edit it, or you can try to use apps like GameGuardian to directly edit values in the memory.

**Comment by oatmeal01** [comment]
try to download mods or modify the game, there's a lot of java game  mods out there, for example Heroes lore Zero(Infinite Gold etc..)

**Comment by MCPE-Beta1177** [comment]
@nikita36078 tell me about it! I want an update
