### ISSUE TITLE
Some broken Java game/apps

### ISSUE THREAD

**Issue by AdityaMH** [nikita36078/J2ME-Loader#62]
I was tested some game/app and found some error:
4x4 Extreme Rally: World Tour (brocken manifest *or broken manifest* (but why all screen/version))
Diamond Rush (going blank (black)(but why all screen/version))
Facebook (going blank)
3D Crash Arena (arena become blank & slowly)

**Comment by nikita36078** [comment]
Well, 3D isn't stable yet, so glitches and bugs in 3D games are expected. I will check other apps later.

**Comment by jan-kleks** [comment]
@AdityaMH I think it's better to do separate bug reports for each game. Am I right @nikita36078 ?

**Comment by nikita36078** [comment]
Yes, it is a good idea :-)

**Comment by AdityaMH** [comment]
something like making game/app compatibility list page with description. or write each game/app bug for each topic (issue)?

**Comment by AdityaMH** [comment]
something like making game/app compatibility list page with description. or write each game/app bug for each topic (issue), @jan-kleks?

**Comment by nikita36078** [comment]
@AdityaMH He meant opening an issue for each app, it would be more convenient.
By the way, I will create list of incompatible/bugged games soon, it should be useful too.

**Comment by AdityaMH** [comment]
@nikita36078 but i found many bugged games yesterday.
next time, i will opening issue for each game/app.

P.S.: can you accepting my request about adding "change orientation" button and "show keyboard" button in common setting (i want playing rf 2018 with real name (320x240) but they only support qwerty to input team)?

**Comment by nikita36078** [comment]
3d crash arena works properly now, diamond rush issue already exists, I didn't find such bug in Facebook, so I close this issue.
