### ISSUE TITLE
this is a issue of lamdemon for swearing at me

### ISSUE THREAD

**Issue by MCPE-Beta1177** [nikita36078/J2ME-Loader#621]
hi nitkita, I'm sorry for spamming you, but there is a huge problem!
lamdemon is swearing at me for no reason

**Comment by woesss** [comment]
Without a reason? Or maybe because everyone is tired of your meaningless messages that you repeat like a parrot? Are you waiting for the new version? - wait like everyone else - silently. Your posts only distract the developer and annoy all subscribers.

**Comment by MCPE-Beta1177** [comment]
@woesss you're right, everyone is tired of my meaningless messages that I repeat like a parrot! i don't have wings, I'm just assuming that I'm sorry

**Comment by MCPE-Beta1177** [comment]
@woesss you're right, everyone is tired of my meaningless messages that I repeat like a parrot, but still, I'm just assuming that I'm really sorry

**Comment by MCPE-Beta1177** [comment]
@woesss I blocked him because he swears at me!

**Comment by nikita36078** [comment]
@MCPE-Beta1177 I block a user after multiple violations. If you want, you can report abuse.

**Comment by MCPE-Beta1177** [comment]
@nikita36078 yeah, that sounds like a good idea to me?

**Comment by MCPE-Beta1177** [comment]
@woesss i am really sorry,
