### ISSUE TITLE
Add Bluetooth API for BlueFTP

### ISSUE THREAD

**Issue by DavidBrazSan** [nikita36078/J2ME-Loader#623]
**Emulator version:**
``1.5.5``

**App version:**
``1.70``

**Game resolution:**
``MultiResolution``

**Device:**
``Samsung Galaxy J2``

**Android version:**
``5.1.1``

**Description of the issue:**
``Add Bluetooth API``

![BlueFTP](https://user-images.githubusercontent.com/60136669/72803877-e1572100-3c2d-11ea-8227-d16584ef83f5.png)

**Comment by nikita36078** [comment]
Duplicate #218. Anyway, I'm not planning to add the Bluetooth support in near future, there's a lot of problems with it.
