### ISSUE TITLE
Bug Audio - Ice Age Village

### ISSUE THREAD

**Issue by DavidBrazSan** [nikita36078/J2ME-Loader#624]
**Emulator version:**
``1.5.5``

**Game version:**
``1.0``

**Game resolution:**
``320x240``

**Device:**
``Samsung Galaxy J2``

**Android version:**
``5.1.1``

**Description of the issue:**
``When you change the menu (purchase menu for the game's main screen, among others), the audio freezes and returns to normal.``

**Comment by nikita36078** [comment]
Fixed

**Comment by DavidBrazSan** [comment]
thank you
