### ISSUE TITLE
Fix This...

### ISSUE THREAD

**Issue by GamingKing123** [nikita36078/J2ME-Loader#626]
I can't play Gangstar City, Green Farm 3 & This type of games which have timing (Example- In Green Farm 3 after buy anything it's take time to build). After i close j2me loader the time stopped. please fix this...

**Comment by oatmeal01** [comment]
this trick is old, try to adjust your time/date to finish building. you can do this to bypass time counter in any java games.

**Comment by nikita36078** [comment]
Just checked a couple of versions of Green Farm - they all work fine, the time count doesn't stop after the game is closed. What game versions do you use?

**Comment by GamingKing123** [comment]
Version- 1.0.3

**Comment by lamdemon** [comment]
@GamingKing123 you should upload the .jar file here

**Comment by nikita36078** [comment]
Can't replicate the bug
