### ISSUE TITLE
Fake Bluetooth support

### ISSUE THREAD

**Issue by demonttl** [nikita36078/J2ME-Loader#627]
I saw some games that requires to enable Bluetooth to play but I don't think it actually uses Bluetooth (game will exit if it detects that you don't enable Bluetooth), so I just wondering if it is possible to make game think that Bluetooth is enable (fake Bluetooth)?

**Comment by nikita36078** [comment]
It's technically possible, but there's a huge chance the game will crash. What is the name of that game?

**Comment by lamdemon** [comment]
@nikita36078 here: https://1drv.ms/u/s!ArepSQfTxj8ygbNMI-enCO04K-M4eA

**Comment by lamdemon** [comment]
After play and exit a few times, it requires me to enable Bluetooth:
![Screenshot_20200118-151901](https://user-images.githubusercontent.com/57144641/73238731-89d82880-41cc-11ea-841b-2f11ca7ec306.png)

**Comment by lamdemon** [comment]
![Screenshot_20200118-151901](https://user-images.githubusercontent.com/57144641/73238783-be4be480-41cc-11ea-9c8f-76fcec3ee234.png)

**Comment by lamdemon** [comment]
![Screenshot_20200118-151901](https://user-images.githubusercontent.com/57144641/73238812-d15eb480-41cc-11ea-8b92-ef4fdc77173b.png)

**Comment by lamdemon** [comment]
![Screenshot_20200118-131450](https://user-images.githubusercontent.com/57144641/73238826-e1769400-41cc-11ea-9855-223e4e820f57.png)

**Comment by lamdemon** [comment]
![Screenshot_20200128-123927](https://user-images.githubusercontent.com/57144641/73238861-fd7a3580-41cc-11ea-8703-0d0abe9bf2f0.png)

**Comment by woesss** [comment]
> here: https://1drv.ms/u/s!ArepSQfTxj8ygbNMI-enCO04K-M4eA

I did not find any calls to Bluetooth in this game.  
Therefore, simulating the enabled bluetooth module will not solve this problem.
The problem is probably a bad crack.

**Comment by nikita36078** [comment]
@woesss No, it really calls `LocalDevice.getLocalDevice().getBluetoothAddress()` after a few launches, I think it's some kind of a license check.

**Comment by MCPE-Beta1177** [comment]
@nikita36078 i guess bluetooth is needed license check. so as i'm saying, this user is so rude, he bullies me when i spam you.
i like your app

**Comment by nikita36078** [comment]
No longer needed, the bluetooth support is added in the new version.
