### ISSUE TITLE
Bluetooth multiplayer on Fatal Force does not work.

### ISSUE THREAD

**Issue by Kriss7475** [nikita36078/J2ME-Loader#63]
I tried to play multiplayer **Fatal Force** with this emulator, but I get bluetooth error. Can attach jar file with the game, in case you need it.   
App version: 1.2.5.1 (stable)

Edit: Identical on 1.2.6-test1, another phone, same jar file.

**Comment by nikita36078** [comment]
J2ME Loader doesn't support bluetooth at the moment, maybe I will implement it later.

**Comment by Kriss7475** [comment]
> later

When?

**Comment by nikita36078** [comment]
I have no such plans right now, so I don't know.

**Comment by jan-kleks** [comment]
@nikita36078 Have you heard about Opposite Lock? "A highly regarded commercial J2ME title now released as open source. Take your pick from 10 maxed-out street legal racers and prove your mettle on 10 international tracks. The game has three modes of play, practice, tournament or time trial, with up to 8-way multiplayer [bluetooth] on supporting handsets." The source code for the demo version is available [here](https://code.google.com/archive/p/oppositelock/). Maybe this would help you to figure out how J2ME uses bluetooth.

**Comment by nikita36078** [comment]
I created special issue for Bluetooth - #218.
