### ISSUE TITLE
Feature request - Load settings from JAD files

### ISSUE THREAD

**Issue by bartlomiejduda** [nikita36078/J2ME-Loader#630]
**Emulator version:**
1.5.5-play (Newest - from the app store)

**Game version:**
Crash Bandicoot Mutant Island 1.0.0.0

**Game resolution:**
``(For example, 240x320 or 640x360)``
360x640 

**Device:**
``(For example, Samsung Galaxy S7)``
Samsung Galaxy S5 SM-G900F

**Android version:** 
6.0.1

**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``

Hello. I would like to ask for new feature request. Could you please add loading settings from JAD files to your emulator? I'll try to explain this on an example. I have discovered cheat option (god mode) for Crash Bandicoot Mutant Island. You can read about this on my github 
https://github.com/bartlomiejduda/Tools/tree/master/NEW%20Tools/Crash%20Bandicoot%20Mutant%20Island%202008/Cheats
This god mode cheat works fine on **KEmulator lite 0.9.8**, but it seems that **J2ME-Loader** can't read this JAD file properly. Could you please check it?

Kind regards,
Bartlomiej.

**Comment by oatmeal01** [comment]
paste this code to the end of jad file
Glu-Cheats-Enable: true

Tested the cheat and it works fine, crash is immortal.

**Comment by bartlomiejduda** [comment]
Ok, now it works fine. I was probably doing something wrong earlier. Sorry for the trouble, this issue can be closed. ;)
