### ISSUE TITLE
keyremap(the left key --'KEYCODE_MENU' on my phone)doesn't work...

### ISSUE THREAD

**Issue by 1130381752** [nikita36078/J2ME-Loader#631]
**Emulator version:v1.5.5
**Device:**
``A android has entity keys, when I set the keyremap(the left key --'KEYCODE_MENU' on my phone, set it to the left soft key), it doesn't work, I press the left key(Menu Key), the emulator pops up a dialog...``
**Android version:4.4.4

**Description of the issue:**
``When I try to modify the code, I removed all the function about the Menu Key,  I pressed the Menu Key, It doesn't work as well, but the emulator doesn't pop up the dialog any more...

Can you consider about changing "press Menu Key -- pop up diaglog" to "long Click Menu Key -- pop up diaglog", and let the Menu Key can be remaped?``

**Comment by nikita36078** [comment]
The menu key remapping is added in the latest version.
