### ISSUE TITLE
Error opening JARs from Android system WebView links

### ISSUE THREAD

**Issue by Nokia64** [nikita36078/J2ME-Loader#632]
**Emulator version:**
1.5.5-open

**Device:**
Samsung SM-G357FZ

**Android version:**
Android 4.4.4

**Description of the issue:**

J2ME Loader fails to open links opened from system WebView.

I'm working on a HTML page like this:
![Screenshot_2020-02-05-22-29-46](https://user-images.githubusercontent.com/57576450/73885426-a37a0f80-485f-11ea-8e1d-03de5bd21f3a.png)
It's meant to serve as a game collection preview, with links to the collection's games stored on the sdcard.

Both the page and the games are stored on the device's internal storage. There's no external content from the internet.
 Page is opened using Android's "HTMLViewer":
![Screenshot_2020-02-05-22-28-50](https://user-images.githubusercontent.com/57576450/73885787-4c286f00-4860-11ea-8c99-635a743a8043.png)

When clicking on the linked .JARs (Linked to internal storage), J2ME Loader pops up for a second, then this message appears:
![Screenshot_2020-02-05-22-29-53](https://user-images.githubusercontent.com/57576450/73885793-5185b980-4860-11ea-8df3-4ad06bf6a675.png)

I've not been able to look at the error log, so I don't know what's going wrong. I suspect J2ME Loader does not support the way the URL is given.
Would be great if it stored crash logs to sdcard like it does with standard game logs.

Thanks.

**Comment by Nokia64** [comment]
Here's an example, to aid in reproducing it.
[j2l-bug.zip](https://github.com/nikita36078/J2ME-Loader/files/4164963/j2l-bug.zip)
Extract the files and open the HTML files with "HTMLViewer"
Open the linked ".jar" file.

**Comment by woesss** [comment]
This seems to be a bug of the HtmlViewer itself. Its file-provider is closed for other applications:
```
        <provider
            android:name="FileContentProvider"
            android:exported="false"
            android:multiprocess="false"
            android:authorities="com.android.htmlfileprovider"
            android:syncable="false"
            android:grantUriPermissions="true" />
```

**Comment by Nokia64** [comment]
Ok. Thanks for the insight into the J2ME Loader-unrelated problem.
