### ISSUE TITLE
NFS:The Run can't open

### ISSUE THREAD

**Issue by Flytheshrimp** [nikita36078/J2ME-Loader#634]
**Emulator version:**

After 1.5.0(1.5.3-play , 1.5.5-play)
**Game version:**
Need for speed The Run
SimpChinese,full-3D and supports touch 
**Game resolution:**
``(For example, 240x320 or 640x360)``
Unknown,maybe 640x360(The website i download it say it's for 640*360,but it work in 640*360 seems not good,things are too small and texts not on right place)
**Device:**
``(For example, Samsung Galaxy S7)``
xiaomi redmi 7 (CN)
**Android version:**
9
**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
Game works perfectly when i using version before 1.5.3(exp.ver1.5.0,ver1.4.x ,e.g.),but it will not play when using ver e.g 1.5.3 1.5.5.
Last version can open it
![Screenshot_2020-02-09-23-17-52-856_ru playsoftware j2meloader](https://user-images.githubusercontent.com/29660486/74104766-fff86a00-4b92-11ea-8d06-db1fd3c5fc72.jpg)
main menu
![Screenshot_2020-02-09-23-17-42-423_ru playsoftware j2meloader](https://user-images.githubusercontent.com/29660486/74104771-0be42c00-4b93-11ea-8aae-46aa40a646e6.jpg)
errors,1.5.5
![Screenshot_2020-02-09-23-15-26-376_ru playsoftware j2meloader](https://user-images.githubusercontent.com/29660486/74104774-143c6700-4b93-11ea-9a16-7b709050c5a5.jpg)
By the way,i can provide the jar inorder to focus the problem.(it's very slow and hard to connect VPN in China.Although i'm a chinese ,i still know to use google drive and meganz.)

**Comment by nikita36078** [comment]
Can you try version 1.5.5 from here (https://github.com/nikita36078/J2ME-Loader/releases)? It looks like you've somehow downloaded a wrong apk.

**Comment by Flytheshrimp** [comment]
> Can you try version 1.5.5 from here (https://github.com/nikita36078/J2ME-Loader/releases)? It looks like you've somehow downloaded a wrong apk.

Well,the problem is gone. It's the apk's fault.I think that I shouldn't download from a website in china.Although it's very fast.Maybe it has been modded in order to add some Ads. but,you know,it's Really Slow to download from github in China.Like 33.6k Dial-up.
