### ISSUE TITLE
About the port of Where's My Water? and Sonic Advance

### ISSUE THREAD

**Issue by TwilightSparkleLover** [nikita36078/J2ME-Loader#637]
**Emulator version:**
1.4.0-play

**Game version:**
1.0.0

**Game resolution:**
``(For example, 240x320 or 640x360)``
240*320
**Device:**
``(For example, Samsung Galaxy S7)``
Huawei P9
**Android version:**
8.0.0
**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
The port of Where's My Water? is slow on my Android device with this software but faster on my Windows with KEmulator
And I can't run the port of Sonic Advance
Should I change the fps?

**Comment by nikita36078** [comment]
Why do you use such ancient version of the emulator? The latest version is 1.5.6.
