### ISSUE TITLE
Can't start normal gameplay (Hungry Puppy 3D)

### ISSUE THREAD

**Issue by Xane123** [nikita36078/J2ME-Loader#638]
**Emulator version:**
1.5.6-play

**Game version:**
1.2.2

**Game resolution:**
176x220

**Device:**
Google Pixel 2

**Android version:**
10

**Description of the issue:**
Hungry Puppy is a game I remember playing many years ago. I'd like to make custom levels in it, but I can only navigate the game's main menu and even enter the level editor (which even KEmulator freezes upon trying).

Regardless of how I try to do it, I can't actually enter gameplay. No error appears on-screen or anything, but it stays in the menu, ignoring my keypress, and never starts showing the 3D level.

![Sequence 01](https://user-images.githubusercontent.com/17244146/75096730-63f63780-5570-11ea-8a85-0488cd4a2e92.gif)

Here's a log file, saved after I tried entering the tropical level list five times (ADVENTURE > TROPICAL). Each time, a "WaterT" error appears in the log.
[log.txt](https://github.com/nikita36078/J2ME-Loader/files/4239685/log.txt)

**Comment by nikita36078** [comment]
It's a Mascot Capsule 3D game, so it won't show graphics anyway, that's the main problem.

**Comment by woesss** [comment]
@Xane123, I'm sorry - tech. details not english.
@nikita36078, кроме капсулы здесь ещё один нюанс - несоблюдение регистра при загрузке ресурсов. Не думал, что аукнется отказ от распаковки - но вот те-на-те. Хотя в PC-эмуляторах тоже провал (может реально на каких-то Нокиях ресурсы и были регистро-независимы, убедиться нет возможности)  костылик я придумал и проверил - при загрузке мидлета взять entry-names из jar в `Map<path, path>` и дополнить lower-case псевдонимами `map.put(path.toLowerCase(), path)`. При загрузке ресурса проверить эту `Map` на оригинал, потом на `map.get(resName.toLowerCase()` - соответственно загружать то что найдено. PR зареквестить в лом - много мерге-конфликтов с рабочей ветки будет, лень разгребать.

**Comment by nikita36078** [comment]
@woesss Спасибо, придется так и сделать. Проверил на Nokia 5320 (s60v3), 3710 (s40v3) - подобный код падает с IOException. Я так понимаю, соньки при установке распаковывали игры, поэтому в эксклюзиве можно было и не заморачиваться с регистром.

**Comment by woesss** [comment]
@nikita36078, что это я про Нокию вспомнил...? Аппаратов SE у меня было несколько штук и до сих пор валяется дамп ФС с какого-то из них - не было там распаковки, да и необязательно регистро-независимость связана с ФС, вполне могла быть и в реализации zlib.

**Comment by SuperWillow** [comment]
@Xane123, проблема не в игре, а в устройстве.  Попробуй обновить версию программы, а у меня игра отлично работает. Значит, проблема в графике.
https://user-images.githubusercontent.com/87235362/202227195-a6053d7a-cb3e-4e1e-b5e4-6f56d6021fb2.mp4

**Comment by nikita36078** [comment]
Fixed
