### ISSUE TITLE
[Forsaken Fortress] issues

### ISSUE THREAD

**Issue by Lanz89** [nikita36078/J2ME-Loader#640]
**Emulator version: 1.5.6
Game version: v 1.0.0 & v 1.0.1
Game resolution: 176x220
Device: Realme Pro 2
Android version: 9**
......................................
Issue: There are 2 versions of this game. Both have problem.

**V 1.0.0** = Can't open. Not compatible?

- https://spac1.net/files/view/forsaken-fortress-549650/

![Screenshot_2020-03-05-14-15-01-72_7811e6ffdebce77637db4a754a2e47d6](https://user-images.githubusercontent.com/46138298/75954483-c1827080-5eee-11ea-88c2-ab6990f5c3bc.png)

---------
**V 1.0.1** = The game keep crashing when hit this type of enemy.

- https://phoneky.com/games/?id=j2j31

![Screenshot_2020-03-05-14-25-46-47_7811e6ffdebce77637db4a754a2e47d6](https://user-images.githubusercontent.com/46138298/75954513-d4954080-5eee-11ea-86ce-7df8be25c046.png)

![Screenshot_2020-03-05-14-15-46-54_7811e6ffdebce77637db4a754a2e47d6](https://user-images.githubusercontent.com/46138298/75954529-deb73f00-5eee-11ea-8946-605d10c7465d.png)

**Comment by woesss** [comment]
V 1.0.0 - requires screen resolution 176x208

**Comment by Lanz89** [comment]
> V 1.0.0 - requires screen resolution 176x208

Now i can open v1.0.0. 

But, the game still crashed when i fight that enemy. Maybe game file problem?
