### ISSUE TITLE
Demon Hunter II (Soco Soft) [Game Freeze]

### ISSUE THREAD

**Issue by Lanz89** [nikita36078/J2ME-Loader#644]
**Emulator version: 1.5.6
Game version: v1.0
Game resolution: 132x176
Device: Realme Pro 2
Android version: 9**
......................................
Issue: Can't start the game. The game freeze at the loading screen. Any solutions?

* This is a rare game. Only this version is available online.

Download Link:- http://www.mediafire.com/file/61wyy0mfpua2z5p/DemonHunterII.jar/file

![Screenshot_2020-03-20-01-26-14-87_7811e6ffdebce77637db4a754a2e47d6](https://user-images.githubusercontent.com/46138298/77096580-7e75e080-6a4a-11ea-8a92-e4f34d7b55de.png)

**Comment by nikita36078** [comment]
Fixed
