### ISSUE TITLE
Back-up bug

### ISSUE THREAD

**Issue by AdityaMH** [nikita36078/J2ME-Loader#645]
This happen when i back-up j2me-loader folder from old phone to new one (android 9).
![MIDlet not found](https://user-images.githubusercontent.com/33791472/77164426-ccd6be00-6ae2-11ea-89c4-20515f38a02c.png)

**Comment by LuisFellp** [comment]
try reinstalling it. i think you won't lose your save, because i haven't lost mine.

**Comment by nikita36078** [comment]
Have you installed J2ME Loader before copying this folder? Try to clear the app data, it should fix the issue.

**Comment by AdityaMH** [comment]
I'm trying to clear app data, but nothing happen, and still same.

But now, I have new solution.
Just reinstalling from "/sdcard/J2ME-Loader/converted/~game name~/res.jar"
Unfortunately, not all game have that file in folder.

**Comment by nikita36078** [comment]
If you still have that backup, could you share it? I think something is wrong with it.

**Comment by woesss** [comment]
@AdityaMH, Games without names start when you click on the list? - if not, save the log after the attempt.  
Have you tried to clear the **emulator** app data (via the Android system settings)? - also save the log at the first start after cleaning.

**Comment by AdityaMH** [comment]
Now, i know what reason this problem.
![Look this](https://user-images.githubusercontent.com/33791472/77411590-3ad6fa00-6def-11ea-8cf9-2fc55a2c70c2.jpg)

I don't know where this problem coming from (maybe from android copying rules or from file manager), but now all fixed.
Someday if i want to backup, i need to packed to zip first.
