### ISSUE TITLE
Need for Speed: The Run - Black Screen

### ISSUE THREAD

**Issue by reenaosm** [nikita36078/J2ME-Loader#646]
**Emulator version:**J2ME Loader v.1.5.6

**Game version:**Need for Speed : Hot Pursuit (3D version) is v.4.3.47  
Need for Speed : The Run (3D version) is v.4.9.53

**Game resolution:**240x320
``(For example, 240x320 or 640x360)``

**Device:**Android 4.4.4 ver. BIHEE A9

**Android version:**4.4.4 ver.

**Description of the issue:**--
Those two 3D java games can't load 3D Flow images. Black screens for both two games.
Here come the 6 screenshots, these are the proof of my issue. So I hope you can fix this problem as early as possible. Thank you very much.

First 3 pics about Need for Speed : Hot Pursuit 3D ver.
![Screenshot_20200323-150411](https://user-images.githubusercontent.com/62536531/77291494-57086780-6d19-11ea-8396-7e5d210af575.png)
![Screenshot_20200323-150454](https://user-images.githubusercontent.com/62536531/77291497-58d22b00-6d19-11ea-82dd-6523241e7719.png)
![Screenshot_20200323-150503](https://user-images.githubusercontent.com/62536531/77291499-58d22b00-6d19-11ea-9476-df189aa68af5.png)

Then 3 pics from Need for Speed : The Run 3D ver.
![Screenshot_20200323-150636](https://user-images.githubusercontent.com/62536531/77291661-ababe280-6d19-11ea-83c3-165b0acf347d.png)
![Screenshot_20200323-150649](https://user-images.githubusercontent.com/62536531/77291664-acdd0f80-6d19-11ea-9ec8-97b21aba28db.png)
![Screenshot_20200323-150715](https://user-images.githubusercontent.com/62536531/77291668-acdd0f80-6d19-11ea-894d-18816c383121.png)

That's all about my reported issue.

**Comment by nikita36078** [comment]
Both games use Mascot Capsule engine, which isn't implemented yet (but I'm already working on it).

**Comment by reenaosm** [comment]
Having seen the reply, I wish you would succeed!

**Comment by nikita36078** [comment]
Fixed
