### ISSUE TITLE
is it possible to add LCD3X shader to make the picture looks close to real?

### ISSUE THREAD

**Issue by xusonfan** [nikita36078/J2ME-Loader#647]
just like the 'myboy'(a GBA game emulator),it provides many kinds of shaders and the LCD3X shader make the game looks much pretty and clear，is it possible to achieve?
Thanks for your hard work on this application!😊

**Comment by nikita36078** [comment]
It's impossible to add it now, current implementation doesn't support shaders. Maybe it will be changed in the future.
