### ISSUE TITLE
Need for Speed - Most Wanted 2 (2014 3D Java Ver.) - Nitro Boost Bugs

### ISSUE THREAD

**Issue by reenaosm** [nikita36078/J2ME-Loader#648]
**Emulator version:**v.1.5.6

**Game version:**v.0.0.12

**Game resolution:**240x320

**Device:** Android v.4.4.4 BIHEE A9
**Android version:** v.4.4.4

**Description of the issue:**
Bugs when it comes to gaining the nitro boost, which is essential to be replenished in the game to win the races.
The game help says gaining boosts can be more quickly replenished by smashing the obstacles or having a near miss with a car.
It's too hard to describe here, so I captured some screenshots of the help text here, about which it is a bit easier for you to understand my issue. Here are the images I will show you in the different sections below, please take a look.

In case you were misled, I firstly gave you a pic about this game's logo.
![1_320903](https://user-images.githubusercontent.com/62536531/77492314-3a844080-6e7b-11ea-8d98-82671983d898.png)

Then, here come the help guideline screenshots:
![1FF7901523CEC293A6E1869B3ED256E3](https://user-images.githubusercontent.com/62536531/77492234-f8f39580-6e7a-11ea-86d6-2799f1e72a89.jpg)
![8F60785257ABD8EE4B470EEA91481132](https://user-images.githubusercontent.com/62536531/77492238-fabd5900-6e7a-11ea-8599-f692790f3178.jpg)

The game during the playing procedure.
![4_programView_320903](https://user-images.githubusercontent.com/62536531/77492487-a4044f00-6e7b-11ea-8b4c-0e8517abd095.jpg)
![6_programView_320903](https://user-images.githubusercontent.com/62536531/77492491-a5ce1280-6e7b-11ea-9fe2-84d81461526e.png)

That's all about my issue to be solved. 
I hope you can fix it as early as you can, thank you very much. (^_^)

**Comment by nikita36078** [comment]
I've checked the game on Nokia 5320, and it works in the same way, no nitro boost from near misses, obstacles, and it seems like you can't destroy police cars (?). It's really strange, like the help was copypasted from another game.

**Comment by reenaosm** [comment]
Okay, I see. Maybe it is because this game was released in 2014, when the Symbian phones were gradually eliminated, so the developers of this game didn't take the bugs seriously.

**Comment by reenaosm** [comment]
Okay, it's fine. Even if I can't get a better result, I can still win the races and pass all the stages. I can still play this game fluently without this enhancement. No need to care about this problem again.
