### ISSUE TITLE
change sounfount support

### ISSUE THREAD

**Issue by molo32** [nikita36078/J2ME-Loader#652]
you can implement a function to
change the internal sounfount of android to sound font of the original mobile phones like here https://youtu.be/ahW627WGWqc

**Comment by nikita36078** [comment]
This feature is already planned #569.

**Comment by HusniMuhammad** [comment]
> you can implement a function to change the internal sounfount of android to sound font of the original mobile phones like here https://youtu.be/ahW627WGWqc

Video in private
