### ISSUE TITLE
Hello my friend can you build a version suitable for pc running?

### ISSUE THREAD

**Issue by Sdator** [nikita36078/J2ME-Loader#656]
Or your better suggestion?

**Comment by nikita36078** [comment]
No, it's impossible to port J2ME Loader to Windows, it contains a lot of Android-specific code and has targeted this platfrom since beginning. You can try KEmulator, it's the most stable java emulator on PC.

**Comment by Sdator** [comment]
> 不，将J2ME Loader移植到Windows是不可能的，它包含许多Android特定的代码，并且自开始以来就针对该平台。您可以尝试KEmulator，它是PC上最稳定的Java模拟器。

thanks for your suggestion.
