### ISSUE TITLE
Low frame rate in android 8.0 and later

### ISSUE THREAD

**Issue by hongbao80** [nikita36078/J2ME-Loader#657]
**Emulator version:** All version

**Game version:** 2.5.8

**Game resolution:**
``(For example, 240x320 or 640x360)`` Multi screen

**Device:**
``(For example, Samsung Galaxy S7)`` Samsung A5 2017 and a lot of device

**Android version:** 8.0 and later

**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``

When game started, frame rate is too low, about 2-3 fps, so we can play game. Graphics is delayed too much. Please, please fix it.

**Comment by nikita36078** [comment]
What is the name of this game?

**Comment by hongbao80** [comment]
@nikita36078 
Here is link download: http://wap.teamobi.com/game/jar/30/13
A lot of model android has same issue, i can't list all of them.

**Comment by nikita36078** [comment]
Just in case - did you test it on the latest emulator version, 1.5.6?

**Comment by nikita36078** [comment]
@hongbao80 I can't reproduce this issue, so more info is needed. I've made a test version - https://mega.nz/file/dYVnQKBa#Wv3aGcm_Gst0bK7rkzx-C2RP0-bq78VHc6TXzG_Jomk.
You need to install it, open the game and when you will experience a low fps - select "Save log" in the emulator menu, wait 15 seconds and send me this file - J2ME-Loader/test.trace.

**Comment by hongbao80** [comment]
@nikita36078 Check your gmail, please.

**Comment by nikita36078** [comment]
Thanks, now I have some ideas how to fix it.

**Comment by AdityaMH** [comment]
Revival 2 have same issue too.

**Comment by nikita36078** [comment]
@AdityaMH Android 8?

**Comment by AdityaMH** [comment]
Android 9, @nikita36078

**Comment by nikita36078** [comment]
Fixed

@AdityaMH I'll open a separate issue, these bugs aren't connected.
