### ISSUE TITLE
Asphalt 2 Graphic Bug

### ISSUE THREAD

**Issue by DavidBrazSan** [nikita36078/J2ME-Loader#658]
**Emulator version:**
``1.5.6-dev-1180``

**Game version:**
``1.0.2``

**Game resolution:**
``240x320``

**Device:**
``Samsung Galaxy J2 J200M``

**Android version:**
``5.1.1``

![Screenshot_20200422-142908](https://user-images.githubusercontent.com/60136669/80015166-b89e2c00-84a7-11ea-815a-4507488ac1a2.png)

![Screenshot_20200422-142918](https://user-images.githubusercontent.com/60136669/80015176-b9cf5900-84a7-11ea-86ef-83b60407ab60.png)

![Screenshot_20200422-142922](https://user-images.githubusercontent.com/60136669/80015177-ba67ef80-84a7-11ea-914f-da6872b0a6c4.png)

**Comment by nikita36078** [comment]
Fixed.

**Comment by DavidBrazSan** [comment]
Thank you very much
