### ISSUE TITLE
What new 

### ISSUE THREAD

**Issue by skelletR** [nikita36078/J2ME-Loader#66]
What new in version J2ME_Loader-1.2.6-test2?

**Comment by AdityaMH** [comment]
Fix switch keylayout & update crowdin translation. That's all i know.

**Comment by skelletR** [comment]
Thanks

**Comment by DiegoSousa123** [comment]
Some games flowed with better graphics, such as Deep 3D, Galaxy on Fire 2, and the game Gladiator now runs perfectly

**Comment by skelletR** [comment]
That is nice thanks

**Comment by nikita36078** [comment]
And I also added MIDlet selection for apps with few MIDlets
