### ISSUE TITLE
You've seen this mod the app?

### ISSUE THREAD

**Issue by DavidBrazSan** [nikita36078/J2ME-Loader#660]
I found this mod on this site
https://a2zapk.com/788712-j2me-loader-1-5-5-b1326-mc-b093-mod-a2z.html
some functions are interesting

**Comment by AdityaMH** [comment]
https://github.com/woesss/JL-Mod/releases

**Comment by stevenfelix505** [comment]
#240 @nikita36078 please add Mascot Capsule 3D support

**Comment by nikita36078** [comment]
Yes, I know about this, at least some features from this version will be added in the future (along with Mascot Capsule).

**Comment by nikita36078** [comment]
And you can ask questions on Discord, I usually reply faster there.

**Comment by stevenfelix505** [comment]
OK @nikita36078
