### ISSUE TITLE
The application is closing

### ISSUE THREAD

**Issue by DavidBrazSan** [nikita36078/J2ME-Loader#664]
When playing any game the app closes when I press more than one button simultaneously without stopping..

**Comment by amarcioz** [comment]
Which game?

**Comment by nikita36078** [comment]
Fixed. New version will be released soon

**Comment by DavidBrazSan** [comment]
OK. Thank you very much

**Comment by jack1432** [comment]
The keyboard is still talking here, but now it only happens in some games like: Crash Titans and Crash Nitro Kart 2, in these games the keyboard disappears when you click any button on the keyboard.

**Comment by nikita36078** [comment]
@jack1432 Can you provide me versions of these games?

**Comment by jack1432** [comment]
[Here it is](https://mega.nz/#F!0B1iECpJ!UI-SDmVqFPndKC3RXR9hYA)

**Comment by jack1432** [comment]
The same thing happens with the game of this problem here. (#589)

**Comment by nikita36078** [comment]
@jack1432 Wait, 3D Formula just crashes in the menu, how is that connected? You said the keyboard dissapears, I can't catch this bug - https://youtu.be/Gizp6uCQ6QY. Am I doing something wrong?

**Comment by jack1432** [comment]
In the video shows how it happens
https://youtu.be/EIdfGe5tlLU

**Comment by nikita36078** [comment]
It looks like you use the same working folder for original J2ME Loader and the modified version. The mod author asked to not do that, it breaks games. Reset the settings for these games, it will fix the issue,
