### ISSUE TITLE
Audio latency

### ISSUE THREAD

**Issue by DavidBrazSan** [nikita36078/J2ME-Loader#665]
Implementing the audio traffic option can improve games with lag?

**Comment by nikita36078** [comment]
What do you mean by "audio traffic"?

**Comment by DavidBrazSan** [comment]
eu quis dizer a frequencia do audio como em outros emuladores

**Comment by DavidBrazSan** [comment]
meant the frequency of audio as in other emulators

**Comment by DavidBrazSan** [comment]
the audio can cause slowdowns in some games, right?

**Comment by nikita36078** [comment]
Theoretically yes, but it in fact there's no noticeable difference in most games. Anyway, current audio implementation of the audioplayer doesn't support the latency control or overall quality change.

**Comment by DavidBrazSan** [comment]
It's ok. thank you very much for your attention
