### ISSUE TITLE
¡Serious Graphic Issue with 2D gameloft games! Tiles doesn't show properly

### ISSUE THREAD

**Issue by Javauser96** [nikita36078/J2ME-Loader#666]
**Emulator version:** 1.5.8

**Game version:**
Alien Quarantine 1.2.3
Diamond Rush 1.0.1

**Game resolution:**
240x320

**Device:**
Samsung Galaxy J7

**Android version:** 8.1.0

**Description of the issue:**
Since i download the last version 1.5.8, the 2D games from Gameloft doesn't work well showing on screen the tiles in a bad position.

![Screenshot_20200427-194602_J2ME Loader](https://user-images.githubusercontent.com/64431719/80403385-cb599c00-88bf-11ea-9a56-3bc7c2f5587e.jpg)

![Screenshot_20200427-194807_J2ME Loader](https://user-images.githubusercontent.com/64431719/80403573-170c4580-88c0-11ea-9bb3-6b8c59e42c76.jpg)

EDIT: The issue is not only with Gameloft Games is with A LOT of 2D games.

**Comment by amarcioz** [comment]
The same with these games Crash Titans and Crash Mutant Island

**Comment by nikita36078** [comment]
Fixed
