### ISSUE TITLE
Game freezes when turns off the screen

### ISSUE THREAD

**Issue by DavidBrazSan** [nikita36078/J2ME-Loader#669]
For some reason when I turn off the screen with the game paused or not, it crashes and I can't play. To come back presico minimize the game and return. can this be solved?

**Comment by nikita36078** [comment]
What game is it?

**Comment by DavidBrazSan** [comment]
> What game is it?

In every game

**Comment by nikita36078** [comment]
I need more info, not an empty issue. What device? Android version? And 2-3 examples of such games.

**Comment by DavidBrazSan** [comment]
Device: Samsung Galaxy J200M
Android: 5.1.1

**Comment by DavidBrazSan** [comment]
An example  https://youtu.be/BFfJVgXh2-k
but it happens with all games

**Comment by nikita36078** [comment]
Thank you, now I see what happens. There's already an issue about this bug - #388, but only now I realized it's related to sleeping, not minimizing/lack of memory.

**Comment by nikita36078** [comment]
Closed as duplicate

**Comment by DavidBrazSan** [comment]
I'm happy to help
