### ISSUE TITLE
Do not have a button layout

### ISSUE THREAD

**Issue by 7bbbbbb** [nikita36078/J2ME-Loader#67]
Please add a option to personalize the position of buttons in the screen.  This app is very nice 10/10

**Comment by DiegoSousa123** [comment]
This option already exists, it is in the menu

**Comment by 7bbbbbb** [comment]
In which part is the option

**Comment by DiegoSousa123** [comment]
She is in the app flyout menu, below the "exit" option.

**Comment by nikita36078** [comment]
Press menu button when game is launched, select [Common settings] and then Keylayout edit mode.

**Comment by 7bbbbbb** [comment]
Sorry for my ignorance but what is the menu button?

**Comment by nikita36078** [comment]
I mean hardware menu button. If you don't have it, enable ActionBar in the emulator settings (in the main menu).

**Comment by 7bbbbbb** [comment]
Thanks
But that option should come on by default
It was difficult to find.
