### ISSUE TITLE
Splinter Cell Conviction - Menu theme not playing

### ISSUE THREAD

**Issue by Gamerhenky** [nikita36078/J2ME-Loader#670]
**Emulator version:**
1.5.9

**Game version:**
1.1.4 (K800i)

**Game resolution:**
240x320

**Device:**
Vivo Y12

**Android version:**
9.0
**Description of the issue:**
The main menu/theme music doesn't play like a normal in anywhere else until minimizing then chose J2ME Loader itself to fix this. As like the other Gameloft games that only support K800i specific, this is the only definitive version choice of mine and support both music/sound effects, has bit more sprites and graphical effects.

**Comment by Gamerhenky** [comment]
It also happen with Prince of Persia: The Forgotten Sands too where the main menu can only be played after quitting the gameplay, minimizing is also doesn't work.

**Comment by nikita36078** [comment]
Fixed
