### ISSUE TITLE
Problem with 3D games from Fishlabs

### ISSUE THREAD

**Issue by Lippi391** [nikita36078/J2ME-Loader#671]
**Emulator version:**
1.5.9 (F-Droid)

**Game version:**
Galaxy on Fire 2 for SE K800i (Link: https://phoneky.com/games/?id=j4j13376) and several other games, like Deep 3D oder Rally Master Pro

**Game resolution:**
240x320

**Device:**
Sony Xperia X Compact

Android 8.0.0

**Description of the issue:**
I can't see any 3D objects, only the backgrounds and menus. I already tried hardware acceleration and Immediate processing mode, without success. The games work fine on the Sony Ericsson SDK emulator.

**Comment by nikita36078** [comment]
J2ME Loader currently doesn't support Mascot Capsule 3D games, so you can either download Galaxy on Fire 2 for Nokia, or use this mod that can run Mascot Capsule games - https://github.com/woesss/JL-Mod

**Comment by Lippi391** [comment]
Nice, the modded version works flawlessly, thank you! ;)

**Comment by Gamerhenky** [comment]
> J2ME Loader currently doesn't support Mascot Capsule 3D games, so you can either download Galaxy on Fire 2 for Nokia, or use this mod that can run Mascot Capsule games - https://github.com/woesss/JL-Mod

Is it J2ME Loader modded version that supports Mascot Capsule 3D looks unfinished yet?

**Comment by amarcioz** [comment]
> J2ME Loader currently doesn't support Mascot Capsule 3D games, so you can either download Galaxy on Fire 2 for Nokia, or use this mod that can run Mascot Capsule games - https://github.com/woesss/JL-Mod
@nikita36078 When will "Mascot Capsule" be supported?  I prefer to play on the original J2ME Loader.

**Comment by nikita36078** [comment]
Mascot Capsule isn't stable yet, it will be added in the future.
@Gamerhenky You can create an issue about these glitches in the mod repository,
