### ISSUE TITLE
3D Qblast - low fps

### ISSUE THREAD

**Issue by fireclouu** [nikita36078/J2ME-Loader#673]
**Emulator version:**
1.5.9-open

**Game version:**
1.0.0

**Game resolution:**
128x128

**Device:**
Redmi 5A

**Android version:**
8.1.0

**Description of the issue:**
[link to file](http://www.mediafire.com/file/9rhsbmqig1k69vx/3d_qblast.jar/file)

**Comment by nikita36078** [comment]
How low is fps? 13 FPS is the native framerate for this game.

**Comment by fireclouu** [comment]
timer seems to count slower than running it on java phone, also tested on pspkvm where a second decrements exactly like real time speed

**Comment by fireclouu** [comment]
my bad, I forgot to update to 1.6.0-open before testing it, now works properly
