### ISSUE TITLE
HoverChase - stuck at loading screen

### ISSUE THREAD

**Issue by fireclouu** [nikita36078/J2ME-Loader#674]
**Emulator version:**
1.6.0-open

**Game version:**
1.0.7

**Game resolution:**
176x220

**Device:**
Redmi 5A

**Android version:**
8.1.0

**Description of the issue:**
stuck at loading screen
[link to file](http://www.mediafire.com/file/l6fc57pu5k4e81t/007-HoverChase.jar/file)

**Comment by nikita36078** [comment]
Same fix as for #690
