### ISSUE TITLE
Gadgies - NullPointerException

### ISSUE THREAD

**Issue by fireclouu** [nikita36078/J2ME-Loader#677]
**Emulator version:**
1.6.0-open

**Game version:**
1.2

**Game resolution:**
240x320

**Device:**
Redmi 5A

**Android version:**
8.1.0

**Description of the issue:**
displays java.NullPointerException but works on other emulators
[link to file](http://www.mediafire.com/file/6gdbpsfwo53u178/gadgies.jar/file)

**Comment by nikita36078** [comment]
Fixed
