### ISSUE TITLE
hangs when activity goes background for old games

### ISSUE THREAD

**Issue by fireclouu** [nikita36078/J2ME-Loader#678]
**Emulator version:**
1.6.0-open

**Game version:**
n/a

**Game resolution:**
(most of old games <240x320)

**Device:**
Redmi 5A

**Android version:**
8.1.0

**Description of the issue:**
It mostly happens on old games only. When you put the app in background, and then go back again, game would not respond to any input and sometimes the game itself froze but you can still open Common Options when you press back. I cant quite call it "to hang" cause [this particular game (3D Qblast)](http://www.mediafire.com/file/9rhsbmqig1k69vx/3d_qblast.jar/file) plays animation normally (wait for the bouncing ball animation and do so above) after doing it. My observation is if the game had music playing while putting it on background and then going foreground again, it triggers the bug. This also happen on game Rayman 3 on #675 since it plays music even in background too.

**Comment by fireclouu** [comment]
it appears to be a duplicate issue of #388

**Comment by nikita36078** [comment]
Yes, it's the same problem
