### ISSUE TITLE
Performance problem in 3D games

### ISSUE THREAD

**Issue by jack1432** [nikita36078/J2ME-Loader#680]
**Emulator version:**

1.6.1-open
**Game version:**

**Game resolution:**

Multi resolution
**Device:**

Samsung Galaxy J5 Pro
**Android version:**
9
**Description of the issue:**
When I increase the resolution a lot in 3D games that support multi resolution the game performance drops a lot making it impossible to play, is this a limitation of J2ME itself? Is there any way to change that?

**Comment by jack1432** [comment]
Example: Tower Bloxx Deluxe version 1.0.2

**Comment by Issei69** [comment]
I had to download and tested that uninteresting game.I dont see any performance drop..full 60fps or sometimes 61.. It's your cpu which is weak...

**Comment by Issei69** [comment]
Samsung J series is banned btw.lol

**Comment by nikita36078** [comment]
@Issei69 He's talking about launching games in non-default resolutions, like HD or FullHD. And don't offtop, please.
@jack1432 It's both emulator and engine problem, I will try to improve 3d perfomance in the future.
