### ISSUE TITLE
Dark theme also changes game colors

### ISSUE THREAD

**Issue by jack1432** [nikita36078/J2ME-Loader#681]
**Emulator version:**

1.6.1-open
**Game version:**

1.0.0
**Game resolution:**

240x320
**Device:**

Samsung Galaxy J5 Pro
**Android version:**
9
**Description of the issue:**
When the theme is changed to Dark the colors of some games are also changed, why does it happen only in some games? is this on purpose?

With Dark theme enabled:
![Screenshot_20200512-171231_J2ME Loader](https://user-images.githubusercontent.com/36806488/81742359-5ddc6c80-9476-11ea-99ae-8f8044c81262.jpg)

With Dark theme off:
![Screenshot_20200512-171325_J2ME Loader](https://user-images.githubusercontent.com/36806488/81742701-ec50ee00-9476-11ea-8ee9-6535d85e053c.jpg)

**Comment by nikita36078** [comment]
It's the same problem as #562. I still don't know what causes this bug.
