### ISSUE TITLE
Can't play streaming radio (Mocha Radio)

### ISSUE THREAD

**Issue by javi2man** [nikita36078/J2ME-Loader#682]
**Emulator version:**
1.6.1

**Game version:**
1.1.0

**Game resolution:**
``(For example, 240x320 or 640x360)``
multi
**Device:**
``(For example, Samsung Galaxy S7)``
Huawei t1 7.0 & Honor5x
**Android version:**
4.4 & 6.0.1
**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
The emulator isn't able to play online live radio, on Mocha Radio, please fix it if u can, thanks!

**Comment by nikita36078** [comment]
Fixed
