### ISSUE TITLE
Mocha Weather crashes

### ISSUE THREAD

**Issue by javi2man** [nikita36078/J2ME-Loader#683]
**Emulator version:**
1.6.1

**Game version:**
1.0.0

**Game resolution:**
``(For example, 240x320 or 640x360)``
multi
**Device:**
``(For example, Samsung Galaxy S7)``
Huawei t1 7.0 & Honor5x
**Android version:**
4.4 & 6.0.1
**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
 On Mocha Weather, when i select a city to show it's weather, the app shows loading... and then crashes, please fix it if u can, thanks!

**Comment by nikita36078** [comment]
I can't find version 1.0.0 (or you just didn't specify the version?), but version 1.1.0 from [there](http://ovi.sigma.apps.bemobi.com/en_fr/mocha_weather.html?pos=1) shows the forecast without any problems.

**Comment by javi2man** [comment]
Yes, you 're right.. with version 1.1.0 is working perfect. Thanks!
