### ISSUE TITLE
Asphalt 6 - low fps

### ISSUE THREAD

**Issue by fireclouu** [nikita36078/J2ME-Loader#684]
**Emulator version:**
1.6.1-open

**Game version:**
1.0.3

**Game resolution:**
480x800

**Device:**
Redmi 5A

**Android version:**
8.1.0
**Description of the issue:**
low fps when in-game, enabling HW acceleration does not help

**Comment by nikita36078** [comment]
I get stable 30 fps on emulator with Android 8.1, so link on the game is needed.

**Comment by fireclouu** [comment]
here's the version i tested: [link](http://dedomil.net/games/263/download-jar/42931)

**Comment by Issei69** [comment]
![Screenshot_2020-05-14-05-38-42-025_ru playsoftware j2meloader](https://user-images.githubusercontent.com/65318838/81878535-f8879900-95a5-11ea-898c-7651ea26d755.jpg)
Not on mine.i got note 7 pro with Snapdragon 675.Lol

**Comment by Issei69** [comment]
Not much but not constant 50fps..but at least 48~50fps playable

**Comment by nikita36078** [comment]
@fireclouu Just to clarify - what fps are you getting?

**Comment by fireclouu** [comment]
in-game it was 7-11
![Screenshot_2020-05-16-00-13-53-926_ru playsoftware j2meloader](https://user-images.githubusercontent.com/22563129/82072343-2b4aa200-970a-11ea-8edb-15e77c0086f4.jpg)
off-track: 15-20
![Screenshot_2020-05-16-00-14-37-811_ru playsoftware j2meloader](https://user-images.githubusercontent.com/22563129/82072446-5e8d3100-970a-11ea-8fe6-ffc16fe34031.jpg)
menu: 45-50
![Screenshot_2020-05-16-00-15-58-858_ru playsoftware j2meloader](https://user-images.githubusercontent.com/22563129/82072551-79f83c00-970a-11ea-889b-c87fdd7ed8d3.jpg)

**Comment by fireclouu** [comment]
tested on 1.7.2-open, now constantly running on correct speed.
