### ISSUE TITLE
Need for Speed Most Wanted White Square Bug

### ISSUE THREAD

**Issue by PauloTheWizard** [nikita36078/J2ME-Loader#685]
**Emulator version:**
1.6.1

**Game version:**
1.0.2

**Game resolution:**
240x320
``(For example, 240x320 or 640x360)``

**Device:**
Xiaomi Mi Play
``(For example, Samsung Galaxy S7)``

**Android version:**
8.1.0
**Description of the issue:**
White square on the police cars when are getting fire

![sxGpaw8 - Imgur](https://user-images.githubusercontent.com/65317223/84607898-2fdbb500-ae86-11ea-9873-1fa9708d6c15.jpg)

 ``(What's the problem? - Screenshots showing the issue if applicable)``
[

**Comment by PauloTheWizard** [comment]
I tested old version of the J2ME Loader and  the fire is displayed correctly

[https://i.imgur.com/zjGQqZB.jpg]()

Tested on J2ME Loader 1.5.9

**Comment by nikita36078** [comment]
Fixed
