### ISSUE TITLE
Fast and furious fugitive 2d or 3d 

### ISSUE THREAD

**Issue by Issei69** [nikita36078/J2ME-Loader#686]
**Emulator version:** 1.6.1

**Game version:**

**Game resolution:**240x320
``(For example, 240x320 or 640x360)``

**Device:**Redmi note 7 pro
``(For example, Samsung Galaxy S7)``

**Android version:**9.0

**Description of the issue:**The game crashes after the menu starts...cant be played
``(What's the problem? - Screenshots showing the issue if applicable)``

**Comment by nikita36078** [comment]
Fixed
