### ISSUE TITLE
Rockola music player crash

### ISSUE THREAD

**Issue by javi2man** [nikita36078/J2ME-Loader#689]
**Emulator version:**
1.6.1 fix2

**Game version:**
1.0.7

**Game resolution:**
``(For example, 240x320 or 640x360)``
multi
**Device:**
``(For example, Samsung Galaxy S7)``
Honor 5x
**Android version:**
6.0.1
**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
The app crashes when trying to play a mp3 song

**Comment by nikita36078** [comment]
Fixed
