### ISSUE TITLE
Bubbles - gameplay bug

### ISSUE THREAD

**Issue by fireclouu** [nikita36078/J2ME-Loader#690]
**Emulator version:**
1.6.1-fixed2-open

**Game version:**
1.5.0

**Game resolution:**
128x128

**Device:**
Redmi 5A

**Android version:**
8.1.0
**Description of the issue:**
gameplay bug, sprite moves for a while then gets freeze
[link to file](http://www.mediafire.com/file/32orzzxmtjsdi80/Bubbles7210.jar/file)

**Comment by nikita36078** [comment]
It should work with Immediate processing mode enabled.
