### ISSUE TITLE
AlphaMania - gameplay bug

### ISSUE THREAD

**Issue by fireclouu** [nikita36078/J2ME-Loader#691]
**Emulator version:**
1.6.1-fixed2-open

**Game version:**
1.3.1

**Game resolution:**
128x128

**Device:**
Redmi 5A

**Android version:**
8.1.0
**Description of the issue:**
gameplay bug, sprite freezes
[link to file](http://www.mediafire.com/file/9niz13u3kr13bdv/AlphaMania.jar/file)

**Comment by nikita36078** [comment]
Same fix as for #690
