### ISSUE TITLE
City Racer - sprite bug

### ISSUE THREAD

**Issue by fireclouu** [nikita36078/J2ME-Loader#693]
**Emulator version:**
1.6.1-fixed2-open

**Game version:**
1.1

**Game resolution:**
128x128

**Device:**
Redmi 5A

**Android version:**
8.1.0

**Description of the issue:**
player car sprite turns completely black, other sprite also seems to be as well
[link to file](http://www.mediafire.com/file/vdx8b4v1t6ly37a/CityRace.jar)

**Comment by nikita36078** [comment]
Fixed
