### ISSUE TITLE
Highway Racer - app crashes

### ISSUE THREAD

**Issue by fireclouu** [nikita36078/J2ME-Loader#694]
**Emulator version:**
1.6.1-fixed2-open

**Game version:**
1.0

**Game resolution:**
128x128

**Device:**
Redmi 5A

**Android version:**
8.1.0

**Description of the issue:**
game hang then crashes while starting new game
[link to file](http://www.mediafire.com/file/isamner8y6hrfix/HighwayRacerNew.jar/file)

**Comment by fireclouu** [comment]
tested on version 1.7.1, game does not start at all

**Comment by fireclouu** [comment]
was tested on v1.7.5, using poco f3, makes my phone unresponsive and lags a lot, still unplayable

**Comment by nikita36078** [comment]
Go to the game settings, System properties and set com.nokia.mid.ui.DirectGraphics.PIXEL_FORMAT to 444 or 4444. That should solve the issue.
