### ISSUE TITLE
no detection for illegal filenames

### ISSUE THREAD

**Issue by fireclouu** [nikita36078/J2ME-Loader#696]
**Emulator version:**
1.6.1-fixed2-open

**Game version:**
-

**Game resolution:**
-

**Device:**
-

**Android version:**
-

**Description of the issue:**
I have encounter some bad game rip that utilizes some characters in midlet name that is illegal for file and folder naming, but the emulator still process it. The result, that certain file stuck on my storage and cannot be deleted by file managers, idk if the emulator manages to remove it after deletion. I cant find the same copy of the game but recently I reproduce it by renaming the midlet name to add some illegal characters to it. The more "extreme" way of considering this one being critical is to change the any package's midlet name to simply `/\` and proceed to install, expect that all games stored in `converted` file will be overriden and gone forever. Make a backup to `J2ME-Loader` before doing so.

**Comment by nikita36078** [comment]
Fixed
