### ISSUE TITLE
【Weird Bug: Sound Volume Problem！】

### ISSUE THREAD

**Issue by fishlabs** [nikita36078/J2ME-Loader#698]
**Emulator version:**
ALL

**Game version:**
Almost ALL Games

**Game resolution:**
ALL

**Device:**
XiaoMi RedMi3

**Android version:**
5.1
**Description of the issue:**
**Dear developer:
First of all, thank you very much for the simulator you developed!  But I found this simulator has a weird bug: in two resolution versions of the same java game, the music volume of 240 * 320 is lower than 176 * 220!  Very affect the experience!  (I checked with crc, the source code in these two JAR files is exactly the same, the mid music files of the two are also the same, the only difference is that the resolution of the pictures in the two JAR files is different). I very much hope you can fix  This bug!  thank!
In addition, I also found that: in the same game, some scenes have high volume and some scenes have low volume. But when I play these mid files in the music player software, they have the same volume. Therefore, I infer that this should also be  A bug in the simulator.**

**Comment by nikita36078** [comment]
You forgot to specify the most important detail - what game is it?

**Comment by fishlabs** [comment]
Thank you for your last reply!
In fact, many games have the above volume problems when they run on the simulator. Below, I use the attachment function to send you several jar game files whose names discribe their respective existing problems.

By the way, the version of J2ME Loader I used is 1.55, but I think the last version of it should still have the volume problem if the sound related code hasn't changed since version 1.55.
——————The following are attachments:













在 2020-05-30 16:59:58，"Nikita Shakarun" <notifications@github.com> 写道：

You forgot to specify the most important detail - what game is it?

**Comment by fishlabs** [comment]
**Dear author, I replied your mail and attached the Jar game files which have volume problems  just a moment ago. But this webpage seems not displaying the attached files. Could you please check your email for them?**

**Comment by fishlabs** [comment]
Oh! I just noticed the below bar! It can also attach files. I‘m adding the 3 jar files once again.
[176x220_Has LOUDER volume when run on J2meLoader(Just test the menu music to distinguish).zip](https://github.com/nikita36078/J2ME-Loader/files/4720362/176x220_Has.LOUDER.volume.when.run.on.J2meLoader.Just.test.the.menu.music.to.distinguish.zip)
[240x320_Has LOWER volume when run on J2meLoader(Just test the menu music to distinguish).zip](https://github.com/nikita36078/J2ME-Loader/files/4720364/240x320_Has.LOWER.volume.when.run.on.J2meLoader.Just.test.the.menu.music.to.distinguish.zip)
[Another Game_The BGM of battle scenes has a much lower volume than the BGM of plot scenes(But when played on music player, Both MID files have the same volume).zip](https://github.com/nikita36078/J2ME-Loader/files/4720365/Another.Game_The.BGM.of.battle.scenes.has.a.much.lower.volume.than.the.BGM.of.plot.scenes.But.when.played.on.music.player.Both.MID.files.have.the.same.volume.zip)

**Comment by fishlabs** [comment]
@nikita36078

**Comment by nikita36078** [comment]
240x320 version sets the volume level to 50%, while 176x220 version doesn't do that, that's why it's louder.
In the second game, the background volume is 100 and the battle volume is 40, so this is a correct behavior too.
