### ISSUE TITLE
Asphalt 4 : Elite Racing 2D ( Sony Ericsson K800i Ver.) Gets Crashed Unexpectedly Sometimes

### ISSUE THREAD

**Issue by reenaosm** [nikita36078/J2ME-Loader#699]
Emulator version : v.1.6.1 - fixed 2

Game version : v.1.1.9

Game resolution : 240x320

Device : BIHEE A9

Android version : v.4.4.4

Description of the issue:
I played this game on my Android 4.4.4 phone, and this is a 2D game. I didn't see it crash the first time I played the game, but this game kept crashing after the second time. Only when every time I reboot my phone to play it, then it works again the first time, but when the second time I open the game, the same situation occurs once again.
Is this a bug? Please help me.
P.S. It's a 2D Gameloft racing game without using Mascot Capsule Engine.

**Comment by nikita36078** [comment]
I need a crash log. Select the "Save log" option in the menu after the game has crashed, and send me file "log.txt" from the J2ME-Loader folder.

**Comment by woesss** [comment]
@reenaosm, 
If you have the option "Immediate processing mode" enabled - try disable it. 
Do not use this option unnecessarily.

**Comment by reenaosm** [comment]
@nikita36078 I have sent the log to your email.

**Comment by reenaosm** [comment]
@woesss I didn’t open the immediate processing mode.

**Comment by nikita36078** [comment]
Thanks, unfortunately there's no errors in the log. You recorded it after the crash, right? Could you try to do it one more time?

**Comment by reenaosm** [comment]
@nikita36078 I changed the mobile platform to Nokia N95, then it's going to be all good. So I guess it's finally about the device I use, and I once again checked the log, no crash signs. Anyway this problem has been solved, it's finally about the problem of Mascot Capsule engine. As a result, I closed this issue. Thank you for your help once again! ^^
