### ISSUE TITLE
Icon app missing?

### ISSUE THREAD

**Issue by AdityaMH** [nikita36078/J2ME-Loader#70]
it's really good for adding hide button in newest version.
But isn't quite right here, some app icon is not going show up. in 1.2.6-test2, all icon app still exist.

-
And sorting app list by name or time it will be better.

**Comment by AdityaMH** [comment]
here screenshot

**Comment by nikita36078** [comment]
Yes, I know about this bug, I will fix it today.

**Comment by nikita36078** [comment]
Fixed in 494af810e700f6c6111091b15f7d203b578fb091. New version is available.
