### ISSUE TITLE
Asphalt Nitro won't open

### ISSUE THREAD

**Issue by DavidBrazSan** [nikita36078/J2ME-Loader#701]
**Emulator version:**
``1.6.1-fixed2``

**Game version:**
``1.1.8``

**Game resolution:**
``240x320``

**Device:**
``Samsung Galaxy J200M``

**Android version:**
``5.1.1``
**Link of game**
http://dedomil.net/games/4575/download-jar/63126

![Screenshot_20200602-102036](https://user-images.githubusercontent.com/60136669/83525365-431c7700-a4bb-11ea-889e-dd02f14324e8.png)

**Comment by woesss** [comment]
You need install it from JAD
