### ISSUE TITLE
Two video to show the Volume Bug

### ISSUE THREAD

**Issue by fishlabs** [nikita36078/J2ME-Loader#703]
**Emulator version:**
All

**Game version:**

**Game resolution:**
``(For example, 240x320 or 640x360)``

**Device:**
Xiaomi RedMi3
**Android version:**
5.1
**Description of the issue:**

**Modify the file name suffix to MP4**
[The BGM of battle scenes has a much lower volume than the BGM of village(But when played on music player, Both MID files have the same volume).zip](https://github.com/nikita36078/J2ME-Loader/files/4741377/The.BGM.of.battle.scenes.has.a.much.lower.volume.than.the.BGM.of.village.But.when.played.on.music.player.Both.MID.files.have.the.same.volume.zip)
[modify zip to MP4_240x320_Has LOWER volume when run on J2meLoader(Just test the menu music to distinguish).zip](https://github.com/nikita36078/J2ME-Loader/files/4741378/modify.zip.to.MP4_240x320_Has.LOWER.volume.when.run.on.J2meLoader.Just.test.the.menu.music.to.distinguish.zip)

**Comment by fishlabs** [comment]
@nikita36078

**Comment by nikita36078** [comment]
Again - these versions aren't the same, and their code can't be the same, it's doesn't make any sense. How can it be the same if the resolution is different? 
There's two type of volume - media volume and player volume. 
Result volume = media volume * player volume.
You can change media volume and game can change player volume. Music is quieter in 240*320 version because game sets player volume to 50%. Of course if you change media volume it doesn't affect the difference between two versions - player volume is still different.

![image](https://user-images.githubusercontent.com/3035571/83964640-fe2b8280-a8b6-11ea-98b6-b36a36c737d8.png)

![image](https://user-images.githubusercontent.com/3035571/83964647-0daacb80-a8b7-11ea-960c-6b3357a0c06c.png)

**Comment by fishlabs** [comment]
Oh! No Wonder！So that’s why！That makes sense！I extremely appreciate your spirit of finding the root of the problem！I remember I compared the class files of these two versions which had the same names weeks ago. It turns out that I remembered it wrong. Just recently I checked them with MD5 on Root Explorer,  and they are really different as you said——Some files with the same name even have different sizes! What a big mistake I made！ And now I sincerely apologize to you and pay great respect to you for your rigorous attitude! 
![图片](https://user-images.githubusercontent.com/34183077/83971170-71abaf00-a90c-11ea-9a15-3e4f9630867c.png)


> 
> 
> Again - these versions aren't the same, and their code can't be the same, it doesn't make any sense. How can it be the same if the resolution is different?
> There's two type of volumes - media volume and player volume.
> Result volume = media volume * player volume.
> You can change media volume and game can change player volume. Music is quieter in 240*320 version because game sets player volume to 50%. Of course if you change media volume it doesn't affect the difference between two versions - player volume is still different.
> When you're checking MIDI files in external player they look the same because player volume in that case is obviously 100%.
> 
> ![image](https://user-images.githubusercontent.com/3035571/83964640-fe2b8280-a8b6-11ea-98b6-b36a36c737d8.png)
> 
> ![image](https://user-images.githubusercontent.com/3035571/83964647-0daacb80-a8b7-11ea-960c-6b3357a0c06c.png)

**Oh! No Wonder！So that’s why！That makes sense！I extremely appreciate your spirit of finding the root of the problem！I remember I compared the class files of these two versions which had the same names weeks ago. It turns out that I remembered it wrong. Just recently I checked them with MD5 on Root Explorer,  and they are really different as you said——Some files with the same name even have different sizes! What a big mistake I made！ And now I sincerely apologize to you and pay great respect to you for your rigorous attitude!** 
![图片](https://user-images.githubusercontent.com/34183077/83971187-943dc800-a90c-11ea-96ab-3ebf53721289.png)
@nikita36078
