### ISSUE TITLE
debug version build problem on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by gspeiliu** [nikita36078/J2ME-Loader#704]
Hello

I tried to build the project with command "./gradlew assembleDebug" on Ubuntu 18.04 LTS and Mac OS 10.15 all with the latest Android Studio. I downloaded all versions of SDK and NDK. It can be built successfully on Mac OS but failure on Ubuntu 18.04 LTS.
The error message as follow:

* What went wrong:
Execution failed for task ':app:generateJsonModelDevDebug'.
> Build command failed.
  Error while executing process /home/xxxxxx/Android/Sdk/ndk/20.0.5594570/ndk-build with arguments {NDK_PR$
JECT_PATH=null APP_BUILD_SCRIPT=/home/xxxxxx/Downloads/BuildSystem/Repos/nikita36078#J2ME-Loader/app/src/m$
in/cpp/Android.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-16 NDK_OUT$
/home/xxxxxx/Downloads/BuildSystem/Repos/nikita36078#J2ME-Loader/app/build/intermediates/ndkBuild/devDebug$
obj NDK_LIBS_OUT=/home/xxxxxx/Downloads/BuildSystem/Repos/nikita36078#J2ME-Loader/app/build/intermediates/$
dkBuild/devDebug/lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}

  /home/xxxxxx/Android/Sdk/ndk/20.0.5594570/build/core/gdb.mk:33: *** missing separator.  Stop.

Could you please help me figure this out?
Thank you

**Comment by nikita36078** [comment]
Looks like an NDK issue, make sure you use the latest version (21.2.6472646). Also, it's better to use assembleDevDebug command, because the buildscript contains multiple flavors (but I don't think it breaks the build).

**Comment by gspeiliu** [comment]
I updated to the latest ndk version. The error message still does not disappear.

* What went wrong:
Execution failed for task ':app:generateJsonModelDevDebug'.
> Build command failed.
  Error while executing process /mnt/xxxxxx/Downloads/Android/ndk/21.0.6113669/ndk-build with argumen
ts {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/home/xxxxxx/Downloads/BuildSystem/Repos/nikita36078#J2ME-Loader/app/src/main/cpp/Android.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-16 NDK_OUT=/home/xxxxxx/Downloads/BuildSystem/Repos/nikita36078#J2ME-Loader/app/build/intermediates/ndkBuild/devDebug/o
bj NDK_LIBS_OUT=/home/xxxxxx/Downloads/BuildSystem/Repos/nikita36078#J2ME-Loader/app/build/intermediates/ndkBui
ld/devDebug/lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}

  /mnt/xxxxxx/Downloads/Android/ndk/21.0.6113669/build/core/gdb.mk:33: *** missing separator.  Stop.

**Comment by woesss** [comment]
Ask this question on [stackoverflow.com](https://stackoverflow.com) - I think there will help you find a solution there faster.

**Comment by nikita36078** [comment]
@gspeiliu Have you figured it out?

**Comment by gspeiliu** [comment]
@nikita36078 Yes, it seems the clone directory makes the error. The folder should not contain the special variable '#'. Thank you. :-)
