### ISSUE TITLE
cannot “返回”

### ISSUE THREAD

**Issue by fishlabs** [nikita36078/J2ME-Loader#705]
**Emulator version:**
1.55

**Game version:**

**Game resolution:**

**Device:**

**Android version:**

**Description of the issue:**

http://www.mpbus.com/Download/Games-1-10553.htm

**Comment by nikita36078** [comment]
Set layout type to "Motorola" in the game settings.

**Comment by fishlabs** [comment]
> Set layout type to "Motorola" in the game settings.

This method really works. 3Q very much！👌
