### ISSUE TITLE
NFS The Run 3D blank screens during car selection and gameplay

### ISSUE THREAD

**Issue by 72BullCrab58** [nikita36078/J2ME-Loader#706]
**Emulator version:**
version 1.6.0-open
update: 1.6.1 fixed2-open

**Game version:**
4.8.27

**Game resolution:**
240x320

**Device:**
Huawei P9 Lite VNS-L31

**Android version:**
7.0

**Description of the issue:**
Car selection and gameplay shows blank screen, user interface is normal, bugs out during gameplay pause and resume
Note: on the last screen, I'm testing on v1.6.1 fixed2 and getting waaay lower than 60fps. Fps is low in the menus as well, 35-44 fps. On 1.6.0 the fps was 60+.
![Screenshot_20200611-181425](https://user-images.githubusercontent.com/66792967/84413279-acfdf480-ac10-11ea-8bbf-100ea8e65a87.png)
![Screenshot_20200611-181444](https://user-images.githubusercontent.com/66792967/84413288-b12a1200-ac10-11ea-8ced-c7fd5e2474a8.png)
![Screenshot_20200611-180520](https://user-images.githubusercontent.com/66792967/84413291-b1c2a880-ac10-11ea-90a9-d3f127553255.png)
![Screenshot_20200611-181414](https://user-images.githubusercontent.com/66792967/84413294-b2f3d580-ac10-11ea-890a-50914e6aba39.png)
![Screenshot_20200611-181451](https://user-images.githubusercontent.com/66792967/84413297-b4250280-ac10-11ea-9d31-14a04ab4cfdc.png)
![Screenshot_20200611-181439](https://user-images.githubusercontent.com/66792967/84413299-b4bd9900-ac10-11ea-88e4-d3590f585926.png)
![Screenshot_20200611-184325](https://user-images.githubusercontent.com/66792967/84415780-8c836980-ac13-11ea-8722-7c1c42db39b1.png)

**Comment by nikita36078** [comment]
Duplicate #646. The emulator doesn't support Mascot Capsule 3D games.
