### ISSUE TITLE
Can't start SimCity Societies

### ISSUE THREAD

**Issue by Keitaro0104** [nikita36078/J2ME-Loader#707]
**Emulator version: Newtest 1.6.1-2 fixedplay
![Screenshot_20200613_082604](https://user-images.githubusercontent.com/49062895/84569927-a1e7c780-adbc-11ea-821a-a3eb3a315aaa.jpg)
**

**Game version:**
SimCity Societies All Version

**Game resolution:**
``(For example, 240x320 or 640x360)``
All Available in Dedomil

**Device:**
``(For example, Samsung Galaxy S7)``
Vivo Y12

**Android version:**
Pie 9.0

**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``

Cant run the game.
On every version.

**Comment by Keitaro0104** [comment]
I forgot to mention this, but SimCity Metropolis is having an exactly same issue.
Meanwhile, SimCity Deluxe is playable.

**Comment by Indra2108** [comment]
Looks like Duplicate #194

**Comment by nikita36078** [comment]
Yes, it's a duplicate.
