### ISSUE TITLE
cTunes 's playlist empty

### ISSUE THREAD

**Issue by javi2man** [nikita36078/J2ME-Loader#713]
**Emulator version:**
1.6.3

**Game version:**
1.0.0

**Game resolution:**
``(For example, 240x320 or 640x360)``
default
**Device:**
``(For example, Samsung Galaxy S7)``
Huawei Honor 5x
**Android version:**
6.0.1
**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
The emulator can't find any photo / video / song to play
![Screenshot_2020-07-13-14-43-15](https://user-images.githubusercontent.com/36956081/87336368-19258e00-c518-11ea-9491-666663558681.png)
Here is the app: http://www.mediafire.com/file/v3h0aa88fsp56dv/cTunes.jar/file

**Comment by nikita36078** [comment]
This app is made for Motorola phones with iRadio service, it searches for media files in iradio folder. You need to create this folder on internal storage and put media files there.

**Comment by javi2man** [comment]
Ok i didn't know that, after doing so, it works fine. Thanks!
