### ISSUE TITLE
Facebook java

### ISSUE THREAD

**Issue by opik1234** [nikita36078/J2ME-Loader#716]
**Emulator version:**

**Device:**
``(For All device)``

**Android version:**

**Description of the issue:**
``(What's the problem?  Please fix a bug. why can't I open Facebook 3.xx.jar java. when opened always crashes)``

**Comment by javi2man** [comment]
facebook java keeps on startup logo and doesn't go from there, could u please mod the jar file?

**Comment by hex007** [comment]
Does Facebook even support the app now? If not, it is not worth it to spend time on this. Can you try other emulators verify if the app works ?

**Comment by nikita36078** [comment]
Duplicate #245.

**Comment by Lucas-mother3** [comment]
> facebook java keeps on startup logo and doesn't go from there, could u please mod the jar file?

Sorry for bringin back, but no, unless you actually use a new Facebook api.
