### ISSUE TITLE
Marble Madness 3D: 3D Graphics fail to load

### ISSUE THREAD

**Issue by vulture-boy** [nikita36078/J2ME-Loader#717]
**Emulator version:**
1.6.3-play

**Game version:**
1.7

**Game resolution:**
240x320

**Device:**
Samsung Galaxy Note8

**Android version:**
9

**Description of the issue:**

From the looks of things, Marble Madness 3D fails to render it's 3D aspects. All the 2D aspects seem fine? 

_Screenshot:_
![image](https://user-images.githubusercontent.com/19735946/89268577-bac76900-d606-11ea-9020-e771501b4f6c.png)

here's a forum post with screenshots of how it should look:
http://www.topsony.com/forum/showthread.php/5883-HOT-Marble-Madness-3D

Probably worth mentioning that it also optionally supports motion controls; dunno if this emulator supports that :)

**Comment by vulture-boy** [comment]
![image](https://user-images.githubusercontent.com/19735946/89268806-08dc6c80-d607-11ea-8619-6bb1caa2c26b.png)

**Comment by woesss** [comment]
This is the version with "Mascot Capsule 3D" - there is no support for this engine in the J2ME-Loader yet.  
You can try another version of the game or run this one on [JL-Mod](https://github.com/woesss/JL-Mod).

**Comment by vulture-boy** [comment]
gave it a try but no dice!

**Comment by nikita36078** [comment]
Fixed
