### ISSUE TITLE
[Feature request] add custom wav codecs in j2me loader

### ISSUE THREAD

**Issue by th0rig** [nikita36078/J2ME-Loader#718]
Actualy this is related to #545 can you add wav codecs for better audio emulation? I think this is useful if some android roms has broken codec support and there's no way to change that other than use third party app.

**Comment by nikita36078** [comment]
I'm not sure what exactly causes the glitching sound. Can you try [this](https://mega.nz/file/wQ0wTQgY#vkDtqtJE8DVJoIOZRDW3r0b_fucrblYu2h-9OzZWJLE) version?

**Comment by th0rig** [comment]
Unfortunaly this version not solve my problem  but thanks for your effort,well it's looks like my my device has problem playing wav audio in general not just j2me loader i can confirm this by playing half live using FWGS(correct me if i wrong)emulator,,,,the sfx half live use is Wav audio well i try to play the sfx using music player and BOOM The audio playback messed just like in j2me loader only some wav audio that play normaly and i'm surprised the sfx audio(All of them) play like it should without sound glitching when in game.
I wonder if this is codec problem, the way rom handle the audio,the way emulator handle the audio,ffmpeg problem or something else,anyway thanks for your hardwork and forgive my grammar, Btw the workaround try to download diferrent for one game eventualy you'll find version without sound glitch issue mostly s40v3 version, Sony Ericcson Satio version, and LG ku990 version, the procces is pain and even if you download games for these phone model some games still has sound issue. Once again thanks for your effort.

**Comment by nikita36078** [comment]
Can you provide me examples of games with the glitched sound and with the correct sound? I can try to compare the wav files in these games.

**Comment by th0rig** [comment]
Uhmm,, i dont think all j2me games use wav for sfx audio but here an example
Vampire romance s40v6 320x240 This one has sfx issue
https://drive.google.com/file/d/1LwLigSOo3mdnA6Zgpwc2J5ifLlU58t4l/view?usp=drivesdk

Vampire Romance Sony erricsion satio 360x640 this on has no sound effect issue but it has other issue as #651 
https://drive.google.com/file/d/1iiLCq2py-bPjhNspVCyoCU_RbGyHlLO4/view?usp=drivesdk

**Comment by nikita36078** [comment]
First version uses WAV format for sfx, second one - AMR, that's why you don't have sound issues there.

**Comment by th0rig** [comment]
Yeah that's why i ask here if feature like custom codec is possible in j2me loader yeah most half life sound effect messed up in built in android media player except mouse click sound effect  if i'm mistaken i'll let you know both audio use wav format i dont know either how and why most audio messed but not those. Because wav audio have two or more different container? Not just because this audio has smallest file size then? Anyway thanks for creating this emulator.

**Comment by th0rig** [comment]
@nikita36078 i found to different wav file one work without sound glitch and other with sound glitch both android built in media player and j2me loader
Here the files
This one work without issue:https://drive.google.com/file/d/1-FX8DqdgxBjCEnVnXX_bjpyzOLk2a9xO/view?usp=drivesdk 9

And this one have audio glitch this one taken from half life audio files they are in wav format:

**Comment by th0rig** [comment]
Sorry closing and reopen with incomplete comment my phone act weird earlier
Btw can you tell me the difference between these two files?

**Comment by pent0** [comment]
Your files require permissions to access

**Comment by th0rig** [comment]
Unfortunaly i cant grant acces via email for some reason maybe this is another stupid changes made by google for privacy bullcrap first they break sd card access now this? Btw i googling how to grant access to my files but only solution i found is ask someone else email to grant access with if i missing something you can give me guide coz i dont know if it's okay to ask email to someone you never meet before.

**Comment by pent0** [comment]
https://gsuitetips.com/tips/drive/share-a-google-drive-file-publicly/

**Comment by th0rig** [comment]
Uhmm i dont see any blue share button anywhere so i use second method and i edit my comment with updated links in post right before i close this issue by accident.

**Comment by woesss** [comment]
Why not just attach them here in your post?

**Comment by th0rig** [comment]
i apologize for the incovenience i post with mobilephone before now i making this comment with laptop here the files you asked for
this wav file have no issue with android built in media player on my rom so j2meloader can play this audio without glitch
[bbm_incoming_call.zip](https://github.com/nikita36078/J2ME-Loader/files/5759514/bbm_incoming_call.zip)
this one with audio playback problem atleast in my rom:
[ag_alert1.zip](https://github.com/nikita36078/J2ME-Loader/files/5759516/ag_alert1.zip)

**Comment by th0rig** [comment]
I need your knowledge is there workaround for my issue? Audio glitch with wav format in j2me loader because System problem with audio codecs/decoder/encoder that too complicated to fix in system side for people with zero knowledge about progamming/coding i dont think this problem easy to fix even rooted i hope there is workaround in j2me loader side

**Comment by nikita36078** [comment]
Try this version - https://mega.nz/file/IR1mgJLJ#i3nZoeOusX5ET0lSAGzSKPCKcuzQWsVzPCgV750XlsQ

**Comment by th0rig** [comment]
Thanks audio problem in wav format fixed in this version
