### ISSUE TITLE
Bug in profile option

### ISSUE THREAD

**Issue by DavidBrazSan** [nikita36078/J2ME-Loader#729]
**Emulator version:**
``1.6.3-dev-1353``

**Device:**
``Samsung Galaxy J200M``

**Android version:**
``5.1.1``
**Description of the issue:**
``App to and closes when creating or editing a profile``

**Comment by nikita36078** [comment]
Could you send me the log after the crash?

**Comment by nikita36078** [comment]
Nevermind, the problem is found.

**Comment by DavidBrazSan** [comment]
Fixed. Thank you
