### ISSUE TITLE
Waitin' for next release 1.6.4

### ISSUE THREAD

**Issue by javi2man** [nikita36078/J2ME-Loader#732]
**Emulator version:**
1.6.3

**Game version:**
1.0

**Game resolution:**
all

**Device:**
all

**Android version:**
all
**Description of the issue:**
Please post the next updated version of j2me loader, i can't wait any more!!!

**Comment by AdityaMH** [comment]
If you are impatient about the release update, please download it at:  https://install.appcenter.ms/users/nikita36078/apps/j2me-loader/distribution_groups/testers

But maybe there will be have some bug, because they are still not perfect.

**Comment by javi2man** [comment]
Wooow!!! i didn't know that i can test beta versions.. Many thanks!!!

**Comment by nikita36078** [comment]
The new release is pretty close :)
