### ISSUE TITLE
Some games wont launch anymore

### ISSUE THREAD

**Issue by KingCollo97** [nikita36078/J2ME-Loader#734]
Emulator version: 1.6.3-play

Game version: Gangstar 2: Kings of L.A v1.0.7

Game resolution:240x320

Device: Nokia 2.2

Android version: 10

Description of the issue: Games that I had previously played no longer launch they just flash a new window/transition screen then go back to the games list
I will add a youtube link
[YouTube video issue showcase](https://youtu.be/RIJZYi_D9eY)

**Comment by nikita36078** [comment]
I need a crash log. Select the "Save log" option in the menu after the game has crashed, and send me file "log.txt" from the J2ME-Loader folder.

**Comment by KingCollo97** [comment]
> I need a crash log. Select the "Save log" option in the menu after the game has crashed, and send me file "log.txt" from the J2ME-Loader folder

[log.txt](https://github.com/nikita36078/J2ME-Loader/files/5280907/log.txt)

**Comment by nikita36078** [comment]
Is there any change in the latest version?

**Comment by KingCollo97** [comment]
Hello and sorry for the late reply but the new version works perfectly and
I havent had any issues since the recent update

Thank you and have a great day
