### ISSUE TITLE
Mobile Midi Editor - Read storage bug

### ISSUE THREAD

**Issue by AdityaMH** [nikita36078/J2ME-Loader#736]
Previous version 1.6.3 can read my internal memory, but in latest version just can read RMS only, not whole internal memory
![Screenshot_2020-09-25-11-14-14-272_ru playsoftware j2meloader](https://user-images.githubusercontent.com/33791472/94226010-b0e42700-ff20-11ea-84dc-ab4572b325d3.png)

**Comment by AdityaMH** [comment]
Now MME fixed with build 1.6.5-dev-1377 (84) .
But i don't know with other.

**Comment by nikita36078** [comment]
Fixed in the latest release too.
