### ISSUE TITLE
Moto Racing Fever (3D) - Render problem

### ISSUE THREAD

**Issue by humbertodias** [nikita36078/J2ME-Loader#738]
**Emulator version:**
1.6.3-play

**Game version:**
Moto Racing Fever 3D
https://phoneky.com/games/?id=j4j41110

**Game resolution:**
240x320

**Device:**
Nokia

**Android version:**
Android 10

**Description of the issue:**
Render problem

OK
https://www.youtube.com/watch?v=ilyuhjwdvi4

NOK
![Moto Racing Fever-render-problem](https://user-images.githubusercontent.com/9255997/95029147-71e36d80-06a6-11eb-99fb-62699ce32505.png)

**Comment by nikita36078** [comment]
Fixed
