### ISSUE TITLE
"Error" when taking a screenshot on a screen scaled to 0%

### ISSUE THREAD

**Issue by SergioFLS** [nikita36078/J2ME-Loader#740]
Running in version 1.6.3 from F-Droid.

![Screenshot_20201007-150301_J2ME Loader.jpg](https://user-images.githubusercontent.com/34007063/95370553-75563f00-08c8-11eb-92a4-c1bfa65344e1.jpg)

![Screenshot_20201007-150127_J2ME Loader.jpg](https://user-images.githubusercontent.com/34007063/95370588-8606b500-08c8-11eb-8921775d192e6958.jpg)

EDIT: Version is Android 9

**Comment by nikita36078** [comment]
0% means empty screen (width*0=0, height*0=0), that's why you get the error. Here's another problem - the screen shouldn't draw anything at 0%, and it's fixed in 1.6.7. Looks like F-Droid build is broken a long time ago, will check it out.

**Comment by nikita36078** [comment]
By the way, if you just want to disable screen stretching, you should uncheck Scale to fit option.
