### ISSUE TITLE
Screenshot problem

### ISSUE THREAD

**Issue by Monosataspp** [nikita36078/J2ME-Loader#743]
![Screenshot_20201009-191600](https://user-images.githubusercontent.com/69386747/95583077-cea7a500-0a65-11eb-8b24-00da9f32049f.png)

![Screenshot_20201009-093841](https://user-images.githubusercontent.com/69386747/95583338-2ba35b00-0a66-11eb-8ac9-3b5e660f4b92.png)

Older version have no problem, but later version screenshot somehow got cutted (no screen resolution problem either).

**Comment by nikita36078** [comment]
It will be fixed in the next version.
