### ISSUE TITLE
'New Skool Skater' sound does not play.

### ISSUE THREAD

**Issue by Adguarduser9** [nikita36078/J2ME-Loader#744]
**Emulator version:**
1.6.7 play

**Game version:**
1.2

**Game resolution:**
240x320

**Device:**
Samsung Galaxy a6 plus

**Android version:**
10

**Description of the issue:**
This app does not play sound from the game 'New skool skater' . I remember my java phone Nokia C2-03 used to play sound from the game.

The problem has been there since the first version of the app.

**Comment by fishlabs** [comment]
What phone series is the game for ? You'd  better download the game for Nokia N73 series, which J2ME Loader supports best and has the least chance of error.

**Comment by Adguarduser9** [comment]
It has been so many days but the issue hasn't got fixed yet. Is it impossible to fix the issue ?

**Comment by nikita36078** [comment]
It can be fixed, I just haven't find a good solution yet.

**Comment by Adguarduser9** [comment]
> It can be fixed, I just haven't find a good solution yet.

Please change the grammar mistake 'find' to 'found' in your reply. Students look at your reply. Sorry if I disturbed you.
