### ISSUE TITLE
Does anyone need help using Soundfont SF2?

### ISSUE THREAD

**Issue by LeandroSousa4441** [nikita36078/J2ME-Loader#747]
**QUESTION**
I am wanting to need to make ones that prefer to use a different version after the last update that was designed for users of Android 4.1 and higher. But what we know, is to need Soundfont from version 2.0x and what do you do with permissions?

**Comment by nikita36078** [comment]
The soundfont support is planned, if that's what you're asking about. Storage permission is needed for storing games, microphone - for audio recorder apps, location - for Bluetooth search.
