### ISSUE TITLE
add zoom in level option

### ISSUE THREAD

**Issue by wzhy90** [nikita36078/J2ME-Loader#748]
**Emulator version:**
1.67

**Game version:**

**Game resolution:**
``(For example, 240x320 or 640x360)``

**Device:**
``(For example, Samsung Galaxy S7)``

**Android version:**
9

**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
add a zoom in option instead of  full screen. nokia 5800 games running in 360x630 will cover on-screen keyboard

**Comment by nikita36078** [comment]
There's the scale option for that, also you can disable the virtual keyboard.
