### ISSUE TITLE
Support for PC and Feature request

### ISSUE THREAD

**Issue by GMPranav** [nikita36078/J2ME-Loader#749]
Hey! I want to speedrun some java games and your emulator   by far the most accurate and bug free emulator I have come across, which is essential for speedruns. But I saw that its only available for mobile devices. Can you consider porting it for Windows?

Also a feature request: Savestates and frame advance. This would help in making Tool-Assisted Speedruns.

**Comment by nikita36078** [comment]
Hello! The emulator is developed for Android, contains a lot of Platform-specific tricks and optimizations, so it's almost impossible to port it, unfortunately. Save states can't be implemented, this app doesn't emulate hardware (J2ME is a software platform) so there's no way to save memory state.
About the frame advance - do you mean frameskip?

**Comment by Malaska678** [comment]
> Hey! I want to speedrun some java games and your emulator by far the most accurate and bug free emulator I have come across, which is essential for speedruns. But I saw that its only available for mobile devices. Can you consider porting it for Windows?
> 
> Also a feature request: Savestates and frame advance. This would help in making Tool-Assisted Speedruns.

U can run this emulator on android emulator

**Comment by GMPranav** [comment]
First of all, thanks a lot for responding.
Now, I know that as a an option, but the thing is, android emulators are not perfect, most of them I have tried are a bit laggy - BlueStacks, LD Player, Nox, etc. It kinda defeats my purpose to have accurate emulation, I would rather just play on my android phone than on android emulator. I thought it would be nice to have native support for PC, but hey its your app, so you decide whats best to work upon.

**Comment by Malaska678** [comment]
@GMPranav Also pc port not possible becoz this loader utilize dalvik vm

**Comment by GMPranav** [comment]
> @GMPranav Also pc port not possible becoz this loader utilize dalvik vm
Alright, thanks a lot for the reply

> About the frame advance - do you mean frameskip?
@nikita36078 No, frame advance, where the emulator would let you input frame by frame.
http://tasvideos.org/EmulatorResources/Using.html here is more information about it.
