### ISSUE TITLE
Lost saved game after force stopping j2me-loader

### ISSUE THREAD

**Issue by crose1988** [nikita36078/J2ME-Loader#75]
version: 1.2.6.1, 1.2.6.2
tested game: doom rpg

working:
1.save status in game
2.exit game then reopen it without close j2me-loader, continue option show in start menu
3.exit game then quit j2me-loader use function in app menu, reopen the game, continue option show in start menu

not working:
exit game then force stop  j2me-loader, reopen the game, only new game option in start menu

game works fine in 1.2.5, crash in 1.2.6

**Comment by nikita36078** [comment]
Fixed in 1.2.6.3.
