### ISSUE TITLE
[Feature Request] Frontend support and Centered mode

### ISSUE THREAD

**Issue by Retroism** [nikita36078/J2ME-Loader#752]
I use it along with DIG which is a frontend for games. Issue is when I launch games from it is that it triggers the screen setup of the specific game rather than launching the game directly using the main activity. 

Centered mode for none fullscreen games hopefully can be added too for those who use physical controllers. Hiding the touchscreen keypads doesn't remove the white area where the keypads are placed. I know it's a small thing but it feels awkward having an empty space at the bottom of the screen. Having the center option can be a good workaround as well ability to upscale the emulation screen by a little so it can be close to an almost fullscreen experience.

**Comment by woesss** [comment]
Do you mean upscale of game screen out of the device screen at the expense of content visibility?

**Comment by stevenfelix505** [comment]
@Retroism 
Centered mode? This one, right?

Centered mode on:
![Screenshot_20201225-195851_Snes9x EX+](https://user-images.githubusercontent.com/57618009/103135687-87d45d80-46ec-11eb-96ed-59e76c855b25.jpg)

Centered mode off:
![Screenshot_20201225-195830_Snes9x EX+](https://user-images.githubusercontent.com/57618009/103135700-a5a1c280-46ec-11eb-9d87-07ecc49e1b0e.jpg)

**Comment by Retroism** [comment]
@stevenfelix505 yes! Is that GBA.Emu? I can't seem to do it in j2me loader, do you have any workarounds?

**Comment by stevenfelix505** [comment]
@Retroism that's Snes9x EX+, the UI is similar to GBA.emu, and sadly, I don't have workarounds.

**Comment by nikita36078** [comment]
Centered mode - #752, #481
You can stretch the game to fullscreen by disabling the "Keep aspect ratio" option, as woesss already said.
Does DIG openg the game setup only on the first launch? Then it doesn't look like a problem - different games require different settings and the main issue is screen resolution.

**Comment by woesss** [comment]
@nikita36078, нет - DIG присылает полный путь к папке конверта, тогда как ConfigActivity ожидает только имя и навешивает его на путь текущей рабочей директории. Вроде на дискорде писали что разработчик дига обновился - я не проверял. Но в виду возможности изменить рабочую директорию, всё-таки нужно использовать полный путь к конверту и строить остальные пути относительно него - юзер может наделать ярлыков при разных настройках папки или из того же дига запускать игры из рабочей папки, отличной от той, что выбрана в эмуляторе на момент запуска. У меня уже есть коммит на эту тему, если что.

**Comment by woesss** [comment]
@Retroism, about DIG - you need to write to its developer so that he doesn't add the "config.edit" action to the launch intent

**Comment by Retroism** [comment]
@nikita36078 problem with unticking aspect ratio is that it is "hit or miss" some games can be stretch full screen centered while some will get wrapped at the left upper corner as and sometimes becomes smaller than the inputted resolution. It's tedious making different settings for each game rather than using a global one that can be used across everygame without messing with resolution. Having a center mode will eliminate this frustration by playing the game at default resolution everytime we launch a different game.

As for DIG, it uses the activity to launch a game but using the MainActivity will launch the game library and not the currently selected one, so using the ConfigActivity is used as a workaround to launch a specific game but will have to manually press the "start" button.

**Comment by Retroism** [comment]
This one is the default aspect ratio of the game but it is in top of the screen, the ability to center or select the location of the emulation screen can be hopefully implemented in the future
![Screenshot_2021-01-21-19-22-21-1115192685](https://user-images.githubusercontent.com/76582521/105344552-0b1a9d80-5c1e-11eb-852f-150089f404a7.png)

While this one is with ignore aspect ratio with force full screen. yes it is centered but it looks ugly and definitely not ideal to play. 
![Screenshot_2021-01-21-19-23-49-1150857671](https://user-images.githubusercontent.com/76582521/105344666-38674b80-5c1e-11eb-895d-def178bb6b54.png)

**Comment by woesss** [comment]
The games themselves are designed for different screen sizes - it is impossible to make a universal setting, since the required sizes are unknown and cannot be determined automatically. I added a gravity setting to the [(mod )](https://github.com/woesss/JL-Mod/releases/latest) - is this option right for you?  
About DIG - I already wrote, don't put `config.edit` action in launch intent, and use `ConfigActivity`. Also, in the current dev build (of origin J2ME Loader), you need to specify the full path to the application dir in the intent

**Comment by Retroism** [comment]
> The games themselves are designed for different screen sizes - it is impossible to make a universal setting, since the required sizes are unknown and cannot be determined automatically. I added a gravity setting to the [(JL-Mod)](https://github.com/woesss/JL-Mod/releases/latest) - is this option right for you?
> About DIG - I already wrote, don't put `config.edit` action in launch intent, and use `ConfigActivity`. Also, in the current dev build of origin J2ME Loader, you need to specify the full path to the application dir in the intent.
> **P.S.** Hmm... the DIG settings do not allow you to select action and data. You need to create a new configuration (emulators-> new) with the same parameters as J2ME Loader and select it for the J2ME system. For the latest public releases of DIG and J2ME Loader it will work as it should.

THANK YOU! this is exactly what I was looking for the center gravity works perfectly. Now I still haven'y tested it with DIG. But thank you I can now play my java games centered with a controller 😘😘😘

**Comment by Retroism** [comment]
![Screenshot_2021-01-22-11-43-06-0771607817](https://user-images.githubusercontent.com/76582521/105443587-06e69280-5ca7-11eb-8c51-8b91d0a48427.png)
![Screenshot_2021-01-22-11-42-57-2052007999](https://user-images.githubusercontent.com/76582521/105443592-0b12b000-5ca7-11eb-8c67-834a2441499a.png)

Tried it your modded version with DIG and it gives this error. It will rotate my screen from Landscape to Portrait as if launching the selected game and skipping the config but will close immediately and show this error.

**Comment by woesss** [comment]
At the moment the mod does not run from the latest DIG version, but works with the previous ones (tested for 1.37).  
The mod requires the full path to the game folder, as in the next release of the J2ME Loader (already in the latest developer build).  
I think this is the final version of the launch intent - so a change is needed on the DIG side.

**Comment by Retroism** [comment]
Ah yes! I downgraded to 1.37 and it works, I guess I'll have to talk to the DIG developer about the issue! Thanks a lot! All my issues have been resolved! Cheers to the team working on this project! Will you add the gravity feature in future versions of the official app?

**Comment by nikita36078** [comment]
Yes, I'll add it.
