### ISSUE TITLE
Could you write an article into the wiki about building midlets using only free toolchains

### ISSUE THREAD

**Issue by KOLANICH** [nikita36078/J2ME-Loader#753]
Hi. Could you, please, write an article into this repo wiki about state of the art way of building J2ME applications using as much free SDKs and tools (i.e., can I use OpenJDK from distro packages, also, can other JVM-based langs be used?) as possible in *nix-based OSes ?

**Comment by pent0** [comment]
I'm not sure if it's something fitting to be placed on an emulator wiki. You may want to ask on other places ([here](https://github.com/j2me-preservation/j2me-preservation) maybe), tagging nikita

**Comment by KOLANICH** [comment]
Thanks for the link to an awesome repo
