### ISSUE TITLE
(FEATURE REQUEST)

### ISSUE THREAD

**Issue by greyhathacker008** [nikita36078/J2ME-Loader#755]
**Emulator version:**
Latest

**Game version:**

**Game resolution:**
``(For example, 240x320 or 640x360)``

**Device:**
``(For example, Samsung Galaxy S7)``
Galaxy m51
**Android version:**
10
**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
Add an option for Shader just like retroarch

**Comment by woesss** [comment]
**Already have!**

>   Only shaders for [PPSSPP](https://www.ppsspp.org) (same format) are supported  
>   To use, you need to put them to the `shaders` folder in the  the emulator's database directory,  
>   further in the game settings, select the graphics mode: "HW acceleration (OpenGL ES)" and select the shader of interest  
>   A small collection of compatible shaders can be taken in this repository: [ppsspp_shaders](https://github.com/woesss/ppsspp_shaders)
