### ISSUE TITLE
Crash after installing and starting the game

### ISSUE THREAD

**Issue by DavidBrazSan** [nikita36078/J2ME-Loader#757]
**Emulator version:**
``1.6.9-dev-1428``

**Device:**
``Samsung Galaxy J200M``

**Android version:**
``5.1.1``

**Description of the issue:**
``When the installation of the game finishes and I will start it, the application crash. I start it again and the game opens normally.``

**Comment by woesss** [comment]
Need a crash log or if you are using a release version - you can send a crash report

**Comment by DavidBrazSan** [comment]
I recorded the screen to show how it happens.

https://user-images.githubusercontent.com/60136669/104746772-77813280-572e-11eb-8b19-65421eaf2d1b.mp4

P.S. after installing I press the Iniciar button

**Comment by nikita36078** [comment]
Select the "Save log" option in the menu after the crash and send me file "log.txt" from the J2ME-Loader folder.

**Comment by woesss** [comment]
@nikita36078 https://github.com/nikita36078/J2ME-Loader/blob/5c5ff404406bab9aa48cfe274d0469e7829e9d09/app/src/main/java/ru/playsoftware/j2meloader/applist/AppsListFragment.java#L234  
`app.getPath()` -> `app.getPathExt()`

**Comment by nikita36078** [comment]
Thank you, I'll fix it.
