### ISSUE TITLE
stream media can't be opened

### ISSUE THREAD

**Issue by AdityaMH** [nikita36078/J2ME-Loader#76]
in version 1.2.6-test2, still support to open file, open link or stream video to another android app.
But in 1.2.6.2, its become not supported (so i can't open stream video (via java browser app to android video player) or open media from java app to android media player app).

**Comment by AdityaMH** [comment]
or if you want check this issue, browsing youtube video via UC Browser Java or Opera Mini Java, click any video then click "watch video". in version 1.2.6-test2 and lower, its become automatically to video player.

**Comment by nikita36078** [comment]
Fixed in 1.2.6.3.

**Comment by AdityaMH** [comment]
This issue happening again in 1.5.0, didn't send to external player.
