### ISSUE TITLE
Undressed is not a valid .jar

### ISSUE THREAD

**Issue by sczther** [nikita36078/J2ME-Loader#760]
**Emulator version:**
1.6.9-play

**Game version:**
???

**Game resolution:**
???

**Device:**
Samsung Galaxy J3(2017)

**Android version:**
9

**Description of the issue:**
Cannot be added, probably an encrypted jar

**Comment by woesss** [comment]
What? More details, please.

**Comment by nikita36078** [comment]
I don't think this file can be restored, closing the issue.
