### ISSUE TITLE
Tetris (iFone) cannot be launched

### ISSUE THREAD

**Issue by sczther** [nikita36078/J2ME-Loader#762]
**Emulator version:**
1.6.9-play

**Game version:**
2.2.9

**Game resolution:**
???

**Device:**

Samsung Galaxy J3(2017)

**Android version:**
9

**Description of the issue:**
Game throws a java error.
[log.txt](https://github.com/nikita36078/J2ME-Loader/files/5862706/log.2.txt)

**Comment by nikita36078** [comment]
Looks like someone adapted this game to Motorola phone and Android VM found some errors in this adaption, I can't fix it.
