### ISSUE TITLE
Skate & Slam crashes after intro

### ISSUE THREAD

**Issue by sczther** [nikita36078/J2ME-Loader#764]
**Emulator version:**
1.6.9-play

**Game version:**
1.2.0

**Game resolution:**
176x208?

**Device:**
Samsung Galaxy J3(2017)

**Android version:**
9

**Description of the issue:**
Game exits with "send to developer" dialogue
[log.txt](https://github.com/nikita36078/J2ME-Loader/files/5863064/log.3.txt)

**Comment by nikita36078** [comment]
Fixed
