### ISSUE TITLE
【Feature request】

### ISSUE THREAD

**Issue by sangkk01** [nikita36078/J2ME-Loader#766]
**Emulator version:** 1.6.9-play

**Game version:**

**Game resolution:**
``(For example, 240x320 or 640x360)``

**Device:**
``For Samsung ``

**Android version:**10

**Description of the issue:**
``Is there any way to game launcher by Samsung thinking j2me loader is a game?``
``Because there are some online java games, when you turn off the screen, your internet connection will be lost``

**Comment by woesss** [comment]
Nothing is clear. The option "keep screen on" (it is in the emulator settings) does not solve your problem?

**Comment by nikita36078** [comment]
Samsung decides itself if app is the game, I can't control it. Anyway, check out your phone settings, the internet connection should stay active even when the screen is turned off.
