### ISSUE TITLE
Support for audio playback with custom SF2 file

### ISSUE THREAD

**Issue by nuclearboi** [nikita36078/J2ME-Loader#770]
**Emulator version:**
``(1.6.9-play)``

**Device:**
``(Moto g7)``

**Android version:**
``(10)``
**Description of the issue:**

As the title says, I want a feature that allows for the music of the games to be played through custom soundfonts via .SF2 files instead of the default Android soundfont.

**Comment by SergioFLS** [comment]
Duplicate? #569

**Comment by nikita36078** [comment]
Yes, duplicate, I will rename the original issue to something more clear.
