### ISSUE TITLE
FolderPlayer_mod MIDlet not working

### ISSUE THREAD

**Issue by nofishonfriday** [nikita36078/J2ME-Loader#771]
**Emulator version:**
1.6.9-play

**MIDlet version:**
v1.3.0

**resolution:**
240x320

**Device:**
Galaxy S5

**Android version:**
10

**Description of the issue:**
Hi,
I'm the developer of [FolderPlayer_mod2](https://github.com/nofishonfriday/FolderPlayer_mod-J2ME-), a J2ME based audio player. When running it via J2ME-Loader, when trying to play an audiofile (mp3) I get the error message "Error reading parent dir".
I suppose J2ME-Loader is mainly targeted at games but if this midlet could be made to run I'd be **very** happy as I used it so long on my old Nokia phone. :)
The MIDlet (.jad/.jar) is available in the [releases](https://github.com/nofishonfriday/FolderPlayer_mod-J2ME-/releases) section.
It's not open source but I could provide you the source code privately if it helps (and I'm happy to answer any questions regarding it).

Thanks.

**Comment by stevenfelix505** [comment]
Can you try this MIDlet below?
[X-plore.jar](https://cdn.discordapp.com/attachments/756752455110361158/810386887880605730/X-plore.jar)

**Comment by nikita36078** [comment]
Just tried it and it works fine. What is the path to music file/its name? Maybe there's something specific in it.

**Comment by nofishonfriday** [comment]
Thanks for checking and giving me a hint. :)
At first I tried putting audiofiles in the "Music" folder that already existed on my Galaxy s5. Playing from there didn't work for some reason and gave above mentioned error message.
It works fine indeed creating my own folder and play audio files from there, yay.

Now one problem still exists though:
I can't see/access my external storage (microSD card) in FolderPlayer. On startup I see only C: drive, while on my old Nokia I saw C: and F:(?) drive (my SD card). Any idea how to solve this by chance?

**Comment by stevenfelix505** [comment]
@nofishonfriday 
FUCK YOU BITCH!
🖕🖕🖕👎👎👎

**Comment by nikita36078** [comment]
@stevenfelix505 No idea what it was, but I have to block you.

**Comment by nikita36078** [comment]
I tested the app through Samsung Remote Test Lab on Galaxy S5 (6.0) and Galaxy Note 20 (10.0) and couldn't reproduce the Music folder issue.
The external sd support is mentioned here - #321.

**Comment by woesss** [comment]
> I get the error message "Error reading parent dir".
@nofishonfriday, try the latest [dev build](https://install.appcenter.ms/users/nikita36078/apps/j2me-loader/distribution_groups/testers) - i think this issue is already solved

**Comment by nofishonfriday** [comment]
@woesss, @nikita36078 
Didn't get the "Error reading parent dir" with the dev build so far.
Thanks for the heads up. Hope it'll make it into official build soon so I can install via Play Store. :)

I think we can close this issue as the only thing remaining is the external SD card support but that's already an existing issue.
Thanks again.

**Comment by nofishonfriday** [comment]
Just to add regarding external SD support:
In case of FolderPlayer_mod, it calls J2ME API `FileSystemRegistry.listRoots()`.

**Comment by woesss** [comment]
The problem is that Android initially does not have an API for obtaining mount points for storage devices and they are different for different devices. In FS, they are presented as regular folders and are located where the manufacturer wants. And for J2ME phones from different manufacturers, they also differed. As a result, it is very difficult to bring all this to a common denominator.

**Comment by nofishonfriday** [comment]
I'm quite fluent with the J2ME API, still developing the FolderPlayer_mod occassionally (seems I'm the only one still using a Java phone lol) but have no idea about Android API currently (maybe looking into it at some point), so this is interesting info, thanks.
