### ISSUE TITLE
Will my problem be solved?

### ISSUE THREAD

**Issue by NamJack** [nikita36078/J2ME-Loader#772]
**Emulator version:**
1.6.9

**Game version:**
http://giaitri321.pro/game-offline/gamehay/2/vuong-quoc-sung-vat-cau-vong/S60-VuongQuoc-PKM-CauVong-240x320.jar

**Game resolution:**
240x320
**Device:**
Vivo 1906
**Android version:**
9
**Description of the issue:**
Has my #558  problem been solved? It's been a while since I created it.

**Comment by pent0** [comment]
You can ask in there again, it will create notification for the developer. No need to open another one
