### ISSUE TITLE
New Nature Park - error

### ISSUE THREAD

**Issue by Avstraliya** [nikita36078/J2ME-Loader#773]
**Emulator version:**
1.6.9-play

**Game version:**
1.0.5

**Game resolution:**
``(For example, 240x320 or 640x360)``
240x320
**Device:**
``(For example, Samsung Galaxy S7)``
Xiaomi Redmi Note 9 Pro
**Android version:**
10
**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
App doesn't load, shows a error![Screenshot_2021-02-28-09-12-03-818_ru playsoftware j2meloader](https://user-images.githubusercontent.com/61800872/109411843-12636280-79a5-11eb-9c83-8369779072f4.jpg)
)

**Comment by nikita36078** [comment]
Just disable the "Touch input" option in the settings, it will fix the game.
