### ISSUE TITLE
Soul of Darkness does not save data

### ISSUE THREAD

**Issue by RobertoR0** [nikita36078/J2ME-Loader#774]
**Emulator version:**
1.6.9

**Game version:**
1.3.1

**Game resolution:**
240x320

**Device:**
Samsung Galaxy J5 Pro

**Android version:**
9
**Description of the issue:**
After exiting the game the saved progress is erased, I don't know if the problem is in the game itself or in the emulator

**Comment by nikita36078** [comment]
Could you please share your jar or send the download link? I can't reproduce this bug.

**Comment by RobertoR0** [comment]
In fact, the error does not occur in version 1.6.9-open, only in automated builds after version 1.6.9

**Comment by nikita36078** [comment]
Thank you for clarification, now I see the bug.

**Comment by nikita36078** [comment]
Fixed
