### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by greyhathacker008** [nikita36078/J2ME-Loader#775]
**Emulator version:**
Latest

**Game version:**
Every game

**Game resolution:**
640x360

**Device:**
``( Samsung Galaxy m51``

**Android version:**10

**Description of the issue:**
``(What's the problem? -can u add an option to save anytime just like other emulator i always loose my game data this option needs to be added ASAP

**Comment by nikita36078** [comment]
Save states can't be implemented, this app doesn't emulate hardware (J2ME is a software platform) so there's no way to save CPU/memory state.
