### ISSUE TITLE
Shaders

### ISSUE THREAD

**Issue by dhanial** [nikita36078/J2ME-Loader#776]
**Emulator version:**
1.70

**Game version:**
Every .jar game

**Game resolution:**
``(For example, 240x320 or 640x360)``
Every resolution
**Device:**
``(For example, Samsung Galaxy S7)``
Every device
**Android version:**
Pie

**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``

How to shaders
In previous version (1.67) i can activate shaders after update it show empty when i want to choose shaders, i had tried to delete j2me loader folder and add shaders again but still empty

**Comment by nikita36078** [comment]
What is your device? Also, is the list completely empty or it contains default Fast filter?
![image](https://user-images.githubusercontent.com/3035571/111526199-7e004a80-876f-11eb-8f5c-f2b55f9aae77.png)

**Comment by nikita36078** [comment]
Does it happen in the profiles or in the game settings?

**Comment by dhanial** [comment]
Device : Redmi Note 4x Snapdragon
Yes this is happen in profies also game setting

**Comment by dhanial** [comment]
![Uploading Screenshot_Solid_Explorer_20210318-000535.png…]()

**Comment by dhanial** [comment]
This shaders on my j2meloader folder still same before update n work before update to 1.70
![Uploading Screenshot_Solid_Explorer_20210318-000535.png…]()

**Comment by dhanial** [comment]
And this when i'm open shaders....nothing on there![Screenshot_J2ME_Loader_20210318-030126.png](https://user-images.githubusercontent.com/37980131/111530826-5bcdf300-8796-11eb-947a-467f64392704.png)

**Comment by nikita36078** [comment]
Wait, I don't see any .ini files on the screenshot, do you have them? They should be in the same folder otherwise the emulator won't find shaders.
Check out a shaders example - https://github.com/woesss/ppsspp_shaders

**Comment by dhanial** [comment]
Wait so the shaders it's same like ppsspp ?

**Comment by nikita36078** [comment]
Yes, the same format.

**Comment by dhanial** [comment]
Damn i have so many shaders collection from my ppsspp, i've never know
that, thank you so much dev, sorry for my noob question

**Comment by nikita36078** [comment]
So, have you got shaders working? Adding missing .ini files should have helped.

**Comment by dhanial** [comment]
Yes it works now, thank you so much
