### ISSUE TITLE
Splinter Cell Conviction Glitchy Green Screen

### ISSUE THREAD

**Issue by Sahkulu** [nikita36078/J2ME-Loader#780]
**Emulator version:**
1.6.9

**Game version:**
1.1.4 SonyEricsson K800i (1MB version)

**Game resolution:**
240x320

**Device:**
General Mobile 8

**Android version:**
9

**Description of the issue:**
![Splinter Cell Conviction Java Bug](https://user-images.githubusercontent.com/50754667/111887490-6ed70200-89e6-11eb-9b04-b0727c9b350e.png)
From the second mission (museum) you gain ability of peeking doors with a broken mirror in game but when you do it a glitchy green screen appears. I hope you fix this.

**Comment by nikita36078** [comment]
Fixed
