### ISSUE TITLE
Provide separate package for ARM64/x86-64 architecture

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [nikita36078/J2ME-Loader#781]
**Emulator version:**
1.6.9

**Game version:**
N/A

**Game resolution:**
640x360

**Device:**
Samsung Galaxy S6

**Android version:**
7.0
**Description of the issue:**
The current release available only with armeabi-v7a and x86 architecture, it would be awesome if this app have a package includes native libs for arm64-v8a and x86-64 dependencies.

**Comment by woesss** [comment]
arm64-v8a and x86-64 are available on Google Play - it will automatically provide an build for the specifications of your system.

**Comment by nikita36078** [comment]
64-bit binaries don't show any perfomance difference over 32-bit ones, so I don't include them in non-Google Play builds.

**Comment by KrasnayaPloshchad** [comment]
Oh thatʼs why I canʼt get it in F-Droid.

**Comment by dogtopus** [comment]
> 64-bit binaries don't show any perfomance difference over 32-bit ones, so I don't include them in non-Google Play builds.

We should reopen this. Some ROMs (e.g. pretty much anything on Pixel 7) now only ship AArch64 system libs, which render J2MELoader unusable on these ROMs, regardless of Google or not.

**Comment by dogtopus** [comment]
Just saw the update. AArch64 is now supported.
