### ISSUE TITLE
Can't load bomberman 3d

### ISSUE THREAD

**Issue by Adguarduser9** [nikita36078/J2ME-Loader#782]
[Bomberman 3d game download link](https://mega.nz/#!g3wmhJgD!pEk1f9lilagrc5hwVY6FRkRLu9hsK6yxnQeD5cJFkZY)

**Emulator version:**
1.7.0 play

**Game version:**

**Game resolution: 240x320, 352×416

**Device:**
`Samsung Galaxy A6 Plus

**Android version:**
10, oneui 2.0

**Description of the issue:**
Bomberman 3d game loads in the version '1.5.6 play'. The game doesn't work in some latter versions of the emulator. In the version '1.7.0 play' too.

**Comment by nikita36078** [comment]
What does exactly happen? Does it crash or stuck somewhere?

**Comment by nikita36078** [comment]
It doesn't crash for me, that's why I asked. Looks like I need a log. Could you select the "Save log" option in the menu after the crash, and send me file "log.txt" from the J2ME-Loader folder?

**Comment by Adguarduser9** [comment]
> It doesn't crash for me, that's why I asked. Looks like I need a log. Could you select the "Save log" option in the menu after the crash, and send me file "log.txt" from the J2ME-Loader folder?

https://drive.google.com/file/d/1wyarkiKHTgo20P50gB8SUtjCXGzLrYWR/view?usp=drivesdk

**Comment by woesss** [comment]
Do other 3D games work?

**Comment by Adguarduser9** [comment]
> Do other 3D games work?

Sonic racing does not work too. I don't know about any other 3d games.

**Comment by nikita36078** [comment]
Could you install and check the Github [version](https://github.com/nikita36078/J2ME-Loader/releases/tag/1.7.0)?

**Comment by Adguarduser9** [comment]
> Could you install and check the Github [version](https://github.com/nikita36078/J2ME-Loader/releases/tag/1.7.0)?

Now the game works  just fine. What's wrong with Google play store version ? Why did you upload buggy version?

**Comment by nikita36078** [comment]
I didn't upload a buggy version, somehow Google Play provided you a wrong apk. Did you download J2ME Loader directly from Google Play, not from some website/another app?

**Comment by Adguarduser9** [comment]
> I didn't upload a buggy version, somehow Google Play provided you a wrong apk. Did you download J2ME Loader directly from Google Play, not from some website/another app?

I think I probably downloaded the apk from apkmirror.com and chose the file that is not compatible with my device's processor. Anyway my problem has been solved. I will always download j2me loader from github.
