### ISSUE TITLE
Ability to set heap size manually

### ISSUE THREAD

**Issue by Truuum** [nikita36078/J2ME-Loader#789]
I want to test some J2ME applications and want the emulator conditions to be close to real devices (for example, set 2/4 MB heap size to check how the application will behave with small amounts of RAM)

translated via google translator, there may be errors

**Comment by Truuum** [comment]
It would also be nice to display information about RAM usage on the screen.

**Comment by nikita36078** [comment]
J2ME Loader basically runs J2ME apps as native Android applications, so there's no way to limit heap or show actual RAM usage.
