### ISSUE TITLE
Internet Radio by nokia crashes when it boots.

### ISSUE THREAD

**Issue by iplaysomegames101** [nikita36078/J2ME-Loader#790]
**Emulator version:**
1.7.0-dev-1467

**Game version:**
1.0.1

**Game resolution:**
240x320
**Device:**
Samsung A20

**Android version:**
Android 9

**Description of the issue:**
Internet radio by nokia crashes when it starts.
https://user-images.githubusercontent.com/54115676/119268682-71163200-bbca-11eb-8486-5f73368bf6c5.jpg

https://user-images.githubusercontent.com/54115676/119268688-770c1300-bbca-11eb-8614-318828e3096c.jpg

**Comment by nikita36078** [comment]
Could you provide the .jar file?
