### ISSUE TITLE
How to Edit the Data？

### ISSUE THREAD

**Issue by 1457384613gh** [nikita36078/J2ME-Loader#792]
How can I open "xx.rsr" or "xx.rsh" to edit?
I would love to edit data of ganes to unlock the levels and get high scores and grades.
![Screenshot_2021-05-26-13-55-47-0096257968.png](https://user-images.githubusercontent.com/69227436/119609981-1d6c3a00-bdbe-11eb-9e0a-a644eda0e15e.png)

**Comment by xiexin52k** [comment]
u can use HexEdit app or copy to PC use Hex Tools modify it

**Comment by 1457384613gh** [comment]
> u can use HexEdit app or copy tot cannot analyze data
It cannot analyze data but show every number of data.

**Comment by xiexin52k** [comment]
> > u can use HexEdit app or copy tot cannot analyze data
> 
> It cannot analyze data but show every number of data.

Open it with hex editor, and then search for the hexadecimal number corresponding to the decimal.
For example: the hexadecimal of 999 is 3e7. You can find 3e7 in these files and modify it. If there are multiple results, you can change the number in the game and search again until there is only one result

**Comment by 1457384613gh** [comment]
> > > u can use HexEdit app or copy tot cannot analyze data
> > 
> > 
> > It cannot analyze data but show every number of data.
> 
> Open it with hex editor, and then search for the hexadecimal number corresponding to the decimal.
> For example: the hexadecimal of 999 is 3e7. You can find 3e7 in these files and modify it. If there are multiple results, you can change the number in the game and search again until there is only one result

But everything is data showing numbers, data of words turned into numbers. What if there is the coincidence of the same numbers?

**Comment by nikita36078** [comment]
There's no another method to edit the RMS data, so I close the issue.
