### ISSUE TITLE
Can't install games from external storage on Android Q

### ISSUE THREAD

**Issue by th0rig** [nikita36078/J2ME-Loader#794]
**Emulator version:**
1.7.0- play
**Device:**
`Sharp SHV41

**Android version:**
Android 10 Q(why don't they name it queen tart?)
**Description of the issue:**
Tanks a lot for your fix before and I want to report again the issue is j2me loader can't install games from external storage

**Comment by woesss** [comment]
More details, please. Describe how you tried to install: through the built-in explorer, from another application. Save the log after the unsuccessful attempt and attach it here.

**Comment by th0rig** [comment]
I'm sorry for your trouble now I can install games from external storage after I try to install games for the second time strange the problem go away by itself it seems so I close this once again sorry for wasting your time

**Comment by th0rig** [comment]
Sorry forgot to mention that I'm using buitl-in file picker to install games I never install games from other app manager because that pointless and probably  will not work as google implement more lame storage access each update not only restrictive but confusing for old android user. Anyway thanks for making this awesome emulator cheers
