### ISSUE TITLE
Feature request add option to move converted games to external sd card

### ISSUE THREAD

**Issue by th0rig** [nikita36078/J2ME-Loader#796]
**Emulator version**
J2me Loader v1.7.0 play

**Android Version**
Android 10(Q)
**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
Can you add option to move converted games to  External storage? If placing converted games isn't possible because we can't make j2mloader folder on Root of external(TANKS GOogle and Greedy MAAnufacturer) sdcard but we can atleast move converted games to Android/data/ru.playsoftware.j2meloader/files

**Comment by woesss** [comment]
`settings->working directory` doesn't help you? Or the emulator's built-in explorer can't get to this folder?

**Comment by th0rig** [comment]
Tanks I don't remember if j2melader have such setting well my all my previous phone were rooted both have native support for choosing between internal storage and sdcard for primary storage via setting withaout root when still use android kitkat tanks to Polytron one of infamous android phones manufacturer and the one with restrictive access to SD card(this is one of reason why I prefer rooted phones) that's why I never bother to check setting other than game settings and after I follow your step to move j2melader database files to externalsdcard Androidd/data/ru.playsoftware.j2meloader/files via setting and viola work like a charm so tank you so much
