### ISSUE TITLE
Madden NFL 08 load times are slow

### ISSUE THREAD

**Issue by Lucas-mother3** [nikita36078/J2ME-Loader#798]
**Emulator version:**
J2ME Loader 1.7.0-open

**Game version:**
Madden NFL O8 version 4.1.26

**Game resolution:**
240x320

**Device:**
Huawei Y6 Prime (2019)

**Android version:**
Android 9 - Pie

**Description of the issue:**
Madden NFL 08 load times are slow, but when I pressed the Recents key, it always load the main game menu... I can't play the whole thing!

**Comment by nikita36078** [comment]
The game fails to load even on the real device (Nokia 5320), so it's not an emulator fault.

**Comment by Lucas-mother3** [comment]
So, okay... I'm duped... I still have Madden 08 on DS and Wii
