### ISSUE TITLE
Rotation mode 

### ISSUE THREAD

**Issue by skelletR** [nikita36078/J2ME-Loader#80]
Hi..now I use the app rotation manager to stuck the screen.. Because if screen is in landscape mode in some games when I turn my phone in landscape the game rotation itself in portrait and can't play.. Can in next update.. Put setting stuck the rotation per game inside without use another app or turn off the auto rotation in my phone

**Comment by oatmeal01** [comment]
This is what i want to suggest too perhaps the next update the dev will add rotation control settings when configuring each installed java games.

**Comment by oatmeal01** [comment]
Here is an example of  landscape touchscreen java game that needs auto-rotation to be able to play in landscape mode. http://terbaik.my.to/download/19466/46/iron_man_3.jar

**Comment by skelletR** [comment]
Thanks for the link yes that with rotation if add very useful I hope the dev adds this

**Comment by nikita36078** [comment]
I think it is duplicate issue, we already have #46 .
