### ISSUE TITLE
Libretro Core

### ISSUE THREAD

**Issue by Retroism** [nikita36078/J2ME-Loader#800]
Any plans on a libretro core release? This emulator is the best one with j2me and it's a great addition if ever. More specially I'd love to see Lemuroid use it since it focuses on handheld consoles with a great simple UI aimed for a relaxing retro gaming experience. If not then it's fine, but still I want to thank you devs for making this amazing emulator that we can enjoy our favorite javagames. :)

**Comment by XerTheSquirrel** [comment]
I am not the developer of J2ME Loader to answer this. However considering Lemuroid and J2ME Loader are both on Android, one could just use the Android application for J2ME Loader.

As for being a core itself, J2ME Loader is very dependent on Android to function so it would be available only for a single system. Currently for Windows/MacOS/Linux there is FreeJ2ME that is available. Then later this year the SquirrelJME core I work on should be available, which is completely standalone and written entirely from scratch so it would work on every RetroArch system.

**Comment by nikita36078** [comment]
Yes, J2ME Loader has always been developed as a standalone Android application, so it's impossible to port it to any emulation frontends.
