### ISSUE TITLE
NokiaUI default pixel format causes issues on "Virtual Me"

### ISSUE THREAD

**Issue by Nokia64** [nikita36078/J2ME-Loader#802]
**Emulator version:**
``1.0.7-open``

**Game version:**
Tested on ``v0.14`` and ``v0.17``

**Game resolution:**
``128x128``

**Device:**
``Samsung SM-G357FZ``

**Android version:**
Android 4.4.4

**Description of the issue:**
The game crashes upon entering a new game, with the following error:
```
E/ACRA    (27210): ACRA caught a IllegalArgumentException for ru.playsoftware.j2meloader
E/ACRA    (27210): java.lang.IllegalArgumentException: Illegal format: 8888
E/ACRA    (27210):     at com.nokia.mid.ui.DirectGraphicsImp.getPixels(DirectGraphicsImp.java:18)
E/ACRA    (27210):     at com.nokia.mid.appl.vime.b.j(Unknown Source)
E/ACRA    (27210):     at com.nokia.mid.appl.vime.VirtualMeMidlet.k(Unknown Source)
E/ACRA    (27210):     at com.nokia.mid.appl.vime.NGameMidlet.t(Unknown Source)
E/ACRA    (27210):     at com.nokia.mid.appl.vime.g.run(Unknown Source)
E/ACRA    (27210):     at java.util.Timer$TimerImpl.run(Timer.java:284)
```
The game directly uses the pixel format returned by ``com.nokia.mid.ui.getNativePixelFormat()`` when calling the ``com.nokia.mid.ui.getPixels(short[]...)`` functions, without checking whether it is a short-based format.
The TYPE_INT_8888_ARGB value returned by J2ME Loader as the native pixel format causes the game to crash, as it is not supported by the getPixels(short[]...) function.

This issue also occurs on real Nokia devices with higher screen depths.
An option to choose the default pixel format could help solving this, but it would likely bloat the menus with a feature unuseful for vast majority of games. Is this worth fixing at J2ME Loader's side or should the game just get patched instead?

Thank you!

**Comment by nikita36078** [comment]
I will consider adding the pixel format setting, at least this is more convenient for users than jar patching.

**Comment by woesss** [comment]
I think better (and maybe in general enough) make one of short-based format as default - `DirectGraphics.<get/set>Pixels` use mostly the oldest games.

**Comment by nikita36078** [comment]
Now you can set the pixel format through system properties: com.nokia.mid.ui.DirectGraphics.PIXEL_FORMAT: 565
Other values can be found here: https://github.com/woesss/JL-Mod/blob/43a6f6f1b4fba7212774443637ad1563a85041fb/app/src/main/java/com/nokia/mid/ui/DirectGraphics.java#L36
