### ISSUE TITLE
Error when enable "Immediate processing mode"

### ISSUE THREAD

**Issue by AdityaMH** [nikita36078/J2ME-Loader#81]
When game flickering, it need to enabled "Immediate processing mode" right?
But, when i "enabled Immediate processing mode", game still flickering when screen touched. and can't moving keypad smoothly.

-
And for me image gallery still showing image res even adding .nomedia

**Comment by nikita36078** [comment]
Immediate processing mode doesn't always fix flickering. What is the game name?
.nomedia hides all media files, so it is a gallery problem.

**Comment by swafah** [comment]
The game name is sims 3

**Comment by DiegoSousa123** [comment]
The imediate processing mode is also not working here, before it worked on Galaxy on fire 2, now it has not worked anymore

**Comment by AdityaMH** [comment]
i think all games who need or enable "Immediate processing mode", include Galaxy on Fire 2 or Revival 2.
and i'm sorry about .nomedia . it's not gallery or bug problem, but it's need refreshing gallery or restart phone to make it work.

**Comment by nikita36078** [comment]
Fixed in 1.2.6.4.
