### ISSUE TITLE
Keymapping issue  on Blackberry Devices

### ISSUE THREAD

**Issue by benknam** [nikita36078/J2ME-Loader#812]
**Emulator version:**
1.7.0-open

**Game version:**
Multi

**Game resolution:**
Multi

**Device:**
Blackberry Classic (Q20)

**Android version:**
Android 4.3 (VM via BBOS 10)

**Description of the issue:**
The key mapping action keep telling "KEYCODE_UNKNOWN", then failed mapping the blackberry key to the game.
![6A068AEED6B188E019B08FCBD553599B](https://user-images.githubusercontent.com/32257056/126116482-64ac7c7f-30f5-4a58-b252-8376d15014ac.jpg)

**Comment by woesss** [comment]
Are the buttons really not assigned or just the button names are not displayed? Was it before or appeared in a new version?

**Comment by benknam** [comment]
> Are the buttons really not assigned or just the button names are not displayed? Was it before or appeared in a new version?

Yeah the buttons were not assigned to the game. If I add a new profile, Once I assign the key to replace the default one, the next tap of this key will show "KEYCODE_UNKNOWN", I'm sure this was cause by the Blackberry keyboard.

**Comment by woesss** [comment]
You do not understand me. The name of the buttons may not be determined, but they will be assigned and they will work in the game. Have you checked them in the game?

**Comment by benknam** [comment]
> We do not understand each other. The name of the buttons may not be determined, but they will be assigned and they will work in the game. Have you checked them in the game?

Sorry for my bad explanation :( .  Yeah, I checked in the game too, it's not working. 

Otherwise as I test again, once the second key was assigned, the previous assigned-key will be cleared (being empty). I guess the keyboard just only send a same code to the loader, once we assign the next key, the loader will think about this is the same code from the keyboard, so the last one will be cleared.

Attached a log file if its helping.
[log.txt](https://github.com/nikita36078/J2ME-Loader/files/6839431/log.txt)

**Comment by JoseskVolpe** [comment]
I suggest to test the assigned keys on a key tester j2me application too. As woesss said, the name could not be obtained but the keycode was asigned. So, sometimes it's the game's problem and not the emulator, because the game is receiving a input but it's not recognizing that emulated keycode, and to solve this, you can try setting the device from Nokia to Siemens, Motorola or any other device listed.

You can check if this MIDlet returns a keycode, and send here if so. If it's not returning anything after you press the assigned key, or it returns a different one from the listed device, so it's a problem with the emulator.

https://ufile.io/apues0r3

**Comment by benknam** [comment]
> We do not understand each other. The name of the buttons may not be determined, but they will be assigned and they will work in the game. Have you checked them in the game?
> If the buttons do not work in the game, test the keyboard with this (or a similar) application: https://play.google.com/store/apps/details?id=aws.apps.keyeventdisplay and show us the output.

Great idea, here's the result：

![69A92129A1218B22AE37BE4DC6C63C02](https://user-images.githubusercontent.com/32257056/126134492-f55a5af1-4081-4d0d-bfed-b306d1b0bfd9.jpg)
Capture from the device

[keyevent_2021-07-19-170536+0800.txt](https://github.com/nikita36078/J2ME-Loader/files/6839464/keyevent_2021-07-19-170536%2B0800.txt)
The saved log file.

**Comment by woesss** [comment]
Strange, the keyboard sends normal events.  
Perhaps the BB incorrectly transfers them to the dialogue - an additional test is needed.  

Run this test app: [keys-test.zip](https://github.com/nikita36078/J2ME-Loader/files/6840489/keys-test.zip) (APK in ZIP, github doesn't allow adding APKs), press the buttons, then open the dialog via the options menu and press the same buttons again. Compare and show the result.

**Comment by benknam** [comment]
> Strange, the keyboard sends normal events.  
> Perhaps the BB incorrectly transfers them to the dialogue - an additional test is needed.  
> 
> Run this test app: [keys-test.zip](https://github.com/nikita36078/J2ME-Loader/files/6840489/keys-test.zip) (APK in ZIP, github doesn't allow adding APKs), press the buttons, then open the dialog via the options menu and press the same buttons again. Compare and show the result.

Thanks woesss, this could be useful. 

I'm keeping testing during this couple hours, I found that actually the blackberry device keyboard is working at all, but once I selected NK/SE layout (or any others except Custom), the BB keyboard should be "alt-lock" so it could directly input "number" but not "letter". So I modified a couple values of "Keymapping" line in the Config.json, which was located in the app config folder, then seems some keys are working directly without alt-lock. Maybe I got the wrong keycode or something, I will test again with the key-test comparation results.

**Comment by benknam** [comment]
> Strange, the keyboard sends normal events.
> Perhaps the BB incorrectly transfers them to the dialogue - an additional test is needed.
> 
> Run this test app: [keys-test.zip](https://github.com/nikita36078/J2ME-Loader/files/6840489/keys-test.zip) (APK in ZIP, github doesn't allow adding APKs), press the buttons, then open the dialog via the options menu and press the same buttons again. Compare and show the result.

Good day woesss, here's result capture from keys-test:

![91B5E4C1385639DB4E81C397D7400B29](https://user-images.githubusercontent.com/32257056/126256516-be2e43f8-b3e0-4b49-9c8f-67cda73743c4.jpg)
Press "q" and showing normally.

![0418F49AE2730072F13FD71C400FF95F](https://user-images.githubusercontent.com/32257056/126256525-22bce1e7-8d01-4d42-9ced-2a8843e1c6f9.jpg)
open the dialog from menu, and showing "KEYCODE_UNKNOWN"

What does it mean?

**Comment by woesss** [comment]
As I suspected, the problem is in the dialogue.
Another test is dialogue only:
[test-keys2.zip](https://github.com/nikita36078/J2ME-Loader/files/6845963/test-keys2.zip)
If this test fails, we need to somehow get rid of the dialogue.
In the meantime, you can edit the mapping in text mode, a list of all android keycodes can be viewed here:
https://github.com/aosp-mirror/platform_frameworks_base/blob/master/core/java/android/view/KeyEvent.java#L94

**Comment by benknam** [comment]
> As I suspected, the problem is in the dialogue.
> Another test is dialogue only:
> [test-keys2.zip](https://github.com/nikita36078/J2ME-Loader/files/6845963/test-keys2.zip)
> If this test fails, we need to somehow get rid of the dialogue.
> In the meantime, you can edit the mapping in text mode, a list of all android keycodes can be viewed here:
> https://github.com/aosp-mirror/platform_frameworks_base/blob/master/core/java/android/view/KeyEvent.java#L94

Thanks woesss, here's the result of test-key2, yes it was failed to detect the input.

![0A5092E632D56B625D7327EF2AADAAD0](https://user-images.githubusercontent.com/32257056/126274408-38462594-88f8-47a4-abe6-9e81be2c931a.jpg)

**Comment by woesss** [comment]
[KeyTest3.zip](https://github.com/nikita36078/J2ME-Loader/files/6846948/KeyTest3.zip)
Another try.  

By the way, are the "scan" values different for different buttons?

**Comment by benknam** [comment]
> [KeyTest3.zip](https://github.com/nikita36078/J2ME-Loader/files/6846948/KeyTest3.zip)
> Another try.
> 
> By the way, are the "scan" values different for different buttons?

Thanks woesss, I'm back onboard,

key-test1 showing no "scan" value.
and yes, in key-test2 & key-test3 app, it's showing the "scan" in deferent value for different button, here's the capture below:

![IMG_20210721_144758](https://user-images.githubusercontent.com/32257056/126444099-b60635ce-e216-4b84-9e83-ae925f99dec2.png)
This is the capture with taping "q w e r t y u I o p" within a dialogue box.

![IMG_20210721_144809](https://user-images.githubusercontent.com/32257056/126444300-d2671878-8a55-476b-992f-384170deb0a7.png)
This is the capture with taping "q w e r t y u I o p" after pressing the  "OK" of the dialogue box.

**Comment by woesss** [comment]
It is clear that nothing is clear!  
I haven't found a way to match scan codes to keys.  
Thus, the only way to solve this problem is to change the GUI of the mapping settings window to do without the dialog.

**Comment by woesss** [comment]
I came up with a fix, a test build of my mod can be downloaded here:
https://install.appcenter.ms/users/j2me.forever/apps/jl-mod/distribution_groups/testers

**Comment by benknam** [comment]
> I came up with a fix, a test build of my mod can be downloaded here:
> https://install.appcenter.ms/users/j2me.forever/apps/jl-mod/distribution_groups/testers

Wooooow that's reallllllllly cooooooooool, woesss!! You did a really great job! This one works so perfectly on my Blackberry Q20 !!! Very perfect !!! I will tell my BB group members as they have another type of keyboard device, so let's test if this one works, too!

**Comment by alemanto** [comment]
It actually detects key presses and kind of works, but continuess press not working (basically holding down the button). You have to tap key so character moves in games.
