### ISSUE TITLE
 j2meloader for PC And retroarch？

### ISSUE THREAD

**Issue by wanger2211** [nikita36078/J2ME-Loader#813]
KEmulator is too old. Have you considered developing j2meloader for PC？

In addition, retroarch is an interesting nostalgic project,
Consider porting j2meloader to retroarch as the libretro core
Of course, this is just an idea. If developers adopt the best, it doesn't matter if they don't
thank you;>

**Comment by rdx-O** [comment]
It is almost impossible to make J2ME-Loader for PC and it's impossible to build for RetroArch either.

For PC
> No, it's impossible to port J2ME Loader to Windows, it contains a lot of Android-specific code and has targeted this platfrom since beginning. You can try KEmulator, it's the most stable java emulator on PC . [Here](https://github.com/nikita36078/J2ME-Loader/issues/749)


For RetroArch
> Yes, J2ME Loader has always been developed as a standalone Android application, so it's impossible to port it to any emulation frontends (like RetroArch).

**Comment by XerTheSquirrel** [comment]
For RetroArch there is FreeJ2ME and in the future there will be SquirrelJME once that is ready enough.

**Comment by wanger2211** [comment]
> 为 PC 制作 J2ME-Loader 几乎是不可能的，也不可能为 RetroArch 构建。
> 
> 电脑用
> 
> > 不，将 J2ME Loader 移植到 Windows 是不可能的，它包含很多 Android 特定的代码，并且从一开始就针对这个平台。你可以试试KEmulator，它是PC上最稳定的java模拟器。[这里](https://github.com/nikita36078/J2ME-Loader/issues/749)
> 
> 对于 RetroArch
> 
> > J2ME Loader 一直是作为独立的 Android 应用程序开发的，因此不可能将其移植到任何仿真前端（如 RetroArch）。

It's a pity
Thank you for your reply~

**Comment by wanger2211** [comment]
> 对于 RetroArch，有 FreeJ2ME，将来一旦准备就绪，就会有 SquirrelJME。

This is exciting good news!
Thank you for your information
