### ISSUE TITLE
Something in real key and virutalboard

### ISSUE THREAD

**Issue by Krchi** [nikita36078/J2ME-Loader#816]
**Device:**
``(For example, Samsung Galaxy S7)``
F21 pro
**Android version:**
11
**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
its a phone with t9 , and it dpad_down act fast in code make up event invalid，other keys are fine(In Nokia GameCanvas)
in Canvas 		public boolean onKeyUp(int keyCode, KeyEvent event)
100 is too small for my phone's DOWN_K, i change it with 160
in VirtualKeyborad 		public boolean keyPressed(int keyCode)
the DualKey's hasCode now is wrong, which makes display error with virtualboard when use real up/down key(it shows left-up/let-down in virtualboard, i don't if this is just in intentional)
in my phone, it doesnt have soft-left and soft-right, so i had to change menu and back to act as them, just in my own modification,

**Comment by nikita36078** [comment]
What do you mean by t9, physical keyboard? 100 ms delay is meant for virtual keyboards, physical ones should be fine without it. What app did you use to test key events?

**Comment by Krchi** [comment]
> What do you mean by t9, physical keyboard? 100 ms delay is meant for virtual keyboards, physical ones should be fine without it. What app did you use to test key events?

yes, virtualboard had no problem.
its ok in Canvas, but which run a game(in GameCanvas), each real key is well down except down key, the keyUp code is run and it seems that the selected state gone very fast, the down key had to delay the event，maybe its some problem in the phone, but down key is fine in normal Canvas, i should take some look in it.

**Comment by Krchi** [comment]
i found in this days update, these arrow keys (left/right/up/left-up/right-up) do not run as expect

**Comment by nikita36078** [comment]
Could you explain in details, what exactly happens?

**Comment by Krchi** [comment]
> Could you explain in details, what exactly happens?

In short, the real down key of my phone doesn't work in some games (when in GameCanvas).
the delay in code is ok
i found it is the phone's problem, after all, bar phones are not common in these days.

**Comment by nikita36078** [comment]
Well, I suppose I can close the issue now
