### ISSUE TITLE
Zombie Infection 2 - controls/gamepad issue

### ISSUE THREAD

**Issue by BeF1990** [nikita36078/J2ME-Loader#819]
**Emulator version:**
1.7.2.

**Game version:**
All versions with touch screen

**Game resolution:**
640x360 and 800x480

**Device:**
Samsung Galaxy TAB S6

**Android version:**
11

**Description of the issue:**
When I use virtual keyboard everything works fine, but when I use gamepad it's impossible to move. The player character starts to move in direction what I want and suddenly stop.

In another Gameloft games like Gangstar 2, Wild West Guns or Splinter Cell Conviction I don't have similar problem.

I know I have touchscreen controls in this game, but I don't want to use it. In all games I use gamepad.

**Comment by nikita36078** [comment]
I'll check this out, but I think these games just aren't intended to play with the physical keyboard.

**Comment by BeF1990** [comment]
But as long as I use virtual keyboard everything works great. The problem exist only when I map gamepad to keys (numerals or arrows).

**Comment by BeF1990** [comment]
I checked again to be sure and it doesn't work on virtual keyboard. You have right. Sorry again. You can close this topic.
