### ISSUE TITLE
Optional pro version for fans

### ISSUE THREAD

**Issue by BeF1990** [nikita36078/J2ME-Loader#820]
You should add "Pro" version of your emulator to Google Play. I'm willing to support you and pay for this great emulator. Truly thx for you job!

**Comment by nikita36078** [comment]
J2ME Loader has donations option in the Google Play version (in-app billing) and other versions (PayPal). I see no reason for adding a Pro version.

**Comment by BeF1990** [comment]
OMG... Now I feel so stupid, I didn't know that. Sorry.

**Comment by nikita36078** [comment]
No problem :)
