### ISSUE TITLE
Delete button does not work in Ice Age Village

### ISSUE THREAD

**Issue by DavidBrazSan** [nikita36078/J2ME-Loader#828]
**Emulator version:**
``Last Version``

**Game version:**
``1.0.3``

**Game resolution:**
``320X240``

**Device:**
``Motorola Moto G3 Osprey``

**Android version:**
``6.0``
**Description of the issue:**
``After completing the tutorial, I have to enter the name of the village and for this I have to open the new keyboard opcao, but when I try to delete, it does not work.
 I use google keyboard.``

**Comment by woesss** [comment]
The game does not support qwerty.
Removing the character on the `#` button

**Comment by DavidBrazSan** [comment]
The # so button works on the 240X320 version. In version 320X240 all the letters and numbers work only the Delete that does not.

**Comment by woesss** [comment]
I checked - pressing the button is transmitted to the game.
On the SE SDK emulator, the game also does not respond to the `del` key
