### ISSUE TITLE
Button mapping support

### ISSUE THREAD

**Issue by Ultra-J** [nikita36078/J2ME-Loader#83]
I personally like the emulator you developed.Because before that, basically can not find a real Java simulator on Android system.With the continuous updating your emulator features are constantly being improved, I very much like to see added support for physical keyboard.For example, support for Sony Ericsson Xperia Play gamepad or Motorola XT894 sliding full keyboard.If you really can achieve, then I can completely abandon the use of previous Symbian phone to play Java games.

**Comment by AdityaMH** [comment]
not all java games or apps can emulated in this emulator and this emulator doesn't support bluetooth too. so think again before abandoned your java phone completely.

**Comment by Ultra-J** [comment]
@AdityaMH Because I live in the area, Java applications are basically closed the corresponding service, so I basically just play some games with Java phones.At the same time as there is no partner who is interested in Java games like me, it is not personally important for me to have Bluetooth connectivity,I play most of the time in Java stand-alone game.

**Comment by nikita36078** [comment]
The emulator already has keyboard support, it works if virtual keyboard is disabled. I'm going to add more advanced keymapping in future.

**Comment by Ultra-J** [comment]
@nikita36078 That is indeed a very good news, very much looking forward to your follow-up update.Thank you for your hard work to pay for emulator.

**Comment by oatmeal01** [comment]
This really is the best Java emulator so far. Thanks for developing this excellent app.

**Comment by AdityaMH** [comment]
do you mean "qwerty" keyboard, @nikita36078 ?
for me, that's not work for my phone.
I think it will better if adding "showing (qwerty) keyboard" in [COMMON SETTING]

**Comment by AdityaMH** [comment]
This tutorial ( https://developer.android.com/training/keyboard-input/index.html ) will affected to game? some Nokia X2 games (320x240), keypad are not affected to input name in game. (real football 2018 for example).

**Comment by oatmeal01** [comment]
@aditya what is the os of your device? i can't install Real football games from 2014 to 2018. J2me loader will automatically close and  goes to homescreen.

**Comment by oatmeal01** [comment]
@aditya what is the os of your device? i can't install Real football games from 2014 to 2018. J2me loader will automatically close and  goes to homescreen.

**Comment by nikita36078** [comment]
@oatmeal01 How much ram do you have? It can be out of memory error.
P.S. Please answer to my question in #108

**Comment by AdityaMH** [comment]
@oatmeal01 lollipop 5.1 and i installed from 2014 to 2018 too. and work like a charm. but still research the file rf 2018 with real player name.

**Comment by oatmeal01** [comment]
@nikita my device has 2GB ram  and im running os 5.0

@aditya i can't install all real football series with 360x640 reso.

**Comment by AdityaMH** [comment]
but my ram is only 1gb. and tested in 360×640 too. but i installed 320×240 (who only for qwerty j2me phone) because they have real name version (Modded).

**Comment by nikita36078** [comment]
@oatmeal1 open an issue then

**Comment by oatmeal01** [comment]
it seems that i can't install this resolutions: 240x400, 360x640. the app will crash

the only resolution that can be installed is
240x320 - touchscreen and non-touchscreen version. 
ill stick with the non-touch version cause the controls from the touch version is hard

**Comment by nikita36078** [comment]
Mapping support added.
