### ISSUE TITLE
Jeux non en français 

### ISSUE THREAD

**Issue by Moutoncorne** [nikita36078/J2ME-Loader#831]
**Emulator version:**
240x320 

**Game version:**
Sony Ericssonn K800I

**Game resolution:**
``(For example, 240x320 or 640x360)``

**Device:**
``(For example, Samsung Galaxy S7)``

**Android version:**
1.7.2
**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
Les jeux ne sont pas en français. J'aimerai que vous mettez la langue française

**Comment by nikita36078** [comment]
Use English here, please. And the emulator has nothing to do with translations, it just launches games. Games can have different localized versions, so you can search for French ones.

**Comment by Moutoncorne** [comment]
How do I get the French versions? Because for the games, I go in dedomil but the sony ericsson k800I games are only in English

**Comment by nikita36078** [comment]
I don't know, just assumed that they may exist somewhere.

**Comment by Moutoncorne92** [comment]
You the creator J2me loader ?

**Comment by nikita36078** [comment]
Yes.

**Comment by Moutoncorne92** [comment]
When is the next update after 1.7.2 coming?

**Comment by nikita36078** [comment]
When it will be ready and stable enough.

**Comment by Moutoncorne** [comment]
Good luck and keep improving. This app is great. Sorry to say but the only thing I would like you to do is to improve the music and sounds of the games. I like the music but I would like you to make it more enjoyable to listen to. I feel like they are old 😅
