### ISSUE TITLE
After a while when I finish the first level, the sound and music stops.

### ISSUE THREAD

**Issue by Moutoncorne** [nikita36078/J2ME-Loader#833]
**Emulator version:**
Sony Ericsson K800I 

**Game version:**
Full the game 

**Game resolution:**
240x320

**Device:**
Huawei 

**Android version:**
??? 
**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
After a while when I finish the first level, the sound and music stops.

**Comment by nikita36078** [comment]
What is the game name?

**Comment by Moutoncorne** [comment]
Full : The Amazing Spider Man, Wrath Of The Titans, Avengers the mobile game, Men In Black 3, assassin creed 3, A good day to : Die Hard, Batman The dark knight rise, Lego Batman, The mobile game, The adventure of tintin, Prince Of Persia :  Forgotten of Sands, Prince Of Persia : zero, Gangstar Rio : City of Saint, Modern Combat 4 Zero Hour, Ghost Recon Futur Soldier, Thor The Dark world, assassin creed brotherhood, Assassin creed révélations, Shrek 4 Forever After, Cowboy and aliens, Kingdom and Lord, Nova 1 and 3, Iron Man 2 and 3, Ice Age : Continentale Drift, Immortal, Avatar 2D, Spiderman Toxic Tower, Spider-Man Ultimate Power, and Total Conquest.
