### ISSUE TITLE
Bug on keyboard

### ISSUE THREAD

**Issue by DavidBrazSan** [nikita36078/J2ME-Loader#837]
**Emulator version:**
``Last Release``

**Description of the issue:**
``When I tighten the button back and view the menu of options the keyboard redifmentions to fit the bar navegation and gets a little smaller.``

**Comment by nikita36078** [comment]
Could you record a video of this bug?

**Comment by DavidBrazSan** [comment]
happens it:

https://user-images.githubusercontent.com/60136669/132997136-ba9f7d0a-b541-487d-97ab-c4f499fb3979.mp4


I think it would be better if you created the option to show the navbar next to the statusbar.

**Comment by Moutoncorne** [comment]
When is the J2ME-Loader update coming to the play store?

**Comment by nikita36078** [comment]
@Moutoncorne It will be released soon.

**Comment by Moutoncorne** [comment]
Okay and thanks you

**Comment by nikita36078** [comment]
Fixed
