### ISSUE TITLE
Storage error: check disk space (over 23 GB left)

### ISSUE THREAD

**Issue by MarvinParlevliet** [nikita36078/J2ME-Loader#838]
**Emulator version:**
1.7.2 (also tried older versions which did not work)

**Device:**
Samsung Galaxy Note4 (N910F)

**Android version:**
LineageOS 18.1 (Android 11)

**Description of the issue:**
I downloaded J2ME Loader from F-Droid and upon launching it, it says "Storage error: check disk space" when I have over 23 GB left. Installing a JAR results in a crash after the Processing screen. Some older versions of J2ME Loader did seem to install the JAR file, but would fail with the error 'No such device'. 

I tried changing the working directory, checking the application's permissions, ejecting my SD card, restarting my device and installing various versions of J2ME Loader, which all did not work. I also tried JL-Mod, which also resulted in the same error, but gave this additional information: "android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 5386 SQLITE_IOERR_SHMMAP): , while compiling: PRAGMA journal_mode"

[log.txt](https://github.com/nikita36078/J2ME-Loader/files/7231383/log.txt)

**Comment by nikita36078** [comment]
Are you sure that the storage permission is granted? SD card isn't supported, but the app should work fine with the default working directory (in the internal storage). Do you have any issues with other emulators/apps that use storage permssion?

**Comment by Marvin4578** [comment]
Hey nikita, first off thanks for your response and for helping to preserve these old games by writing this emulator. 

Yes, I'm sure the permission is granted. Here's a video of what happens (with the app set to the default working directory):

https://user-images.githubusercontent.com/21282031/134820559-e8f26435-98e9-41cc-9a5f-50f7e4078889.mp4

I haven't had any problems with other apps, I've tried RetroArch for instance and it works just fine.

**Comment by Marvin4578** [comment]
Sounds great, I'll test it out when the update's there.

**Comment by nikita36078** [comment]
Should be fine now
