### ISSUE TITLE
[Feature request] Phisical controler support

### ISSUE THREAD

**Issue by supergameromegaclank** [nikita36078/J2ME-Loader#855]
A feature that could definitly enhance the experience with the emulator is compatibility with controlers.
There's some games like Metal gear wich would feel better to play with a mappable Bluetooth controler instead of a touch screen.
Hopefully this is something you are considering for future versions of the emulator, since it is in others like Kemulator.

**Comment by Feodor0090** [comment]
Physical keys remapping is already supported, it works fine with built-in/otg/bt keyboards. It doesn't support gamepads?

**Comment by nikita36078** [comment]
Yes, the option you're looking for is "Key mappings", it can be found in game settings and in profiles.
