### ISSUE TITLE
Soulcalibur Mobile not installing

### ISSUE THREAD

**Issue by TTLTTLR** [nikita36078/J2ME-Loader#865]
**Emulator version:** 1.7.4-play

**Game version:** 1.0.0 (Sony Ericsson K800i)

**Game resolution:** 240 × 320
``(For example, 240x320 or 640x360)``

**Device:** Infinix HOT 10 Play
``(For example, Samsung Galaxy S7)``

**Android version:** 10

**Description of the issue:** When the JAD file is tapped, the emulator returns to the game list screen and the message "Error: Bad descriptor" appears. However, the game worked in a previous version of the emulator. I altered the file a tad (changed only the MIDlet-Name and MIDlet-Vendor), but that has never stopped games from installing, at least not before.
``(What's the problem? - Screenshots showing the issue if applicable)``

**Comment by RocketKnightX** [comment]
Can you fix Las Vegas Nights and Crash of the Titans too?
