### ISSUE TITLE
Question and Feature request external plug-in for save state

### ISSUE THREAD

**Issue by th0rig** [nikita36078/J2ME-Loader#868]
**Emulator version:**
V1.7.4-play

**Game version:**

**Game resolution:**
``(For example, 240x320 or 640x360)``

**Device:**
``(For example, Samsung Galaxy S7)``

**Android version:**

**Description of the issue:**
I wonder if savesates possible? via additional plug-in just like PSP using plug-in make us of plug-in to save current session of gameplay when on custom firmware even on original hardware although not all games will Happy with this feature but if this feature really possible to implement in emulator that will be neat.

**Comment by nikita36078** [comment]
It's impossible, J2ME Loader doesn't emulate hardware, so it can't save the CPU/RAM state.
