### ISSUE TITLE
[Discuss]Simulator detection for some games

### ISSUE THREAD

**Issue by xiexindev** [nikita36078/J2ME-Loader#872]
**Emulator version:**
All version

**Description of the issue:**
I often play games with simulator detection code

**1.  Local time**
![image](https://user-images.githubusercontent.com/19523795/141712564-428a0e13-fb2f-48ab-a3b9-2111b94be09b.png)

e.g: The Chinese meaning in the picture is: Authorization expires

This code may seem very low-level, but it works very well now! Because you can only fix it by changing the date of the device, but this will cause other problems on our device. 

**2. Memory size**
![image](https://user-images.githubusercontent.com/19523795/141714313-96f68d84-4df6-4bd1-8710-988b991809d4.png)

e.g: The Chinese meaning in the picture is: The game can only be played on mobile phones

In the past, phones didn't have much ram, but now Android phones have 6GB or more. This causes memory size validation to fail.

**3. os. name**
reference: https://github.com/nikita36078/J2ME-Loader/issues/863

The solution I've come up with is to add some custom system attributes to the game's configuration, and then change the corresponding bytecode to replace the system functions at install time. Do you have a better solution?
(We can change the game code fix it, but most players don't)

game files(replace .zip to .jar):
[江湖(Memory size).zip](https://github.com/nikita36078/J2ME-Loader/files/7535631/Memory.size.zip)
[精灵召唤之梦游仙境(Local time).zip](https://github.com/nikita36078/J2ME-Loader/files/7535632/Local.time.zip)

delegate functios:
![image](https://user-images.githubusercontent.com/19523795/141717080-5ed4844d-6c99-4fed-ba56-6c84ef14d340.png)
![image](https://user-images.githubusercontent.com/19523795/141717111-616f7945-40d0-48b6-9272-bb71406c7eca.png)

**Comment by xiexindev** [comment]
I think adding custom attributes would pollute the system property. It would be better to add a setting item to the configuration page, like fps limit

**Comment by shinovon** [comment]
2. I made a MemoryTest MIDlet and ran it on J2ME Loader.
It shown 524288 Kbytes, device is Galaxy S10 Lite.
3. The app's code uses `property.substring(0,7)`, what means string cropped to 7 characters and it's causing the exception, and J2ME Loader gives "Linux" in os.name property. So that is the game code issue.

**Comment by xiexindev** [comment]
> 1. I made a MemoryTest MIDlet and ran it on J2ME Loader.
>    It shown 524288 Kbytes, device is Galaxy S10 Lite.
> 2. The app's code uses `property.substring(0,7)`, what means string cropped to 7 characters and it's causing the exception because J2ME Loader gives "Linux" in os.name property. So that is the game code issue.

 I do not deny that it can run on some devices, I just explain that this problem will exist. Android is an open platform, and some vendors may allocate more memory to applications.
All validation is a code issue, and if J2ME Loader can solve them, it's good for game compatibility

**Comment by xiexindev** [comment]
> > 1. I made a MemoryTest MIDlet and ran it on J2ME Loader.
> >    It shown 524288 Kbytes, device is Galaxy S10 Lite.
> > 2. The app's code uses `property.substring(0,7)`, what means string cropped to 7 characters and it's causing the exception because J2ME Loader gives "Linux" in os.name property. So that is the game code issue.
> 
> I do not deny that it can run on some devices, I just explain that this problem will exist. Android is an open platform, and some vendors may allocate more memory to applications. All validation is a code issue, and if J2ME Loader can solve them, it's good for game compatibility

J2ME is an old platform, and current devices may not be fully compatible with them. However, we can try to improve the compatibility of J2ME Loader to accommodate these programs
