### ISSUE TITLE
lcdui.Form is not updating

### ISSUE THREAD

**Issue by shinovon** [nikita36078/J2ME-Loader#873]
**Emulator version:**
1.7.4-play

**Game version:**
.

**Game resolution:**
240x320

**Device:**
Samsung Galaxy S10 Lite

**Android version:**
11

**Description of the issue:**
Lcdui Form's content updating only after minimizing J2ME Loader app.

**Comment by nikita36078** [comment]
In what applications does this bug happen?

**Comment by shinovon** [comment]
> In what applications does this bug happen?

JTube (My app)

What happened:
When I open SettingsForm it's showing me a blank screen, then after I minimize J2ME-Loader and return back - form's content appears.

**Comment by shinovon** [comment]
SettingsForm constructor code:
`public SettingsForm() {`
`super("Settings");`
`setCommandListener(this);`
`addCommand(applyCmd);`
`videoResChoice = new ChoiceGroup("Video Quality", ChoiceGroup.EXCLUSIVE, Constants.VIDEO_QUALITIES, null);`
`append(videoResChoice);`
`// and other ui items`
`}`
Commands handler code:
`if(c == settingsCmd) {`
`if(settingsForm == null) {`
`settingsForm = new SettingsForm();`
`}`
`display(settingsForm);`
`settingsForm.shown();`
`}`

SettingsForm.shown() contains only setSelectedIndex() functions.

**Comment by shinovon** [comment]
Caused by other problem.
