### ISSUE TITLE
Rotation, Hide Buttons Suggestion and Common Settings issue

### ISSUE THREAD

**Issue by oatmeal01** [nikita36078/J2ME-Loader#88]
- Please add rotation control feature in configuring each installed game. This feature must work without activating auto-rotation. The process is when you enter HeightxWidth(e.g.640x360) in screen options it detects to launch the game in landscape orientation and when you enter WidthxHeight(e.g.360x640) it automatically detects to launch the game in portrait orientation. 

- Another suggestion is that you add Mark All/Unmark All buttons from hide buttons. Its annoying configuring each game marking all buttons to hide.

- I also find some issue that when action bar is not activated on some phones(like ViVo y53), you can't access COMMON SETTINGS by long tapping the recent key. So far my other devices can access COMMON SETTINGS by long tapping recent key.

**Comment by skelletR** [comment]
Yes all that needed in next update

**Comment by AdityaMH** [comment]
about screen 360x640, not only portait, they have landscape too. and i still want play 320x240 games in portait screen.

**Comment by skelletR** [comment]
Yes needed for all a rotation lock per game

**Comment by oatmeal01** [comment]
@aditya dont worry about java games (360x640) that are built in landscape it wont affect the game even if its locked in portrait mode. I'm telling about games that needs auto-rotation to be able to play in landscape. Here's the logic just check it yourself, when you download a game and the size entered in Screen Option is: (640 x 360, Height is declared first before Width) - all the games are playable only in landscape mode and you need to activate Auto-rotation to be able to play it in full landscape. If you download a game and the size is: (360 x 640, Width is declared first  before Height) - All the games are playable without activating Auto Rotation.

**Comment by oatmeal01** [comment]
Landscape Example:
- http://terbaik.my.to/download/19466/46/iron_man_3.jar  - this game is (640x360) and it needs autorotation to be able to play in landscape.
- http://www.tamlovethao.mobie.in/files/FarmFrenzylandscape.jar - this game is (240x400) and does not need auto rotation to be able to play in landscape.

**Comment by oatmeal01** [comment]
All the games which you declared the height first before the width (640x360) in screen option are only playable in landscape when you activate auto-rotation.

**Comment by jasper1412** [comment]
> Please add rotation control feature in configuring each installed game. This feature must work without activating auto-rotation. The process is when you enter HeightxWidth(e.g.640x360) in screen options it detects to launch the game in landscape orientation and when you enter WidthxHeight(e.g.360x640) it automatically detects to launch the game in portrait orientation.

What you meant is a orientation control, but this can be controlled on settings, just disable auto-rotate for fixed portrait.

> Another suggestion is that you add Mark All/Unmark All buttons from hide buttons. Its annoying configuring each game marking all buttons to hide.

By long-pressing the game, go to `Settings`, scroll down and untick `Show keyboard` on settings before running the emulator. This is per-app option.

> I also find some issue that when action bar is not activated on some phones(like ViVo y53), you can't access COMMON SETTINGS by long tapping the recent key. So far my other devices can access COMMON SETTINGS by long tapping recent key.

Platform-specific issue.
