### ISSUE TITLE
Problems trying to play those games that i dumped from GT-C3303K

### ISSUE THREAD

**Issue by erikiorai** [nikita36078/J2ME-Loader#887]
**Emulator version:** 1.7.4-play

**Game version:** Brain Challenge v7.6.2, Crazy Penguin v7.1.4, Diamond Twister v7.1.4

**Game resolution:** any resolutions

**Device:** Samsung Galaxy Note10 Lite (SM-N770F)

**Android version:** 11.0

**Description of the issue:**
when i try to play any those games mentioned above it shows this pop up

ALERT
Exeption occur!
Game Termineted.
Error code 2:
those games i dumped from samsung champ GT-C3303K
here is a video capture
https://user-images.githubusercontent.com/14198423/150804357-d47988cb-01df-4409-855c-01852e185a09.mp4

**Comment by ptnn0** [comment]
Can you provide here those games? I will try..

**Comment by Fun4TubeGr** [comment]
Sure here they are https://drive.google.com/drive/folders/11kOcSRbWLcp0VeZ9XH-NnpEuqfIte2WD

**Comment by Fun4TubeGr** [comment]
Oh sorry google drive rejected the files here is a mega link https://mega.nz/file/xBo2DLhQ#DPmgAyPaIdy0X983rFFdsh4a2U0ffbMYnAC2Wu1QWqA

**Comment by woesss** [comment]
Do you have a JAD file for this game? It requires certain JAD/Manifest properties.

**Comment by Fun4TubeGr** [comment]
Ok thanks it works now

**Comment by Fun4TubeGr** [comment]
It works fine just one small problem as you can see in screanshot but all and all i don't care for this issue im not planing to purchise this game anyway but i purchesed some games that on gt-s5610 its any way to copy the licence file on j2me so i can play withaout asking it to purchase?

![SmartSelect_20220124-181526_J2ME Loader](https://user-images.githubusercontent.com/14198423/150821060-49f75aba-5e29-429c-a3be-b1ac962af7fc.jpg)

**Comment by woesss** [comment]
RMSBackup should help, but I do not know where it can be found now.
