### ISSUE TITLE
Help I can't open JAMDAT RACING

### ISSUE THREAD

**Issue by EduMendozaHD** [nikita36078/J2ME-Loader#889]
Hi nikita can you fix this problem? The game closes when I open it. I leave you the crash.txt and the game for you to fix it.

Game And Crash.txt
https://www.mediafire.com/folder/flfgrz3iim8ib/Game

**Comment by nikita36078** [comment]
Go to the game settings and put the following line into the System properties field:
`microedition.locale: en-US`
This game crashes because only English locale is supported.

**Comment by edumen2** [comment]
> Vaya a la configuración del juego y coloque la siguiente línea en el campo de propiedades del sistema: `microedition.locale: en-US` Este juego falla porque solo se admite la configuración regional en inglés.

Thank you it works perfectly

**Comment by EduMendozaHD** [comment]
> Vaya a la configuración del juego y coloque la siguiente línea en el campo de propiedades del sistema: `microedition.locale: en-US` Este juego falla porque solo se admite la configuración regional en inglés.

Thank you it works perfectly
