### ISSUE TITLE
COD Black Ops (2010) doesn't work

### ISSUE THREAD

**Issue by Lucas-mother3** [nikita36078/J2ME-Loader#890]
**Emulator version:**
the latest build

**Game version:**
1.0.0

**Game resolution:**
``(For example, 240x320 or 640x360)``
360x640
480x800

**Device:**
``(For example, Samsung Galaxy S7)``
Huawei Y6 Prime 2019

**Android version:**
9

**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
It always stuck in the loading screen in boot
![Screenshot_20220201_232759_ru playsoftware j2meloader](https://user-images.githubusercontent.com/76678069/151998992-4eea4e74-3b21-4ebb-ba03-6e5881597a20.jpg)

**Comment by nikita36078** [comment]
Install the game through .jad, not .jar.
