### ISSUE TITLE
How can I see emulator logs on Android 11?

### ISSUE THREAD

**Issue by shinovon** [nikita36078/J2ME-Loader#892]
After update 1.7.5 emulator directory has changed and I can't access files in there.
Can I change it back or that is not possible?

**Comment by nikita36078** [comment]
You can open that directory in Files (default file manager), ZArchiver, Total Commander, X-plore or any other compatible app. Recently Google forced new storage changes for Android 11+. I had two options - move data folder to the private directory (Android/data) or/and rewrite a tons of code to support Storage Access Framework, potentially creating new bugs. I decided to stay with the first option, at least for now.

**Comment by shinovon** [comment]
Is root required for that?
![Screenshot_20220221-081254_My Files](https://user-images.githubusercontent.com/43963888/154883094-64d4b213-91e0-4e06-bdd6-9b751e979379.jpg)
(Hidden files is on)

**Comment by shinovon** [comment]
Thanks
