### ISSUE TITLE
Needed more Scale type options

### ISSUE THREAD

**Issue by Monosataspp** [nikita36078/J2ME-Loader#895]
**Emulator version:**
1.7.5

**Game version:**
4.7.53

**Game resolution:**
240x400

**Device:**
Samsung Galaxy A32

**Android version:**
11

**Description of the issue:**
The problem with the large screen device, it make the game look so small (even with the big resolution games) but the Fit or Fill window is too much for me (i don't want the keypad input to be overlay with touchscreen games), so maybe added a x2 or even x3 Scale type
![Screenshot_20220225-163334_J2ME Loader](https://user-images.githubusercontent.com/69386747/155830983-569e71e0-997a-4aa7-a331-e68327c279a1.jpg)

**Comment by woesss** [comment]
Use the "fit" option and the "scale" slider to zoom out the image. Or use the "telephone" layout - it does not intersect with the game image, automatically reducing it.

**Comment by Monosataspp** [comment]
> Use the "fit" option and the "scale" slider to zoom out the image. Or use the "telephone" layout - it does not intersect with the game image, automatically reducing it. For touchscreen games, you can disable the onscreen keyboard.

Thank, but i'll stick with the keypad, thank you very much.
