### ISSUE TITLE
On low FPS, emulator menu is ignored

### ISSUE THREAD

**Issue by Noitarud** [nikita36078/J2ME-Loader#897]
**Emulator version:**
1.7.4

**Game version:**
2.2.3

**Device:**
Lenovo tablet

**Android version:**
10
**Description of the issue:**
This app is not a game, but a database (Bible), so I didn't think to need a high frame rate, so I set five(5).

Problem occurs in following feature:
Application has text search of its database (emulator has replaced this with its own interface, and results list), you can search 'the' and you will see so many hundred until something prevents more. If the frame rate is unlimited selecting one will go to the place. If the frame rate is low selecting one will be ignored (go back). (I suggest you do not search for 'the' - this will take a long time at 5 FPS, try 'double portion')

Low priority.

[kjv.zip](https://github.com/nikita36078/J2ME-Loader/files/8258203/kjv.zip)

**Comment by nikita36078** [comment]
On 1.7.8 selection doesn't stuck and works properly.

**Comment by Noitarud** [comment]
I have noticed two other things with this guest app:

In menu select "About", the text appears cut short.
In menu select "Preferences", the "Paper" is in fact sample text, long-pressing on that oversized image lets you change the displayed font.
