### ISSUE TITLE
Any way to batch install java files?

### ISSUE THREAD

**Issue by Exanoff12** [nikita36078/J2ME-Loader#898]
**Emulator version:**

1.7.5-play
**Game version:**

n/a
**Game resolution:**
``(For example, 240x320 or 640x360)``
n/a
**Device:**
``(For example, Samsung Galaxy S7)``
Nokia 2
**Android version:**
7.1
**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``

hi, so i recently downloaded a java games dump archive from archive.org . the downloaded zip file contains about 1000 java games . i was wondering if there is any way that i can select the zip and install everything from it at once without picking each one because it would take me ages to manually install everything . thanks in advance

**Comment by nikita36078** [comment]
Duplicate #482
