### ISSUE TITLE
Some ideas for future releases

### ISSUE THREAD

**Issue by jasper1412** [nikita36078/J2ME-Loader#90]
Typical emulator functions like save/load states, fast forwarding and shaders.

**Comment by oatmeal01** [comment]
shaders... a nice idea

**Comment by nikita36078** [comment]
Save states and fast forwarding currently can't be implemented due to the emulator limitations, about shaders - I want to make emulator more stable before any graphic improvements.

**Comment by AdityaMH** [comment]
How about adding default keypad bg/color setting? each person have different color taste. so they can playing game with same color without changing color after converting complete (first setting). Or  adding menu "QWERTY keyboard" caller in [COMMON SETTING], without that they can't input team name in Real Football 2018 (320×240).

**Comment by jasper1412** [comment]
@AdityaMH I agree with keyboard implementation,but as @nikita36078 said on any other improvements, development of the app is prioritized to emulation stability, so implementation of custom colors is not on the list, yet.
