### ISSUE TITLE
Total Conquest Touch input bug.

### ISSUE THREAD

**Issue by Naimur75** [nikita36078/J2ME-Loader#900]
**Emulator version:**
1.7.5-play

**Game version:**
1.0.0

**Game resolution:**
480*800

**Device:**
Realme C3

**Android version:**
Android 10

**Description of the issue:**
Total Conquest 480*800 Touch input can't work. It is my favorite game. I can't put any building. The bug start in trial when Archer lookout to build.

![Screenshot_2022-03-29-15-54-03-68_7811e6ffdebce77637db4a754a2e47d6](https://user-images.githubusercontent.com/102588710/160586074-773e954c-90ef-494e-8886-0abc597583e7.jpg)

**Comment by nikita36078** [comment]
Does this bug still happen? I couldn't reproduce it back then, and still can't, no matter what game/Android version I use.
