### ISSUE TITLE
Error opening Graphwar

### ISSUE THREAD

**Issue by ElNico56** [nikita36078/J2ME-Loader#903]
**Emulator version:**
1.7.5-play

**Game version:**
1.0.0+

**Device:**
Samsung Galaxy A52

**Android version:**
12

**Description of the issue:**
File does not open, throws error
"Fail attribute MIDlet-Name not found"

**Comment by nikita36078** [comment]
It's a desktop (Java SE) application, this emulator supports only mobile (Java ME) apps.
