### ISSUE TITLE
For a tablet, the control buttons are too big. It would be great if you could add a controller. Adjust the size of the buttons a bit

### ISSUE THREAD

**Issue by tee4341** [nikita36078/J2ME-Loader#904]
**Emulator version:**
1.7.5
**Game version:**
1.0
**Game resolution:**
``128x128``
**Device:**
``(Nokia/SE)``
**Android version:**
9 pie
**Description of the issue:**
``(For a tablet, the control buttons are too big. It would be great if you could add a controller. Adjust the size of the buttons a bit)``
![16-05-2022_09-03-29_trim (1)](https://user-images.githubusercontent.com/48321898/168515980-8f843f8b-9395-4b7a-89e4-7c11bae84d8d.gif)
![16-05-2022_09-06-26_trim (1)](https://user-images.githubusercontent.com/48321898/168515992-8e43acee-47dd-4888-9fe4-b19d5043563d.gif)
The program works wonderfully. Now I like to play games 128*128 but I can't scale down the controller.
![168511529-6bfb2ae3-fb67-4f83-9318-75ded1e2d121](https://user-images.githubusercontent.com/48321898/168516065-55567175-5cb0-46e4-b849-8c45da95501a.gif)
Helping write a little bit of code would be greatly appreciated

**Comment by nikita36078** [comment]
Probably I'm late here, but you can control button size in the menu - Virtual keyboard - Keylayout edit mode / Keylayout resize mode.
