### ISSUE TITLE
J2ME Loader Clears Recent Saves for GB upon Force-Close

### ISSUE THREAD

**Issue by KaiserZandrich** [nikita36078/J2ME-Loader#911]
Emulator version: 1.7.5, claimed fixed as early as 1.2.6.3

Game version: Pokemon Red "2.2.0"

Game resolution: N/A

Device: Huawei P30

Android version: 10

Description of the issue:

Referred to issue #75; J2ME wipes all recent saves upon force-close/background close for GB emulated titles. This is true for Pokemon Red and Crystal, which are both two different emulators (I'm assuming).

Is there any way to recover the files themselves, or are they actually wiped on force-close?

**Comment by nikita36078** [comment]
It's how GB emulator (MeBoy) works - it saves the game only when tap Exit button. So there's no way to prevent this issue from the J2ME Loader side.
