### ISSUE TITLE
port it for RetroArch libretro

### ISSUE THREAD

**Issue by AngelofMe** [nikita36078/J2ME-Loader#913]
**Emulator version:**

**Game version:**

**Game resolution:**
``(For example, 240x320 or 640x360)``

**Device:**
``(For example, Samsung Galaxy S7)``

**Android version:**

**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``

**Comment by xiexindev** [comment]
That should be RetroArch's job, The J2ME-Loader is a standalone emulator

**Comment by Dystnine** [comment]
Duplicate #813
