### ISSUE TITLE
how ican to translate this app to my language?

### ISSUE THREAD

**Issue by AshiVered** [nikita36078/J2ME-Loader#917]
i don't found the res/values folders...

**Comment by shinovon** [comment]
![image](https://user-images.githubusercontent.com/43963888/184269355-014748cf-f741-4ea3-88cb-d00bdd5b4637.png)

**Comment by nikita36078** [comment]
You can translate J2ME Loader on [Crowdin](https://crowdin.com/project/j2me-loader).
