### ISSUE TITLE
Can't read "J2ME-apps.db" after reinstalling

### ISSUE THREAD

**Issue by Estrangeling** [nikita36078/J2ME-Loader#929]
**Emulator version:**
J2ME-Loader v1.7.7

**Device:**
OPPO A96

**Android version:**
Android 11

**Description of the issue:**

File "*/J2ME-apps.db" is not readable

![Screenshot_2022-09-18-13-22-52-92_7811e6ffdebce77637db4a754a2e47d6 1](https://user-images.githubusercontent.com/78679218/190887657-5153c2e2-9b69-4db7-9914-f9201a0c4563.jpg)

Please help, I cannot load the old database after reinstalling the application.

Long story short, I am very nostalgic and I have installed many J2ME games in the previous installation of J2ME-Loader on my phone.
At the moment there are exactly 368 games installed. They are installed to version 1.7.6 of J2ME-loader. My system is Android 11.

When I tried to update the app to version 1.7.7, the system said "installation failed, an app with the same signature has already been installed" or something like that.

So I decided to uninstall the old version and install the new version, I know if I uninstall J2ME-Loader the folder "/storage/emulated/0/Android/data/ru.playsoftware.j2meloader" will be deleted, and it contains all the games I have installed.
So I renamed the folder by adding a 1 at the end, uninstall and reinstall and renaming the folder back.

Cannot read "*/J2ME-apps.db", see screenshot above.

Okay, so if version 1.7.7 cannot read the database of version 1.7.6, then if I roll back to version 1.7.6, it should work.
So I renamed the folder, uninstalled 1.7.7 and reinstalled 1.7.6 and renamed the folder back.
Nope, same issue.

So how do I get the games back without reinstalling all of them? 
The data definitely is not corrupted or edited in any way, I merely renamed the root folder, so it must be usable.
I noticed these three files at the root folder: J2ME-apps.db, J2ME-apps.db-shm and J2ME-apps.db-wal.
So the list of the games is stored in a sqlite database located at J2ME-apps.db.

How do I make the app read the old database? My guess is that different installations use different usernames and/or passwords for the database. And if so, they are not tied to versions as different installations of the same version cannot read the same database.

I am extremely tech-savvy and fluent in PowerShell and Python, know a little JavaScript and I am [Ξένη Γήινος](https://codereview.stackexchange.com/users/234107/%ce%9e%ce%ad%ce%bd%ce%b7-%ce%93%ce%ae%ce%b9%ce%bd%ce%bf%cf%82), so I am absolutely no fool.

Below is a list of the content of said folder in json format. I wrote the Python 3 program that dumped it.
[j2me-apps.txt](https://github.com/nikita36078/J2ME-Loader/files/9593183/j2me-apps.txt)

And the three database files:

[Google Drive](https://drive.google.com/file/d/1sWscyNOiVQdtK5yLh-iyvGX4r5sfE20P/view)

Any help is appreciated.

**Comment by Estrangeling** [comment]
I have successfully opened the database on a Windows computer using sqlite3 and found out the database is not password protected.

**Comment by woesss** [comment]
If you did not rename the installed games, then the database files are not important, you can safely delete them, and the next time you start the emulator, they will be created based on the contents of the directory. But I suspect that the problem is not in the database, but in the access rights and with the rest of the files there will be the same trouble. Try to rename the directory again (the emulator must be closed before any manipulations), start the emulator, close it and move / copy the contents to the directory it created by itself.

**Comment by Estrangeling** [comment]
Yes, after I deleted the database files and renamed the folder back, the database is recreated but the games are still not found, but after I moved all the things from the old folder to the folder created by this installation (using a computer because this stupid system wouldn't allow me to move things to /storage/emulated/0/Android/data), and deleted the database, the database is recreated and the games show up again.

So this is indeed a permission issue.
Thank you woesss
