### ISSUE TITLE
error with "Suspend" on MeBoy application

### ISSUE THREAD

**Issue by fireclouu** [nikita36078/J2ME-Loader#93]
![screenshot_2018-02-04-18-19-07](https://user-images.githubusercontent.com/22563129/35785588-5a3883c6-0a5c-11e8-9a8a-6c94e0ad29e1.png)

This is MeBoy, a gb/gbc emulator.

It happens when you start the game on MeBoy, goes to menu and press `Suspend` option.

> Oh! and another thing:
![screenshot_2018-02-14-19-26-49](https://user-images.githubusercontent.com/22563129/36202054-3bb462d6-11bd-11e8-8a0c-c487d41e53e0.png)
enabling Sounds on Settings menu inside MeBoy crashes the app.

**Comment by jasper1412** [comment]
We have a progress here! Enabling sounds menu on 1.2.7.7 now does not crash the app. But literally the sound isn't playing on this game.

**Comment by jasper1412** [comment]
Unfortunately on 1.2.7.9-open, Settings menu stops working.
![screenshot_2018-03-06-17-44-31](https://user-images.githubusercontent.com/22563129/37025329-5cdd2656-2166-11e8-895f-e9d73cad7176.png)

**Comment by jasper1412** [comment]
1.2.8-open now fixes `Settings` menu

**Comment by oatmeal01** [comment]
1.2.8.4 - Still, sound is not working.

**Comment by jasper1412** [comment]
version 1.4.9-play seems okay with suspend  command but cannot resume its saved state, audio and graphics now functions great, though after exiting on certain loaded cat from meboy-f and loads it again, audio emulation gets crippled for some reason.

**Comment by fireclouu** [comment]
works correctly on the latest build
