### ISSUE TITLE
Dexing error after converting jar for any jar game

### ISSUE THREAD

**Issue by p0ryae** [nikita36078/J2ME-Loader#930]
**Emulator version:**
Version 1.7.7

**Games**
I have tried every single possible resolution for the games mentioned. I have tried supported games such as SILENT HILL 3, Ancient Empires 2, Assassin Creeds 3, gangster 2 and etc.

**Device:**
HTC Wildfire S

**Android version:**
4.2.2

**Description of the issue:**
No game gets initialized and after the JAR process, an error for dexing will pop up.

**Comment by nikita36078** [comment]
This phone doesn't have enough RAM for JAR convertation, only very small J2ME apps can be processed. Minimum requirement is 1GB, 1.5-2GB is recommended. As a workaround, you can convert apps on other device with more memory and copy them to this one.
