### ISSUE TITLE
Dexing missing class file after converting jar to dex in ver 1.7.7

### ISSUE THREAD

**Issue by skypeaful** [nikita36078/J2ME-Loader#931]
**Emulator version:**
1.7.7

**Game version:**
1.0

**Game resolution:**
240x320

**Device:**
Realme 8

**Android version:**
11

**Description of the issue:**

Since j2meloader update to 1.7.7, the dex converted isn't stable. For example, i open the game Vuong quoc sung vat liet hoa java, you can get in [Link](https://mega.nz/file/GEkVQTxL#9cEPNnya2m5k_82YOVX5MvXaKCiQukjwki4N64BehaY) or opera store. So I attached image of j2meloader ver 1.7.5 and j2meloader ver 1.7.7

In v1.7.7 after converted to dex, the class a/a.class is missing but in old version 1.7.5 the class a/a.class is still appear so I think 100% this is problem of converted of New version, please fix that issue, thank. I also attached images of a/a.class in orginal .jar as proof. Sorry for my bad English 😂
![IMG_20220925_071027](https://user-images.githubusercontent.com/16753459/192123031-72e78c9e-2f46-462a-abcc-b8805c0885af.jpg)
![IMG_20220925_071211](https://user-images.githubusercontent.com/16753459/192123034-8480e9c7-4b12-49ba-812e-88f3f89c7c8b.jpg)
![Screenshot_2022-09-25-07-12-54-66_2602b93dc3ef59eeb51bac049073361e](https://user-images.githubusercontent.com/16753459/192123035-9d08e0a2-10ae-440c-ad66-176dadbda68b.jpg)

**Comment by xiexindev** [comment]
this problem like this: https://github.com/nikita36078/J2ME-Loader/issues/814
There are some incorrect bytecode in the jar file, the new version is installed by skipping these class files.
