### ISSUE TITLE
github releases 64-bit?

### ISSUE THREAD

**Issue by soundsnow** [nikita36078/J2ME-Loader#934]
arm64-v8a please!

**Comment by 2270057439** [comment]
[Uploading J2ME_1.7.7_Arm64_v8a.apk.zip…]()

**Comment by 2270057439** [comment]
> arm64-v8a，拜托！
[arm64-v8a](https://github.com/2270057439/J2ME-Loader/releases/download/untagged-b5be752f1942c717bb35/J2ME_1.7.7_Arm64_v8a.apk)

**Comment by nikita36078** [comment]
Duplicate #781. I'll add 64bit libs in the next release.
