### ISSUE TITLE
RAM search cheat value

### ISSUE THREAD

**Issue by soundsnow** [nikita36078/J2ME-Loader#941]
memory ranges: Jh (Java heap)
enter a value to search for
value: =, ≠, <, ≤, >, ≥
type: auto, dword, float, double, word, byte, qword, xor

**Comment by soundsnow** [comment]
![Screenshot_20221031-220228](https://user-images.githubusercontent.com/109885044/199026366-4de9fb77-233f-46ad-9ae9-00424beeb311.png)

**Comment by shinovon** [comment]
Duplicate, see #886, #619

**Comment by xiexindev** [comment]
U can edit game record files(It's difficult and not accurate).
or use GameGuardian (system must be root or VirtualXposed)
