### ISSUE TITLE
Очень сломанная игра

### ISSUE THREAD

**Issue by SuperWillow** [nikita36078/J2ME-Loader#945]
**Emulator version:**
1.7.7

**Game version:**
Minecraft 3D - 1.0

**Game resolution:**
``240x320``

**Device:**
``HONOR 50 Lite``

**Android version:**
Android 11

**Description of the issue:**
Короче я хотела поиграть в Minecraft для мобильных ява-устройств, и вот что из этого вышло. Игра стала сломанной, там вообще странные текстуры и сильно сломана, вот скриншоты: 
![Screenshot_20221116_222657](https://user-images.githubusercontent.com/87235362/202222864-7ae0b657-8c3b-430d-a558-bd6dc7a2df83.jpg)
![Screenshot_20221116_222718](https://user-images.githubusercontent.com/87235362/202222920-d0acf22c-633d-490b-821d-83d94c7972bd.jpg)
![Screenshot_20221116_222847](https://user-images.githubusercontent.com/87235362/202222992-aec0b9e0-97b9-4e18-9a4b-26bf80e29886.jpg)
![Screenshot_20221116_222857](https://user-images.githubusercontent.com/87235362/202223023-561a3a71-3ce4-491d-a951-408aadd0ed15.jpg)
Прошу это исправить и оптимизировать под J2ME Loader. Я знаю, что игры Minecraft не существует под мобильные Java-устройства :trollface:

**Comment by nekono48** [comment]
Это не проблема эмуляторы это проблема самой игры https://youtube.com/shorts/mSfTtIvDK8A?feature=share

**Comment by SuperWillow** [comment]
> Это не проблема эмуляторы это проблема самой игры https://youtube.com/shorts/mSfTtIvDK8A?feature=share

Спасибо:)
