### ISSUE TITLE
提个建议 suggestions

### ISSUE THREAD

**Issue by e1399579** [nikita36078/J2ME-Loader#946]
**Emulator version:**
1.77

**Game version:**
1.0

**Game resolution:**
240x320

**Device:**
Sony J9210

**Android version:**
11

**Description of the issue:**

希望在配置文件中，添加虚拟键盘界面编辑功能，因为游戏无非就是240*320和360*640等有限的几种，大部分是240*320的，没必要每导入一个游戏，都要再重新编辑一次，真的很烦很累！

I wish the config settings to add [edit virtual keyboard UI] function,because the most of games has same resolution with 240*320.If i must edit virtual keyboard for every game,it's very annoying.

**Comment by woesss** [comment]
You can save keyboard settings to a profile and then import from profiles to any game. In the configuration window, open the options menu (three dots in the appbar) - there you will find the options for loading / saving the profile. If you select "make default" when saving, the profile will be loaded automatically on each subsequent installation. You can also make an existing profile the default at any time in the profiles window.

**Comment by e1399579** [comment]
Thanks,i create a new profile and import succeed.Something is strange,i tried it before and the virtual keyboard checkbox is grey,maybe the profile is old version's.And anyway,thank you very much!

**Comment by woesss** [comment]
The keyboard flag is grey - which means that the profile does not contain keyboard settings. That is, it was exported without this flag, or the keyboard was not configured, or the profile was created from the profiles window.
