### ISSUE TITLE
Wont Install on Samsung Galaxy V

### ISSUE THREAD

**Issue by dimaspaf14** [nikita36078/J2ME-Loader#953]
**Emulator version:**
1.7.8

**Game version:**
Non-game

**Game resolution:**
Phone res 480x800

**Device:**
Samsung Galaxy V (SM-G313HZ)

**Android version:**
4.4.2 (SDK 19)

**Description of the issue:**
Wont install on this samsung device.. 
[Video](https://youtube.com/shorts/TZyuFnwQolg?feature=share)

**Comment by nikita36078** [comment]
Same with 1.7.9? It can't be an emulator issue, there's nothing that could prevent the emulator from installing, your device is also listed as support in Google Play. Maybe you didn't have enough space or something like it.
