### ISSUE TITLE
How do I run?

### ISSUE THREAD

**Issue by UnBeatWaterGH** [nikita36078/J2ME-Loader#954]
**Emulator version:**
Probably the latest verdion

**Game version:**
Can’t really run game

**Game resolution:**
``(For example, 240x320 or 640x360)``
How do I run?

**Device:**
``(For example, Samsung Galaxy S7)``
M1 Mac Mini (2020)

**Android version:**
MacOS 13

**Description of the issue:**
``(What's the problem? - Screenshots showing the issue if applicable)``
How do I run APK thing?

**Comment by XerTheSquirrel** [comment]
J2ME Loader is for Android only, so you would have to install something like Android Studio or IntelliJ Ultimate, then build the project and run it from there. It does not natively run on macOS, iOS, Windows, or Linux.

**Comment by XerTheSquirrel** [comment]
No reason to be an asshole.

**Comment by UnBeatWaterGH** [comment]
No reason to use an Android Emulator.
