### ISSUE TITLE
Gangstar 2 crashs 320x240

### ISSUE THREAD

**Issue by light-and-ray** [nikita36078/J2ME-Loader#955]
**Emulator version:**
1.7.8-play

**Game version:**
1.0.3 
**Game resolution:**
320x240 (Horizontal)

**Device:**
Android device: Retroid Pocket 3+, also tried on Redmi Note 10S
Emulated devices: Nokia C3-00, Nokia E5-00, Nokia E71 / E72, Samsung GT-S3353 / GT-S3350

**Android version:**
11

**Description of the issue:**
http://dedomil.net/games/236/screen/11
Any of these games crash when I press "New Game". Any other [Gangstar games](http://dedomil.net/games/search/gangstar/page/1) in the same aspect ratio from the same website work well, even Gangstar: Crime City which has been released earlier

Log: 
[log.txt](https://github.com/nikita36078/J2ME-Loader/files/10609278/log.txt)

P.s. Gangstar 2 240x320 (vertical) 1.0.7 version works well, but I prefer to have horizontal games

**Comment by woesss** [comment]
Install it via JAD

**Comment by light-and-ray** [comment]
Okay, it works now. Thank you. Unfortunately this version is too outdated... But the problem is gone
