### ISSUE TITLE
Angry Birds Seasons Crashes upon launching.

### ISSUE THREAD

**Issue by riich17** [nikita36078/J2ME-Loader#956]
**Emulator version:**
1.7.8-play

**Game version:**
2.0.34

**Game resolution:**
240x400 (Same as Angry Birds Classic)

**Device:**
Xiaomi Redmi 9

**Android version:**
Android 11

**Description of the issue:**
The game can be installed successfully. However, when I try to open it, the game just crashes. It seams the emulator can't just load it.

This game is pretty obscure, but it's an official release that was once available on the store.

The only link I could get to download and test the rom was this:

https://mega.nz/file/vRJXkCQI#2zcTv2l6j-kEvRBREeEl23CWacAz3-akUO7IYyOlA84

**Screenshots**
![Screenshot_2023-02-24-01-09-30-787_ru.playsoftware.j2meloader.jpg](https://user-images.githubusercontent.com/72539785/221115099-b6ca3a26-2c2f-4681-95fa-32626e796645.jpg)

![Screenshot_2023-02-24-01-09-28-582_ru.playsoftware.j2meloader.jpg](https://user-images.githubusercontent.com/72539785/221115100-6a981102-f297-441d-aeef-cc141b7be2fc.jpg)

**Comment by shinovon** [comment]
It can be DRM protected

**Comment by shinovon** [comment]
yep, it is.
![image](https://user-images.githubusercontent.com/43963888/221198937-e9523f89-bc93-4861-a63d-5bba065eb5ea.png)

**Comment by woesss** [comment]
It requires the [Nokia In-App Payment API](https://nikita36078.github.io/J2ME_Docs/docs/nokiainapp/) extension, but the emulator doesn't have it yet.
