### ISSUE TITLE
Errors while building app in Android studio 

### ISSUE THREAD

**Issue by Hidte09** [nikita36078/J2ME-Loader#963]
[CXX1405] error when building with ndkBuild using D:\J2ME LOADER\app\src\main\cpp\Android.mk: Build command failed.
Error while executing process C:\Users\hidte\AppData\Local\Android\Sdk\ndk\22.1.7171670\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=D:\J2ME LOADER\app\src\main\cpp\Android.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=0 APP_PLATFORM=android-16 NDK_OUT=D:\J2ME LOADER\app\build\intermediates\cxx\Release\3f5y4c5l/obj NDK_LIBS_OUT=D:\J2ME LOADER\app\build\intermediates\cxx\Release\3f5y4c5l/lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
Android NDK: Your APP_BUILD_SCRIPT points to an unknown file: D:\J2ME LOADER\app\src\main\cpp\Android.mk    

fcntl(): Bad file descriptor
C:/Users/hidte/AppData/Local/Android/Sdk/ndk/22.1.7171670/build//../build/core/[add-application.mk:88](http://add-application.mk:88/): *** Android NDK: Aborting...    .  Stop.

**Comment by woesss** [comment]
Most likely because of the space in the folder name

**Comment by Hidte09** [comment]
Then how to fix it not getting errors again.
