### ISSUE TITLE
3D Graphics bugs

### ISSUE THREAD

**Issue by DiegoSousa123** [nikita36078/J2ME-Loader#97]
Some 3D games have bumpy colors, for example: Red turns blue, or skin color turns light blue. The games I tested are: Wwe SmackDown vs. Raw, Need For Speed ​​Shift 3D and Asphalt 3 3D

**Comment by oatmeal01** [comment]
There's a problem with the 3d engine, 2d games has been fixed

**Comment by jasper1412** [comment]
this is fixed on 1.2.7.5
