### ISSUE TITLE
Real Dark mode

### ISSUE THREAD

**Issue by soundsnow** [nikita36078/J2ME-Loader#972]
Maybe you can indeed call Light mode Light mode
because RGB:255,255,255. ffffff
But Dark mode is obviously far from the real Dark mode
Windows 11 Dark mode Task Manager
sorry, this this is Windows 10
![6d28602jghv51](https://user-images.githubusercontent.com/109885044/227903611-95399fc3-55ff-4585-80fb-62daec71f1f9.png)

**Comment by woesss** [comment]
"Dark" doesn't equal "Black"
