### ISSUE TITLE
[Feature Request] Installation through JAD files

### ISSUE THREAD

**Issue by leopard20** [nikita36078/J2ME-Loader#98]
Hi.
Can you also add installation of games through their JAD companion files?
Some games (especially games by NetLizard such as Contr Terrorism 2) need to be installed through the JAD files, otherwise the game asks you to buy it. If you install them through the JAD files the games think  you have installed them from the internet, making them believe you have the full version!

**Comment by DiegoSousa123** [comment]
Yes yes yes

**Comment by jasper1412** [comment]
this one can be closed. 1.2.7.8 now supports .jad installation

**Comment by ExtremeNerd** [comment]
Some .jad files show "can't convert". You can rename file to .txt and open it to get the .jar midlet URL. Then download .jar from that URL then you can easily run it. That is what I had to do with Official Opera Mini in J2ME Loader downloaded from F-droid....
