### ISSUE TITLE
7000+ games without any settings

### ISSUE THREAD

**Issue by soundsnow** [nikita36078/J2ME-Loader#980]
Hi @nikita36078 ,do you know [kahvibreak](https://bluemaxima.org/kahvibreak)?
Kahvibreak is a preservation project and collection of Java 2 Micro Edition mobile phone games, presented using the Flashpoint launcher and emulated via the J2ME emulators KEmulator and FreeJ2ME. 

Opening games with the kahvibreak launcher does not require any setup.  Because it has a built-in game database. The current version is 1.6, more games will be added in the next version

From its database, you can see and judge Resolution, Orientation, Font size, Layout/Manufacturer (Nokia, SonyEricsson, Siemens, Motorola, etc.), hidden extra virtual buttons, and touch-screen games hide virtual buttons by default

https://bluemaxima.org/kahvibreak/Kahvibreak%201.6.zip
Kahvibreak Database File Path
Kahvibreak Version.zip/Data/Platforms/J2ME.xml

**Comment by nikita36078** [comment]
Any connections with commercial games can cause legal issues, so I can't include any games in the emulator.
