### ISSUE TITLE
Question about multitouch 

### ISSUE THREAD

**Issue by skelletR** [nikita36078/J2ME-Loader#982]
Eventually, it supports multi-touch ? Especially for touch screen games?

**Comment by shinovon** [comment]
#938
Multi-touch input is enabled only if there is `Nokia-UI-Enhancement: EnableMultiPointTouchEvents` parameter in the manifest,
There are some Nokia Asha & Symbian^3 games that support this feature.

**Comment by skelletR** [comment]
> #938 Multi-touch input is enabled only if there is `Nokia-UI-Enhancement: EnableMultiPointTouchEvents` parameter in the manifest, There are some Nokia Asha & Symbian^3 games that support this feature.

Oh, i understand. Thanks you, i hope some feature in the J2ME-Loader can add, modified etc. To support multitouch in the game, if the game not supported multitouch by itself
