### ISSUE TITLE
J2ME Loader Emulator as a RetroArch Libretro Core

### ISSUE THREAD

**Issue by AnthonyFBA** [nikita36078/J2ME-Loader#987]
My Request: Should the J2ME Loader Emulator Being Available on PC Exclusively as a RetroArch Libretro Core? Hope This Brings Nikita's Attention. 

RetroArch on EmuGen Wiki: https://emulation.gametechwiki.com/index.php/RetroArch
![JL](https://user-images.githubusercontent.com/70442205/230909610-2666f993-ebbe-4cb7-8222-2100c8a5d117.png)
![500px-Retroarch](https://user-images.githubusercontent.com/70442205/230909617-a83303ae-e681-4161-9487-5f0e4cb2383d.png)

**Comment by XerTheSquirrel** [comment]
That is not possible, it would involve rewriting everything. See #800 #813 .

**Comment by AnthonyFBA** [comment]
Could a Team of RetroArch In Association With Nikita36078 Took J2ME Loader's Android Source Code & Rewriting Everything To Be a Libretro Core?
