### ISSUE TITLE
List Of Tested Java Games (Touchscreen)

### ISSUE THREAD

**Issue by oatmeal01** [nikita36078/J2ME-Loader#99]
# **Touchscreen Games**
>\- All the games that are listed here are tested to work with J2ME Loader. 

**(AR)** - Auto-Rotation Enabled.

| Game Name | Size(s) | Orientation |
| :---         |     :---:      |     :---:      |
|  A Good Day To Die Hard  | 640x360      |  L (AR) |
| Age Of Empires III   | 360x640     | P  |
|    Age Of Empires III: Asian Dynasties | 360x640      |  P|
|   Assassin's Creed Brotherhood | 640x360     |  L (AR)|
|  Assassin's Creed Revelations  | 640x360     |  L (AR)|
|    Assassin's Creed 3 | 640x360     |  L (AR)|
|   Assassins's Creed 2 | 240x400     |  L |
| Block Breaker 3 Unlimited   | 360x640   |  P|
|  Bubble bash 2  | 360x640     |  P|
|  Bubble Bash 3  | 360x640   |  P|
| Bubble Bash   | 360x640     |  P|
|    Candy Machine| 360x640     |  P|
|    Call of Duty 5| 360x640     |  P|
|    Carnival Land| 360x640    |  P|
|   Catchphrase | 360x640     |  P|
|    Clash of Titans | 240x400     |  P|
|    Cowboys And Aliens| 640x360     |  L (AR)|
|  Date Or Ditch 2  | 360x640     |  P|
|   Date Or Ditch | 180x320     |  P|
|    Diamond Twister 3 | 360x640     |  P|
|   Diamond Twister  | 360x640     |  P|
|  Dictator Defense  | 240x400<br/>360x640     |  P|
|  Disney Magic Kingdoms  | 640x360     |  L (AR)|
|  Dogz 2  | 360x640     |  P|
|  Dragon Mania  | 640x360     |  L (AR)|
|  Dungeon Hunter: Curse of Heaven  | 640x360     |  L (AR)|
|   Earthworm Jim | 240x400<br/>640x360     |  L<br/>L (AR)|
|  Edge  | 360x640     |  P|
|   Edge Extended | 360x640    |  P|
| Far Cry 2| 640x360     |  L (AR)|
|   Farm Frenzy 2| 640x360     |  L (AR)|
|   Farm Frenzy | 240x400    |  L |
|   Fashion Icon | 240x400     |  L |
| Gangstar 2   | 640x360     |  L (AR)|
| Gangstar 3: Miami Vindication   | 640x360     |  L (AR)|
|   Gangstar City | 640x360     |  L (AR)|
|  Gangstar Rio  | 640x360     |  L (AR)|
| Generator Rex   | 360x640     | P|
|  Ghost Recon: Future Soldier  | 640x360     |  L (AR)|
| Green Farm 3   | 240x400<br/>640x360     | L <br/>L (AR)|
|Green Farm    | 240x400<br/>640x360     |  L<br/>L (AR)|
|  Guitar Rock Tour 2  | 360 x640    |  P|
|  Guitar Rock Tour  | 640x360     |  L (AR)|
|  H.A.W.X  | 360x640     |  P|
|    Harry Potter and the Deathly Hollows Part 2| 640x360     |  L (AR)|
|  Heroes Lore Zero  | 240x420     |  P|
|  High School Hook Ups  | 240x400<br/>640x360     |  L<br/>L (AR)|
|  Ice Age Scrat Ventures | 640x360     |  L (AR)|
|   Ice Age Vilage | 640x360     |  L (AR)|
| Iron Man 3   | 640x360     |  L (AR)|
| Jurassic Park   | 640x360     |  L (AR)|
|    Kingdoms and Lords| 640x360     |  L (AR)|
|   Las Vegas Nights | 240x400     |  P|
|   Let's Go Bowling | 360x640     |  P|
|   Let's Golf | 360x640     |  P|
|   Little Big City 2 | 640x360     |  L (AR)|
|    Littlest Petshop| 240x400<br/>640x360     | L<br/>L (AR)|
|  Lord of the Rings Middle Earth Defence | 360x640    |  P|
|  Lost Planet 2  | 640x360     |  L (AR)|
|   March of Heroes | 640x360     |  L (AR)|
|  Mega Tower Assault  | 640x360     |  L (AR)|
|    Men In Black 3| 640x360     |  L (AR)|
|  Miami Nights 2  | 240x400<br/>640x360     |  L<br/>L (AR)|
|   Midnight Bowling 3 | 240x400     |  P|
|  Midnight Bowling 2  | 640x360     |  L (AR)|
|  Midnight Pool 3  | 640x360     |  L (AR)|
|  Midnight Pool 4 | 640x360     |  L (AR)|
|  Modern Combat 2  | 640x360     |  L (AR)|
|  Modern Combat 4  | 640x360     |  L (AR)|
|  Monsters University  | 640x360     |  L (AR)|
|    Monsters vs Aliens | 240x349   |  P|
| My Life in New York   | 640x360     |  L (AR)|
| NBA Pro Basketball 2010   |360x640     |  P|
|   New York Nights 2 | 640x360     |  L (AR)|
|   Night at The Museum 2 | 640x360     |  L (AR)|
| Ninja Prophecy   | 360x640    |  P|
|   NOVA 3 | 640x360     |  L (AR)|
|  NOVA  | 640x360     |  L (AR)|
|  NOVA Legacy  | 640x360     |  L (AR)|
|   Oregon Trail Gold Rush | 640x360     |  L (AR)|
|   Plants vs Zombies | 640x360     |  L (AR)|
|   Prince of Persia Forgotten Sands | 640x360     |  L (AR)|
|   Predators | 640x360     |  L (AR)|
|   Prince of Persia Zero | 640x360     |  L (AR)|
|   Rayman Raving Rabbids TV Party| 360x640    |  P|
|    Sally's Studio| 240x400     |  L|
| Sexy Poker 2009   | 360x640     |  P|
|   Sherlock Holmes | 640x360     |  L (AR)|
|  Silent Hill Mobile 3  | 360x640    | P|
|   Snake Revolution | 360x640     |  P|
|   Sonic Runners Adventure | 640x360     |  L (AR)|
|   Sonic Unleashed | 240x400     |  L|
|   Soul Calibur | 640x360     |  L (AR)|
|    Soul of Darkness| 640x360     |  L (AR)|
|    Spider-Man Toxic City| 240x400     |  L |
|   Spider-Man Ultimate Power| 640x360     |  L (AR)|
|  Splinter Cell Conviction  | 640x360     |  L (AR)|
|   Surviving High School | 360x640     |  P|
|  Tekken Mobile  | 240x400     |  L |
|   Tetris Revolution | 360x640     |  P|
|   The Adventures of Tintin | 640x360     |  L (AR)|
|   The Amazing Spider-Man 2 | 640x360     |  L (AR)|
| The Amazing Spider-Man   | 640x360     |  L (AR)|
|   The Avengers | 240x400<br/>640x360   | L<br/>L (AR)|
|   The Dark Knight Rises | 640x360     |  L (AR)|
|    The Sims 2 Castaway| 360x640    |  P|
| Thor: Dark World   | 640x360     |  L (AR)|
|   Total Conquest | 640x360     |  L (AR)|
|    Tower Bloxx New York| 360x640   |  P|
|  UNO and Friends  | 640x360     |  L (AR)|
|   UNO Spin| 240x400     |  L |
|Vampire Romance    | 640x360     |  L (AR)|
| Where is Wally   | 360x640     |  P|
|  Wild West Guns  | 640x360     |  L (AR)|
|Wonder Zoo    | 640x360     |  L (AR)|
|   Word Crafter | 640x360     |  L (AR)|
|  World at Arms  | 640x360     |  L (AR)|
|  Wrath of the Titans  | 640x360     |  L (AR)|
|   Zombiewood | 640x360     |  L (AR)|

Lis of Tested Java Games (Non-Touchscreen): #108
List of Java Games w/ Glitch: #94

## **Recommended Devices for Java Games Source:**
>**\- Nokia 5800 Xpress Music** - 360x640/640x360
**\- Samsung GT-5230** - 240x400
**\- Nokia 6300, N73, N95** - 240x320

**Comment by jaoopotente-ui** [comment]
would them 240x400 ones work on my nokia asha 311?

**Comment by successtheman** [comment]
You can add Derek Jeter Pro Baseball 2009 to this list 240x400 it is nearly flawless with touchscreen I believe it's a build for SGH-A877. It's available on that andrew-lviv site
